### PR TITLE
Fix Polish translations

### PR DESCRIPTION
**Pull request by agilob**
4 translations in "Uploads" view made no sense and were completely out of context.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Thanks for your contribution and welcome!
The translation is done via transifex, please translate it there.

**Comment by AndyScherzinger** [comment]
@agilob I just fixed the strings in transifex based on your pull request (so the translations will be fixed in the next release) :) Nevertheless, if you have the time and interest in registering at https://www.transifex.com and help us out with the Polish translations that would be awesome since we are having some (15) string which aren't translated for Polish language at the moment. So this would really help us having it 100% translated for Polish :rocket:

**Comment by agilob** [comment]
Thanks @AndyScherzinger

**Comment by AndyScherzinger** [comment]
You are very welcome! :smiley: 

here you can find the remaining open strings for the Android app https://www.transifex.com/nextcloud/nextcloud/translate/#pl/android/97057962?translated=no

**Pull request closed without merging**
