### PR TITLE
Avatar Etags

### LINKED ISSUE #1566: Refresh user avatar
### Actual behaviour
-Change user photo (or other info) and nextcloud client not reflect it.

### Expected behaviour
-When change any user info on server must be reflected in the client. This already happens for the background image. So both images should be cached for a certain amount of time, e.g. 24 hours.
 
### Steps to reproduce
1. Login on android client.
2. Change user profile on nectcloud server
3. Launch android client.
4. See sidebar info and see old profile...

### Environment data
Android version: 6.0

Device model: Moto X

Stock or customized system: Stok

Nextcloud app version: 2.0.rc5 or anything else..

Nextcloud server version: 2.0.1

#### Web server error log
```
IMHO Irrelevant
```

#### Nextcloud log (data/nextcloud.log)
```
IMHO. Irrelevant
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Resolves #1566

This caches the etag of an avatar and sends the etag to server and gets
- a new avatar if etag changed -> use new one
- a 304 response, meaning nothing changed -> show old avatar

Edit: not query the server too often we could also implement a 15min timeout, or whatever time.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Once https://github.com/nextcloud/server/pull/6876 is merged the problem should be solved as we then always have a bitmap.

**Comment by rullzer** [comment]
https://github.com/nextcloud/server/pull/6876 is merged :)

**Comment by tobiasKaminsky** [comment]
nextcloud/server#6876 is independent from this PR as it is NC13 only.
Once NC13 is our oldest supported release we can remove 
https://github.com/nextcloud/android/blob/c7ee4f1a60a5494abc4f6d91e087a664263910a9/src/main/java/com/owncloud/android/ui/TextDrawable.java#L97-L97

Remaining question is how we can annotate this.

**Comment by mario** [comment]
Is this ready for review @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
Yes. Do you want to have it in 2.1?

**Comment by mario** [comment]
Yes

**Comment by tobiasKaminsky** [comment]
Then rebased and ready for review & test.

**Pull request merged**
