### PR TITLE
Resolved issue relative to calendar refresh in link-sharing

### LINKED ISSUE #4901: Date not refreshed in ExpirationDatePicker (after setting an expiration date) in share by link
Hello,

When you share a file via URL, and define an expiration date, if you come back to the "picker" the date is wrong (not refreshed).

Here is the steps list to reproduce :
1) Go to properties of a file of your choice, "Sharing" tab
2) Click on "Share link" (key : share_via_link_section_title)
3) Click on the three dots to open contextual menu and click on "Set expiration date"
4) Define an other date than the given one (something like in a month)
5) Click on OK, and click now on "Expires dd.mm.yyyy" (the tab you've clicked to define the date)
6) The date in the picker is wrong. -> Here is the issue

I add a "micro-issue" within this one, when you define a date with this same datepicker, the toolbar appears for no reason.

Version : 3.9.0 stable

### PR DESCRIPTION
**Pull request by Shagequi**
Hi,

it resolves #4901 
:)

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Nice one.

Can you also change this on the other occurrence?
And please line wrap it, so that it fits into 120 chars. Maybe start with a new line for ".newInstance(…)"?

**Comment by Shagequi** [comment]
@tobiasKaminsky That's alright :)

**Comment by Shagequi** [comment]
@tobiasKaminsky I configured Android studio like written in CONTRIBUTE.md, but it doesn't seem to be the same as yours :/.
Do you have any export/config file relative to this ?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky I configured Android studio like written in CONTRIBUTE.md, but it doesn't seem to be the same as yours :/.
> Do you have any export/config file relative to this ?

For me the line wrapping also does not happen automatically.
I see a line on char 120 and then do the wrapping manually.

**Comment by tobiasKaminsky** [comment]
Can you also change this on the other occurrence?

There are in total three calls for this newInstance

**Comment by Shagequi** [comment]
It should be ok now @tobiasKaminsky :)

**Comment by tobiasKaminsky** [comment]
@Shagequi fine so far, but please change line wrap, same like here: https://github.com/nextcloud/android/pull/4918/files#diff-9314a3f23fe2e33ecf15916c73edbe41R464

I tried to do it, but I am not allowed to push to your repo ;-)

**Comment by Shagequi** [comment]
@tobiasKaminsky 
Done :)

Mhhh, you should be able to edit my code, I allowed to edit it from maintainers. 
In my case, I'm apparently not allowed to push on a branch on this project.

**Comment by tobiasKaminsky** [comment]
> In my case, I'm apparently not allowed to push on a branch on this project.

I needed to add you also to Android team.

**Pull request merged**
