### PR TITLE
Retain search

### LINKED ISSUE #686: Keep filtering results on back/home button
Currently, in master:

- do filtering, click on something, go back - search disappears

This is unwanted from what I understand. 

Unfortunately changing this requires changes to search, and there are already some search changes waiting for 1.5 in two PRs (integration-with-master and searching in text file) so if I did any changes now, we'd have a *REALLY* hard time merging the three (it's already gonna be hard with 2).

So what I propose is that we postpone this bugfix for 1.5.0 where I can then properly do it after all currently pending PRs are done. If you disagree let me know and I'll try to squeeze this into 1.4.2

CCing @tobiasKaminsky @AndyScherzinger and @jancborchardt for input and decision.

### LINKED ISSUE #2243: There seems to be something wrong with the sidebar
### Actual behaviour
When you collect a folder, open the sidebar, select your favorites option, then find your favorite folder in the interface, then click enter the folder, it seems that everything looks normal, but when you return, But found that the previous directory shows all the files, not the original collection of those files, but the sidebar options still remain in the collection interface, I think this is very unreasonable

### Expected behaviour
No matter how you click on the favorites asking price folder, exit should be consistent with the previous interface, showing the collection of files, not all
 
### Steps to reproduce
1. Collect a folder
2. Then click enter the folder in the favorites screen of the sidebar
3. If you go back to the root directory, you will find that all the files are displayed in the root directory, which does not seem reasonable

### Environment data
Android version: android 5.1.1

Device model: Nexus5

Stock or customized system:

Nextcloud app version :v3.0.1

Nextcloud server version: 12.0.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

Fixes #686
Fixes #2243

### CODE REVIEW

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky pls fix codacy when one of you gets to this PR :)

**Comment by tobiasKaminsky** [comment]
@mario not working for me :-/

Entered search term "about" and search:


open up text file


Then pressing back or "arrow left" results in 

There needs to be the search query "about" so that
- is visible to the user that search results are presented
- the search can be dismissed
  - as right now a click back closes the app
  - to get the file list back you have to open up the drawer and select "all files"

**Comment by mario** [comment]
@tobiasKaminsky I used EXACTLY this workflow and it worked. Will test again in a bit.

**Comment by AndyScherzinger** [comment]
haven't tested it yet but just fixed codacy (+rebase)

**Comment by mario** [comment]
I will try to fix this tonight before leaving.

**Comment by mario** [comment]
So I've made some progress on this. However, it requires some changes to the overall structure of the app in the fact that all these previews should not inherit from FileDisplayActivity, but should instead have their own activity. Once this is done, the search will be trivial. 

Postponing this to currently 1.5.1 (or 2.0.1, whatever).

**Comment by AndyScherzinger** [comment]
Thanks for the update @mario :) 

@tobiasKaminsky I'd also then vote for postponing this issue/pr for the next bugfix release.

**Comment by mario** [comment]
@AndyScherzinger if any of you can do this (separating previews to their own activity) while I'm away, that would be cool! :)

**Comment by AndyScherzinger** [comment]
I am blocked for the rest of the week unfortunately and am hoping that we can release an RC to GPlay soon... Really hope to get that done so we can gain some more user feedback. 

@tobiasKaminsky are you able to build beta releases for GPlay?

**Comment by mario** [comment]
@AndyScherzinger I can build a release still for the next few days so no worries. We have changelog + events refactor + those lint fixes to merge by @tobiasKaminsky and let's do it! :)

I was kindly asking if you can do it in the next few weeks so I can fix search after that :)

**Comment by mario** [comment]
Oh and the new screen!

**Comment by AndyScherzinger** [comment]
Ah okay :) weeks sounds way better then the next days :)

**Comment by tobiasKaminsky** [comment]
Closing this one as it is rather old.
If we want to fix this, we can still re-open.

**Pull request closed without merging**
