### PR TITLE
Fix failing operations (create folder, download file) due to user agent change

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@mario still fine by me

**Comment by mario** [comment]
👍 

Works for me, while to be honest, previous version did too xD

**Comment by AndyScherzinger** [comment]
> Works for me, while to be honest, previous version did too xD

Same here :D

**Pull request merged**
