### PR TITLE
Use app specific log folder

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Use app specific log folder. This is always writeable by the app.
Now the log file can be written on the very early beginning as no permission is needed.
Also the cause of storage migration problems can now be logged.

Needs: https://github.com/nextcloud/android-library/pull/60
Should fix: https://github.com/nextcloud/android/issues/297

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 looks good to me, just a minor question in the corresponding lib PR

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
Guys...this PR depends on logFolder branch of library for testing and should not merged in this state...

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/1002

**Pull request merged**
