### PR TITLE
show info if no userinfo is available

### LINKED ISSUE #1916: Account information should show that there are no details provided
### Actual behaviour
No indication that no user details are provided
zrzut ekranu 2018-01-03 o 10 10 41

### Expected behaviour
Indicator that no info is provided. Alternatively allow user to edit those details from the app.
zrzut ekranu 2018-01-03 o 10 10 41 2

 
### Steps to reproduce
1. Setup account with no details (no www, address, twitter)
2. Go to manage accounts > Open the account
3. Weep

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:
master

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #1916 

This uses the same way as "error" message are displayed, to stay consistent.
Any feedback regarding the wording is appreciated ;-)

### CODE REVIEW

**Comment by przybylski** [comment]
Well, this isn't an error and the icon is indicating one

**Comment by tobiasKaminsky** [comment]
Do you have an idea what icon we can use instead? 
Currently included icons are here: https://github.com/nextcloud/android/tree/4af76bccee89ddd477e09611f214eb31e841162b/src/main/res/drawable-xhdpi

Or shall we just show no icon and only the text?

@nextcloud/designers

**Comment by jancborchardt** [comment]
The person-silhouette icon is a good icon for this. It isn't needed in the header and can replace the error icon. (And yes, this is not an error so that icon is not proper. :)

Text-wise:
> No personal info set
> Add name, picture and contact details on your profile page

Link "your profile page" so one can open it. :)

**But really it should be possible to directly edit and add this info on mobile too of course. ;)**

**Comment by tobiasKaminsky** [comment]
Making it clickable is for some reasons not working, although it is working on participate screen :/
So I will have to leave it this way for now.
For making it editable: #1925

**Comment by jancborchardt** [comment]
Cool, ok! :) Only one thing, with the "No personal info set" I meant that should replace the first line, the bigger text which is now "No info". Otherwise good!

**Comment by tobiasKaminsky** [comment]
Well, this makes more sense of course 👍

**Comment by jancborchardt** [comment]
Tutto perfetto! :)

**Comment by przybylski** [comment]
@tobiasKaminsky may I add my 2cents to this code (clean it up)?

**Comment by tobiasKaminsky** [comment]
@przybylski of course you can :-) 
I am happy for any additional code review, just note it on the corresponding lines 👍

**Comment by przybylski** [comment]
@tobiasKaminsky done, sorry for such a long delay

**Comment by tobiasKaminsky** [comment]
Great @przybylski  thank you very much for your enhancements 👍

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
Merging with only one approval as @AndyScherzinger is on vacation.

**Pull request merged**
