### PR TITLE
Use Material Design For Rename Public Share Dialog

### PR DESCRIPTION
**Pull request by alperozturk96**
- [ Done ] Tests written, or not not needed

### CODE REVIEW

**Review by tobiasKaminsky — CHANGES_REQUESTED** [review]
Wrong screenshots :)

**Comment by tobiasKaminsky** [comment]
Isn't there a screenshot change needed?

**Review by tobiasKaminsky — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
