### PR TITLE
resolves: #1207 make daily contact backup string translatable

### PR DESCRIPTION
**Pull request by AndyScherzinger**
see #1207

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@mario are you fine with the content of this PR?

**Comment by AndyScherzinger** [comment]
@mario are you fine with the content of this PR?

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@tobiasKaminsky please re-approve and merge.

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky I'll have to rebase this one again thanks to lint because whenever the lint scores on master change and also change on the PR we have a merge conflict which is easy to resolve but will always lead to a reset of the approvals, so I'd say if we just need to resolve the lint result file conflict, we simply merge if the approvals have been there. Else it is just a huge pain...

**Comment by mario** [comment]
Sure

**Comment by tobiasKaminsky** [comment]
I second this. If two approvals are there and only minor changes (like merge master or merge lint) are needed, and drone and codacy are still green, then just merge.

**Pull request merged**
