### PR TITLE
Enable multiple lines for settings of automated upload: instant_upload_existing

### LINKED ISSUE #10554: Enable multiple lines for settings of automated upload: instant_upload_existing
### Steps to reproduce

Using Nextcloud Android App Version 3.20.3 (via F-Droid store) on Huawei P40 lite
German language settings

To reproduce:
1. Open Nextcloud App on smartphone
2. Go to Settings (Einstellungen) - Automated Upload (?, Automatisches Hochladen), Enable (Einrichten)
3. Find the settings for _instant_upload_existing_ "Vorhandene Dateien ebenfall..." not fully readable

Suggestion:
Remove (?) line 234 in file *android/app/src/main/res/layout/synced_folders_settings_layout.xml*
saying *android:singleLine="true"* for item *instant_upload_existing*

### Expected behaviour

Text is readable in any language due to an (automated) line break, similar to other texts/labels
(At first glance, none of the other labels contains a *android:singleLine="true"* line)

### Actual behaviour

Text is cut, last words are cut, meaning of the setting not understandable

nc-app

### Android version

EMUI 12.0.0 (system says I am using latest version)

### Device brand and model

Huawei P40 lite (edition without Google Play Store)

### Stock or custom OS?

Stock

### Nextcloud android app version

3.20.3 (via F-Droid store)

### Nextcloud server version

Storage Share 24.0.1 via managed hosting at Hetzner NX11

### Using a reverse proxy?

I don't know

### Android logs

_No response_

### Server error logs

_No response_

### Additional information

Best log and/or information is the screenshot above ;-).

### PR DESCRIPTION
**Pull request by dhruvpatidar359**
Signed-off-by: DHRUV PATIDAR <dhruvpatidar35@gmail.com>

- [x] Tests written, or not not needed
closes #10554

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
> Hello @AlvaroBrey should i try to fix the DCO check or not ?

Yep, please do!

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
@dhruvpatidar359 not sure what happened here, but while trying to fix DCO you seem to have completely deleted your commit and added 1 unrelated commit and 2 merges...

**Comment by dhruvpatidar359** [comment]
@AlvaroBrey  Should I make a new pr ?

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey Should I make a new pr ?

either that, or fix your branch 🤷

**Pull request closed without merging**
