### PR TITLE
Add RetryTestRule to DrawerActivityIT

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Flaky test

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Is this still nedeed after your awesome work on screenshot tests?

**Comment by AlvaroBrey** [comment]
> Is this still nedeed after your awesome work on screenshot tests?

Yes, this test is still flaky

**Comment by AlvaroBrey** [comment]
@tobiasKaminsky :ping_pong:

**Comment by tobiasKaminsky** [comment]
In my experience we currently only have failing tests is EndToEnd, but it can also not hurt to have it in, if you think it is needed :)

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
