### PR TITLE
change codecov token to nextcloud-android-bot

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger @rullzer do you have an idea why codecov is not working anylonger?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky nope, haven't had anythign to do with codecov, so no idea unfortunately :/

**Comment by tobiasKaminsky** [comment]
Still testing…

**Comment by tobiasKaminsky** [comment]
Not needed.
Code cov is now working.

**Pull request closed without merging**
