### PR TITLE
images: slightly rounded corners

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
@jancborchardt what do you think?

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice in list view, but for grid view it either needs to be veeeery small of a rounding or none at all. :)

**Comment by AndyScherzinger** [comment]
I agree fine @jancborchardt, fine for the list view and the grid view shouldn't have an rounding

**Comment by tobiasKaminsky** [comment]
Hm. I really like it on grid view…But I will change it, as you said, masters of design :-)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger @jancborchardt

**Comment by JorisBodin** [comment]
I also prefer no rounding in the grid view. It looks good in your latest screenshot.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger you were right, 20dp was too much.
I changed it to 10dp.
What do you think?

**Comment by AndyScherzinger** [comment]
Multiples of 8 would be typical, so how about 8dp?

**Comment by tobiasKaminsky** [comment]
Looks also fine :-)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky looks good, just SpotBugs has a raised score :(

**Comment by tobiasKaminsky** [comment]
> HTTP_PARAMETER_POLLUTION: HTTP Parameter Pollution

no idea why this suddenly pops up.
I increase spotbugs.

**Pull request merged**
