### PR TITLE
Delete all local files on account removal

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #627 

To discuss:
- how to prevent that an user clicks on account removal and then immediately kills the app to prevent file deletion

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
you can't I#d say, the user could also copy all the files manually and then delete the account.
Else you would nbeed to do cyclic checks for account folders for which there is no account in the database...

**Comment by tobiasKaminsky** [comment]
So you are fine with this?

**Comment by mario** [comment]
Well you could run the remove process in a job ...

**Comment by tobiasKaminsky** [comment]
Sure, but I wanted to have this done on the moment the user clicks on it and not scheduled for sometimes later.

**Comment by mario** [comment]
Solution:

- strike out the account name (aka, you can't click it)
- switch to other acc if it exists, if not show login screen
- run a job (you can schedule it to run after 3 seconds, and in the future you'll be able to schedule it right away :P) with all the delete magic
- prevent adding the same account while there is pending delete for that account
- done :D

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky yes, that means I am fine with deleting all local files on account removal 👍

**Comment by mario** [comment]
@tobiasKaminsky can you please do the things I've written here so we can merge this?

**Comment by tobiasKaminsky** [comment]
Done :tada: 
Tested with
- initially 2 accounts, removing one -> manage account activity with striked through account, drawer only shows persisting account
- initially 1 account, removing one -> login screen

**Comment by mario** [comment]
@AndyScherzinger if you feel like this is ok, feel free to merge - I will not be able to review it in a while. Thanks.

**Comment by AndyScherzinger** [comment]
👍 tested successfully after latest rebase

**Pull request merged**
