### PR TITLE
Begin debug logs when build type is debug

### PR DESCRIPTION
**Pull request by iskradelta**
Previous check was not true hence no logs
being made ever. #297

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
This also does not work as the build process uses the build type RELEASE.
For simplicity I suggest to enable this on beta at any time and just remove the check.

It would be great if you can change it this way.

**Comment by iskradelta** [comment]
I see, nice catch! Pushed a new commit now, without the if statement, this is only on the beta branch, I guess the master branch should have the "if build type is debug"?

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
Will be in the next beta.

**Pull request merged**
