### PR TITLE
disable 'MissingTranslation' as this is handled by transifex

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Additionally every new PR would fail if we introduce new strings... ;-)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1 👍

**Comment by AndyScherzinger** [comment]
👍 The build still fails @tobiasKaminsky

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger approve :)

**Comment by AndyScherzinger** [comment]
:+1: re-approved

**Pull request merged**
