### PR TITLE
Remove mime type info from details screen 

### PR DESCRIPTION
**Pull request by AndyScherzinger**
This is described in #1212 - https://github.com/nextcloud/android/issues/1212#issuecomment-322190484 to be exact.

Screenshot:
device-2017-10-06-113802

Can be merged for 2.0.0RC9, 2.0.0 final or later since it is just the removal of one info from the view... I'll leave that decision to you @tobiasKaminsky @mario ... imho a "just merge" no-brainer ;)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Ah, you mean like in the list view?

**Comment by comradekingu** [comment]
sharevialink

What does it look like when things are shared?

**Comment by AndyScherzinger** [comment]
@comradekingu 
screenshot_20171009-211042

**Comment by AndyScherzinger** [comment]
> Great, looks better. :) Next up: Moving the size and date under the filename in a second line? ;)

@jancborchardt there you go:
device-2017-10-09-225248

device-2017-10-09-225321

**Comment by tobiasKaminsky** [comment]
@jancborchardt is this fine for you?
@AndyScherzinger please rebase :-)

**Comment by jancborchardt** [comment]
@AndyScherzinger aaawesome! :) Much better.
If we can see that there is no preview (only filetype icon) we can also show it smaller, like same size as it would be in the list view.

Otherwise fine - I don't want to keep piling requests into this one change. ;)

**Comment by AndyScherzinger** [comment]
> If we can see that there is no preview (only filetype icon) we can also show it smaller, like same size as it would be in the list view.

should be done in another issue/PR and need some more detailing. For example, looking at the screenshots the details screen shows the file name with up to three lines. With the icon in the list view size we could only show one line or make everything aligned-top...

**Comment by jancborchardt** [comment]
Alright, sounds good! My :+1: still stands. :)

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger can you rebase? 49 changed files seems a little too much ;-)

**Comment by AndyScherzinger** [comment]
> 49 changed files seems a little too much

@tobiasKaminsky nope, that is absolutely correct, due to the removal of now unused strings in all string.xml files of all languages (lint check...)

**Comment by tobiasKaminsky** [comment]
Ah...Transifex is doing this by itself, but then lint would complain.

**Comment by AndyScherzinger** [comment]
exactly, a warning per item/language... :/

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky @mario for review :)

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
Merged to master for 2.1

**Pull request merged**
