### PR TITLE
Fix weird forum link in Participate page

### LINKED ISSUE #574: Weird forum link in Participate page
Hi,

The english value for translation key 'participate_contribute_forum_text' is incorrect and does not display anything is the app: Menu > Participate.

It's true for all languages because english source is wrong and has been declined in other languages.

The value is currently set to:
Help others on the &lt;a href="%1$s>forum&lt;/a>

=> at least is misses a " and maybe more ;-(.

### PR DESCRIPTION
**Pull request by AndyScherzinger**
fixes #574

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by mario** [comment]
lgtm - I like the look of this PR :D

**Comment by AndyScherzinger** [comment]
@mario the plugin is really picky (and seems to be case sensitive, so the line needs to start with LGTM in capital letters) 0_o

**Comment by mario** [comment]
LGTM - gee. Approving my own PR :P

**Comment by AndyScherzinger** [comment]
> gee. Approving my own PR :P

Nope it is your bracnh/commit but my PR xD

**Comment by mario** [comment]
Details, details :P

**Pull request merged**
