### PR TITLE
Grey-out auto upload options until enabled

### LINKED ISSUE #1260: Grey-out auto upload options until enabled
As suggested by @gahujipo here: https://github.com/nextcloud/android/pull/797#issuecomment-319973580

> The preferences window for auto upload shows a switch next to "Preferences for auto uploading". At the first sight it was not clear to me that that switch is uses to enable the auto upload feature for that folder pair. My idea was to grey out the options in the window unless the switch is set to true.

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

Fixes #1260

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 looking good code wise

**Comment by mario** [comment]
@tobiasKaminsky  :P

**Comment by tobiasKaminsky** [comment]
Isn't there a giant discussion how to change this at #2034 ?
Will this fit into your idea @AndyScherzinger?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this still fits with my idea on the overall change since this is related to the on/off status while my other ideas are related to media/custom type folder pairs. Thus this is still valid :+1:

**Comment by tobiasKaminsky** [comment]
The visual difference between enabled and disabled is too low in my opinion.
It is also confusing that there is an checked, but disabled checkbox (only upload on wifi).
Moreover you can click on save when the switch is disabled (left image), which is also confusing. What is saved?

I still like the idea, but somehow it is now even more confusing for me.

As we have sane defaults for these synced folders, we could enable the folder upon on save and then omit this switch in preferences dialog.

@jancborchardt

**Comment by tobiasKaminsky** [comment]
Please feedback by @nextcloud/designers, for me the questions in my last post are still open.

**Comment by mario** [comment]
@nextcloud/designers whenever you get a chance :P

**Comment by jancborchardt** [comment]
Absolutely agree with Julius. Unless the first setting is enabled, everything below is irrelevant and does not need to be shown.

**Comment by mario** [comment]
Can we get this merged for 3.1, and then we'll improve for 3.2? @AndyScherzinger @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
I already approve and would also be fine with merging and improving upon this foundation with 3.2 cc @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky what do you think? Imho this PR could be merged being a better solution than the actual state and improve upon it afterwards?

**Comment by tobiasKaminsky** [comment]
:+1: 
I will open up a following issue to enhance this.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the corresponding issue is assigned to milestone 3.1 -> so should this PR then be backported?

**Comment by AndyScherzinger** [comment]
Nevermind, you already wrote that in the roadmap issue for 3.1... sorry...

**Pull request merged**
