### PR TITLE
Fix Upload Problems For Encrypted Folder

### PR DESCRIPTION
**Pull request by JonasMayerDev**
**By Alper**

- [X] Tests written, or not not needed

### CODE REVIEW

**Comment by JonasMayerDev** [comment]
Already approved when PR was created by Alper:
After quick test, upload still has bugs (on master and in this PR) (will report as new issues) but definitely works better than before.

**Comment by tobiasKaminsky** [comment]
Can you fix spotbugs?

**Review by ZetaTom — CHANGES_REQUESTED** [review]
Upload fails when app is set up with only media permission.

<details><summary>Logcat</summary>
<p>

```
E  Upload of /data/user/0/com.nextcloud.client/files/nextcloud/tmp/alice@10.0.2.2%3A8080/D/IMG_20240220_092102.jpg to /D/IMG_20240220_092102.jpg: Unrecovered transport exception
   java.io.FileNotFoundException: /storage/emulated/0/Pictures/IMG_20240220_092102.jpg.enc: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at com.owncloud.android.lib.common.network.FileRequestEntity.writeRequest(FileRequestEntity.java:87)
        at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499)
        at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192)
        at com.owncloud.android.lib.resources.files.UploadFileRemoteOperation.uploadFile(UploadFileRemoteOperation.java:214)
        at com.owncloud.android.lib.resources.files.UploadFileRemoteOperation.run(UploadFileRemoteOperation.java:162)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
        at com.owncloud.android.operations.UploadFileOperation.encryptedUpload(UploadFileOperation.java:652)
        at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:443)
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193)
        at com.nextcloud.client.jobs.upload.FileUploadWorker.upload(FileUploadWorker.kt:224)
        at com.nextcloud.client.jobs.upload.FileUploadWorker.uploadFiles(FileUploadWorker.kt:174)
        at com.nextcloud.client.jobs.upload.FileUploadWorker.retrievePagesBySortingUploadsByID(FileUploadWorker.kt:148)
        at com.nextcloud.client.jobs.upload.FileUploadWorker.doWork(FileUploadWorker.kt:103)
        at androidx.work.Worker$1.run(Worker.java:82)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
   Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
        at com.owncloud.android.lib.common.network.FileRequestEntity.writeRequest(FileRequestEntity.java:87) 
        at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:499) 
        at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114) 
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096) 
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398) 
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) 
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) 
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) 
        at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192) 
        at com.owncloud.android.lib.resources.files.UploadFileRemoteOperation.uploadFile(UploadFileRemoteOperation.java:214) 
        at com.owncloud.android.lib.resources.files.UploadFileRemoteOperation.run(UploadFileRemoteOperation.java:162) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193) 
        at com.owncloud.android.operations.UploadFileOperation.encryptedUpload(UploadFileOperation.java:652) 
        at com.owncloud.android.operations.UploadFileOperation.run(UploadFileOperation.java:443) 
        at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:193) 
        at com.nextcloud.client.jobs.upload.FileUploadWorker.upload(FileUploadWorker.kt:224) 
        at com.nextcloud.client.jobs.upload.FileUploadWorker.uploadFiles(FileUploadWorker.kt:174) 
        at com.nextcloud.client.jobs.upload.FileUploadWorker.retrievePagesBySortingUploadsByID(FileUploadWorker.kt:148) 
        at com.nextcloud.client.jobs.upload.FileUploadWorker.doWork(FileUploadWorker.kt:103) 
        at androidx.work.Worker$1.run(Worker.java:82) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```

</p>
</details>

Cursory analysis:
- `originalStoragePath` differs from `uploadedSourcePath`.
- permissions may cause `.enc` file to become inaccessible
- see below screenshot

Screenshot from 2024-04-03 12-17-35

**Comment by alperozturk96** [comment]
> Upload fails when app is set up with only media permission.
> 
> Logcat
> Cursory analysis:
> 
> * `originalStoragePath` differs from `uploadedSourcePath`.
> * permissions may cause `.enc` file to become inaccessible
> * see below screenshot
> 
> Screenshot from 2024-04-03 12-17-35

Could you review again?

**Pull request merged**
