### PR TITLE
Showing Unicode encoded IDN strings in drawer navigation

### LINKED ISSUE #1046: IDN-domains not displayed correctly
### Actual behaviour
-IDN-domains (https://www.denic.de/en/know-how/idn-domains/) do work but in the account name they are displayed in their ACE string instead of IDN version.
Of course this is no bug, just a visual improvement.

### Expected behaviour
-Display IDN-domains correctly
 
### Steps to reproduce
1. Get an IDN-domain
2. Log in
3. check account name

### Environment data
Android version: 7.1.2

Device model:  Oppo Find 7

Nextcloud app version: Nextcloud-dev 20170525

Nextcloud server version: 12.0.0

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #1046

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky for the review since he has a test account for it :)

**Comment by tobiasKaminsky** [comment]
Well…I did not yet tested it ;-)
But will do it now

**Comment by tobiasKaminsky** [comment]
Works fine.
I'll do a manual backport now.

**Pull request merged**
