### PR TITLE
Dev version: use always latest library

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
I expect lint to fail as warnings will increase, which I will then adjust

This was changed sometime back to 1.0.33 which is wrong.
For dev version we want to have the latest client commit alongside with the latest library, which is always "-SNAPSHOT"

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Which means before doing a release we need to create the branch and change the lib version number?

**Comment by tobiasKaminsky** [comment]
No, this is only valid if the build flavor is "versionDev" due to "versionDevImplementation".
These deps are only included if the flavor matches.

implementation 'com.github.nextcloud:android-library:1.0.33' -> on all flavors except versionDev
versionDevImplementation 'com.github.nextcloud:android-library:master-SNAPSHOT' -> only for versionDev

**Comment by AndyScherzinger** [comment]
👍 fine by me

**Comment by AndyScherzinger** [comment]
Pinging @mario for second review :)

**Comment by mario** [comment]
👍

**Pull request merged**
