### PR TITLE
[BUILD ONLY] Jmue/storageprovider

### PR DESCRIPTION
**Pull request by ezaquarii**
Do not merge this branch. It is create only to force building QA apk.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Keep alive

**Comment by tobiasKaminsky** [comment]
Do we still need this?
If not, please close :-)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I guess we need it until #3905 gets rebased _and_ merged

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky I guess we need it until #3905 gets rebased _and_ merged

But we are working on #3905? So why do we need this?

**Comment by ezaquarii** [comment]
This is to be closed.

**Pull request closed without merging**
