### PR TITLE
Remove play services

### PR DESCRIPTION
**Pull request by mario**
This change removes play services and fixes a number of regressions for the Auto Upload. Special thanks to the Android job maintainer for his fixes, for accepting my fixes, and all the people who tested stuff.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: looks good to me and kudos to everyone involved in this change! :rocket:

**Comment by mario** [comment]
Unsure if this fixes all issues, and has one side-effect ... but long-term, probably for the best.

**Comment by AndyScherzinger** [comment]
What is the side effect?

**Comment by mario** [comment]
Well, if your device is affected by the bug, it'll auto upload "a few" images again once you upgrade. But after that, you're golden :D

**Comment by tobiasKaminsky** [comment]
👍 always 👍 when removing google ;-)
Great job!

**Pull request merged**
