### PR TITLE
Media store auto upload further fixes

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Opened against #797  to get rid of the remaining errors.

EDIT: Strange this should only show the changes... :/

### CODE REVIEW

**Comment by mario** [comment]
Very strange :-/

But anyway, should be fine...

Dunno why you didn't merge this right away xD

👍 

@AndyScherzinger please :)

**Comment by AndyScherzinger** [comment]
👎 killed this PR by cherry picking the changes ;)

**Comment by tobiasKaminsky** [comment]
Hmm, I wanted to avoid getting the #797 branch way too big.
And technically these error fixes have nothing to do with the branch.
I was only basing from this branch so that we do not have any conflicts after merging...

**Comment by mario** [comment]
Too late since some time ago xD

**Comment by tobiasKaminsky** [comment]
So...If I fix the other remaining issues and maybe some warnings...all in #797? :S

**Comment by mario** [comment]
If you can do it right now, yes :P Otherwise we do not wait... cc @AndyScherzinger

**Comment by AndyScherzinger** [comment]
I'd say just wait for 30 minutes

**Pull request closed without merging**
