### PR TITLE
Fix disappearing videos in Media screen

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Steps to reproduce original bug:

1. Open Media tab
2. Play a video
3. Go back within 30 seconds.

After this the videos were missing. When fixing it I also discovered a bug with thumbnail generation, which is also fixed here.

- [x] Tests written, or not not needed

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Thanks, seems like it fixes the mentioned issue (did also notice this when I recently tested the media tab).

Though, sometimes during loading when I scroll fast it ahows strange looking placeholders. Is this expected?
Screenshot_20220128-111812_Nextcloud QA

**Comment by AlvaroBrey** [comment]
> Thanks, seems like it fixes the mentioned issue (did also notice this when I recently tested the media tab).
> 
> Though, sometimes during loading when I scroll fast it ahows strange looking placeholders. Is this expected? 
Not that I know of, but it also seems unrelated to this PR and I can't reproduce it. Feel free to open an issue

**Comment by szaimen** [comment]
> Not that I know of, but it also seems unrelated to this PR and I can't reproduce it. Feel free to open an issue

Not really important, just noticed it :)

**Comment by tobiasKaminsky** [comment]
I assume that this is "fixed" / circumvented by #9783.
Let us check and maybe resolve after merging of #9783?

**Comment by tobiasKaminsky** [comment]
Closing in favor of https://github.com/nextcloud/android/pull/9783

**Pull request closed without merging**
