### PR TITLE
Backport e2e user agent fix

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Backport of changes of #2200

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky -> lint warnings increased :(

**Comment by mario** [comment]
👍 

While Lint could be fixed I guess.

**Comment by AndyScherzinger** [comment]
:+1: also, regarding lint: we can imho ignore this, since this is the backport to 3.0.x so it doesn't matter that much.

**Comment by mario** [comment]
OK then merge @AndyScherzinger

**Comment by AndyScherzinger** [comment]
@mario DONE :rocket:

**Pull request merged**
