### PR TITLE
Further rtl support

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Also enabled rtl support in app.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 looks good to me, pinging @mario for second review :)

**Comment by AndyScherzinger** [comment]
pinging @mario for second review :)

**Comment by AndyScherzinger** [comment]
rebased, pinging @mario for second review :) (build will push a new lint-score when finished!)

**Comment by AndyScherzinger** [comment]
again rebased to latest master

**Comment by AndyScherzinger** [comment]
@mario next one for second review 😋

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
Talked to Mario on irc, merge confirmed and approved

**Pull request merged**
