### PR TITLE
align grid/sort buttons

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
For #6274 

image

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@stefan-niedermann can you test this please?
It seems that second issue is also gone, at least on my Nokia 6.1 test device

**Comment by stefan-niedermann** [comment]
Confirmed to work on `2,7"` emulated smartphone & `10"` emulated tablet.

**Comment by tobiasKaminsky** [comment]
> So give me a few hours.

You call 13 min a few hours? You rock!

**Comment by tobiasKaminsky** [comment]
Is also the flickering shadow gone?

**Comment by stefan-niedermann** [comment]
Yes

**Comment by stefan-niedermann** [comment]
> You call 13 min a few hours? You rock!

Yeah, it compiled quicker than i thought :laughing: :laughing: :laughing: :smiling_imp: 

So, let's see where your promised green pipeline is! :)

**Comment by tobiasKaminsky** [comment]
> So, let's see where your promised green pipeline is! :)

image


:tada:

**Pull request merged**
