### PR TITLE
Fix an auto upload still occurring after acc delete

### LINKED ISSUE #942: Auto Upload stays active even after account removal on device
This came in via Google Play store review:

> Please add folder sync feature. Bug: I add login@domain1 account and configure auto upload. After, I delete this account and add login@domain2 and configure auto upload. Now when i take a photo, auto uploader in nextcloud wants to upload it to domain1 and domain 2, but login@domain1 has been fully deleted.

Device:     HTC One (M8) (htc_m8)
App version:     10040299 (1.4.2)
OS:     Android 7.1

### PR DESCRIPTION
**Pull request by mario**
This fixed #942

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 looks good to me - Lightspeed bugfixing! 🚀

**Comment by mario** [comment]
@AndyScherzinger yes, good catch. Will do it right away.

**Comment by mario** [comment]
(Cancelling jobs won't work as expected anyway until uploads are refactored into jobs, but nevermind - we should still do it).

**Comment by mario** [comment]
@AndyScherzinger done.

**Comment by tobiasKaminsky** [comment]
👍

**Comment by AndyScherzinger** [comment]
👍

**Pull request merged**
