### PR TITLE
deploy artifact on success

### LINKED ISSUE #4017: Accessing CI build artifacts
### Is your feature request related to a problem? Please describe.

I want to run CI-built package when reviewing a PR. I need to fetch the source code and compile it myself.

### Describe the solution you'd like

Since CI has already build apks at this point, why just not fetch them from there?
1. A QR code with URL to the APK could be posted in PR discussion automatically when CI build is complete.
2. Build artifacts can be cleared automatically after some delta T

### Additional context

Current setup discourages smoke testing while reviewing PRs as there is no convenient way to fetch build artifacts.

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #4017 

- [x] change versionID/name to drone number (so it increases every time)
- [x] create & add keystore for qa, add secrets to drone
- [x] find a way to remove all previous comments with APK
- [x] generate QR code
- [x] squash
- [ ] write a blog post about it

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
As discussed with Chris, this should be possible to directly install, in parallel to dev and prod version.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky so why not merge it? (labeling it as "1. developering"?)

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky so why not merge it? (labeling it as "1. developering"?)

As discussed with Chris, this should be possible to directly install, in parallel to dev and prod version.

**Comment by ezaquarii** [comment]
@tobiasKaminsky so which avenue you chose? If CI-specific signing key - no further input, that will work.

If we're doing a flavour and custom package, I'd not call it `test`, as this could be reserved for tests in code. Something like `pr` or `ci` maybe? We can later add a fancy launcher icon with drone motive to distinguish between installed versions.

**Comment by AndyScherzinger** [comment]
I guess, pr, ci or qa would all be fine. I'd vote for qa since it represents the purpose rather than the origin.

**Comment by ezaquarii** [comment]
Pkg suffix qa tells the story very well. +1

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky fine with qa?

**Comment by tobiasKaminsky** [comment]
Yeah, QA is good.
I fear that push will not work, but I hope this is ok :-)

**Comment by tobiasKaminsky** [comment]
So it seems even if I sign it via keystore it is still needed to "allow unknown apps", as this is not (yet and will never be) signed by Google.

But at least it its signed…

**Comment by AndyScherzinger** [comment]
Needs a rebase

**Comment by tobiasKaminsky** [comment]
APK file: 231234 (test)

**Comment by tobiasKaminsky** [comment]
Please test latest APK file

**Comment by ezaquarii** [comment]
> Please test latest APK file

I don't see any APK link. Should there be one anywhere here?

**Comment by ezaquarii** [comment]
> Please test latest APK file

@tobiasKaminsky I don't see any APK link here (some time ago there was a link to uploaded apk). Should there be one anywhere here?

**Comment by ezaquarii** [comment]
> APK file: https://www.kaminsky.me/nc-dev/android-artifacts/9199.apk

@tobiasKaminsky 404 not found!

**Comment by tobiasKaminsky** [comment]
> > Please test latest APK file
> 
> @tobiasKaminsky I don't see any APK link here (some time ago there was a link to uploaded apk). Should there be one anywhere here?

The QA build process is removing any old apk comment, but it failed to create a new one.
Give me some sec :-)

**Comment by ezaquarii** [comment]
> The QA build process is removing any old apk comment, but it failed to create a new one.
> Give me some sec :-)

Funny fact: It actually posted a link 25 seconds after my comment.

**Comment by tobiasKaminsky** [comment]
> APK file: https://www.kaminsky.me/nc-dev/android-artifacts/9202.apk

@ezaquarii noooow :-D

**Comment by tobiasKaminsky** [comment]
APK file

**Comment by tobiasKaminsky** [comment]
Finally done :-D

**Comment by tobiasKaminsky** [comment]
qrcode

**Comment by tobiasKaminsky** [comment]
APK file: https://www.kaminsky.me/nc-dev/android-artifacts/9983.apk 
 //www.kaminsky.me/nc-dev/android-artifacts/9983.png)

**Comment by tobiasKaminsky** [comment]
APK file: https://www.kaminsky.me/nc-dev/android-artifacts/9983.apk  qrcode

**Comment by tobiasKaminsky** [comment]
APK file: https://www.kaminsky.me/nc-dev/android-artifacts/9988.apk  qrcode

**Comment by tobiasKaminsky** [comment]
APK file: https://www.kaminsky.me/nc-dev/android-artifacts/9988.apk <br/><br/> qrcode

**Pull request merged**
