### PR TITLE
align app version code/name throughout builds (1.4.3)

### PR DESCRIPTION
**Pull request by AndyScherzinger**
drone builds fail if version code isn't aligned in builds

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Good finding!
This needs to be done for all three AndroidManifest files, I have adapted #150

**Comment by AndyScherzinger** [comment]
Great! Yeah, I missed the modified folder, but you didn't :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky https://download.nextcloud.com/android/ is still missing 1.4.3!

**Comment by tobiasKaminsky** [comment]
only @mario or @LukasReschke can do this

**Comment by mario** [comment]
It is in the works! :)

**Comment by mario** [comment]
Done. And merging.

**Pull request merged**
