### PR TITLE
fix crash in dismissLoadingDialog #279

### PR DESCRIPTION
**Pull request by AndyScherzinger**
for details, see #279

tested on Nexus5X, Android N

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please review (and merged in case you approve the changes) since this fixes some crashes reported in the Play console.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky still needs the +1 :wink:

**Comment by AndyScherzinger** [comment]
Pinging @tobiasKaminsky --> also here needs a +1 :wink:

**Comment by tobiasKaminsky** [comment]
LGTM

**Pull request merged**
