### PR TITLE
Adding a fallback when setting the span text crashes

### LINKED ISSUE #1387: GPlay:   java.lang.IndexOutOfBoundsException - com.owncloud.android.utils.DisplayUtils.createTextWithSpan
```
java.lang.IndexOutOfBoundsException: 
  at android.text.SpannableStringBuilder.checkRange (SpannableStringBuilder.java:1270)
  at android.text.SpannableStringBuilder.setSpan (SpannableStringBuilder.java:684)
  at android.text.SpannableStringBuilder.setSpan (SpannableStringBuilder.java:677)
  at com.owncloud.android.utils.DisplayUtils.createTextWithSpan (DisplayUtils.java:388)
  at com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment.setupDialogElements (SyncedFolderPreferencesDialogFragment.java:141)
  at com.owncloud.android.ui.dialog.SyncedFolderPreferencesDialogFragment.onCreateView (SyncedFolderPreferencesDialogFragment.java:113)
  at android.support.v4.app.Fragment.performCreateView (Fragment.java:2087)
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1113)
  at android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1295)
  at android.support.v4.app.BackStackRecord.run (BackStackRecord.java:801)
  at android.support.v4.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:1682)
  at android.support.v4.app.FragmentManagerImpl$1.run (FragmentManager.java:541)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95
  at android.os.Looper.loop (Looper.java:241)
  at android.app.ActivityThread.main (ActivityThread.java:6274)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)
```

All reported are for ```SyncedFolderPreferencesDialogFragment.onCreateView (SyncedFolderPreferencesDialogFragment.java:113)``` so I'll add a fallback here.

### PR DESCRIPTION
**Pull request by AndyScherzinger**
resolves #1387 reported on GPlay

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky / @mario can you review/approve/merge since this is a bugfix for auto upload preference fragment crashes 😺

**Comment by tobiasKaminsky** [comment]
:-1: 
The right fix in my opinion is to harden the createTextWithSpan() function as this is called from at least 2 points:
sb.setSpan(..., start, end, ...) crashes.

start is set to 0 if the text is not found (I would prefer to use =0 instead of ++ for simplier reading)
end is computed via: end = start + spanText.length()

This is can somehow be longer than text.length(). So the right fix would be to check this: if (end > text.length())

In this case I would simply set end to text.length().

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please review again :) https://github.com/nextcloud/android/pull/1388/commits/dcece32f72dc7b4f8fa9dfa94a6083c2162aab1d I did the "right" fix because the DisplayUtils method itself wasn't really doing the right thing since it would also have created a span 0-SpanTextLength if the span text wasn't found in the original string.

**Comment by tobiasKaminsky** [comment]
:+1: great fix :-)

**Comment by AndyScherzinger** [comment]
talked to @mario on IRC, we are fine to merge the fixes

**Pull request merged**
