### PR TITLE
Updating gradle-plugin to 3.0.0-beta7 + forced move buildToolsVersion 26.0.2

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* gradle-plugin 3.0.0-beta7
* buildToolsVersion 26.0.2 (enforced by 3.0.0-beta7)

Hope this'll also work for f-droid with the next release/RC, so putting @bubu on cc as well as @tobiasKaminsky and @mario

### CODE REVIEW

**Comment by Bubu** [comment]
@AndyScherzinger I don't think build tools 26.0.2 is on the fdroid build server yet.

Does this fix a problem so it has to be included for 2.0 or can this wait for later?

**Comment by AndyScherzinger** [comment]
@Bubu tricky to answer... This is a build issue. Google uses time bombs, so as soon as beta6 turns 4 weeks old it'll enforce an update to beta7 except you setting a special environment variable with a daily changing value to not break the build. Now, when you upgrade to beta7 the plug in enforces the build tools update in the same way beta6 enforces beta7.

So for now it works but just for a couple more days :/

**Comment by Bubu** [comment]
@AndyScherzinger I see, then you need to upgrade.
But preferably you'd need to wait for a version that doesn't break after 4 weeks for the final 2.0 release?

**Comment by Bubu** [comment]
@AndyScherzinger I just did a test build and apparently the gradle now automatically installs missing build tools versions. So this should hopefully be no problem at all for f-droid... :crossed_fingers:

**Comment by AndyScherzinger** [comment]
@Bubu that depends. Unfortunately Google doesn't provide any information on when they will ship a final version of the plugin :/
The build tools is a final version though.

**Comment by AndyScherzinger** [comment]
Fingers crossed, that sounds awesome so we might merge it and give it a try?

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
@Bubu I merged it to dev so the next Nextcloud dev build tagged for f-droid will contain this chance. Hope f-droid picks that build up very soon so we see if it works 😃

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky rebased to latest master, in case you want/can do a RC9 release today

**Comment by tobiasKaminsky** [comment]
👍 
I'll rebase and merge it afterwards now.

**Pull request merged**
