### PR TITLE
reformatting Code

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
I used this option.
As you can see *no* rearrange code as this was changing way too much (in my opinion).

screenshot_20170203_154906

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky Where do I find these settings? BTW: The reformatting also changed the translation files.

**Comment by mario** [comment]
I actually like "Rearrange code", I just don't like <p> stuff that happens with reformatting :-/

**Comment by tobiasKaminsky** [comment]
"Re-arrange code" destroyed the order of comments, e.g. a comment was not right above the variable it should describe.
What do you not like on "reformatting"? Theoretically we can define our own code/style guide, but then we must make (somehow) sure that this is used by AndroidStudio automatically.

**Comment by mario** [comment]
@tobiasKaminsky understood. I forgot to clarify what I don't like - I don't like <p> :)

**Comment by tobiasKaminsky** [comment]
...? What? Am I missing a part of your answer?

**Comment by mario** [comment]
Closing for now, but we need to do reformatting eventually for sure.

**Comment by tobiasKaminsky** [comment]
👍 should be done when most of the outstanding PRs are merged ;-)

**Pull request closed without merging**
