### PR TITLE
Spelling: End-to-end encryption, notifications sent by server

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
Thanks for the fixes @comradekingu :heart: 

cc @mario @tobiasKaminsky for second review. I'd vote for not merging the PR before 3.1.0 has been released as stable since the merge of the wording fixes will remove all existing translations which likely won't be translated again in time so I'd say merge after 3.1 so translators have enough time until 3.2

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky merged since I created a 3.1.x branch like you mentioned :)

**Pull request merged**
