### PR TITLE
add license/source code link

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #1548 
Discussed with Björn on IRC therefore slightly different, the most important things are in it.
Clicking on both items opens the link in a browser.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 fine by me.

Does this mean #1548 is resolved or do we want to add more infos? (at a later point in time...)

**Comment by tobiasKaminsky** [comment]
For me it is enough. All other libs are specified in source code with correct licenses. I do not see a real benefit to list them all.

**Comment by mario** [comment]
Should we say all new stuff is AGPL3 though?

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
Technically it is GPLv2 until all old code which was GPLv2 (and not written by one of us) is gone. Until then the GPLv3+ gets overruled by the GPLv2 code

**Comment by AndyScherzinger** [comment]
For contributions I hope people read the readme.md :)

**Pull request merged**
