### PR TITLE
resolves #1477 properly showing empty message after refresh when all …

### LINKED ISSUE #1477: Notifications list doesnt really refresh
### Steps to reproduce
1. Receive a push notification
2. Tab on the push notification
3. See list of notifications
4. Web UI: delete the notification
5. Phone: pull down the notifications list
6. See the loading circle

### Expected
After loading circle the list should be empty

### Actually
The item is still shown.

### Steps to continue
7. Open side navigation
8. Go to notifications
9. A new view starts with the empty list
10. Back button brings you back to the old notification list with the already deleted entry

### Environment data
Android version: 6.0

Device model: Huawei P8 lite

Stock or customized system: stock

Nextcloud app version: 2.0.0rc5

Nextcloud server version: 12.0.2

### PR DESCRIPTION
**Pull request by AndyScherzinger**
…notifications have been deleted

successor of #1478 - please have a look @tobiasKaminsky @mario :)

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Well :/ Drone is failing due to special chars in commit message :/
Will try to fix this soon

**Comment by AndyScherzinger** [comment]
Well, just manipulated the commit message of the last commit and it doesn't change anything still the same error message in droneCI log...

**Comment by AndyScherzinger** [comment]
> Well :/ Drone is failing due to special chars in commit message :/
Will try to fix this soon

That be great, reset all things also the master, so it seems to not be an issue with the

**Comment by tobiasKaminsky** [comment]
:+1: 
I did a rebase and drone is working now again.

**Comment by AndyScherzinger** [comment]
Nice! So just waiting for @mario's approval :)

**Comment by mario** [comment]
👍

**Pull request merged**
