### PR TITLE
Update dark theme computing

### LINKED ISSUE #1487: Theming change invertion threshold to 55%
raise threshold from 50 to 55% as changed on the server side, see https://github.com/nextcloud/server/pull/6344 and https://github.com/nextcloud/server/issues/4776

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: https://github.com/nextcloud/server/pull/6344
fix #1487

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
well.... 
resolves: #1487

**Comment by AndyScherzinger** [comment]
👍

**Comment by AndyScherzinger** [comment]
@mario fine with putting this fix into 2.0.0? :)

**Comment by mario** [comment]
Yup

**Comment by AndyScherzinger** [comment]
then 2 👍 it is 🎉

**Pull request merged**
