### PR TITLE
Release 2.0.0RC6

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Updated manifests for 2.0.0 RC6

cc @mario @tobiasKaminsky

### CODE REVIEW

**Comment by mario** [comment]
👍 
Sure, but we're not ready for RC6 :P

**Comment by AndyScherzinger** [comment]
I know - But this way we can simply merge and tag :)

**Comment by tobiasKaminsky** [comment]
About releasing schedule, my idea is that we fix today and monday outstanding bugs, like #1468 and then do a RC6 on monday afternoon?

**Comment by mario** [comment]
I'm fine with RC6 on Tuesday, sure.

**Comment by tobiasKaminsky** [comment]
We need also a new android-lib version 1.0.27 as there is at least one fix which should be in 2.0

**Comment by AndyScherzinger** [comment]
new lib release sounds fine too 👍

**Comment by AndyScherzinger** [comment]
New lib released: https://jitpack.io/#nextcloud/android-library/1.0.27

**Comment by enoch85** [comment]
Guys, for how long will you "postpone" the 2.0.0 release? Seems pretty stable to me. Maybe bugs from now on can go into 2.0.1?

**Comment by AndyScherzinger** [comment]
Afaik there are two remaining issues left open.

Login issues (relogin and also LDAP)
Log spamming with the byte size you reported

**Comment by enoch85** [comment]
> Log spamming with the byte size you reported

Thought that was fixed with https://github.com/nextcloud/android/pull/1468 Not merged yet, but still. :)

**Comment by AndyScherzinger** [comment]
That one is not yet fully checked but also isn't shipped with the dev version...

**Comment by tobiasKaminsky** [comment]
Both LDAP bugs are NC10 related, so I suggest that we fix & merge #1468 and after that RC6.
All other bugs will then be postponed to 2.0.1

**Comment by AndyScherzinger** [comment]
Sounds good to me. This PR can be merged to master at any time though ;)

**Comment by AndyScherzinger** [comment]
rebased to check if drone turns green now :)

**Comment by mario** [comment]
I'm unsure if we should postpone, but it's you two who think it's fine ... so fine :) I'll test my PR via the emulator now.

**Comment by AndyScherzinger** [comment]
> I'm unsure if we should postpone

If I understood @tobiasKaminsky then the auto upload issue would be fixed before the RC6 and afaik there is nothing else that needs fixing, right?

**Comment by mario** [comment]
@AndyScherzinger well the constant login-screen-appears is an actual issue related to userID/username/whatever. Same goes for favoriting etc. I've CCed you on a few iOS tickets that experience the same issue.

RC6 fine, but yea ... I wouldn't go for 2.0.0 stable without ALL the fixes.

**Comment by AndyScherzinger** [comment]
@mario ah, that was the issue in the iOS tickets, now I understand. 
@tobiasKaminsky Well, I'd also say we need to fix the relogin issue if currently still present in the Android app since that would be quite an issue for users. :/ I had this issue on Sunday but it disappeared on Monday so I didn't have the change to debug or grab some logs...

**Comment by mario** [comment]
@AndyScherzinger please merge this PR. So hard to see it here xD

**Comment by AndyScherzinger** [comment]
DONE :)

@ all - master is now pre-configured for RC6, so whenever all RC6 relevant PRs have been merged to master it'll be all setup correctly right away (+the gplay config of course)

**Pull request merged**
