### PR TITLE
Split up play services to avoid support version conflict

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Found by lint:
> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 25.0.0, 24.0.0.

This also decreases the size of the generated apk:
new version 7,2mb
current one: 11mb

Built is working fine locally, but did not tested push. I assume that gradle resolves deps correctly and thus no problem occurs, but @mario is the pro on this one.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 code looks good to me, can't tell if it has an impact on push notifications or other areas, so also waiting for the expert's feedback from @mario

**Comment by AndyScherzinger** [comment]
👍 conflicts resolved, all green. pinging@mario for +1 and merge :)

**Comment by AndyScherzinger** [comment]
👍 conflicts resolved, all green. pinging @mario for +1 and merge :)

**Comment by mario** [comment]
Pls merge

**Pull request merged**
