### PR TITLE
Fix conditions check

### PR DESCRIPTION
**Pull request by mario**
@tobiasKaminsky @AndyScherzinger

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
A bit more context please so I can at least test what you fixing :-)

**Comment by mario** [comment]
Previously wifi only and charging only was ignored

**Comment by AndyScherzinger** [comment]
Just tested wifi only and it still ignored it and simply uploads via cellular :(

**Comment by AndyScherzinger** [comment]
Same at home :/

@tobiasKaminsky can you please give it a test drive?

**Comment by mario** [comment]
@AndyScherzinger ah sorry. Can you re-pull and try?

**Comment by AndyScherzinger** [comment]
No worries, pulled and re-tried, still ignored wifi-only :(

Will be off for today now, Sorry

**Comment by mario** [comment]
Sorry, missing stuff all around :( Should be fine now.

On Mon, Jan 22, 2018 at 10:25 PM, Andy Scherzinger <notifications@github.com

**Comment by AndyScherzinger** [comment]
👍 
Argh, had to test ;) Works again while a remaining bug is that (at least on Android 8) uploads queue due to missing wifi connection don't get (instantly) restarted when connected to a wifi network again, but that is another issue which I mentioned somewhere else earlier.

**Comment by mario** [comment]
@AndyScherzinger in theory, they should restart in max 15-20 mins. You need to have at least part of the app active in order to use receivers on Android 8.

**Comment by tobiasKaminsky** [comment]
👍

**Pull request merged**
