### PR TITLE
#145 Alternative fix for drawer navigation fix in upload activity

### PR DESCRIPTION
**Pull request by AndyScherzinger**
fix for #145 - alternative implementation approach to #146

pinging @przybylski and @tobiasKaminsky for feedback

### CODE REVIEW

**Comment by przybylski** [comment]
better, one thing tho, showFiles(boolean) does set parameter in MainApp, maybe move that to super implementation (DrawerActivity) ?

**Comment by AndyScherzinger** [comment]
@przybylski DONE, see https://github.com/nextcloud/android/pull/148/commits/58f86500ad8938e6dab73f18b0c581f679aa4fb5 - I moved it to FileActivity though, so the Drawer implementation can still declare the method abstract to force others to implement it and FileActivity is a super class of the using classes for Upload and Display so I found that to be a nice place to put it. :) Fine with you? :smiley: :+1:

**Comment by przybylski** [comment]
👍

**Comment by tobiasKaminsky** [comment]
:+1: 
Then we should release a RC2 within the next few days?

**Comment by AndyScherzinger** [comment]
Yes we should. Can you guys take care of it?

**Comment by tobiasKaminsky** [comment]
LGTM
The only remaining "problem" is that you do not get back to the folder you had opened before switching to "uploads".
But this is a separate issue.

**Pull request merged**
