### PR TITLE
Backport: Fix #2094

### LINKED ISSUE #2094: Don't start file observer if no files are marked as "Set as available offline"
cc @tobiasKaminsky @AndyScherzinger

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Backport of: https://github.com/nextcloud/android/pull/2095

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky drone just dislikes your stable branch 😆

**Comment by tobiasKaminsky** [comment]
Drone and me are now friends again :hugs:

**Comment by AndyScherzinger** [comment]
👍

**Comment by mario** [comment]
👍

**Pull request merged**
