### PR TITLE
Fix: implicitly using the default locale is a common source of bugs

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Use instead:
internal: Locale.ROOT
otherwise Locale.getDefault()

### CODE REVIEW

**Comment by mario** [comment]
Needs rebase.

**Comment by tobiasKaminsky** [comment]
Done :-)

**Comment by AndyScherzinger** [comment]
👍 Fine by me

**Comment by mario** [comment]
👍 
Rebase and merge.

**Pull request merged**
