### PR TITLE
fix documentprovider test failure because of asynchronous upload

### PR DESCRIPTION
**Pull request by jmue**
Signed-off-by: Jens Mueller <tschenser@gmx.de>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Hm. According to log this still happens…
https://www.kaminsky.me/nc-dev/android-integrationTests/16217-IT-master/com.owncloud.android.providers.DocumentsStorageProviderIT.html#testServerChangedFileContent

I wonder why…As when the eTag changed, also the content should have changed, or?

**Comment by jmue** [comment]
This is how I would expect it. Hmm, maybe the remote path for the server webdav operation is broken?

**Comment by jmue** [comment]
Do you use server side encryption?

**Comment by tobiasKaminsky** [comment]
> Do you use server side encryption?

Not on CI server…

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
