### PR TITLE
Switch to AndroidX

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This was done automatically by AndroidStudio and "should" only be a replace of imports and names.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Well... drone raises 83 compile errors so at least the build fails in CI

**Comment by tobiasKaminsky** [comment]
Seems to come from butterknife, so we have to wait a bit for a new release there.

I tried to use latest master branch via jitpack, but this fails due to annotationProcessor.

**Comment by tobiasKaminsky** [comment]
With Butterknife 9.0.0 SNAPSHOT it is compiling, but we should wait for a stable release!

**Comment by AndyScherzinger** [comment]
Butterknife reached RC1 status, so we are getting there :) https://github.com/JakeWharton/butterknife/releases/tag/9.0.0-rc1

**Comment by AndyScherzinger** [comment]
https://github.com/JakeWharton/butterknife/releases/tag/9.0.0-rc2 has been released, so we are getting there, slow and steady :P

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I would go with RC2.
After all we have it only in master and thus in dev version.
Upcoming 3.4.0 is already branched and 3.5.0 is in ~3 months.

I'll update this one.

**Comment by tobiasKaminsky** [comment]
Removed pending codacy warnings and rebased.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky sure fine with me. Do you have the time to fix the 2 lint errors? Then I'd say we are fine with merging it afterwards :)

**Comment by tobiasKaminsky** [comment]
i fixed them, but we have to rebase once #3324 is merged.

**Comment by tobiasKaminsky** [comment]
Rebased again after #3324 was merged.
@AndyScherzinger you can merge it then :+1:

**Comment by AndyScherzinger** [comment]
👍 just waiting for droneCI

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger currently we do not use UI automator, so I disabled it for now :hide:

**Pull request merged**
