### PR TITLE
Adjust documentation for nc

### PR DESCRIPTION
**Pull request by LukasReschke**

### CODE REVIEW

**Comment by LukasReschke** [comment]
@nextcloud/android Mind giving this a LGTM? THX a lot.

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mar1u5** [comment]
👍

**Comment by AndyScherzinger** [comment]
Hmmm, good point not sure LGTM is able to detect that. @LukasReschke any idea if that is possible? Works for all of us, I can also +1 my own PRs :grin:

**Comment by LukasReschke** [comment]
> Hmmm, good point not sure LGTM is able to detect that. @LukasReschke any idea if that is possible? 

Don't think so 🙈

**Pull request merged**
