### PR TITLE
Activity compare tests for #6646

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This adds tests for #6646, so no backport is needed.

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
@dependabot-bot rebase

**Comment by AlvaroBrey** [comment]
Merging this into the #9043 branch to centralize screenshots work there

**Pull request merged**
