### PR TITLE
Catch sorting error

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Since long time we try to get rid of the TimSort error. This occurs if the underlying data set is changing while sorting, e.g. if the upload status changes during sorting.

This does not solve this, instead it only tries to prevent crashing the app.
Shall I add this to all other Arrays.sort(...) and Collections.sort(...)?

### CODE REVIEW

**Comment by mario** [comment]
Honestly I'd rather have the app crash xD Can't we make an immutable copy of the data, and sort on that?

**Comment by tobiasKaminsky** [comment]
I guess a regular user does not like to have an app crashing out of a sudden ;-)
Making an immutable copy is possible, but then we show outdated data, which can confuse the user.
Of course showing an unsorted list is also not what an user expects.
--> I do not have a good solution :/

**Comment by tobiasKaminsky** [comment]
@mario so what to do?
Leaving it the way it is, try to prevent crash with this PR, or think about something else/better?

**Comment by mario** [comment]
@tobiasKaminsky I'd say:

- use a immutable copy of data
- do sorting on that
- check if there's new data, and if there is show a snackbar (or something?) allowing user to refresh if there is new data

**Comment by tobiasKaminsky** [comment]
Found a new crash on google dev and this happens here:
```

java.lang.IllegalArgumentException: 
  at java.util.ComparableTimSort.mergeHi (ComparableTimSort.java:866)
  at java.util.ComparableTimSort.mergeAt (ComparableTimSort.java:483)
  at java.util.ComparableTimSort.mergeForceCollapse (ComparableTimSort.java:422)
  at java.util.ComparableTimSort.sort (ComparableTimSort.java:222)
  at java.util.Arrays.sort (Arrays.java:1259)
  at java.util.Collections.sort (Collections.java:174)
  at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent (FileDataStorageManager.java:861)
  at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent (FileDataStorageManager.java:154)
  at com.owncloud.android.operations.RefreshFolderOperation.fetchKeptInSyncFilesToSyncFromLocalData (RefreshFolderOperation.java:576)
```

In addition to your idea @mario I suggest that we try sorting 2x (it should be quite fast) and only then notify the user.

**Comment by tobiasKaminsky** [comment]
```
java.lang.IllegalArgumentException: 
  at java.util.ComparableTimSort.mergeHi (ComparableTimSort.java:866)
  at java.util.ComparableTimSort.mergeAt (ComparableTimSort.java:483)
  at java.util.ComparableTimSort.mergeCollapse (ComparableTimSort.java:404)
  at java.util.ComparableTimSort.sort (ComparableTimSort.java:213)
  at java.util.Arrays.sort (Arrays.java:1312)
  at java.util.Arrays.sort (Arrays.java:1491)
  at java.util.Vector.sort (Vector.java:1329)
  at java.util.Collections.sort (Collections.java:201)
  at java.util.Collections.sort (Collections.java:156)
  at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent (FileDataStorageManager.java:861)
  at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent (FileDataStorageManager.java:154)
  at com.owncloud.android.datamodel.FileDataStorageManager.prepareRemoveSharesInFolder (FileDataStorageManager.java:1619)
  at com.owncloud.android.datamodel.FileDataStorageManager.saveSharesInFolder (FileDataStorageManager.java:1544)
  at com.owncloud.android.operations.RefreshFolderOperation.refreshSharesForFolder (RefreshFolderOperation.java:537)
  at com.owncloud.android.operations.RefreshFolderOperation.run (RefreshFolderOperation.java:219)
  at com.owncloud.android.lib.common.operations.RemoteOperation.run (RemoteOperation.java:322)
```

**Comment by tobiasKaminsky** [comment]
As I did not found an issue, I added this to next milestone as we should try to fix this.

**Comment by tobiasKaminsky** [comment]
Better approach in #2228

**Pull request closed without merging**
