### PR TITLE
Firebase

### PR DESCRIPTION
**Pull request by mario**
@AndyScherzinger @tobiasKaminsky please merge this asap and tag RC2. Thanks.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: fine by me 

@tobiasKaminsky can you take care of the tagging? I am afk now...

**Comment by AndyScherzinger** [comment]
@mario Drone fails now! So something isn't right yet!

**Comment by mario** [comment]
@AndyScherzinger 

      - sh -c "if [ '$FLAVOUR' != 'Generic' ]; then sed -i '/com.google.*/s/^.*\\/\\///g' build.gradle; fi"

This line needs to be modified to fit:

// implementation 'com.google.firebase:firebase-core:11.0.4'

**Comment by mario** [comment]
@tobiasKaminsky if you know how to change that, please do and merge!

**Comment by tobiasKaminsky** [comment]
Can only do it in one hour

**Comment by mario** [comment]
Yup, sure...

**Comment by tobiasKaminsky** [comment]
Drone was satisfied, therefore merged.

**Comment by AndyScherzinger** [comment]
👍 nice

**Pull request merged**
