### PR TITLE
Screenshots black

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@dependabot-bot rebase

**Comment by tobiasKaminsky** [comment]
> @dependabot-bot rebase

Sad, I thought I could use this, even if it not a dependabot branch…

**Comment by tobiasKaminsky** [comment]
This can now be rebased and "just" added in screenshots.yml

**Comment by AndyScherzinger** [comment]
> This can now be rebased and "just" added in screenshots.yml

Done this already :)

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I vote for merging it as it is, so that we can enhance all screenshots at once, if possible.
Otherwise this will stay here forever.

**Comment by AndyScherzinger** [comment]
Fine with me @tobiasKaminsky 👍

**Pull request merged**
