### PR TITLE
Rename folder to existing name issue

### LINKED ISSUE #2040: Rename folder to existing name -> wrong snackbar
### Actual behaviour
-"could not give server new name"

### Expected behaviour
- "renaming not possible, name already taken" or similar
 
### Steps to reproduce
1. rename a file/folder to an already existing name
2. look at snackbar

### PR DESCRIPTION
**Pull request by cheikhSall**
fix #2040

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger merge instead of rebase? :fearful:

**Comment by AndyScherzinger** [comment]
👍 

@tobiasKaminsky rebase didn't work because the original commit doesn't contain a user.name just a user.mail and thus the rebase crashes with a fatal, thus I resolved the conflict via the github website.

**Comment by AndyScherzinger** [comment]
Thank you for your contribution @cheikhSall ❤️ 

Just in Case you want to look at other issues, the best way to get started is probably https://github.com/nextcloud/android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 and @tobiasKaminsky, @mario and me are here to help in case you have any questions 😃

**Pull request merged**
