### PR TITLE
Migrate NContentObserverJob to WorkManager

### PR DESCRIPTION
**Pull request by ezaquarii**
This change removes API-24+ `NContentObserverJob` and replaces it with a work unit executed by `WorkManager`

Changes:

1. Create `BackgroundJobManager`, single point of entry for all app-specific background job management, removing platform details and exposing business-specific API

2. Migrate `NContentObserverJob` to `WorkManager` `Worker` task, preservnting trigger semantics; `WorkManager` is a wrapper on top of `JobService`, preserving API semantics, so there is no change in functionality

3. Refactored class depdencencies to improve testability

Change rationale:

1. Using API level 24 classes prevented Dagger to work on Android M and older, causing `ClassNotFoundExceptions` due to missing classes on older platforms; fixing this problem would require to build own abstraction over job scheduler

2. The app use 2 background job systems: native platform `JobScheduler` and Evernote `JobManager`.

3. Google released `WorkManager` that is backward compatible and fixes job scheduler API bugs 21-22

### CODE REVIEW

**Comment by ezaquarii** [comment]
This is not me. My PR didn't touch encryption code at all.
```
12:07:07 V/InstrumentationResultParser: 1) encryptionMetadata(com.owncloud.android.util.EncryptionTestIT)
12:07:07 V/InstrumentationResultParser: java.security.InvalidAlgorithmParameterException: Expected IV length of 12 but was 0
12:07:07 V/InstrumentationResultParser: at com.google.android.gms.org.conscrypt.OpenSSLCipher$EVP_AEAD.engineInitInternal(:com.google.android.gms@16089022@16.0.89 (040700-239467275):22)
12:07:07 V/InstrumentationResultParser: at com.google.android.gms.org.conscrypt.OpenSSLCipher.engineInit(:com.google.android.gms@16089022@16.0.89 (040700-239467275):6)
12:07:07 V/InstrumentationResultParser: at javax.crypto.Cipher.tryTransformWithProvider(Cipher.java:2664)
12:07:07 V/InstrumentationResultParser: at javax.crypto.Cipher.tryCombinations(Cipher.java:2575)
12:07:07 V/InstrumentationResultParser: at javax.crypto.Cipher$SpiAndProviderUpdater.updateAndGetSpiAndProvider(Cipher.java:2480)
12:07:07 V/InstrumentationResultParser: at javax.crypto.Cipher.chooseProvider(Cipher.java:567)
12:07:07 V/InstrumentationResultParser: at javax.crypto.Cipher.init(Cipher.java:975)
12:07:07 V/InstrumentationResultParser: at javax.crypto.Cipher.init(Cipher.java:910)
12:07:07 V/InstrumentationResultParser: at com.owncloud.android.utils.EncryptionUtils.decryptStringSymmetric(EncryptionUtils.java:490)
12:07:07 V/InstrumentationResultParser: at com.owncloud.android.utils.EncryptionUtils.decryptFolderMetaData(EncryptionUtils.java:201)
12:07:07 V/InstrumentationResultParser: at com.owncloud.android.util.EncryptionTestIT.encryptionMetadata(EncryptionTestIT.java:182)
12:07:07 V/InstrumentationResultParser: at java.lang.reflect.Method.invoke(Native Method)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
12:07:07 V/InstrumentationResultParser: at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
12:07:07 V/InstrumentationResultParser: at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
12:07:07 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
12:07:07 V/InstrumentationResultParser: at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
```

**Comment by tobiasKaminsky** [comment]
A quick note
- please add license header to new files
- a smoke test lead to a long time waiting until a taken image was uploaded. I guess this is due to WorkManager. Is there a way to speed this up? As right now users are used to have it faster and might then complain. If not, we need to add this to What'sNew, as using WorkManager is definitely the right way!

**Comment by ezaquarii** [comment]
Can you please share exact test procedure?
I tested it and it worked as expected on Android 9, OnePlus 6T.

The underlying implementation should work the same way as previous
version, as it uses JobScheduler with identical trigger, so it's
not immediately obvious what could go wrong.

**Comment by tobiasKaminsky** [comment]
> Can you please share exact test procedure?

- clean installation on emulator
- set up sync folder, no wifi, no battery
- took a few images via camera
- previously: nearly immediately images were uploaded
- now: need to wait some time (not sure but I guess max 15min)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky which emulator version an device image are you using? So @ezaquarii can reproduce it with the same setup 😊

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky which emulator version an device image are you using? So @ezaquarii can reproduce it with the same setup blush

Emulator with Android 9 x86 (with Google APIs)

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger 

The job had "requires charging" constraint set. I removed it and I cannot reproduce it on my phone. Could you please try again?

**Comment by ezaquarii** [comment]
@AndyScherzinger @tobiasKaminsky Ping?

**Comment by tobiasKaminsky** [comment]
Sorry for the delay, I totally overlooked it :-(

I tested it and now it behaves like the old implementation :+1: 
I will review it today and then merge.

**Comment by AndyScherzinger** [comment]
Sorry for my absence these days and thanks @tobiasKaminsky for taking care of the task 🙏

**Comment by AndyScherzinger** [comment]
coda-wise it looks good to me while some/many newly created files lack the license header. COuld you add those @tobiasKaminsky? ❤️

**Comment by tobiasKaminsky** [comment]
I found only two, in test folder?
There I added & pushed it.

**Pull request merged**
