### PR TITLE
Add numeric buttons on PassCodeActivity

### PR DESCRIPTION
**Pull request by zmatsuo**
- Implimenting new numeric buttons for input passcode.
  - Soft Keyboard is need for passcode.
    But Soft Keyboard disappear sometimes.
	Then I tried add buttons.
  - But I think now Soft Keyboard always appear.
  - New button's design is not cool.
	('2 abc','3 def',...,Clear icon,Back icon and ...)
  - Do you think that the numeric buttons are necessary?
  - You can switch Soft Keyboard when Back is longClicked

- I add guard time when passcode is not match
  - against Brute-force attack :)
  - and add small animation :)
  - Do you think that time is increase(3sec->6sec->12sec->...)?

- I tried implimenting snackbar instead of mPassCodeHdrExplanation.
  - It is simple. But too simple notification?
  - If snackbar is enought, We can delete mPassCodeHdrExplanation.
  - If snackbar is not enought, I Will delete snackbar.

- Replace four EditTexts to TextInputLayout.
  - TextInputLayout is easy to handle KEYCODE_DEL and Soft Keyboard.
  - I think Soft Keyboard is normal Soft Keyboard (like built-in soft keyboard)
    or Password input keyboard (like Keepass2Android)
  - Use TextInputLayout#setError() instead of toast()

- I add goHome() when ACTION_CHECK.equals(getIntent().getAction())

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @zmatsuo,

can you open a PR targeting ```master```, we are pulling the PRs to beta manually while the pR should always target the master :) Thanks 😺

**Comment by AndyScherzinger** [comment]
Edit: My mistake, you did branch based on the beta so this is fine then, but you would then need to cherry pick your commits for another master based branch for a PR to get it merged to master.

**Comment by AndyScherzinger** [comment]
Hi @zmatsuo,

what is the reason for adding a pin keyboard? 
--> Most PIN implementations in apps simply use the phone's keyboard, e.g. Amazon prime video simply shows me the pin element in the way the Nextcloud app did and has let me use the standard keyboard.

**Comment by zmatsuo** [comment]
Soft Keyboard sometimes disappeared.

Reproduction(My device is Galaxy S4,stock 5.0.1)
1. start Nextcloud app
2. push home button(go home app)
3. long press home button (show app history)
4. select Nextcloud app
5. Soft Keyboard disappear

So I want to fix this.
First I try to detect Soft Keyboard disappeared.
(setListenerToRootView() ...  I need to change function name.)
But I think code is tricky a little.
Next I add numeric buttons and control 4 EditTexts.
I found TextInputLayout, I replace TextEdits to TextInputLayout.
So I think Soft Keyboard is good and numeric buttons is good too.
I implement user can select Soft Keyboard and numeric buttons.

Please longClick 'BACK\nSOFTKEY',
buttons disappeared and Soft Keyboard appeared.
Push back buttons appear, when Soft Keyboard appeared.

I think that Numeric buttons is good if numeric button's degsign is cool
and button's usability is no problem,
But keyboard (Hardware keyboard(ex. BT connected key) 
and password input keyboard (like Keepass2Android))  is need too.
So I implement selectable buttons and Soft Keyboard.

BUT It is difficult for me that I create screen layout.
Back button's horizontal alignment is not good.
I try to fix but I can't (I will try to fix tonight).
And I found that some buttons hide when rotate screen. :cry:

### Other apps using pin.

- Soft Keyboard
-- Authy 2-Factor Authentication  
   https://play.google.com/store/apps/details?id=com.authy.authy

- Numeric buttons
-- android screen lock
-- dial apps
-- LastPass authenticator   
   https://play.google.com/store/apps/details?id=com.lastpass.authenticator
-- IIJ SmartKey   
   https://play.google.com/store/apps/details?id=jp.ad.iij.smartkey2

**Comment by zmatsuo** [comment]
I fixed layout.
I added layout file for landscape.

**Comment by AndyScherzinger** [comment]
Hi @zmatsuo 
are you aware that this PR just targeted the beta and thus won't be in the stable releases?

**Comment by zmatsuo** [comment]
Thank you for the merge @tobiasKaminsky 

Hi, @AndyScherzinger 
I have rewritten a lot.
So, I think that the beta version is good first. :smile:

**Comment by mario** [comment]
@zmatsuo what he's saying is that we need the branch back! :)

**Comment by AndyScherzinger** [comment]
@mario @zmatsuo what I am saying is that if this should ever make it into the stable releases there needs to be a new branch forked from master with the relevant commits for this change. We will never merge anything from the beta branch. Changes for stable will always be on (master-based) feature branches that we pull to beta.

**Comment by mario** [comment]
Yes but he deleted his branch.

**Comment by zmatsuo** [comment]
> We will never merge anything from the beta branch.

Oh! I understand.  Surely this PR branches from beta.
[This doccument](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#contribution-process) shows branches from master. Sorry :cry:

@mario @AndyScherzinger Thank you for pointing out.

I want this PR to be merged into master.

How should I do?  :disappointed_relieved:

**Comment by zmatsuo** [comment]
I open new PR #620 
It's OK? @mario @AndyScherzinger 

git checkout master
git branch -b passcodeLock 
git cherry-pick ...

If something is wrong, please fix it.

**Pull request merged**
