### PR TITLE
Enhance recommend to a friend #315

### PR DESCRIPTION
**Pull request by jsrck**
This enables "Recommend to a friend" via other apps than mail, e.g. WhatsApp or SMS.
In addition the fdroid link was added.
Pull request for https://github.com/nextcloud/android/issues/315

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Codewise it seems to be fine :+1: 
But on testing I first choose "copy to clipboard" and on the second time I could not choose anything, so it just get copied again to clipboard.
There was nothing like "use as default" (or how it is translated in english).

Is this happening also for you? Tested on a Samsung S5 Neo.

**Comment by tobiasKaminsky** [comment]
:+1: 
Tested it again on an emulator and there I can choose between "just once" and "always".
So everything is fine over here. Must some issue on Samsung...

**Comment by jsrck** [comment]
For me everything is fine, too. I tested in on an emulator and on a Samsung S2 GT-I9100 with Android 6.0.1 (CyanogenMod).

**Comment by AndyScherzinger** [comment]
👍 fine by me too. added some lint fixes to make the build turn green :) ... merging for 1.5.0 🚀 

@jsrck thanks for this contribution!

**Pull request merged**
