### PR TITLE
Housekeeping: Branch 3.1.0-morris

### PR DESCRIPTION
**Pull request by AndyScherzinger**
@tobiasKaminsky @MorrisJobke can we delete `3.1.0-morris`?

### CODE REVIEW

**Comment by rullzer** [comment]
Morris doesn't use android so he doesn't get a vote :wink: 
Kill it, approved by our android master @tobiasKaminsky

**Comment by MorrisJobke** [comment]
I need following commits for our brander ;)

🙈 

```php
				$patches[] = 'commit/efa1dc24c17992a795c61200ce387468c6f081f9';
				$patches[] = 'commit/440abd4b9506a94cfe4082762ee9c17d684632ba';
				$patches[] = 'commit/4bce5462f2004d26c0cd2ce0aa63752dc950c3f0';
				$patches[] = 'commit/5e9ca9dafe711c4184933a922d12e9efed8073f1';
				$patches[] = 'commit/8873399c753e557ebce84f179785132317fb975a';
				$patches[] = 'commit/0b65622f568558bf2e2430479ec285638283f8bf';
				$patches[] = 'commit/a2b933dc7a3354b084348672ae11ca76eb0e9f1c';
				$patches[] = 'commit/d86088c79a2917bfca268bc0617edc8d44092453';
				$patches[] = 'commit/d62bc0be21b653b411ec106674cc9a063a701b8d';
				$patches[] = 'commit/277b94130a445a3015a8c18cd96fe3c5f71d8b86';
				$patches[] = 'commit/a4dad674c9e6295c039afe0254e741d1c9d8dfc4';
				$patches[] = 'commit/c0550d5651e6b55dd351278fd18fdde6d6ea16ff';
				$patches[] = 'commit/29dcdc73315ba1a4f160a8d4a9627c283164f271';
				$patches[] = 'commit/e93f9f6fdd78909d0d700e023ebc1e716d400af0';
```

**Comment by AndyScherzinger** [comment]
So we keep this branch forever? Shouldn't it just be tagged and the branch then be deleted?

**Comment by MorrisJobke** [comment]
> So we keep this branch forever? Shouldn't it just be tagged and the branch then be deleted?

I will delete it once we moved over to newer release ;)

**Pull request closed without merging**
