### PR TITLE
backport #3359: Use own fork with backported android 9 fix

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky RC3? 3.4.1?

**Comment by AndyScherzinger** [comment]
Since it is a major issue I'd say, if you have the time, probably do an RC3 today

**Comment by tobiasKaminsky** [comment]
Yeah, totally forgot about this.
This should of course be in RC2.

**Pull request merged**
