### PR TITLE
Use upload_and_delete for direct camera upload

### LINKED ISSUE #4609: Upload from Camera doesn't work for more than one picture
### Actual behaviour
When uploading several files directly from the camera to a folder without waiting for the previous pictures to finish uploading. It won't upload any pictures besides the first ones. The other ones will fail with "Local File not foud"

### Expected behaviour
- You should be able to take as many pictures as you want without waiting after each pictures until it finished uploading it
 
### Steps to reproduce
- Open the nextcloud app
- Choose a folder on the server
- Press the plus button and choose "upload from camera"
- Take a picture and accept it.
- Now nextcloud starts uploading that picture.
- Don't wait before it finished uploading, choose "upload from camera" again and upload an other picture.
- It will fail uploading the second file. In the upload log it shows "local file not found"

### Environment data
Android version: 9

Device model: Xiaomi Mi A2 Lite

Stock or customized system: Stock

Nextcloud app version: 3.8.0

Nextcloud server version: 16.0.5

### PR DESCRIPTION
**Pull request by AndyScherzinger**
…to allow for multiple image uploads without having to wait for a successful upload before taking the next photo.

Resolves #4609

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by FiC5020** [comment]
Great, if work for me too. I can make 10 photos in offline or with poor Internetconnection and all 10 photo where upload on the server. Very thanks for this prompt solution.

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky for review and to include in the next bugfix release 💪

**Comment by AndyScherzinger** [comment]
@FiC5020 thanks for taking the time to test the fix, this is highly appreciated 🙏

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
