### PR TITLE
 Picture "details "page reappear when it shouldn't. #1221

### LINKED ISSUE #1221: Picture "details "page reappear when it shouldn't.
### Actual behaviour
-Tell us what happens
Once the "details" from a picture has been requested, the page will always reappear when switching application back and forth.

### Expected behaviour
-Tell us what should happen
"Details" page should not reappear once it has been closed.

### Steps to reproduce
1. Go down a folder with pictures.
2. Click on the picture to display it.
3. Click the 3 vertical dots on the top right menu and select "Details"
4. Pressing the back arrow to return to the picture in picture view mode. (it actually show for a split second the folder then switch back to picture view mode).
5. Change folder by pressing back arrow.
6. Switch to another app on the device not closing NC Dev.
7. Switch back to NC Dev.
7. First thing NC Dev will show is the previous picture detail page. Presseing arrow back will point to the previous folder as well.

### Environment data
Android version:

Device model: 
LG G3 D852
Stock or customized system:
Stock
Nextcloud app version:
NC Dev 20170723
Nextcloud server version:
NC 12

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### PR DESCRIPTION
**Pull request by jsrck**
(I hope) this pull request fixes #1221. At least I can't reproduce the bug any more with this line inserted. Please check it well – I'm an Android-beginner.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario can you have a look at this one please? I won't find the time before CW32 :(

**Comment by tobiasKaminsky** [comment]
:+1: works for me.
Tried it also with rotating details/picture view.

Thank you very much for your contribution! :tada:

**Comment by AndyScherzinger** [comment]
@mario can you please check this PR? I am still afk... Thanks!

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
Thanks :)

**Pull request merged**
