### PR TITLE
Cleanup of the TouchViewImage class

### PR DESCRIPTION
**Pull request by ardevd**
Removed redundant modifiers, useless statements and variable declarations.

### CODE REVIEW

**Comment by mario** [comment]
Bonus points if you completely remove the usage of this class :P

**Comment by ardevd** [comment]
@mario First I'd need to figure out why it's there in the first place :P

**Comment by AndyScherzinger** [comment]
@ardevd that is easy to explain:
* double tap / pinch - to zoom on the (preview) images

What I would suggest is that we move to https://github.com/chrisbanes/PhotoView which would also support animated gifs :)

**Comment by AndyScherzinger** [comment]
Plus would laos be that the refered lib is still maintained while the TouchView is dead

**Comment by ardevd** [comment]
@AndyScherzinger Nice! I'll look into it asap.

**Comment by ardevd** [comment]
@AndyScherzinger Sounds good to me. Added #2583 for reference.

**Comment by mario** [comment]
Sure

**Comment by tobiasKaminsky** [comment]
:+1: 

> support animated gifs

@AndyScherzinger this already works out of the box with android.
But replacing it with a newer, maintained version is a good idea.

**Comment by AndyScherzinger** [comment]
:+1: 
> @AndyScherzinger this already works out of the box with android.

Right! Didn't know that :+1:

**Pull request merged**
