### PR TITLE
Upload files into subfolder

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix for #4375

This uploads file in corresponding subfolder, and creates it.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Something went very wrong with Spotbugs...?!

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you do a manual backport (IMHO we should just backport any fix except for very large ones)

**Comment by erikkroes** [comment]
Can this be merged please? Would mean a lot if it could!

**Comment by AndyScherzinger** [comment]
@erikkroes this PR has been merged last year in October! Shipped with 3.9.0

**Comment by erikkroes** [comment]
Ah, sorry for the confusion. I must have some updating to do then.

**Pull request merged**
