### PR TITLE
Make search work again

### LINKED ISSUE #1535: Photos & Favs Won't Load
Replaced RC5 with the new RC6. Followed instructions removing account and setting back up again.

Photos wont load from server
Favourites wont load from server

Using a Sony XperiaZ5 
Android 7.1.1

Log is empty. Tried uninstall and restart

Dj

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

Favorites, Photos and Shared files somehow stopped working. This fixes it.

Please test for possible issues with search overall, rotation etc and fix if there's something wrong.

resolves #1535

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
See attached some screenshots... unfortunately I won't have the time to fix it since I am not an expert on this part of the code base so it would also take me much more time to fix.

device-2017-09-13-190034
device-2017-09-13-190112
device-2017-09-13-185958

* Rotation in general works fine, except for search via the tool bar, see screenshots the search doesn't stretch all over the bar (might be okay for 2.0.0)
* favs/shared works on my phone also no issues with rotation
* what doesn't work and maybe never did (yet) is back navigation:
  * searching and then hitting the back arrow or "X" will close the search bar but leave you with the search result and the drawer icon
  * entering a folder (found by search) and hitting the back arrow navigates you to the root folder with search result/toolbar state reset.

@tobiasKaminsky @mario how should we proceed here? From what I understood from @mario's comment search hasn't worked at all so this would be an enhancement while I can't say since I haven't used/tested it before for quite a while...

**Comment by mario** [comment]
@AndyScherzinger I don't know *shrug*. Back when search/favorites/photos/etc was written, tested and approve it worked and it streched the majority of action bar. Dunno what happened but my PR at least fixes part of things. 

Hopefully, @tobiasKaminsky has the time since he did the changes to the initial search implementation.

**Comment by tobiasKaminsky** [comment]
> what doesn't work and maybe never did (yet) is back navigation:
> - searching and then hitting the back arrow or "X" will close the search bar but leave you with the search result and the drawer icon
> - entering a folder (found by search) and hitting the back arrow navigates you to the root folder with search result/toolbar state reset.

This was already discussed in
https://github.com/nextcloud/android/issues/686
with a potential PR in https://github.com/nextcloud/android/pull/1272, but:
https://github.com/nextcloud/android/pull/1272#issuecomment-321082088
> So I've made some progress on this. However, it requires some changes to the overall structure of the app in the fact that all these previews should not inherit from FileDisplayActivity, but should instead have their own activity. Once this is done, the search will be trivial.
Postponing this to currently 1.5.1 (or 2.0.1, whatever).

So I would be fine with a "basic" search in 2.0 with the above and known disadvantages.
And for 2.0.1 or 2.1 we need to enhance this.

If you are fine with this, I will test the PR only in the scope of working search/favs and then we can merge this.

**Comment by AndyScherzinger** [comment]
I am also fine with this as in basic search while with still have the back navigation issues etc. since this one fixed the search for me and so it makes sense to ship this PR with 2.0 :)

**Comment by AndyScherzinger** [comment]
👍 rebased against latest master, so from my understanding we are fine with merging this with the known open issues mentioned by @tobiasKaminsky which we postpone to > 2.0.0

**Comment by tobiasKaminsky** [comment]
If @mario is fine with this approach, I still have to review/test it, so no merging right now please

**Comment by mario** [comment]
Not entirely happy, but compromise has to happen - so yes. Please test if
favorites/shared files/etc works, and if it does ... merge.

**Comment by tobiasKaminsky** [comment]
Tested on regular nc 12 and also on nc12 with ldap
:

**Comment by AndyScherzinger** [comment]
Woohoo, so Rebase and Merge :rocket:

**Pull request merged**
