### PR TITLE
Fixing recycler view error

### PR DESCRIPTION
**Pull request by sobin007**
how good is this?

### CODE REVIEW

**Comment by mario** [comment]
Hi, is this completely replacing list view with recycler view? If so, awesome if this is your contribution! It looks like it references 2016 in places?

Can you also look into things Codacy said and fix them? (except missing breaks, I guess they're missing for a reason)

**Comment by AndyScherzinger** [comment]
Hi all, it is right now basically a reopen of #1122 by skymania and me. It could be used as an inspiration for an implementation. Working on the branch itself seems to be not worth a try since a rebase which would have to be done first is very complicated. But if you want to use the branch feel free @sobin007 :)

**Comment by AndyScherzinger** [comment]
Hi @sobin007, since you opened the PR would you be willing to work on a/the recycler view implementation?

**Comment by AndyScherzinger** [comment]
no response for more than a month, thus closing the PR. Please re-open if someone is willing to work on it.

**Pull request closed without merging**
