### PR TITLE
Add Android P check for tinting cursors

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Should help with #3800 while I haven't tested it yet. Need to re-install Android Studio first...

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
On Android 9 emulator I still get this:

```
2019-03-29 09:31:18.997 9218-9218/com.nextcloud.client E/ThemeUtils: setTextViewCursorColor
    java.lang.NoSuchFieldException: No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.owncloud.android.utils.ThemeUtils.setTextViewCursorColor(ThemeUtils.java:582)
        at com.owncloud.android.utils.ThemeUtils.themeEditText(ThemeUtils.java:459)
        at com.owncloud.android.utils.ThemeUtils.themeSearchView(ThemeUtils.java:467)
        at com.owncloud.android.ui.fragment.ExtendedListFragment.onCreateOptionsMenu(ExtendedListFragment.java:187)
        at androidx.fragment.app.Fragment.performCreateOptionsMenu(Fragment.java:2561)
        at androidx.fragment.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3321)
        at androidx.fragment.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:331)
        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:379)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by AndyScherzinger** [comment]
> I still get the error on Android 9 emulator

I'll have another look, thanks

**Comment by tobiasKaminsky** [comment]
> > I still get the error on Android 9 emulator
> 
> I'll have another look, thanks

Have you tested this? Or even fixed it? :-D

**Comment by AndyScherzinger** [comment]
> Have you tested this? Or even fixed it? :-D

Not yet, needs fixing first, just keeping it up-to-date with the master branch at the moment... :/

**Comment by tobiasKaminsky** [comment]
Damn, I think I overlooked this one and created #4242, which is basically the same.

**Pull request closed without merging**
