### PR TITLE
Allow accessing URLs with custom cert in editor

### LINKED ISSUE #9536: [3.18.1 RC1] unable to open txt files
### Actual behavior
If I try to open a txt file with e.g. only a size of 289 bytes, a spinning wheel is shown and after a while the message "Das Laden dauert sehr lange ...  ZURÜCK" (Loading takes very long ...   BACK) is shown. The same file can easily been opened using the Nextcloud web GUI. No errors are logged on the server.

### Expected behavior
It should be possible to open and display txt files using the Nextcloud Android app.

### Steps to reproduce
1. Open the Nextcloud app and navigate to a folder which contains a txt file.
2. Select it and wait.
-> The files isn't displayed but a message "Loading takes very long ..." is displayed.

### Environment data
Android version: 11.0
Device model: Samsung Galaxy S20
Stock or customized system: Stock ROM
Nextcloud app version: 3.18.1 RC1
Nextcloud server version: 22.2.3

### LINKED ISSUE #9771: cant edit markdown files
### Steps to reproduce
1. open app.
2. click 3 dot menue next to share button next to file name
3. click edit
4. spinning blue wheel appears
5. after a while little grey box appears saying "loading takes very long..." but no other info
6. wait. wait. wait. nothing ever happens.

### Expected behavior
Honestly I dont know what should happen. I have never actually seen the file editer. Its never worked through all the various versions of the app. 

### Actual behaviour
Just loads forever. 

### Can you reproduce this problem on https://try.nextcloud.com?
No. This tablet **by design** does not connect to the internet. It only ever connects to a local lan, and the server only ever runs on the local lan with no connection to the broader internet (other then me moving files over by USB stick). so no cant reproduce on random internet facing service. 

### Environment data
Android version: 10

Device model: Samsung tablet

Stock or customized system: NA

Nextcloud app version: Not sure, still waiting to see if the app times out or gives some other information or something. Will wait five minutes then edit this comment. 

Nextcloud server version:  22.2.3

Reverse proxy: idk what that is

### Logs
its really hard to annonimise logs so I wont bother unless somone tells me its absolutly nessisary.

### PR DESCRIPTION
**Pull request by Unpublished**
Fixes #9536 
Fixes #9771

~~Not sure how to handle detekt failures yet...doesn't look solely related to changes in this PR.~~

- [ ] Tests written, or not needed

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
> Not sure how to handle detekt failures yet...doesn't look solely related to changes in this PR.

From [the detekt logs](https://github.com/nextcloud/android/runs/5309415939?check_suite_focus=true):

```
/home/runner/work/android/android/src/main/java/com/owncloud/android/ui/NextcloudWebViewClient.kt - 20min debt
	TooGenericExceptionCaught - [e] at /home/runner/work/android/android/src/main/java/com/owncloud/android/ui/NextcloudWebViewClient.kt:32:18
```

In this case I suppose catching any exception makes sense, so just add `@Suppress("TooGenericExceptionCaught")` to the class.

Besides that,

> Fixes https://github.com/nextcloud/android/issues/9536
Fixes https://github.com/nextcloud/android/issues/9771

How do you know those issues are actually fixed by this change? Do you have the same issues?

**Comment by Unpublished** [comment]
> In this case I suppose catching any exception makes sense, so just add `@Suppress("TooGenericExceptionCaught")` to the class.

Sounds fine to me, done.

> 
> Besides that,
> 
> > Fixes #9536
> > Fixes #9771
> 
> How do you know those issues are actually fixed by this change? Do you have the same issues?

Yep, I'm having the same issues.

**Comment by AlvaroBrey** [comment]
rebased and fixed conflicts

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Thank you @Unpublished! I'll try to get this into 3.19.1 RC2

**Pull request merged**
