### PR TITLE
Use png instead of vector drawable for bitmap

### LINKED ISSUE #4842: Crash in image viewer
STR:
1. Download an image
2. Open the downloaded image by clicking it
3. Tap anywhere in the image area to hide nav bar
4. Wait 1s to not trigger double tap to zoom
5. Tap again to reshow nav bar -> crash

************ CAUSE OF ERROR ************

```
android.content.res.Resources$NotFoundException: Drawable com.nextcloud.client:drawable/backrepeat with resource ID #0x7f08021b
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/backrepeat.xml from drawable resource ID #0x7f08021b
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:854)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:634)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:902)
	at android.content.res.Resources.getDrawable(Resources.java:841)
	at android.content.res.Resources.getDrawable(Resources.java:816)
	at com.owncloud.android.ui.preview.PreviewImageFragment.toggleImageBackground(PreviewImageFragment.java:771)
	at com.owncloud.android.ui.preview.PreviewImageFragment.togglePreviewImageFullScreen(PreviewImageFragment.java:754)
	at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$onCreateView$1$PreviewImageFragment(PreviewImageFragment.java:197)
	at com.owncloud.android.ui.preview.-$$Lambda$PreviewImageFragment$grkrZeoYp6ERIY3D7bncEWhFG8g.onClick(Unknown Source:2)
	at com.github.chrisbanes.photoview.PhotoViewAttacher$3.onSingleTapConfirmed(PhotoViewAttacher.java:197)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6882)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: <bitmap> requires a valid 'src' attribute
	at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:849)
	at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:770)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
	at android.content.res.ResourcesImpl.createFromXmlForDensity(ResourcesImpl.java:1506)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:838)
	... 17 more
```

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30090090
Build flavor: gplay

************ FIRMWARE ************
SDK: 28
Release: 9

### PR DESCRIPTION
**Pull request by Unpublished**
More information: https://issuetracker.google.com/issues/37063170

Fixes #4842

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
> Maybe we should increase than the px?

if we fallback to px, then yes we need to have the image per density (I know we didn't have before moving to vector, but should have it now then)

**Comment by jancborchardt** [comment]
Not sure if I understand correctly, but yes it should be made so that on any device the checkers are a regular size. So not super tiny on high-res for example. Just like before. :)

**Comment by Unpublished** [comment]
Missed that, added density variants and it indeed looks better now :)

**Comment by Unpublished** [comment]
Missed that, added density variants and it indeed looks better now :)

**Comment by tobiasKaminsky** [comment]
now this looks great again :-D

**Comment by tobiasKaminsky** [comment]
@Unpublished thanks for your contribution.
As you are also a member of Nextcloud, next time you can directly push a branch to our repo.
This makes reviewing a bit easier for others.

Thanks again!

**Comment by Unpublished** [comment]
Will delete my fork so I don't forget next time.

/backport to stable-3.9

**Pull request merged**
