### PR TITLE
Improve push

### PR DESCRIPTION
**Pull request by mario**
This fixes push magic for various use-cases.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
PushUtils in modified have private functions, but in gplay you changed it to public.
I assume that there is no way to have only one file as they are otherwise identical?

Besides that  :+1:

**Comment by mario** [comment]
I will change them to public, thx for noticing.

**Comment by mario** [comment]
@tobiasKaminsky approve again pls.

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger please approve

**Comment by AndyScherzinger** [comment]
👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please reapprove ;)

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
