### PR TITLE
Migrate RemoteOperation.execute calls to User

### PR DESCRIPTION
**Pull request by ezaquarii**
- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
@ezaquarii ready for review?

**Comment by ezaquarii** [comment]
@AlvaroBrey Sorry, wrong signalling. Not done yet.

**Comment by ezaquarii** [comment]
@AlvaroBrey 
```
SEVERE: Execute com.******.client.EndToEndRandomIT.pseudoRandom: FAILED
```
However, I do not see any error stack trace in the build output. Not sure what to do about it.

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey
> 
> ```
> SEVERE: Execute com.******.client.EndToEndRandomIT.pseudoRandom: FAILED
> ```
> 
> However, I do not see any error stack trace in the build output. Not sure what to do about it.

Don't worry, `EndToEndRandomIT` is the definition of flaky.

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Thank you @ezaquarii !

**Pull request merged**
