### PR TITLE
only add account, but not go to main app

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Usage: start com.nextcloud.client/com.owncloud.android.authentication.AuthenticatorActivity with "onlyAdd" set to true as boolean

Wished by @grote

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by grote** [comment]
Thanks a lot @tobiasKaminsky for the quick PR!

Unfortunately, it doesn't seem to work for me. I tried to debug it, but for some reason I can't even build master from a fresh checkout with `./gradlew assembleGeneric`. Tried debugging this, but gave up.

So I need to guess here: Maybe `onNewIntent()` isn't called and the flag needs to be checked in `onCreate()` instead?

**Comment by tobiasKaminsky** [comment]
> Unfortunately, it doesn't seem to work for me. I tried to debug it, but for some reason I can't even build master from a fresh checkout with `./gradlew assembleGeneric`. Tried debugging this, but gave up.

My fault :-( I changed library but did not merged the corresponding client PR in time.



> So I need to guess here: Maybe `onNewIntent()` isn't called and the flag needs to be checked in `onCreate()` instead?

True. I just tested it with having NC app up and running.
Now it should also work if the app never has been started.

**Comment by grote** [comment]
Awesome thank! Now both works, compiling and only adding the account. The workflow I need is now perfect, right after adding the account, the user gets back to where they started.

Ready to merge from my side!

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky feel free to merge,Looks good Code-wise

**Pull request merged**
