### PR TITLE
Move magic numbers in layout files to @dims

### PR DESCRIPTION
**Pull request by divayprakash**

### CODE REVIEW

**Comment by divayprakash** [comment]
Closes  #12

**Comment by divayprakash** [comment]
@AndyScherzinger Could you please add the **hacktoberfest** label to this PR?

**Comment by AndyScherzinger** [comment]
Hi @divayprakash can you have a look at your changes? The builds are constantly failing!
--> e.g. ```/drone/src/github.com/nextcloud/android/build/intermediates/res/merged/debug/values/values.xml:390: error: Error: Float types not allowed (at 'shadow_dx' with value '0.5').```

Did you test your Changes in Android Studio / compile the app? :wink:

**Comment by divayprakash** [comment]
@AndyScherzinger Sorry about that, I'll fix this up ASAP.

**Comment by divayprakash** [comment]
@AndyScherzinger Build successful at 2135b13

**Comment by AndyScherzinger** [comment]
Nice work @divayprakash! @tobiasKaminsky or I will have a final look at it this weekend, latest beginning of next week! Thanks for your contribution!

**Comment by divayprakash** [comment]
@AndyScherzinger Could you add me to the GitHub organization?

**Comment by AndyScherzinger** [comment]
Hi @divayprakash Thanks for the code contribution! :+1: 

I can't add you since I do not have the technical permission to do that. @jancborchardt @jospoortvliet can you add @divayprakash to the organization and Android team please? :smiley:

**Comment by LukasReschke** [comment]
> You've invited Divay Prakash to Nextcloud! They'll be receiving an email shortly. They can also visit https://github.com/nextcloud to accept the invitation.

Done.

**Comment by AndyScherzinger** [comment]
Thanks @LukasReschke :+1:

**Pull request merged**
