### PR TITLE
remove CustomEditTextField

### LINKED ISSUE #4619: fail on logon
### Actual behaviour
Fail when push logon button.

### Environment data
Android version: 7.1.2

Device model: Meizu M6note fw 7.2.0.0A

Stock or customized system: stock. tested again after fresh installation.

Nextcloud app version: all 3.*

Nextcloud server version:16.0.5

#### Nextcloud log (data/nextcloud.log)
```
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.Layout.getLineForOffset(int)' on a null object reference
at android.widget.Editor.updateCursorPositionMz(Editor.java:7836)
at android.widget.Editor.updateCursorsPositions(Editor.java:1963)
at android.widget.TextView.getUpdatedHighlightPath(TextView.java:5783)
at android.widget.TextView.onDraw(TextView.java:5969)
at com.owncloud.android.ui.components.CustomEditText.onDraw(CustomEditText.java:71)
at android.view.View.draw(View.java:17305)
at android.view.View.updateDisplayListIfDirty(View.java:16282)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.draw(View.java:17308)
at com.google.android.material.textfield.TextInputLayout.draw(TextInputLayout.java:1577)
at android.view.View.updateDisplayListIfDirty(View.java:16282)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.draw(View.java:17308)
at android.widget.ScrollView.draw(ScrollView.java:1743)
at android.view.View.updateDisplayListIfDirty(View.java:16282)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.updateDisplayListIfDirty(View.java:16277)
at android.view.View.draw(View.java:17066)
at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
at android.view.View.draw(View.java:17308)
at com.android.internal.policy.DecorView.draw(DecorView.java:786)
at android.view.View.updateDisplayListIfDirty(View.java:16282)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2837)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2639)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2241)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1276)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6483)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:888)
at android.view.Choreographer.doCallbacks(Choreographer.java:700)
at android.view.Choreographer.doFrame(Choreographer.java:635)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:874)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6381)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M6Note
Model: M6 Note
Id: N2G47H
Product: meizu_M6Note_CN

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: m1721.Flyme_7.0.1545878716

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #4619 

- remove CustomEditTextField
- do not use fancy material header for textInput, but regular TextView
- do not show QR button on legacy login
- fix layout in tablet mode

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Wouldn't this remove the url special handling implemented by @mario? Which was only needed for customers I think anyways...

**Comment by tobiasKaminsky** [comment]
True, but I do not recall any customer that is actually using it…
It is also a test, so that the reporter of the issue can test the apk.

**Comment by mario** [comment]
There is one customer. But I am on vacation today xD

**Comment by AndyScherzinger** [comment]
> There is one customer. But I am on vacation today xD

Which is highly deserved 👍

**Comment by tobiasKaminsky** [comment]
> There is one customer. But I am on vacation today xD

Ah, did not knew. Enjoy your vacation.
We can have a chat about it tomorrow.

**Comment by tobiasKaminsky** [comment]
@ambraspace I pushed another try.
This time I removed TextInputLayout, to see if this helps.
Can you give it another try once the apk is built?

**Comment by ambraspace** [comment]
> @ambraspace I pushed another try.
> This time I removed TextInputLayout, to see if this helps.
> Can you give it another try once the apk is built?

@tobiasKaminsky, this one presented the activity for entering Web server address, but failed upon checking the connection (I guess it happened when it tried to show the activity with username/password.

`************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
 at com.owncloud.android.authentication.AuthenticatorActivity.setOldLoginVisibility(AuthenticatorActivity.java:1344)
 at com.owncloud.android.authentication.AuthenticatorActivity.onGetServerInfoFinish(AuthenticatorActivity.java:1298)
 at com.owncloud.android.authentication.AuthenticatorActivity.onRemoteOperationFinish(AuthenticatorActivity.java:1199)
 at com.owncloud.android.services.OperationsService.lambda$dispatchResultToOperationListeners$0(OperationsService.java:727)
 at com.owncloud.android.services.-$$Lambda$OperationsService$2BVgsxDpOpa4JqgzeD7OGZBLSiI.run(lambda)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6285)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:939)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:829)

************ APP INFORMATION ************
ID: com.nextcloud.android.qa
Version: 11151
Build flavor: qa

************ DEVICE INFORMATION ************
Brand: Meizu
Device: M6Note
Model: M6 Note
Id: N2G47H
Product: meizu_M6Note

************ FIRMWARE ************
SDK: 25
Release: 7.1.2
Incremental: m1721.Flyme_6.0.1510480068`

**Comment by tobiasKaminsky** [comment]
@ambraspace thanks for testing, once again I pushed a fix.

But it seems that the TextInputLayout stuff is misbehaving. 
Once you can confirm that it is now working, we need to find a way to restore old UX and still prevent your device from crashing the app.
At least we have narrowed it down :+1:

**Comment by ambraspace** [comment]
> @ambraspace thanks for testing, once again I pushed a fix.
> 
> But it seems that the TextInputLayout stuff is misbehaving.
> Once you can confirm that it is now working, we need to find a way to restore old UX and still prevent your device from crashing the app.
> At least we have narrowed it down +1

@tobiasKaminsky This one is OK. No error produced. Thanks!

**Comment by tobiasKaminsky** [comment]
@ambraspace once again :-)

Can you then also please type in server address, wait until login loaded, then wait > 60s so that you see a "revert to old login" and see if this is also showing fine?

**Comment by ambraspace** [comment]
> @ambraspace once again :-)
> 
> Can you then also please type in server address, wait until login loaded, then wait > 60s so that you see a "revert to old login" and see if this is also showing fine?

@tobiasKaminsky Yes, the old one also works fine (v.11156).

**Pull request merged**
