### PR TITLE
Fix login colors in NC25

### PR DESCRIPTION
**Pull request by AlvaroBrey**
- AuthenticatorActivity: fetch user capability after account creation
- AuthenticatorActivity: on NC25, don't tint status/navigation bars

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
> * AuthenticatorActivity: fetch user capability after account creation

Why do we need them? They will be fetched on first loading of root folder. Or is it too late and thus some colors are not shown correctly?
I remember that therefore we fetch capabilities during login?

**Comment by AlvaroBrey** [comment]
> > * AuthenticatorActivity: fetch user capability after account creation
> 
> Why do we need them? They will be fetched on first loading of root folder. Or is it too late and thus some colors are not shown correctly?

It's too late, the FAB and permission dialog will get drawn before the SynchronizeFolderOperation completes.

>  I remember that therefore we fetch capabilities during login?

We fetch the capabilities for the server, but in NC25 the color capability when logged in (calculated from user background) can be different from the one from the server.  See https://github.com/nextcloud/android/issues/10915 and https://github.com/nextcloud/android/issues/10638#issuecomment-1285070831 for context

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
Thanks for explanation!

**Pull request merged**
