### PR TITLE
Trying to generalize avatar setting.

### PR DESCRIPTION
**Pull request by przybylski**
@AndyScherzinger as your request for help with generalization I made this.

### CODE REVIEW

**Comment by przybylski** [comment]
DISCLAIMER: I haven't tested it ;)

**Comment by AndyScherzinger** [comment]
Tested the branch, works! :+1: 
Thanks a lot for your help @przybylski! You're the :bomb:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you :+1:  ?

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
