### PR TITLE
Add logcat infos to readme

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Especially the third option is very nice as it does not require root nor adb.
Thanks @jasonbayton

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 fine by me!

**Comment by jasonbayton** [comment]
Have you tested the output from the 3rd option yet @tobiasKaminsky ? I saw a lot of detailed info there but didn't really verify with anyone it was what you want as far as logs go.

**Comment by tobiasKaminsky** [comment]
After you suggestion in one thread I got a logcat from someone and expected that this was generated by "your" option.
But now, after trying it by myself, it does not generate a logcat, but instead a very detailed dump of the device with many many categories, like meminfo, Historical broadcasts summary.

I will have a detailed look tomorrow and maybe remove the third option.

Thank you for pointing this out :+1:

**Comment by tobiasKaminsky** [comment]
Removed third option, replaced it by app links.
Thanks again @jasonbayton

**Comment by AndyScherzinger** [comment]
👍 looks good to me

**Comment by mario** [comment]
👍

**Pull request merged**
