### PR TITLE
Better handling of temp file during upload

### LINKED ISSUE #2505: tmp folder is filled by auto upload
### Actual behaviour
When activating auto upload all files are copied into the folder /internal/nextcloud/tmp and left there after the upload. After some months of taking fotos and videos with my phone this is wasting more than 6GB of data. Deleting the files in the tmp folder causes a complete re-upload of all fotos and videos. My fotos and videos are stored by default on an SD card.

### Expected behaviour
I expected that the tmp folder will be cleared after the upload.
 
### Steps to reproduce
1. Choose a folder on an SD card for auto upload

### Environment data
Android version: 7.0 Security Patch 01.02.2018

Device model: Samsung J5 2017

Stock or customized system: Stock system

Nextcloud app version: 3.1.0

Nextcloud server version: 13.0.0

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix https://github.com/nextcloud/android/issues/2532
Fix #2505 

- use internal temp directory as it seems that external sd storage might not get deleted
- always try to delete temp file

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by mario** [comment]
What if the internal temp "drive" doesn't have enough space, which will often be the case in such strange setups? :)

**Comment by tobiasKaminsky** [comment]
Good question…
We can first check this, or return a correct error message, if copying is not working.
What do you think?

**Comment by mario** [comment]
@tobiasKaminsky both is good. First we check and if something happens during the copying process, we return the correct error message.

**Comment by tobiasKaminsky** [comment]
> both is good. First we check and if something happens during the copying process, we return the correct error message.

This is now both implemented.

**Comment by AndyScherzinger** [comment]
👍 looks good but needs a rebase 😃

**Pull request merged**
