### PR TITLE
Added new restore icon (to replace the small one)

### PR DESCRIPTION
**Pull request by Shagequi**
Fixing issue : [#4848 ](https://github.com/nextcloud/android/issues/4848)

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Once you think the PR is good for review, please add "2. to review" as label.

**Comment by tobiasKaminsky** [comment]
As you are a member, you can also push a branch / PR directly to our nextcloud repo.
This makes reviewing a bit easier for the other contributors :-)

**Comment by tobiasKaminsky** [comment]
Thank you for your PR.
How it looks like:
image

How the restore button of web ui looks like:
image

How it previously looked:
image


Can you try to re-use the old icon, but make it bigger?
Original svg logo can be found here: https://github.com/nextcloud/android/blob/f8801115f2f9a27b6da52aaf5b1c36940b1f2652/drawable_resources/history.svg

**Comment by Shagequi** [comment]
@tobiasKaminsky 

Thanks for these advices and guidelines 
In my opinion, I find the icon too "bold" : 

Screenshot_20191121-174622_Nextcloud

But I may apply this one if you want to.

**Comment by AndyScherzinger** [comment]
@jancborchardt can you comment on the @nextcloud/designers preference regarding the icon? (Last two comments). Thanks ❤️

**Comment by Shagequi** [comment]
@AndyScherzinger @tobiasKaminsky 
It would be a pleasure to push on your repository, except that I don't really understand the relationship between the guidelines and the current situation of the repo branches.

I'm very motivated to help you improve this application, but these branches don't really motivate to do the things properly (since the order is not very present)

Don't you want help to clean up the branches and issues so that we can have a proper and workeable project to work on ?

**Comment by jancborchardt** [comment]
Yep, the current icon is indeed too thick, thanks for looking into that @Shagequi

Is this a Material design icon? If not, can we pick one from Material icons?
Cause it seems a bit big and thin now, and the arrow is not so visible.
And then could you also do a pull request for server to replace the icon in `core/img/actions` so it is consistent – thanks a lot! :)


@Shagequi regarding branches:
You are a member of the Nextcloud github org, so you do not need a fork. Simply create a branch on this repository, like you did on your fork.
That way if changes are needed, other collaborators can do those too.
Master is the main branch and everything else are feature branches (pull requests). Do you mean there are  a lot of outdates branches lying around which should be cleaned up?

**Comment by jancborchardt** [comment]
(This is off-topic, but to clean up branches, a good starting point is to go through the stale branches and delete those not needed anymore: https://github.com/nextcloud/android/branches/stale :)

**Comment by tobiasKaminsky** [comment]
> Is this a Material design icon? If not, can we pick one from Material icons?

I thought I picked it up from server repo? :thinking:

**Comment by tobiasKaminsky** [comment]
@Shagequi let us have this discussion in a new ticket please.
@jancborchardt you should know it better and not start off topic here!

**Comment by AndyScherzinger** [comment]
> Is this a Material design icon? If not, can we pick one from Material icons?

It is looking like one, while I would suggest:
https://materialdesignicons.com/icon/replay
replay

> I thought I picked it up from server repo? 🤔

You did, and the server's icon is _not_ a material design icon

**Comment by Shagequi** [comment]
@AndyScherzinger I approve this icon, more visible :)

**Comment by tobiasKaminsky** [comment]
I am fine with this material icon, but what about @jancborchardt ?

**Comment by jancborchardt** [comment]
Yes, the icon was correctly picked from the server repo. :) However @Shagequi is right that the server icon is too bold. Which is why I said above:

> And then could you also do a pull request for server to replace the icon in core/img/actions so it is consistent – thanks a lot! :)

And yes, the Material replay icon looks good!

**Comment by tobiasKaminsky** [comment]
@Shagequi is this really the material icon? For me it looks somehow the same like the old one…?

**Comment by Shagequi** [comment]
@tobiasKaminsky 

Here is the difference between the two icons :

NextCloud : 
Screenshot_20191125-145735_Nextcloud

My version :
Screenshot_20191125-145746_kDrive

Unless I'm mistaken, the one I propose has been redesigned by one of our UI designer.
So it's based on Material.

**Comment by tobiasKaminsky** [comment]
> It is looking like one (but isn't), while I would suggest:
> https://materialdesignicons.com/icon/replay
> replay
> 
> What do you think @jancborchardt @tobiasKaminsky @Shagequi ?
> 
> > I thought I picked it up from server repo? thinking
> 
> You did, and the server's icon is _not_ a material design icon

Andy suggested the one by Android's material design and Jan approved it, so please use this one.

**Comment by AndyScherzinger** [comment]
> Andy suggested the one by Android's material design and Jan approved it, so please use this one.

@Shagequi would yoou replace it within this PR or should I? (fine either way) 😃

**Comment by Shagequi** [comment]
@AndyScherzinger Yes I will replace the icon today :)

**Comment by AndyScherzinger** [comment]
celebrate

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @jancborchardt see screenshot, fine from my pov, please merge after final review :)
device-2019-11-28-181634

**Comment by tobiasKaminsky** [comment]
Thanks for your PR @Shagequi :tada

**Comment by jancborchardt** [comment]
Good stuff @Shagequi! :) As mentioned above, could you also open a pull request to change the same in the server:
https://github.com/nextcloud/server/blob/master/core/img/actions/history.svg
(There’s also a .png version of it.)

Just make sure it’s the same dimensions, and that it’s compressed. You can compress SVG with the scour command in this script: https://github.com/nextcloud/server/blob/master/build/image-optimization.sh#L10

**Pull request merged**
