### PR TITLE
AS Arctic Fox | 2020.3.1 Update to Gradle/AGP 7.0.2

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* Also removed obsolete DSL element 'dexOptions'

It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky see https://drone.nextcloud.com/nextcloud/android/2216 the base image is still on Android 8 and JDK11 isn't active so the builds fail, do you know where update this?

**Comment by tobiasKaminsky** [comment]
This is very similar to https://github.com/nextcloud/android/pull/8781

**Comment by AndyScherzinger** [comment]
Yes but as always with dependabot it doesn't get all changes needed for an AS upgrade but does one lib per pr...

**Comment by AndyScherzinger** [comment]
I'll fix spotbugs when I get back from vacation

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I added all missing changes you did on #8781 to this PR and fixed some spotbugs warnings/errors to make the code checks happy :)

**Comment by AndyScherzinger** [comment]
Hi @AlvaroBrey thanks for taking a look. I checked the failing tests and screenshots while none of that should be related to this PR's changes.

**Comment by AlvaroBrey** [comment]
> Hi @AlvaroBrey thanks for taking a look. I checked the failing tests and screenshots while none of that should be related to this PR's changes.

Hey @AndyScherzinger, I rebased this because of some weird interactions between the Android gradle plugin, JaCoCo and Kotlin 1.5 that we saw over at the library (see https://github.com/nextcloud/android-library/pull/715 for reference). I merged Kotlin 1.5 here this week, so I wanted to make sure this didn't happen as well.

Don't worry about the screenshot tests, they are currently broken.

**Review by AlvaroBrey — APPROVED** [review]

**Pull request merged**
