### PR TITLE
Fix 1521

### PR DESCRIPTION
**Pull request by mario**
Also excludes pretty much everything else, so you only restore the app itself I guess. 

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
Unsure we should do this (I'd rather prefer smooth migration) but *shrug*...

**Comment by AndyScherzinger** [comment]
What do you think @tobiasKaminsky? 
Imho (if done right 😝) the what'S new "first run" could be used for cleaning up backup/restore data that should not be in place, like certain DB entries.

**Comment by tobiasKaminsky** [comment]
We can use "firstRun" to detect, but DB cleanup or similar tasks should be done in a new function.

So this does what? Prevent apps like Titanium to backup data? If so, then there is no need to backup the app at all, because then it is at restore always a vanilla app?

**Comment by mario** [comment]
Indeed. So maybe just disable backup? *shrug*

**Comment by tobiasKaminsky** [comment]
For a backup we "only" need to have the account, auto upload and "keep available offline" restored. 
Or am I missing something?
Everything else (favorites, file cache, ...) can be retrieved during runtime.

While auto upload and "keep available offline" is harder to do, we maybe should focus on restoring account? And if we (somehow) can detect that it is a backup, we can show an hint that auto upload and keep available offline needs to be configured again.

**Comment by mario** [comment]
Closing this.

**Pull request closed without merging**
