### PR TITLE
Link to providers list in the setup screen

### LINKED ISSUE #53: Link to a list of Nextcloud providers on the setup screen
I bet many new users are unfamiliar to the concept of ownCloud/Nextcloud requiring URL/user/pass and not just user/pass.

To improve usability, I suggest that we put a link next to the server address box in the setup screen, saying: "Looking for a server? Get it here." And we link it to "https://owncloud.org/providers/" or the equivalent Nextcloud page when it is ready.

Apart from making it usable for Dropbox-minded users, this has the extra benefit of pointing more customers to the own/Next-cloud providers in that list, and this in turn increase the licensing fees Nextcloud can negotiate to get from the said providers.

PR: #561

### PR DESCRIPTION
**Pull request by mabkenar**
This will close #53.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Thank you for your PR. 
Next you can also push the changes as a new branch in our repository. This will make testing / collaboration much more easier.

Can you also provide a screenshot?

**Comment by mabkenar** [comment]
> Next you can also push the changes as a new branch in our repository.

Oh I forgot that this was the way we used to do it. Ok, sorry! next time! 

> Can you also provide a screenshot?

Unfortunately not, since I haven't built it on my own machine. But the changes to the UI should be trivial, since this PR only changes a text string (and its associated link address) that already exists in the UI.

What is the best/fastest way to make a screenshot after a change in the code? I would be grateful to know.

**Comment by tobiasKaminsky** [comment]
Best way for screenshot is using an emulator (if you have set up one)

**Comment by tobiasKaminsky** [comment]
screenshot_1484928397

- I think we need a line break
- it should be "click here to get one from a provider" as otherwise the user do not know that this is clickable
@eppfel what do you think?

**Comment by eppfel** [comment]
Yes, to both. Two sentences, two lines. And an imperative sentence is necessary.

**Comment by tobiasKaminsky** [comment]
@mabkenar can you do the two fixes?
Thank you for this contribution!

**Comment by AndyScherzinger** [comment]
device-2017-01-25-172944

**Comment by AndyScherzinger** [comment]
👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky or @mario please review and 👍 
This is a really minor change so I'd say we push it out with 1.4.2

**Comment by tobiasKaminsky** [comment]
👍 
1.4.2 is also fine 👍

**Comment by mabkenar** [comment]
Thank you all for reviewing, making screenshots, and approving this change. While this is a small change technically, I believe it fills a very important information gap for new users. We can of course improve the setup experience with a more streamlined process in the future.

**Pull request merged**
