### PR TITLE
Whats new 3.0

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This is for slides that will be shown on 3.0 final, so we can add them a bit later.

- add 3.0 features (E2E image is missing)
- add bullet points, see below
- improved lint:  do not warn/error on unused translated ressources

 -> 

Current state, image for E2E is missing, old image, will also have bullet point list:

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@jancborchardt suggests to have a written text instead of list.
(I will keep the list option in, as we maybe have in future only a short text)

**Comment by jancborchardt** [comment]
Nice! The only thing to improve would be a bit of whitespace above the heading »What’s new …«, and if possible vertically aligning the whole content. Otherwise :+1: :)

**Comment by AndyScherzinger** [comment]
Nice as for the changes except I have to say I dislike the graphics since they all have a different visual style which I find quite disturbing but that might be just me :/

- E2e: Nc website style multi blue, thinner line style 
- Device images: details, Android ish and full colored
- Ipv6: bold lines, roundish and dual colored

**Comment by mario** [comment]
I also think bullets are easier to read than a bunch of text :)

**Comment by tobiasKaminsky** [comment]
@jancborchardt @AndyScherzinger @mario as I do not mind, please discuss this and then I can fix this.
As there are (luckily) not that much bugs in RC I think we can release end of January. So until then we need a conclusion.

**Comment by jancborchardt** [comment]
@AndyScherzinger yeah, true. I mean for the IPv6 logo I think it's ok, since that's just the logo of it – maybe we change the color?

Who did the original "what's new" graphics? Or maybe @Espina2, are you interested in updating them according to the website icons you made? :)

**Comment by comradekingu** [comment]
I had a go https://www.youtube.com/watch?v=1xeAY-9XvA8

---

New in 3.0.0 RC1

End-to-end encryption

Clickcable folder encryption, from any client.
Add clients by carring over 12 words.

Adaptive images

Small images are fast and work great for sharing.
Zoom in to download a full version.

IPv6 support

IPv6 when the server supports it, still the same
IPv4 if not.

---
The arrow is a few pixels to the right. It might even be removed.
Would be really sleek if the image frames were the same width as the border on the end-to-end encryption slide.

**Comment by jancborchardt** [comment]
@comradekingu the wording is mostly fine, I discussed it with @tobiasKaminsky. ("Clickable" is not smth done on mobile, and "carrying over 12 words" sounds a bit strange?

The room for improvement is in the images as mentioned.

**Comment by AndyScherzinger** [comment]
> Who did the original "what's new" graphics?

@jancborchardt they had been done by @eppfel afaik

**Comment by jancborchardt** [comment]
Ok, I will see to make another graphic for encryption based on the current file list slide. And for the IPv6 logo I'll modify the color a bit.

**Comment by jancborchardt** [comment]
And @eppfel you are very welcome to contribute again any time! :) The design team misses you, and I'm sure the Androids too!

**Comment by jancborchardt** [comment]
Here you go:
whats_new_end_to_end_encryption
whats_new_resized_images
whats_new_ipv6

SVG sources at https://cloud.jancborchardt.net/s/J7BZMiGQIGDwoNS (including a new _files.svg cause there was an error in the shadow)

**Comment by AndyScherzinger** [comment]
> The design team misses you, and I'm sure the Androids too!

Yes we do ❤️

**Comment by AndyScherzinger** [comment]
@jancborchardt 👍 looking good to me 😍

**Comment by jancborchardt** [comment]
@AndyScherzinger cool! :) Just updated the encryption lock icon color from black to same grey as the share icons, now it’s good to go!

**Comment by mario** [comment]
@jancborchardt what about moving to bullets rather than a text?

**Comment by jancborchardt** [comment]
@mario I explictly wanted to move to text since the short bullet lines breaking for 1 or 2 words just look strange. The text improvements come from me.

**Comment by mario** [comment]
@jancborchardt in that case, text needs to be significantly shorter.

**Comment by AndyScherzinger** [comment]
@jancborchardt could you then also take a look at #1990 just to not break things you discussed with Tobias please :)

**Comment by comradekingu** [comment]
ncadjusted3rc1

Encrypted folder 10px → Gives a nice even margin top left corner
Document and PDF folder 1px → to align with above change
All bars 2px ← to drive the point of equal margins home
Bottommost gray bar 11px ↓
Both bottom bars 1px ↓
Knocked 1px out of both the document and PDF icon vertically to have the icons align with the same margin top and bottom against the divider

My gripe here is there is no reasoning i can see as to why the bars are where they are, albeit now consistently so. I think 18px from the top (as opposed to 25-26 now) to align with the top part of the folder, along with the same rounding would look nice.

The alternative is equidistant, 3 equally spaced fields in between.

But the light gray one is bigger, why?

**Comment by tobiasKaminsky** [comment]
@jancborchardt please answer @comradekingu suggestions.
Plan is to have a final release with NC13 (if everything is working well), so we need this soon.

**Comment by comradekingu** [comment]
ncadjusted3rc1-1

Rounded off, fixed a shadowing inconsistency on one of the big bars.

**Comment by jancborchardt** [comment]
@tobiasKaminsky let's please merge as is. It's simply based on the original design by @eppfel and I'm merely adding a slide.

@comradekingu if you have detail suggestions, please open a separate pull request afterwards with before & after pictures. Thanks!

**Comment by tobiasKaminsky** [comment]
Last approval @jancborchardt @mario @AndyScherzinger

**Comment by AndyScherzinger** [comment]
👍 fine with me

**Comment by mario** [comment]
I disagree with the whole bunch of text, but since there are other, more important battles to be won, 👍

**Comment by eppfel** [comment]
Miss you too guys. ❤️

**Pull request merged**
