### PR TITLE
Grab Espresso results and apk

### PR DESCRIPTION
**Pull request by hannesa2**
I start to keep artifacts https://github.com/nextcloud/android/pull/8035#issuecomment-784820452 to download and give us the chance for a better investigation

### CODE REVIEW

**Review by tobiasKaminsky — APPROVED** [review]
Nice, I like the idea :+1:

**Review by AndyScherzinger — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
> white-Light-IT test failed: https://www.kaminsky.me/nc-dev/android-integrationTests/8046-Screenshot-white-Light-04-56

@hannesa2 the espresso results seem to be the same output as above link.

**Comment by hannesa2** [comment]
Now some artifacts are available
image

image

### Screenshot compare

It shows no problems

### The logcat would be interesting 

image

### One job there the post task fails complete
image

**Comment by hannesa2** [comment]
Storage consumption could be an issue. 
I keep artifacts for 5 days, maybe 2 are enough ?
Do we need the apk ?

**Comment by hannesa2** [comment]
### One job there the post task fails complete
image

**Comment by hannesa2** [comment]
> > white-Light-IT test failed: https://www.kaminsky.me/nc-dev/android-integrationTests/8046-Screenshot-white-Light-04-56
> 
> @hannesa2 the espresso results seem to be the same output as above link.

Yes, of course. 

Does it mean we don't need one of them ? 
If yes, we should collect pro and cons for each of them

**Comment by hannesa2** [comment]
This pull request could help to reduce that much emails. 

Eg. this could be obsolete now
image

**Comment by AndyScherzinger** [comment]
> Do we need the apk ?

No 👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky should the upload be dropped to your server? Less comfort, but quite a cut on runtime for the job.

**Comment by tobiasKaminsky** [comment]
Uploading it via artifacts has the big drawback than we have to download a zip file, extract it and open index.html.
Upload to server on the other hand is very easy to use.

```
0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:26 --:--:--     0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```
It seems that upload is running into brute force on my server. 
All in all these are only 25 files and 5 folders, so only 30 curl requests, but if each takes ~25s is it 12min in total.

--> I will have a look

**Comment by hannesa2** [comment]
> All in all these are only 25 files and 5 folders, so only 30 curl requests, but if each takes ~25s is it 12min in total.

Yes, I observed a loop for a lot of minutes to upload stuff. But it was infinity

**Comment by tobiasKaminsky** [comment]
I restarted Screenshot Tests, https://github.com/nextcloud/android/pull/8046/checks?check_run_id=1978348530

Let us have a look if it is better now.

**Pull request merged**
