### PR TITLE
if privacy url is set to a pdf file, do not open it inline but external

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Title says it all, otherwise the pdf was not shown...
(needed for branding as some wants to link a pdf)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 please fix codacy though, other issue would imho be to maybe reverse it, no? Like if it is text/html mime type then webview, else call general view intent.

**Comment by tobiasKaminsky** [comment]
Your idea will unfortunately not work with our privacy url: https://nextcloud.com/privacy 
Mimetype of "privacy" is unknown. It indeed would work back in 90s, where everything ended with "html" or "php" ;-)

**Comment by AndyScherzinger** [comment]
You're right :)

**Comment by mario** [comment]
👍

**Pull request merged**
