### PR TITLE
🎨 Material 3️⃣

### LINKED ISSUE #10640: 🎨 Use Material 3️⃣theming implementation
implement Material 3 via https://github.com/nextcloud/talk-android/issues/2312 theming functions

### PR DESCRIPTION
**Pull request by AlvaroBrey**
- [x] needs https://github.com/nextcloud/android-common/pull/7
- [x] change common version to tag
- [x] background and icons on tabs
- [x] background to surface for bottom sheets 
- [x] settings activity background color wrong most of the time 
- [x] icon coloring on multi-seclect toolbar
- [x] overflow menu tinting on profile toolbar
- [x] adapt color for ripple effect on toolbar `MaterialButton`s
- [x] fast scrollers color
- [x] account selection dialog: the selected "check" is tinted to old primary
- [x] account info (click on user while in manageaccountsactivity) background is old primary
- [x] pop-up menu background on content as well as overflow menu background on toolbar are still blue, best to go for generic dark/light grey/white tones and theme hard via styles.xml
- [x] markwon markdown rendering not respecting dark/light primary color
- [x] link share details fragment 
- [x] backup contacts and calendars fragment
- [x] multi-select (actionmode) color is plain wrong
- [x] preview activity toolbar text color 
- [x] fix theming coloring on screenshot tests 
- [x]  colors are default primary right after login (as FDA doesn't refresh after login)
   -  FDA _does_ refresh after login, but the user capabilities aren't fetched yet
       - capabilities are fetched in AuthenticatorActivity but not stored
       - done in https://github.com/nextcloud/android/pull/10717/commits/e7d6715a108ee38455a9a0deebf5c5accfcd5084
- [x] what to do with login/etc screens, and drawer header? it doesn't work very well. see https://github.com/nextcloud/android/tree/m3-firstrun for some attempts
    - Generally we need to discuss what to do with places (like drawer header and login screen) where we used to expect the primary color with no changes.
    - Decided that for now they will be left as is

Fixes #10640, #10643

**NOTE FOR REVIEWERS**: I suggest enabling "hide whitespace changes" in the github diff for a more pleasant experience

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Sharing fragment got revamped for m3:

|before|after|
|---|---|
|share_before|share_after|

**Comment by AlvaroBrey** [comment]
@tobiasKaminsky @AndyScherzinger this is finally ready for testing/review. Still pending merge of the common PR and doing a tag release there, before this can be merged.

This ended up, as feared, being a monstrous PR both in terms of amount of commits and modified files. Most changes to existing files are pretty straightforward so I'd recommend focusing on new and deleted files. But specially needed is some smoke testing.

To see a before/after, the easiest way is to use the diff view for the screenshots, which are also updated in this PR.

**Review by AlvaroBrey — COMMENTED** [review]
@AndyScherzinger in the "new file" bottom sheet (https://github.com/nextcloud/android/pull/10717/files#diff-632953d8eac3fffe03cb3b5bcceb06a286b1d40c79b265bbc4b056f8e1ffbd15) it seems you removed all dividers except the one for folder info. Is this intentional?

**Comment by AndyScherzinger** [comment]
> seems you removed all dividers except the one for folder info. Is this intentional?

@AlvaroBrey yes, that was one of the feedback items from the designers in the m3 files app review call.

**Review by AndyScherzinger — APPROVED** [review]
fine by me

**Comment by AndyScherzinger** [comment]
Fine by me from a smoke testing perspective since I run this branch as my production setup since the beginning.

Only bug I consistently have is that the theming of the settings activity is mixed (light toolbar, dark content, separator lines) when opening the first time, but is okay the second time (light toolbar, light content, no separator lines) on my OP9Pro on Android 12.

**Comment by szaimen** [comment]
I just tested this and it seems like that templates are not shown anymore. Not sure though if that bug is already present in master.

| 3.21.2 | this pr |
|---|---|
|  Screenshot_20221012-094927_Nextcloud | Screenshot_20221012-094854_Nextcloud QA |

**Comment by AndyScherzinger** [comment]
@szaimen this works fine for me on c.nc.c could you maybe test there again so we know it's is not a server issue you are facing?

**Comment by szaimen** [comment]
@AndyScherzinger I can open an issue if you think that the issue is unrelated ot this PR :)

**Comment by AndyScherzinger** [comment]
@szaimen yes please and maybe send a test account to the devs? :)
And yes,  external storage might play a role, can't say for sure but then the client shouldn't matter imho.

**Comment by AlvaroBrey** [comment]
@szaimen try dragging the bottomsheet up. It doesn't auto-expand anymore I think

**Comment by szaimen** [comment]
> @szaimen try dragging the bottomsheet up. It doesn't auto-expand anymore I think. We should probably add a drag indicator or something

I tried but they are simply not shown :/

**Comment by szaimen** [comment]
Another thing: the plus butron should be greyed out when the directory is read only:
Screenshot_20221013-090440_Nextcloud QA

**Comment by AndyScherzinger** [comment]
> Another thing: the plus button should be greyed out when the directory is read only:

fixed via https://github.com/nextcloud/android/pull/10717/commits/09bbded5679f8ba3a2fbcdbe2b2227df27b54c54 thanks @szaimen

**Comment by AlvaroBrey** [comment]
> Fine by me from a smoke testing perspective since I run this branch as my production setup since the beginning.
> 
> Only bug I consistently have is that the theming of the settings activity is mixed (light toolbar, dark content, separator lines) when opening the first time, but is okay the second time (light toolbar, light content, no separator lines) on my OP9Pro on Android 12.

I can no longer reproduce that since https://github.com/nextcloud/android/pull/10717/commits/4d6f74e22bb01051f987857aab38757260b1bf0c, are you sure it's still happening on this branch when up to date?

**Comment by AndyScherzinger** [comment]
> I can no longer reproduce that since https://github.com/nextcloud/android/commit/4d6f74e22bb01051f987857aab38757260b1bf0c, are you sure it's still happening on this branch when up to date?

Yes, constantly on my phone, I'll check if reproducable in an emulator

**Comment by AlvaroBrey** [comment]
> Yes, constantly on my phone, I'll check if reproducable in an emulator

Actually I can reproduce it, although only the dividers, not the rest.

**Comment by AndyScherzinger** [comment]
Screenshot_20221013_142222

Initial launch of settings on Android 12 with-google-api x86_64bit emulator

**Comment by AlvaroBrey** [comment]
Rebased on master, fixed conflicts and build errors

**Comment by AlvaroBrey** [comment]
Time to finally merge this and get it into dev! This took a great deal of effort. Thanks @AndyScherzinger for all your contributions, and also thanks @szaimen, @tobiasKaminsky for the help!

**Comment by szaimen** [comment]
🎉🎉🎉🎉🎉

**Comment by AndyScherzinger** [comment]
Whoop Whoop! 🎉

Nice to see this being merged 😎

**Pull request merged**
