### PR TITLE
hide outdated version warning if extended support is enabled

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Needs https://github.com/nextcloud/server/pull/15922

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by knckendev** [comment]
i clone project nextcloud android.But run in android studio  it show error 
Screen Shot 2019-06-14 at 9 40 31 AM

**Comment by AndyScherzinger** [comment]
Hi @knckendev, can you pull the master again. This is fixed now (after I merged #4137)

**Comment by knckendev** [comment]
> Hi @knckendev, can you pull the master again. This is fixed now (after I merged #4137)

ok thanks you

**Pull request merged**
