### PR TITLE
actual -> current

### PR DESCRIPTION
**Pull request by mabkenar**
Longman Dictionary says: Do not use actual to mean 'at the present time'. Use current or present
http://www.ldoceonline.com/dictionary/actual
http://english.stackexchange.com/questions/29654/using-actual-to-signify-current

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
What is the second change about? I see no difference.

**Comment by mabkenar** [comment]
@tobiasKaminsky There should be no other change. Only two replacement of actual -> current in line 143 and that's all. I am also confused why GitHub shows a (null) change in line 175. I checked, the lines are char-to-char the same.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky should be fine then imho.

**Comment by tobiasKaminsky** [comment]
It remains strange ;-)
:+1:

**Pull request merged**
