### PR TITLE
Disable analytics via manifest

### PR DESCRIPTION
**Pull request by mario**
Please make a point release with this.

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
RC1 is planned to be released on 28th.
Can you also give some background please? We do not have analytics enabled at built time, or?

**Comment by mario** [comment]
We also don't have it disabled. Since the GPlay version ships with Analytics, and even if we don't really track anything, Firebase still sends some random data which might not be compliant with GDPR, so we need to do it now.

This disables it.

**Comment by mario** [comment]
Ah, @tobiasKaminsky , can wait until 28th - I was smart enough to disable it via code earlier.

**Comment by ardevd** [comment]
:+1:

**Comment by mario** [comment]
@AndyScherzinger afaik all analytics code has been removed by @tobiasKaminsky earlier anyway, as far as I know :)

**Comment by mario** [comment]
So there's not much to brand :P

**Comment by AndyScherzinger** [comment]
> So there's not much to brand :P

I know but how could this feature (which has been built for paying customers) be activated by a customer after this PR has been merged?

**Comment by mario** [comment]
@AndyScherzinger it can't, for a good reason. Unless we implement a consent/consent withdrawal, this feature is useless.

**Comment by AndyScherzinger** [comment]
merged then :+1:

**Comment by mario** [comment]
Cool. As soon as we get a proper consent workflow (both on start-up and in settings), we can remove this.

**Pull request merged**
