### PR TITLE
Backport mail sharing

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Backport of #2671

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
I didn't have the change to test the backport yet but wanted to open the PR for code review etc. as soon as possible :)

**Comment by AndyScherzinger** [comment]
Backport: Tested and works

Please review @tobiasKaminsky @mario

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
