### PR TITLE
Lint: fix Obsolete SDK_INT Version Check

### PR DESCRIPTION
**Pull request by AndyScherzinger**
removing obsolete/legacy stylings

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
pinging @mario @tobiasKaminsky for review :)

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
rebased! pinging @mario for second approval

**Comment by mario** [comment]
v9 and 11? Really xD

👍

**Pull request merged**
