### PR TITLE
Use capability in SearchRemoteOperation

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [x] Tests written, or not not needed

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
tested the qa apk with external storage on my instance and it seems to work :)

**Comment by AlvaroBrey** [comment]
@tobiasKaminsky it seems like this broke `testGallerySearch`. Can you take a look?

**Comment by tobiasKaminsky** [comment]
I updated tests, so this should work again 🤞

**Review by AlvaroBrey — APPROVED** [review]

**Comment by szaimen** [comment]
Thanks @tobiasKaminsky and @AlvaroBrey for implementing this 💙

**Comment by AlvaroBrey** [comment]
Thank you @szaimen for the library part and your help! :)

**Comment by szaimen** [comment]
> Thank you @szaimen for the library part and your help! :)

You are welcome :)

**Pull request merged**
