### PR TITLE
Update user name with correct id found by user ocs call

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #1257 

There already was an existing function that updated accounts, so I extended this one.

So now there is no distinction between any NC version or old/new accounts, all are handled by the same:
- every existing/new account currently will have version 1
- an update is performed one time, correct id, set version to 2

We can discuss if and how we handle this once EOL of <NC12.

### CODE REVIEW

**Comment by mario** [comment]
Cool. Will review later. Cookies PR coming too?:)

**Comment by mario** [comment]
Looks decent, but please rebase.

**Comment by tobiasKaminsky** [comment]
It is one click in github, you can also do this ;-)

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
👍 fine by me but can we please please stop doing master merges to branches and use rebase :)

**Pull request merged**
