### PR TITLE
show SVG images

### PR DESCRIPTION
**Pull request by AndyScherzinger**
This PR adds support for viewing SVG images as requested in #457.

It adds a library to support proper rendering (since standard Android can't properly open/display e.g. inkscape svg files): https://github.com/nextcloud/android/pull/465/files#diff-c197962302397baf3a4cc36463dce5eaR51

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you take a look at this and also merge it to the beta? 
I tried but it only works for downloaded files, for the non-downloaded files it seems your thumbnail/preview logic gets triggered and nothing happens. Unfortunately I couldn't find the implementation which does that. Any help/hints are highly welcome.

**Comment by jancborchardt** [comment]
Wooo SVG support! :+1:

**Comment by mario** [comment]
What's the status of this PR?

**Comment by AndyScherzinger** [comment]
basically done, only thing is that it isn't compatible with @tobiasKaminsky's preview-thumbnail-fetching PR since for SVG we need to download the file to be able to render it on the client (no serverside SVG preview rendering available).

So this can be merged but then Tobias' PR would need to take care of not previewing SVG or Tobias' gets merged first than this one need to take care of this part.

**Comment by tobiasKaminsky** [comment]
We should get #69 merged soon. Otherwise this PR will stay there forever :/

**Comment by AndyScherzinger** [comment]
Closed in favor of #805

**Pull request closed without merging**
