### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by rakekniven**
Added missing versions.
Details are not known.

Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
The missing versions are already included included in the 3.30RC1 PR :)

**Comment by rakekniven** [comment]
OK, I was maintaining wikipedia page and found newer releases on app store than CHANGELOG is listing.

**Comment by AndyScherzinger** [comment]
No worries, the infos can be found her: 
https://github.com/nextcloud/android/pull/2936/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by rakekniven** [comment]
Sure, but IMHO the average user will not read/search PRs :-)
btw. the Google Play Store page does not extended release information nor an app history, or?

**Comment by rakekniven** [comment]
> Of course the master branch should be having the changelog up-to-date at release time :)

This is simply not possible. iOS app teached me this ;-)

**Comment by AndyScherzinger** [comment]
Well, for Android it usually did. I got a bit more complicated with our latest branching strategy, while it is still part of our release issues, like #2868 
The last 2 hotfix releases were kind of ad-hoc... ;-)

**Comment by rakekniven** [comment]
Oh, you have lot of tasks in great detail. Good work :+1:

**Comment by AndyScherzinger** [comment]
3.2.4 has been released and changelog on master is up-to-date :dancer:

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/releases will always contain the complete changelog.

**Pull request closed without merging**
