### PR TITLE
add Android FindBugs plugin

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Locally I am also using this.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Not sure why I closed this, so test again.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky would this need to be replaced by SpotBugs?

**Comment by tobiasKaminsky** [comment]
Seems that this version is not longer available…
You can give it a try, but I think otherwise we can close it.

**Comment by AndyScherzinger** [comment]
I am fine with closing since I only check my PRs via CI

**Pull request closed without merging**
