### PR TITLE
Remove sticky headers from activities list view

### PR DESCRIPTION
**Pull request by ezaquarii**
This will prevent application from crashing on adapter update.

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### CODE REVIEW

**Comment by ezaquarii** [comment]
@AndyScherzinger @tobiasKaminsky This is a low-risk mitigation for #4620 suitable for 3.8 branch.

How to address this in 3.9.x is another story.

**Comment by AndyScherzinger** [comment]
Wouldn't we then simply loose the headers?

We had headers before, made them sticky with the last release and now temporarily remove them to fix the crash?

**Comment by ezaquarii** [comment]
Headers are still there, just not sticky.

**Comment by AndyScherzinger** [comment]
Then I am fine with the quick fix for 3.8.1 while we should then have another issue ticket scheduled for 3.9.0 since we should get this working.

**Comment by tobiasKaminsky** [comment]
:+1: for the quick fix.
:tada: as always many thanks for your help @ezaquarii

**Pull request merged**
