### PR TITLE
Add scan document feature

### PR DESCRIPTION
**Pull request by thelittlefireman**
Signed-off-by: thelittlefireman <thelittlefireman@users.noreply.github.com>

APK size about 36Mb
based on [https://github.com/meganz/AndroidDocumentScanner](https://github.com/meganz/AndroidDocumentScanner)

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

### CODE REVIEW

**Comment by thelittlefireman** [comment]
Some icon are not visible in dark mode (dark icon on dark background) an need a fix

**Comment by AndyScherzinger** [comment]
While I haven't had a chance to test or look at the code, nice work @thelittlefireman 🤩

36 MB sounds way better, since the actual releases are around 23MB so at least I would be fine with this bump.

Also pinging @tobiasKaminsky since I might not find the time during the next 2 weeks to look into it (at least not throughly)

**Comment by AndyScherzinger** [comment]
@thelittlefireman I switched back to the libs theme @style/DocumentScannerTheme which needs to be used so the icons etc. look fine. Ideally we create one inheriting this theme and change colors etc. Also there is an issue with the texts (english/mixed). Haven't had the time to look into that yet.

**Comment by tobiasKaminsky** [comment]
I finally found some time to rebase and test it. 
I am really sorry for this long delay.

While testing I had this, I cropped an image:
resized_Screenshot_20220107-094811

but result is then like this:
resized_Screenshot_20220107-094822

This is then also what is being uploaded.
Do you have an idea how to fix this?

**Comment by thelittlefireman** [comment]
hi, sorry but relay no time to work on it.
@tobiasKaminsky 
I do not, maybe it's a library issue.

also, i see this library that use a compress version of open CV, seems realy cool [https://github.com/zynkware/Document-Scanning-Android-SDK](https://github.com/zynkware/Document-Scanning-Android-SDK)

**Comment by tobiasKaminsky** [comment]
Thanks for this hint!

Closing in favor of #9717

**Pull request closed without merging**
