### PR TITLE
Feature/add exclude hidden file or folder option when create custom media folder type

### PR DESCRIPTION
**Pull request by BBBOND**
- [x] Tests written, or not not needed

Adding a synchronization directory of custom file types will synchronize all files to the cloud. However, many useless hidden files are often written into the directory by third-party software, causing conflicts in synchronization. Therefore, an option to exclude hidden files has been added. to solve this problem.

iShot_2023-12-15_22 02 35

### CODE REVIEW

**Comment by BBBOND** [comment]
Anyone who can help me to add feature to this project?

**Comment by AndyScherzinger** [comment]
@BBBOND best to rebase against `master` instead of merging the master changes. Else you pollute the PR with commits not part of the PR originally.

**Comment by BBBOND** [comment]
@AndyScherzinger Sorry, I seem to have made a mistake in this PR. Let me create it again.

**Pull request closed without merging**
