### PR TITLE
Sorts favourite files first in list

### PR DESCRIPTION
**Pull request by ryanwr**
Shows files marked as favourites first, closes issue #107

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you (also) have a look? Code looks good to me. To be discussed if (as implemented in this PR by @ryanwr) there should be 2 chained sortings or if the sorting for the favorites should be incorporated in the 3 existing sorting implementations. That way you don't have to do a second sorting which makes the sorting implementations more complex but would save us 1 complete/additinal loop especially when it comes to very large file listings.

**Comment by tobiasKaminsky** [comment]
I doubt that there is a real performance loss as there are very very few favorites files I guess.
So I would vote for keeping it this way.
Or is someone eager doing some performance tests? ;-)

**Comment by AndyScherzinger** [comment]
Then I am fine doing it like this :+1: 
I'll will test it again (probably tomorrow) for all 3 sorting-options and if it works correctly will then merge it.

**Comment by AndyScherzinger** [comment]
Test were successful - so merging to master.

Thanks @ryanwr for your contribution! :tada: This will be part of the next stable release 1.4.0

**Comment by jancborchardt** [comment]
@ryanwr very cool contribution! :) Added you to the Nextcloud organization and Android team :)

**Comment by ryanwr** [comment]
Thanks! Happy to help

**Pull request merged**
