### PR TITLE
Bugfix 456

### PR DESCRIPTION
**Pull request by mario**
This PR fixes issue #456, and in addition, fixes a bug where we tried to fetch EXIF tags for PNG files that don't really have them.

I now toggle full screen on view click as well, because some images are too small and people might be having trouble clicking on them.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
You can add your next PR/branch to our repository. 
With having all feature branches in our repo it is easier to collaborate or test the branch.

**Comment by AndyScherzinger** [comment]
without having the branch at hand with the wrap_content change, what happens for a square png with a pinch-to-zoom, will it then still use the whole screen?

**Comment by mario** [comment]
@AndyScherzinger not at the moment. I'll take a look and see if I can adapt this for the pinch-to-zoom situation as well.

**Comment by mario** [comment]
Attaching an image so you folks can see how it looks. Pinch-to-zoom works, and zooming happens inside the actual image dimensions (aka does not expand). Let me know if it should!
screenshot_20170119-190341

screenshot_20170119-190616

**Comment by AndyScherzinger** [comment]
> Pinch-to-zoom works, and zooming happens inside the actual image dimensions (aka does not expand). Let me know if it should!

@mario it did before, so I'd say yes, but than the actual solution you implemented wouldn't work anymore since it just did the view content wrapping.

**Comment by mario** [comment]
@AndyScherzinger should be fixed now.

**Comment by mario** [comment]
Closing per @tobiasKaminsky request - a new one will be opened with the branch from NC repo.

**Pull request closed without merging**
