### PR TITLE
lgtm: not self assigning :+1:

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
prevent self :+1:

### CODE REVIEW

**Comment by mar1u5** [comment]
:+1:

**Comment by LukasReschke** [comment]
LGTM

**Comment by mar1u5** [comment]
LGTM

**Comment by mar1u5** [comment]
LGTM

**Comment by mar1u5** [comment]
...uhm: why does approvals/lgtm does not report 👍 😱

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@mar1u5 because now only people in the Maintainer List can do approvals ;)

**Comment by mar1u5** [comment]
I see 😅 @AndyScherzinger

**Pull request merged**
