### PR TITLE
Revamp of upstream strings

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by mario** [comment]
👍 

Awesome, thank you for your contribution!

**Comment by tobiasKaminsky** [comment]
Wow, thank you!
Some one of design should also have look (@eppfel @jancborchardt )

**Comment by AndyScherzinger** [comment]
Erm, merged the wrong PR... How do we want to proceed?

**Comment by mario** [comment]
I like the PR. It's fine. Leave it.

**Pull request merged**
