### PR TITLE
l10n: Changing string text "path" to "folder"

### PR DESCRIPTION
**Pull request by Valdnet**
Reason for change:

1. Unify the name to other applications.
2. More understandable for the user.
3. Report also by translator for line: 444.

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Cc @nextcloud/designers for feedback on the text change, also @rakekniven 😊

**Comment by rakekniven** [comment]
Hello, like the idea to avoid using "path" and using "folder" instead. Ok from my side.

**Review by AndyScherzinger — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
/backport to stable-3.14
otherwise it will cause transifex bot to create conflicts

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Screenshots need to be updated I guess, else 👍

**Review by jancborchardt — APPROVED** [review]
Much better, less technical language and we do use "folder" over "path" elsewhere too. :) Thanks!

**Review by AndyScherzinger — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger screenshots are still wrong, e.g:
https://www.kaminsky.me/nc-dev/android-integrationTests/7657-Screenshot-White-Dark-14-18/#comnextcloudclientSettingsActivityIT_showMnemonic_Error_dark_white

So this should net be merged!

**Comment by AndyScherzinger** [comment]
> So this should net be merged!

Then I missed them since I did replace the screenshots: https://github.com/nextcloud/android/pull/7657/commits/e1725f22cc2b368c08424ddd291d9a93dee90215

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I just checked, the screenshots are just right and the screenshot test errors you are referring to are from _before_ committing the new ones...

**Comment by tobiasKaminsky** [comment]
/backport to stable-3.14
we need it, otherwise transifex will not work

**Pull request merged**
