### PR TITLE
3.3.1 RC2

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* bumped version code

cc @tobiasKaminsky, please ignore the branch name ;)

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
For Gplay we also need a changelog file in /fastlane/metadata/android/en-US/changelogs/30030151.txt

**Comment by AndyScherzinger** [comment]
> For Gplay we also need a changelog file in /fastlane/metadata/android/en-US/changelogs/30030151.txt

Added to the PR :+1:

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
Lint error is unrelated to this PR

**Pull request merged**
