### PR TITLE
Remove explicitly displayed chooser

### LINKED ISSUE #1415: How to set a default PDF viewer with Android / Nextcloud
### Actual behaviour
-Tell us what happens

When I open a pdf document in the Android Nextcloud app it opens a "window" where I can choose between 8 different apps to open the PDF document with.

### Expected behaviour
-Tell us what should happen

It should offer me a way to set one of the readers as my default choice so that another time I skips the choice and opens PDF documents directly in the chosen viewer.

For comparison, opening a PDF document in Dropbox defaults to open the document in the embedded Dropbox PDF viewer.  Similarly with Google Drive and the Drive PDF viewer, so somehow it must be possible for an app to pick a default viewer.
 
### Steps to reproduce
1. navigate to a folder with pdf documents
2. open one
3. observe the choices of apps and lack of option to pick a default

### Environment data
Android version:
7.0

Device model: 
Samsung Tab A

Stock or customized system:
Stock

Nextcloud app version:
1.4.3

Nextcloud server version:
Irrelevant

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### PR DESCRIPTION
**Pull request by rhari991**
resolves #1415

### CODE REVIEW

**Comment by mario** [comment]
👎 

This is not a solution afaik. It doesn't allow you to set the default app.

[Rejected with PullApprove](https://pullapprove.com/nextcloud/android/pull-request/1652/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=nextcloud/android)

**Comment by rhari991** [comment]
The currently used `Intent.createChooser()` option always displays the chooser option, even if an explicit opening app is selected. By removing this, Android should show a chooser with a default option if more than one app is available (at least it does for me).

s1

**Comment by mario** [comment]
Ah, great! Sorry, is late.

Approving!

👍 

[Approved with PullApprove](https://pullapprove.com/nextcloud/android/pull-request/1652/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=nextcloud/android)

**Comment by AndyScherzinger** [comment]
👍 tested successfully!

@rhari991 I rebased and force pushed to your branch (!) to have it up-to-date with the Nextcloud master (newer app version).

This should be merged right after 2.0 release.

**Comment by tobiasKaminsky** [comment]
@rhari991 as the feature request would affect your branch, maybe you want to add it here directly?
This would be awesome 🎉 
https://github.com/nextcloud/android/issues/531#issuecomment-336171136

> https://github.com/nextcloud/android/issues/531#issuecomment-336171136 

Reference for inspiration: Automattic/simplenote-android:Simplenote/src/main/java/com/automattic/simplenote/ShareBottomSheetDialog.java@74466a2#L38

**Comment by AndyScherzinger** [comment]
Awesome contribution @rhari991 🥇 merged to master 👍

**Pull request merged**
