### PR TITLE
Taaem fix

### PR DESCRIPTION
**Pull request by mario**
This fixes an issue with really really big folders, and has been tested by @taaem.

Ideally in the future, we'll use persistent storage (sqlite) for this instead of the Data Holder I just wrote, but this works.

IMHO, important enough to be in 1.4.2.

### CODE REVIEW

**Comment by taaem** [comment]
For reference issue #694. Without this the app gets unusable and is force closing all the time.

**Comment by mario** [comment]
This would resolve issue #694

**Comment by AndyScherzinger** [comment]
👍 Looks good

One question though, since I have never seen this in the wild. any reason for writing it this way?
```
String dataHolderItemId;
dataHolderUtil.save(dataHolderItemId = dataHolderUtil.nextItemId(), result);
```
compared to?
```
String dataHolderItemId = dataHolderUtil.nextItemId()
dataHolderUtil.save(dataHolderItemId, result);
```

**Comment by mario** [comment]
> One question though, since I have never seen this in the wild. Any reason for writing it this way?

Not really, left-overs from testing. So please re-approve :)

**Comment by AndyScherzinger** [comment]
👍 looking good 🌹

**Comment by tobiasKaminsky** [comment]
👍 
Ready for 1.4.2 as it is a bug fix

**Pull request merged**
