### PR TITLE
i18n: Change name of encryption

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

- [ ] Tests written, or not not needed

### CODE REVIEW

**Comment by Valdnet** [comment]
Corrected 😉.

**Review by tobiasKaminsky — APPROVED** [review]

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Thanks @Valdnet !

**Comment by AlvaroBrey** [comment]
Backports are not actually needed, as the PR that introduced these strings was not backported to 3.22 or 3.23

**Pull request merged**
