### PR TITLE
Add ktlint

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
There is ./gradlew ktlintFormat, which is also available within AS.
But I do not think that we should do this automatically, or?

**Comment by ezaquarii** [comment]
> But I do not think that we should do this automatically, or?

It should reject commits if they are not formatted. This saves on useless review round-trips and suppresses inflammatory discussions.

Besides, Kotlin has some features that make Java style unfit for purpose and it will take time until the knowledge spreads.

**Comment by tobiasKaminsky** [comment]
> It should reject commits if they are not formatted. This saves on useless review round-trips and suppresses inflammatory discussions.

I really like this, but this seems to be a github enterprise feature only.
While we can encourage people to run this check locally, we cannot ensure this.
Do you have a better idea?

**Comment by ezaquarii** [comment]
> I really like this, but this seems to be a github enterprise feature only.

I was thinking about making it part of the CI job and "failing build" if it is not formatted according to the lint, the same way we fail on SpotBugs.

**Comment by tobiasKaminsky** [comment]
Right, I misunderstood it.
Then this is already implemented:

image

**Comment by AndyScherzinger** [comment]
seems to work while the report for ktlint ist really a html file but rather a `br` seperated list of issues that have been found (no body, no header, etc.)

**Comment by tobiasKaminsky** [comment]
> seems to work while the report for ktlint ist really a html file but rather a `br` seperated list of issues that have been found (no body, no header, etc.)

Yeah, this is just a quick & easy list. 
Do you think we reall need the header/body stuff?

**Comment by AndyScherzinger** [comment]
for now, I am completely fine with the solution 👍

**Pull request merged**
