### PR TITLE
Motivate more users 

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
corresponding issue: #139

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky code looks good to me. :+1:  Please review since I made some changes to fix UI issues and to get the "All files" and "on Device" menu items working in the participate screen.

@jancborchardt and @nextcloud/designers please have a quick look at the screenshots and also note that I added one more info optimization: The account chooser's list shows all accounts except the active one (which is displayed in the header anyways) since you already chose that one...).

Drawer Menu with new menu item
device-2016-09-04-211940

The participate screen (scrollable of course)
device-2016-09-04-212115

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I also pushed the latest changes to the beta branch seconds ago.

**Comment by eppfel** [comment]
I must say, that I am missing an call-to-action. What is the most probable way users will participate? This option should be more prominent. My guess: RC Tester on Google Play or report a bug/issue, because this applies to all releases. 

That way we don't loose people to lazy to read. If I don't know about f-droid these links will confuse me. 

Is there maybe a way to check whether the app was installed via f-droid or Play?

Just my two cents.

**Comment by eppfel** [comment]
BTW, The participate icon looks good.

**Comment by AndyScherzinger** [comment]
Thanks @eppfel :)
As for the call to action, we are hoping to get some feedback discussion on this. As most of the time putting a draft out here to push it further. That's why I cc'ed a lot of people.
As to questions, unfortunately we cannot detect from where an app has been installed, you could even compile it yourself and install it via Android Studio or just download it from the Nextcloud installation page.
Most common action is a good question. We basically need support in all the areas, RC testing, beta testing, bug reporting and translations.

**Comment by eppfel** [comment]
Just to make it clear: I am missing an call-to-action in the participation screen. 
I would guess most people use Google Play over other Channels, so there is that for a prioritization.
And with 3 submissions out of ~250 testers (and much more users in general), you need more people reporting back.

So maybe like this: I (subjectively) ordered the various actions by the user's expertise. First the  simple stuff. I removed copy; tried to rewrite for users perspective.

---

Found a bug? Something's odd?
**[Report an issue on Github](https://github.com/nextcloud/android/issues)** <-- Maybe even a button

Interested in helping us testing the next Version?

**Test the release candidate: [Get it on Google Play Store](https://play.google.com/apps/testing/com.nextcloud.client)** <-- a second smaller button
The release candidate (RC) is a snapshot of the upcoming release and it is expected to be stable. Testing your individual setup could help to ensure this.
[RC on F-Droid](https://f-droid.org/repository/browse/?fdfilter=nextcloud&fdid=com.nextcloud.client)

**Test the Beta version**: Fdroid Beta Link / APK Link
This includes all upcoming features and is very bleeding edge. Bugs/errors can occur and if they do, please report them to us.

**Activly Contribute**
- Join the chat on IRC: #nextcloud-dev
- Help others on the forum: https://help.nextcloud.com
- Be part of the Team and contribute as a developer: [CONTRIBUTING](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md)

**Comment by AndyScherzinger** [comment]
@eppfel uuh, I got that wrong, thanks for the clarification!

@tobiasKaminsky what do you think? I like @eppfel's approach in the text. It seems shorter am more "call-to-action" or easier to comprehend, less formal.

**Comment by tobiasKaminsky** [comment]
Is fine for me. Great help @eppfel 
@jancborchardt are you fine with this?

**Comment by jancborchardt** [comment]
Yeah, @eppfel’s feedback is great! :) I was also thinking it’s a bit much text and very small links – which will be hard to click on mobile.

**Comment by AndyScherzinger** [comment]
Changes due to the feedback have been made, 1.3.0 RC1 tag has been created so I am confident we will publish it tomorrow :rocket:

**Pull request merged**
