### PR TITLE
Remove Corrupt Account Warning

### PR DESCRIPTION
**Pull request by xXSTrikeXx**
as mentioned in #1676
Preperation for stable-release.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
See the drone link, you missed one piece of the puzzle so the app doesn’t compile anymore. xD

**Comment by AndyScherzinger** [comment]
Hi @xXSTrikeXx 
dont't worry about the master, I can do a rebase later :)

**Comment by xXSTrikeXx** [comment]
@AndyScherzinger tried to edit it in the browser. Sometimes Github confuses me....

**Comment by AndyScherzinger** [comment]
👍 fine by me

**Comment by AndyScherzinger** [comment]
pinging @mario @tobiasKaminsky for review :)

**Comment by xXSTrikeXx** [comment]
year fist complete code removal :D

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger merge!

**Pull request merged**
