### PR TITLE
Fix davdroid url: base url was retrieved too early

### LINKED ISSUE #3076: 3.3.0RC3 Settings: setup DAVdroid Intent doesn't pass URL
Hello,

I have tried 3.3.0RC3 :) and have found this:

### Actual behaviour
Nextcloud Android app: 3.3.0RC3

- Set up Nextcloud account in app
- Settings / More: Sync calendars and contacts
- DAVdroid is started, but with no URL. Only the user name is passed, and it's in the email address field because there's no URL

screenshot_1537631732

### Expected behaviour
- URL should be passed

With 3.2.3, this works as expected:

screenshot_1537631691

Thanks for your work!
Ricki

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
fix #3076 

- cod cleanup -> lambda

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: fine with me.

Should be backport imho

**Comment by tobiasKaminsky** [comment]
Backport done

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
:exclamation: final rebase prior merging for CI run

**Pull request merged**
