### PR TITLE
Search view wrong files

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #857 

The main clue is that the current system does not allow to have "any" ocfile, instead there must always be a parentId/parentFolder. Without that things like downloading files do not work.
As the favorites/photos can show any files (even if they have never been synced) we need to download the parentOCFile, maybe even recursive until "/".
Of course this is only done once for each folder.

Sidenote: I tried it with ~3500 and it took quite a long time to display the images. Fetching the files recursively was not the problem as on the second time all files were fetched already, but it still took ~20s.

### CODE REVIEW

**Comment by mario** [comment]
Well I guess the real solution then would be to fix the underlying problem *shrug*

But let me check if this works right now...

**Comment by mario** [comment]
👎  unfortunately :(

So I just tested this and ...

a) action bar search does not work at all (it doesn't search?)
b) all search views show up with no data

Can @AndyScherzinger or @tobiasKaminsky please confirm?

**Comment by tobiasKaminsky** [comment]
This happened as of @AndyScherzinger has rebased it and due that https://github.com/nextcloud/android/commit/9c1339b1e408976ee08a49de2d8acc32933e61d6#diff-a76a7c99598d82da114ff289c2498fdeR1359 (isCancelled()) was merged...

If we rebase stuff we must keep sure that all is working.

**Comment by mario** [comment]
Photos sometimes work for me, otherwise "No files here" most of the time (not even No photos here). Favorites just show all files.

**Comment by mario** [comment]
Well, works better than before, but there are still issues...

a) On main view (All files) I don't see all the files! - namely, those that are shared
b) search for something, then delete or click x to close search - results are still there, instead of wherever I was at (all files)

**Comment by mario** [comment]
(Also, needs rebasing on master)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky to comment on your original side note:

> Sidenote: I tried it with ~3500 and it took quite a long time to display the images. Fetching the files recursively was not the problem as on the second time all files were fetched already, but it still took ~20s.

This will always be slow until we move to recyclerview, since for the listview it loads all 3500 caches thumbnails first and then renders the whole thing and being on a phone/tablet this takes quite a while, so this will vastly improve with recyclerview! 👍

**Comment by mario** [comment]
@tobiasKaminsky what about missing "shared" files in the main list view?

**Comment by mario** [comment]
Rebased, will test now.

**Comment by mario** [comment]
Looks ok-ish. Now we only need to solve #891 and #905 and then we're ready with this PR. Let me try to look into it now...

**Comment by mario** [comment]
More bugs: 

- open Favorites, I get both favorited and not favorited files :-/
- shared - I get all files again :-/

:(

So there are still bugs that need to be resolved other than the two issues I've mentioned above...

**Comment by tobiasKaminsky** [comment]
> More bugs

I have fixed swipe to refresh right now.
How can I reproduce your bugs?

**Comment by mario** [comment]
No specific steps. Play around - search, stop searching, rotate, change views, stuff like that :-/

**Comment by mario** [comment]
Issues remaining to be solved in this PR (for now):

- [ ] - #891 and #905 - overlapping fragments
- [ ] - Empty view appears before it even started loading the data - this should not happen (everywhere) 
- [ ] - When in favorites, and you rotate I get both favorites and non-favorites (and also issues with UI?). This could happen in other "search" parts as well
- [ ] - Click photos, it starts loading, show's there's nothing, and then loads grid view with photos few seconds later - STRANGE! Rotating this screen is also super weird.
- [ ] - Shared view shows all shared files, but lacks the shared icon next to files?!
- [ ] - On device has "Nextcloud" as title?

Screenshots:
screenshot_20170505-130758

screenshot_20170505-131023

**Comment by tobiasKaminsky** [comment]
> On device has "Nextcloud" as title?

This is the current behaviour also on master.
It is the initial name if you are in the root folder (whether showing all files / only on device). If you navigate to a folder this folder name then will be displayed.
So no bug to me. If we want to do this, then we shall do it with an new issue and a new PR after this one.

**Comment by mario** [comment]
@tobiasKaminsky sure, open another issue. What about other bugs? :)

**Comment by tobiasKaminsky** [comment]
@mario I have created new issues for all your bugs, to have a better track of them.
For me there is only #964 open, which I will fix tomorrow.

**Comment by mario** [comment]
@tobiasKaminsky couldn't we fix it all as part of this PR? It's all VERY related.

**Comment by tobiasKaminsky** [comment]
Yes, I will fix all (except "on device" issue) in this PR.
But discussion many bugs in one thread is, at least for me, very hard to read, so therefore just opened some issues for discussing.

**Comment by mario** [comment]
@tobiasKaminsky sounds good. Thanks for the clarification.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky Just tried a fresh install which is a direct crash&burn (might nede to check the file system for any remains from older installations though...)
```
05-12 11:59:38.664 32283-32283/com.nextcloud.client E/SQLiteLog: (1) table virtual already exists
05-12 11:59:38.671 32283-32283/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
  Process: com.nextcloud.client, PID: 32283
  java.lang.RuntimeException: Unable to create service com.owncloud.android.services.observer.SyncedFolderObserverService: android.database.sqlite.SQLiteException: table virtual already exists (code 1): , while compiling: CREATE TABLE virtual(_id INTEGER PRIMARY KEY, type TEXT, ocfile_id INTEGER )
      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3308)
      at android.app.ActivityThread.-wrap5(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1617)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6290)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
   Caused by: android.database.sqlite.SQLiteException: table virtual already exists (code 1): , while compiling: CREATE TABLE virtual(_id INTEGER PRIMARY KEY, type TEXT, ocfile_id INTEGER )
      at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
      at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
      at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
      at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
      at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
      at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1704)
      at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1635)
      at com.owncloud.android.providers.FileContentProvider.createVirtualTable(FileContentProvider.java:1162)
      at com.owncloud.android.providers.FileContentProvider.access$700(FileContentProvider.java:63)
      at com.owncloud.android.providers.FileContentProvider$DataBaseHelper.onUpgrade(FileContentProvider.java:1004)
      at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
      at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
      at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:435)
      at android.content.ContentProvider.query(ContentProvider.java:1055)
      at android.content.ContentProvider$Transport.query(ContentProvider.java:243)
      at android.content.ContentResolver.query(ContentResolver.java:571)
      at android.content.ContentResolver.query(ContentResolver.java:482)
      at com.owncloud.android.datamodel.SyncedFolderProvider.getSyncedFolders(SyncedFolderProvider.java:88)
      at com.owncloud.android.services.observer.SyncedFolderObserverService.onCreate(SyncedFolderObserverService.java:66)
      at android.app.ActivityThread.handleCreateService(ActivityThread.java:3298)
      at android.app.ActivityThread.-wrap5(ActivityThread.java) 
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1617) 
      at android.os.Handler.dispatchMessage(Handler.java:102) 
      at android.os.Looper.loop(Looper.java:154) 
      at android.app.ActivityThread.main(ActivityThread.java:6290) 
      at java.lang.reflect.Method.invoke(Native Method) 
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by tobiasKaminsky** [comment]
Yes, the database migration had a conflict and if you have installed this or externalLinks or similar then the database scheme version was updated but with the "wrong" content.
So please try it again after deinstalling the app.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky nope, like I said:

> Just tried a fresh install which is a direct crash&burn

which is simply due to the fact that the table gets created twice... so I had to push https://github.com/nextcloud/android/pull/896/commits/28e8eaa37611fa940b39653215c2f4bdc79b80b3 ;)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky 

Two issues:

**Shared**
After querying shows this for about 10(!) seconds:
device-2017-05-12-140244

Then this 🎉 
device-2017-05-12-135619

* the first message shouldn't ever be shown here! It should show the empty results message / icon for shared
* it should still show loading or any kind of proper message while filling the list view

**Favorites**
Doesn't show my favorites (see even in the shared view above)
device-2017-05-12-140219
* the first message shouldn't ever be shown here! IF, then it should show the empty results message / icon for shared
* it should just show my favorites - which it doesn't

Server is v11.0.3

**Comment by tobiasKaminsky** [comment]
The first is a more general problem as this can happen also on very slow connection and very large folders, so this needs to be solved in a global way.

Favorites is working fine for me, but neither for you nor @mario . He will debug into it.

**Comment by mario** [comment]
@AndyScherzinger can you test & approve this? :)

**Comment by AndyScherzinger** [comment]
👍 fine with me, also tested with _ALL_ my images (2004-today) which takes way more than 20s to load the default image + then the thumbnail loading for all starts (which is not optimal). So the focus for 1.6 should be recycler view, this is a killer for the photos view (and other large folders!)

**Comment by mario** [comment]
👍

**Pull request merged**
