### PR TITLE
Fixes #1656

### LINKED ISSUE #1656: No log in app v2.0.0rc7
### Actual behaviour
When I go to logs in settings (Journaux in my french version), nothing appear. I just have Clear logs and send logs buttons. Clear logs go to the precedent view and send logs no attach any attachments.

### Expected behaviour
Select logs in settings should display all logs of the application. Send logs button should attach logs.
 
### Steps to reproduce
1. Open the app
2. Go to the settings view
3. Select logs
4. No log displayed

### Environment data
Android version: 7.1.2

Device model: Nexus 4

Stock or customized system: LineageOS 14.1

Nextcloud app version: V 2.0.0RC7

Nextcloud server version: 12.0.3

#### Web server error log
```
Nothing (no action on web server)
```

#### Nextcloud log (data/nextcloud.log)
```
Nothing (no action on web server)
```
#### logcat log
```
Nothing special (no error)
```
screenshot_20171011-134657

### PR DESCRIPTION
**Pull request by mario**
Fixes #1656

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
👍

**Comment by AndyScherzinger** [comment]
👍 fine by me while in a later PR the preference key should be kept in preference-classes not in the upload activity.

**Comment by tobiasKaminsky** [comment]
This can/should be done while rebasing, otherwise we will forget it ;-)

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky done.

**Pull request merged**
