### PR TITLE
Auto upload rotation bug

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #910

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 Looks good to me, cc @mario

**Comment by mario** [comment]
@AndyScherzinger if you feel like this is ok, feel free to merge - I will not be able to review it in a while. Thanks.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky issue found, tricky one...

1. open auto upload preference screen
2. choose upload behavior, so popup opens
3. rotate device
4. hit back button so upload behavior pop up closes
5. hit remote folder, so file chooser opens
6. rotate device 
7. hit cancel
8. **issue**: upload behaviors pop up is shown

**Comment by tobiasKaminsky** [comment]
Nice catch :+1: 
I fixed it, please try it again.

**Comment by AndyScherzinger** [comment]
👍 fixed!

**Pull request merged**
