### PR TITLE
New details view animations

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Is it worth to update this branch?

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
I'll check this one out...

**Comment by AndyScherzinger** [comment]
actual WIP:
device-2017-06-27-104903
device-2017-06-27-103430

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky do you know how to rest/hardwire the submodule for the user manual against the latest master? :/

**Comment by AndyScherzinger** [comment]
I screwed up the branch completely... removed (will still keep working on it...)

**Comment by jancborchardt** [comment]
@AndyScherzinger yeah, this looks already similar to what I had in mind! Basically think of it like the right sidebar in the Files app of the web interface. :)

**Comment by jancborchardt** [comment]
Cause a file has two aspects:

- Viewing the file itself
- Viewing all the the metadata like comments, activity, sharing, etc - which also includes ofncourse a preview etc :)

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger yeah, this looks already similar to what I had in mind! Basically think of it like the right sidebar in the Files app of the web interface. :)

That is what I do 💃 File and its meta data 👍

**Pull request closed without merging**
