### PR TITLE
Add SQL query pagination in UploadStorageManager

### LINKED ISSUE #5891: UploadsStorageManager: Couldn't read row 1872, col 1 from CursorWindow.
### Steps to reproduce
1.  Open the app

### Actual behaviour
- The app crashes

### Environment data
Android version: 9

Device model: OnePlus 6T

Stock or customized system: Stock

Nextcloud app version: 30110090

Nextcloud server version: 18.0.3

Reverse proxy: nginx

************ CAUSE OF ERROR ************

java.lang.IllegalStateException: Couldn't read row 1872, col 1 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetString(Native Method)
at android.database.CursorWindow.getString(CursorWindow.java:465)
at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
at android.database.CursorWrapper.getString(CursorWrapper.java:137)
at com.owncloud.android.datamodel.UploadsStorageManager.createOCUploadFromCursor(UploadsStorageManager.java:321)
at com.owncloud.android.datamodel.UploadsStorageManager.getUploads(UploadsStorageManager.java:302)
at com.owncloud.android.datamodel.UploadsStorageManager.getFailedUploads(UploadsStorageManager.java:368)
at com.owncloud.android.files.services.FileUploader.retryFailedUploads(FileUploader.java:1005)
at com.owncloud.android.utils.FilesSyncHelper.lambda$restartJobsIfNeeded$0(FilesSyncHelper.java:222)
at com.owncloud.android.utils.-$$Lambda$FilesSyncHelper$fa2LBpPOxRVQOm4F_Glue5u4hdM.run(Unknown Source:10)
at java.lang.Thread.run(Thread.java:764)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30110090
Build flavor: generic

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus6T
Model: ONEPLUS A6013
Id: PKQ1.180716.001
Product: OnePlus6T

************ FIRMWARE ************
SDK: 28
Release: 9
Incremental: 1909112330

### PR DESCRIPTION
**Pull request by ezaquarii**
Fix #5891 

- [ ] rebase after merge of #5918

Signed-Off-By: GDR! <gdr@gdr.name>

### CODE REVIEW

**Comment by ezaquarii** [comment]
@gjedeer Thank you for finding the solution. We've moved the PR into nextcloud org and we'll continue working on it here, retaining your original commit and copyright.

For the time being, the most important thing for me is to be able to reproduce this problem reliabily. Do you know how can I do it?

**Comment by tobiasKaminsky** [comment]
I tried to write a test to reproduce this error reliable, but I failed:
https://github.com/nextcloud/android/pull/6013/files#diff-55f8cb758e6581bd10ee0d0efe6020cdR92

This is working for me even with 20k uploads…

**Comment by tobiasKaminsky** [comment]
So, let us move this on…
I created #5918 with some positive tests.
Once #5918 is merged, I'll rebase this on master and if tests are fine, this is good to go.

**Pull request merged**
