### PR TITLE
Refactor Activities screen to use ViewModel pattern

### PR DESCRIPTION
**Pull request by ezaquarii**
This PR started as a genuine `Account`/`User` migration effort, but when I realized that the underlying `Presenter` pattern is reduntant and overcomplicated, I collapsed multiple API layers into single `ViewModel`. Overall it is half the size of previous solution and tested.

- Removed ActivitiesPresenter and replaced it with ViewModel
- Removed repository patterns
- Replaced async tasks with AsyncRunner and task functions
- Removed dead code

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### Testing 

- [x] View model has tests

### CODE REVIEW

**Comment by ezaquarii** [comment]
@tobiasKaminsky Screenshots tests fail. This is not unusual, but one of them is `ActivitiesActivity` test which I touched in this PR. I tried to find access to screenshot files but couldn't find accessible images. I think this one deserves extra scrutiny.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky Screenshots tests fail. This is not unusual, but one of them is `ActivitiesActivity` test which I touched in this PR.I think this one deserves extra scrutiny.

Previously it showed a snackbar that connection is not possible.
https://www.kaminsky.me/nc-dev/android-integrationTests/15321-Screenshot-master-light-blue/#comnextcloudclientActivitiesActivityIT_openDrawer

Has this behaviour changed? Seems that this snackbar is not shown, or too late for test?
While testing it manually (disabling network connection, open up activities, I do see a snackbar)

Shall I change it?

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the Screenshot test still need fixing :/

**Comment by ezaquarii** [comment]
Seems like somebody cleaned it up elsewhere.

**Pull request closed without merging**
