### PR TITLE
Build unit and androidTest code before committing

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [ ] Tests written, or not not needed

### CODE REVIEW

**Review by AlvaroBrey — COMMENTED** [review]
In my opinion this slows down development too much, and we will end up skipping pre-commit hooks :\

Are we really uploading code with compilation errors so frequently that it's worth it to slow down every commit?

**Comment by tobiasKaminsky** [comment]
> Are we really uploading code with compilation errors so frequently that it's worth it to slow down every commit?

For me it happens "every time" when refactoring stuff.

Is there a way to have this optional?

**Comment by AlvaroBrey** [comment]
> Is there a way to have this optional?

I mean, you could have it depend on an environment variable, and then set that in your shell RC, or manually, for example.

Not sure if there's a better way. I'd at least move it to `pre-push` instead of `pre-commit`, though.

**Comment by tobiasKaminsky** [comment]
Is indeed to much overhead.
As we now also want to have tests on every PR, chances that this happens are even less.

**Pull request closed without merging**
