### PR TITLE
Add automatic Per App Languages

### PR DESCRIPTION
**Pull request by Arthur-GYT**
All is in the title ^^.

https://developer.android.com/guide/topics/resources/app-languages

### CODE REVIEW

**Comment by Arthur-GYT** [comment]
@AndyScherzinger It's normal for https://github.com/nextcloud/android/actions/runs/8678863344/job/23816001660?pr=12875 to fail all the time ?

**Comment by AndyScherzinger** [comment]
@Arthur-GYT yes, there is a single screenshot test that needs fixing. I think @alperozturk96 is looking into that one.

**Comment by Arthur-GYT** [comment]
> With latest master screenshot tests should work.

@alperozturk96 

I have updated the branch

**Comment by alperozturk96** [comment]
> Again ^^'
> 
> https://github.com/nextcloud/android/actions/runs/8879187564/job/24376356296?pr=12875


Unfortunately, our ss tests are not stable, sometimes need to re-run again to get successful output. We can try a couple of more time if it's still same, I guess we can force merge it.

@tobiasKaminsky

**Review by AndyScherzinger — APPROVED** [review]
tested successfully 👍

**Pull request merged**
