### PR TITLE
Reduce lint errors

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Side note: our transifex-bot is only commit languages with >50% strings translated, all others are now removed to get rid of lint errors.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: looks good to me :)

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger can you re-approve & merge?

**Comment by AndyScherzinger** [comment]
:+1: re-approved

**Pull request merged**
