### PR TITLE
Improve share link handling

### LINKED ISSUE #2742: Improve share link handling
as discussed in the forum with @jancborchardt and @jasonbayton: https://help.nextcloud.com/t/nextcloud-android-app-update-with-improved-user-interface-and-sharing/32900/15?u=jan

When a share link is created, copy it to the clipboard directly for fast sharing while not showing the "Send to" dialog anymore. This way the experience is smoother and the user can still edit the links permissions etc. without having to close the send action dialog but can do that anytime afterwards via the newly introduced menu item.

Upon initial creation when the link is auto copied into the clipboard show a Toast saying: "Share link copied"

### PR DESCRIPTION
**Pull request by tilosp**
Resolves #2742

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: code is fine with me and also successfully tested on OP3T. I added some theming code for the snackbar's action. cc @tobiasKaminsky for review and approval. I vote to sneak this into 3.3.0 :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky rebased to latest master :exclamation:

**Comment by tobiasKaminsky** [comment]
- open up file detail view
- click on checkmark for "share link", see snackbar with "share" -> :heavy_check_mark: 
- click on "clipboard icon", get toast -> :heavy_check_mark: 
- open overflow menu, click "send link", see again snackbar :x: as the user then needs again to click on "share" within snackbar. Here the "share dialog" should immediately be shown
(also it seems as a new network call is done, this is not necessary, or?)

**Comment by AndyScherzinger** [comment]
> - open overflow menu, click "send link", see again snackbar :x: as the user then needs again to click on "share" within snackbar. Here the "share dialog" should immediately be shown
(also it seems as a new network call is done, this is not necessary, or?)

I'll fix that, is is a bug always been there

**Comment by tobiasKaminsky** [comment]
:+1: Thanks for the fix, working now as expected

@tilosp thanks again for this PR :tada: 
It was nice to meet you at Conf!

**Pull request merged**
