### PR TITLE
Move grid columns to AppPreferences interface

### PR DESCRIPTION
**Pull request by ezaquarii**

### CODE REVIEW

**Comment by ezaquarii** [comment]
It looks like IT test failed again. It did not before and I can't see how my change could have break it.

Is it a known issue with a flaky test?

**Comment by AndyScherzinger** [comment]
> It looks like IT test failed again. It did not before and I can't see how my change could have break it.

> Is it a known issue with a flaky test?

Yes, this is known. I am unsure if @tobiasKaminsky takes care of this. If I remeber correctyl he wanted to work on this, while I can't say if he did already.

**Comment by tobiasKaminsky** [comment]
> Yes, this is known. I am unsure if @tobiasKaminsky takes care of this. If I remeber correctyl he wanted to work on this, while I can't say if he did already.

I did. I changed the tests so that the uploaded/created files/folders get removed after each test, so that the execution order does not matter.
Additionally #3704 is a next stop to see the real problem with the tests.

**Comment by AndyScherzinger** [comment]
❗️ rebased for final checks CI run

**Pull request merged**
