### PR TITLE
Bump docker image

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Currently Docker Hub is building the new image.

### CODE REVIEW

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
👍

**Comment by AndyScherzinger** [comment]
see https://drone.nextcloud.com/nextcloud/android/1089 won't fix the issue :(

**Comment by mario** [comment]
Can we simply run

sudo locale-gen

before it runs?

**Comment by tobiasKaminsky** [comment]
Merged, as I only did a rebase

locale-gen is used in new dockerimage.

**Pull request merged**
