### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by xXSTrikeXx**
Fixes a brooken link.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@xXSTrikeXx it is actually: https://github.com/nextcloud/android/blob/master/.pullapprove.yml#L29 which defines the list of users... ;)

**Comment by xXSTrikeXx** [comment]
well, you wrote in irc there is not such file :D I clicked on it and got a 404 ^^

**Comment by AndyScherzinger** [comment]
@xXSTrikeXx true, but the link I posted differs ;) It is not related to a maintainers file but the pull approve config part that defines the list of users that are allowed to approve PRs ;)

**Comment by xXSTrikeXx** [comment]
Looks better now? :P

**Comment by AndyScherzinger** [comment]
👍 perfect :)

cc @mario for quick review/approval :)

**Comment by mario** [comment]
👍

**Pull request merged**
