### PR TITLE
Migrate Account to User in some APIs

### PR DESCRIPTION
**Pull request by ezaquarii**
Migrate remaining Account uses to User model when it was
possible without wider refactoring.

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

- [x] Smoke tests only

### CODE REVIEW

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
@ezaquarii ready to merge?

**Comment by ezaquarii** [comment]
> @ezaquarii ready to merge?

I didn't have time to check CI output yesterday evening so I didn't mark it as ready. But if CI looks ok, it's done.

I can take look at it late evening.

**Comment by ezaquarii** [comment]
```
com.owncloud.android.providers.DocumentsStorageProviderIT > testServerChangedFileContent[android(AVD) - 8.1.0] 
FAILED
	org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
```

@AlvaroBrey  I think it's not mine.

**Comment by AlvaroBrey** [comment]
Thanks @ezaquarii !

**Pull request merged**
