### PR TITLE
Lint for 3.3.x

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Test if this is creating correct lint/findbugs values.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
<h1>Lint</h1><table width='500' cellpadding='5' cellspacing='2'><tr class='tablerow0'><td>Type</td><td><a href='https://www.kaminsky.me/nc-dev/-lint/.html'></a></td><td><a href='https://www.kaminsky.me/nc-dev/-lint/.html'>PR</a></td></tr><tr class='tablerow1'><td>Warnings</td><td>94</td><td>109</td></tr><tr class='tablerow0'><td>Errors</td><td></td><td></td></tr></table> <h1><a href='https://www.kaminsky.me/nc-dev/-findbugs/.html'>FindBugs</a> (new)</h1><table width='500' cellpadding='5' cellspacing='2'><tr class='tableheader'><th align='left'>Warning Type</th><th align='right'>Number</th></tr><tr class='tablerow0'><td>Bad practice Warnings</td><td align='right'>35</td></tr><tr class='tablerow1'><td>Correctness Warnings</td><td align='right'>164</td></tr><tr class='tablerow0'><td>Experimental Warnings</td><td align='right'>4</td></tr><tr class='tablerow1'><td>Internationalization Warnings</td><td align='right'>13</td></tr><tr class='tablerow0'><td>Malicious code vulnerability Warnings</td><td align='right'>9</td></tr><tr class='tablerow1'><td>Multithreaded correctness Warnings</td><td align='right'>9</td></tr><tr class='tablerow0'><td>Performance Warnings</td><td align='right'>157</td></tr><tr class='tablerow1'><td>Security Warnings</td><td align='right'>162</td></tr><tr class='tablerow0'><td>Dodgy code Warnings</td><td align='right'>134</td></tr><tr class='tablerow1'><td><b>Total</b></td><td align='right'><b>687</b></td></tr></table> <!DOCTYPE HTML PUBLIC '-//IETF//DTD HTML 2.0//EN'><html><head><title>404 Not Found</title></head><body><h1>Not Found</h1><p>The requested URL /nc-dev/-findbugs/findbugs-summary-.html was not found on this server.</p><hr><address>Apache/2.4.34 (Ubuntu) Server at www.kaminsky.me Port 443</address></body></html>

**Comment by tobiasKaminsky** [comment]
<h1>Lint</h1><table width='500' cellpadding='5' cellspacing='2'><tr class='tablerow0'><td>Type</td><td><a href='https://www.kaminsky.me/nc-dev/android-lint/stable-3.3.x.html'>stable-3.3.x</a></td><td><a href='https://www.kaminsky.me/nc-dev/android-lint/.html'>PR</a></td></tr><tr class='tablerow1'><td>Warnings</td><td>94</td><td>109</td></tr><tr class='tablerow0'><td>Errors</td><td></td><td></td></tr></table> <h1><a href='https://www.kaminsky.me/nc-dev/android-findbugs/.html'>FindBugs</a> (new)</h1><table width='500' cellpadding='5' cellspacing='2'><tr class='tableheader'><th align='left'>Warning Type</th><th align='right'>Number</th></tr><tr class='tablerow0'><td>Bad practice Warnings</td><td align='right'>35</td></tr><tr class='tablerow1'><td>Correctness Warnings</td><td align='right'>164</td></tr><tr class='tablerow0'><td>Experimental Warnings</td><td align='right'>4</td></tr><tr class='tablerow1'><td>Internationalization Warnings</td><td align='right'>13</td></tr><tr class='tablerow0'><td>Malicious code vulnerability Warnings</td><td align='right'>9</td></tr><tr class='tablerow1'><td>Multithreaded correctness Warnings</td><td align='right'>9</td></tr><tr class='tablerow0'><td>Performance Warnings</td><td align='right'>157</td></tr><tr class='tablerow1'><td>Security Warnings</td><td align='right'>162</td></tr><tr class='tablerow0'><td>Dodgy code Warnings</td><td align='right'>134</td></tr><tr class='tablerow1'><td><b>Total</b></td><td align='right'><b>687</b></td></tr></table> <h1><a href='https://www.kaminsky.me/nc-dev/android-findbugs/stable-3.3.x.html'>FindBugs</a> (stable-3.3.x)</h1><table width='500' cellpadding='5' cellspacing='2'><tr class='tableheader'><th align='left'>Warning Type</th><th align='right'>Number</th></tr><tr class='tablerow0'><td>Bad practice Warnings</td><td align='right'>35</td></tr><tr class='tablerow1'><td>Correctness Warnings</td><td align='right'>165</td></tr><tr class='tablerow0'><td>Internationalization Warnings</td><td align='right'>14</td></tr><tr class='tablerow1'><td>Malicious code vulnerability Warnings</td><td align='right'>10</td></tr><tr class='tablerow0'><td>Multithreaded correctness Warnings</td><td align='right'>9</td></tr><tr class='tablerow1'><td>Performance Warnings</td><td align='right'>123</td></tr><tr class='tablerow0'><td>Security Warnings</td><td align='right'>202</td></tr><tr class='tablerow1'><td>Dodgy code Warnings</td><td align='right'>137</td></tr><tr class='tablerow0'><td><b>Total</b></td><td align='right'><b>695</b></td></tr></table>

**Comment by AndyScherzinger** [comment]
should probably be redirected to `stable-3.4.x` when we start to create the 3.4.x branch

**Comment by tobiasKaminsky** [comment]
I'll open up a new one for stable-3.4.x

**Pull request closed without merging**
