### PR TITLE
Screenshots: further languages

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
- change grey area for davdroid
- minor fix
- add more languages
- text is now 3 rows

image

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by tobiasKaminsky** [comment]
Some languages, e.g. french, are so verbose, that we need three text lines.
@jancborchardt can you do this for me? Technically I can do this, but I am sure that then you have an idea regarding space/positioning :-) 

If it is easier for you, you can use
https://github.com/nextcloud/android/blob/d3bd486e598d47b0dacc0160b1654009e8b0e8e1/scripts/screenshots/phone.svg
https://github.com/nextcloud/android/blob/master/scripts/screenshots/tablet.png

and send me both files.

**Comment by AndyScherzinger** [comment]
👍

**Comment by mario** [comment]
👍

**Pull request merged**
