### PR TITLE
Set minSdkVersion to 24 + remove checks

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Moving the assets breaks my AS.
We seem to have anydpi-v26/ic_launcher.xml and this cannot access drawable/ files, but needs drawable-v26 or lower.
Strangely, it compiles still via CLI.

So either we try to fix it (not sure how) or we revert it.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky as mentioned build fine for me.

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky what to do here? I expect this to be a AS caching issue of some sorts and that a fresh clone of the repo would solve the matter for you.

**Comment by ZetaTom** [comment]
Looks good to me; build succeeds and runs fine on my machine.

One thing I've noticed, is that the app icon for the QA build now also reads *Dev* instead of *QA*. (see `app/src/qa/res/drawable/ic_launcher_foreground.xml`)

**Pull request merged**
