### PR TITLE
Move push token preference to AppPreferences

### PR DESCRIPTION
**Pull request by ezaquarii**
Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### CODE REVIEW

**Comment by ezaquarii** [comment]
@tobiasKaminsky 

Could you pls interpret the CI error for me? I'm really confused:

```
> Task :findbugs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':findbugs'.
> FindBugs rule violations were found. See the report at: file:///drone/src/github.com/nextcloud/android/build/reports/findbugs/findbugs.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 3s
1 actionable task: 1 executed
found warnings: 475
previous warnings: 475
SUCCESS: count stayed the same
```

1. there are a lot of older violations
2. I checked files touched by my commits but I failed to eyeball any new issues there

Halp!

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky looks cde to me code-wise. Feel free to merge after review.

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger Anything left here to do? Shall we merge?

**Comment by AndyScherzinger** [comment]
Yes, I just hit the button. I would have liked to get Tobias' feedback but he is hard to get this week.

**Comment by ezaquarii** [comment]
Thank you.

**Comment by AndyScherzinger** [comment]
my pleasure, really!

**Pull request merged**
