### PR TITLE
Clicking on link in activity list shows correct file/folder

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref #1151 

One drawback is that we have to sync every file during activity fetching as it can happen that they have never been synced, so this will take a little bit longer than before.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky  does it have to be done during activity fetching or could it be done "on demand" whenever someone actually clicks on an item?

**Comment by mario** [comment]
I definitely vote for "on demand". Everything else is ... bad :)

**Comment by tobiasKaminsky** [comment]
Currently neither FileDisplayActivity and all other PreviewActivity need to have a real, filled ocFile.
I tried retrieving the complete ocFile in onClick function (when you click on the activity info) but this is an UI thread, so I would have to add a new asyncTask with first shows a spinner while retrieving.
--> I'll try it.

(Retrieving the activity is only slow for the first time of every item. If ocFile is already downloaded there is no delay)

**Comment by mario** [comment]
Make sure to take rotation into account ;)

**Comment by tobiasKaminsky** [comment]
Now it is "on demand".
Screen rotation also works.

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger go for it.

**Comment by AndyScherzinger** [comment]
:+1:  done

**Pull request merged**
