### PR TITLE
Fix crashing issue on bootup

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

This should fix an issue with one of the most reported crash on the play store.

cc @tobiasKaminsky @AndyScherzinger

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Which issue?
Is there another way to solve it? As now you have a permanent notification:

 

Of course the user can disable tho notification channel, but this is then required by each single user...

**Comment by mario** [comment]
When you call context.startForegroundedService (this is something you added to bootup receiver for 8.0), you also need to call startForeground which we didn't do before this PR.

This service will hopefully go away anyway eventually.

**Comment by tobiasKaminsky** [comment]
👍

**Comment by AndyScherzinger** [comment]
👍

**Pull request merged**
