### PR TITLE
Add support for QR codes & deep links

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
- bump min sdk from 14 to 15. Needed by lib, but according to google we do not have any with <4.0.3
image
- in login screen, you can now scan a QR code (requires Camera access)
- you can also click on any nc://login… link and it will also log you in.
- if new library version up released, we can switch to use this

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Can I be annoyed by this? Simply because I vote/fight/argue for a version bum 14->15 (see #2923) and get blocked but when we need a QR code scanner we happily do so?

**Comment by tobiasKaminsky** [comment]
Hm. You are right, sorry :heart:!
The last time we talked about this, there were active 4.0.x devices, now there are none.
So we still should keep min 14, until we have a go in #2923.

I can show the button for >=15 only, but I have to figure out how I can do this in build.gradle.

**Comment by AndyScherzinger** [comment]
> The last time we talked about this, there were active 4.0.x devices, now there are none.

Well, 13 to be true ;) And for customers it could be a case if they run a branded client ;)

> So we still should keep min 14, until we have a go in #2923.

No, we should drop 14. If _whoever_ can't provide any feedback regarding this, even within the last **3 months** then they shouldn't have a say in this or have to deal with the situation afterwards. You are either involved in this or you are not and if you are not (which seems obvious) than you don't get to vote on this. Just my 2 cents.

> I can show the button for >=15 only, but I have to figure out how I can do this in build.gradle.

Please let's move on to v15 🙏

**Comment by tobiasKaminsky** [comment]
> Well, 13 to be true ;)

API14: 4.0, 4.0.1, 4.0.2 
API15: 4.0.3, 4.0.4

So, apart from any customers, fdroid, manual installations, we do not have 14 in use.

**Comment by AndyScherzinger** [comment]
> So, apart from any customers, fdroid, manual installations, we do not have 14 in use.

correct 👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I revamped the qr code icon :)
device-2018-12-19-090801

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky tested the scanner with non-Nc-login-link qr codes. The scan then returns to the login screen (like in the screenshot above) but I don't get any feedback as a user that the qr code is not a Nc-Login-code so I think it would be good to show a Toast or Snackbar stating exactly that. :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky some issues I found:

* use non fitting qr code -> return back to login screen (no feedback)
* use nc:// url with wrong credentials (spinner and return back to login overview screen where you choose between login and provider!) -> should end up on login screen again and also provide a feedback about the failed login
* test suite still uses `nextcloud:` as the protocoll not `nc://` should be updated within this PR

What works:
* login via proper qr code with valid credentials 👍

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger can you re-test it again?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky erm, my commit is gone?! with my visual changes?!

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky rebased and fixed the scan icon. non-fitting QR codes still return back to login screen without any feedback. Just try this one:
frame

**Comment by tobiasKaminsky** [comment]
Due to force push, where your qr image gone away, a permission for vibrate was also missing…

**Comment by AndyScherzinger** [comment]
👍 Nice, all good. Just signing the code is missing...

**Comment by marinofaggiana** [comment]
@tobiasKaminsky where is the image that you have used for QRCode button ?

**Comment by AndyScherzinger** [comment]
@marinofaggiana it from the material design icons list: http://materialdesignicons.com/icon/qrcode-scan

**Pull request merged**
