### PR TITLE
#129 Add authorities prefixes to providers

### PR DESCRIPTION
**Pull request by przybylski**

### CODE REVIEW

**Comment by przybylski** [comment]
#129

**Comment by tobiasKaminsky** [comment]
Have you tested it with an owncloud app in parallel?
I think we have to modify also the package name of the class, or?

**Comment by przybylski** [comment]
I haven't but It shouldn't be a problem, BUT ill check.

**Comment by tobiasKaminsky** [comment]
I tried it, but it did not work. I had to change authorities to
com.nextcloud.android.providers.UsersAndGroupsSearchProvider

**Comment by AndyScherzinger** [comment]
I've tested it with @przybylski's latest commit and it is working. :+1:

**Comment by AndyScherzinger** [comment]
@przybylski @tobiasKaminsky - one minor thing though which we can postpone for now. The authority changes are now using ```com.nextcloud.android``` which nicely matches the app's id except for the newly introduced document provider which is packaged in ```org.nextcloud```. Not sure if we want to change this, but using com.nextcloud.android as a parent package for new thing seems consistent naming wise.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you also do a final test/approval ?

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger regarding com.nextcloud vs. org.nextcloud we should discuss in a new issue.

**Comment by tobiasKaminsky** [comment]
I have tested it with both apps installed in parallel.
It works :+1:

**Pull request merged**
