### PR TITLE
Contact backup & import

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
**ToDo**
- when in contact backup setting and selecting a file to restore, fragment is not correctly replaced

**To discuss**
- filter contacts in contact list?

Settings screen
screenshot_1492001241

Date chooser for selecting backup file. Range is determined by files in folder.
If a file does not exist, an error is shown.
If a date is clicked the latest (in case of multiple files on a day) file is directly opened as contact list.
screenshot_1492001245

Contact list
screenshot_1492001329

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Didn't have the time to take a closer look at the code, so just some minor issues I saw:

* ListView should be replaced with a RecyclerView 
* contact avatar including padding and margin should be exactly 72dp so the text aligns with the toolbar header 
* headlines in contacts settings should be bold 
* if possible then the avatars should be circular, like you can see in the Manage Accounts view

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger thank you for your design review.
Everything you mentioned is now done.

**Comment by tobiasKaminsky** [comment]
@mario the pending codacy reports are from the third party lib.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario I excluded the third party folder on codacy check now :)

**Comment by AndyScherzinger** [comment]
Just flipped through, scrolling the contact list lead to a crash:
```
04-17 20:18:49.754 8564-8564/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.nextcloud.client, PID: 8564
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String ezvcard.property.StructuredName.getGiven()' on a null object reference
    at com.owncloud.android.ui.activity.ContactListAdapter.onBindViewHolder(ContactListFragment.java:389)
    at com.owncloud.android.ui.activity.ContactListAdapter.onBindViewHolder(ContactListFragment.java:336)
    at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6062)
    at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6095)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5277)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5153)
    at android.support.v7.widget.RecyclerView$Recycler.prefetch(RecyclerView.java:5932)
    at android.support.v7.widget.RecyclerView$ViewPrefetcher.run(RecyclerView.java:4524)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6290)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by AndyScherzinger** [comment]
Applied minor design tweaks like material design spacings and the Nc letter avatars :)
device-2017-04-19-191141

device-2017-04-19-191343

**Comment by mario** [comment]
👍

**Pull request merged**
