### PR TITLE
Fix notification color

### PR DESCRIPTION
**Pull request by AndyScherzinger**
fixes the coloring for notifications coming in via push

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
fixes the coloring for notifications coming in via push

Before:
screenshot_20170824-144432

After:
screenshot_20170824-184505

Implementation respects server side theming values

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky please review

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger remember when I told you we'll need this? :P

**Comment by AndyScherzinger** [comment]
> remember when I told you we'll need this? :P

@mario nope, we need what? The coloring or something else that is missing here?!

**Comment by mario** [comment]
Well i told you we will need theme coloring that you just did :)

So I merged :)

**Pull request merged**
