### PR TITLE
Fix seekbar tinting for video/audio player

### LINKED ISSUE #1761: Bubble on Video Player Progress Bar not visible
While playing a Video, it appears that the progress bar is not showing progress:

I identified this is really because the progress bar is thicker than the bubble and they both have the identical color. Thus the bubble is  there and functional, it is just not visible:

skizze

In full screen mode everything is fine, as the progress bar line is much thinner:

App Version 2.0.0.

@AndyScherzinger

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Fixes #1761 by correctly removing the background (which then would get tinted...)

Please review @mario @tobiasKaminsky

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Looks very good.
Can you also fix it for fullscreen? ❤️

**Comment by AndyScherzinger** [comment]
> Can you also fix it for full screen?

Did some research but didn't find any way to influence the full screen, my guess it is an OS screen...

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
👍 
What a pitty.

**Comment by AndyScherzinger** [comment]
Yeah, truely a pity. My guess it is either via OS styling or default app theme...

**Pull request merged**
