### PR TITLE
Centralize theming of search bar

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
In the last screenshot I am not sure if we should tint the search input field. I think it is better to not use primary color here, but use black for all.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
> In the last screenshot I am not sure if we should tint the search input field. I think it is better to not use primary color here, but use black for all.

👍

**Comment by tobiasKaminsky** [comment]
> > In the last screenshot I am not sure if we should tint the search input field. I think it is better to not use primary color here, but use black for all.

> :+1: 

Then I'll change this.

**Comment by tobiasKaminsky** [comment]
> > > In the last screenshot I am not sure if we should tint the search input field. I think it is better to not use primary color here, but use black for all.
> 
> > +1
> 
> Then I'll change this.

This is also used in PinCodeActivity…
For very light themes this just looks strange, so it is better to have it black on white.

**Comment by AndyScherzinger** [comment]
still fine with me 👍 

So awaiting @ezaquarii's review :)

**Comment by AndyScherzinger** [comment]
Pinging @ezaquarii to maybe get this in before Monday (rc branching)

**Comment by AndyScherzinger** [comment]
Pinging @ezaquarii to maybe get this in for RC1

**Pull request merged**
