### PR TITLE
UX: Enhance sharing when resharing is forbidden

### PR DESCRIPTION
**Pull request by vnidens**
Pull request for #1176.

Restored Sharing menu for the reshared file.
Warning is showed when resharing isn't allowed.

### CODE REVIEW

**Comment by mario** [comment]
Needs rebase.

**Comment by tobiasKaminsky** [comment]
This will somehow conflict with #1792. 
I will have a look if this can / needs to be combined.

**Comment by AndyScherzinger** [comment]
> This will somehow conflict with #1792.
I will have a look if this can / needs to be combined.

@tobiasKaminsky any feedback on this? :)

**Comment by tobiasKaminsky** [comment]
This is included in #1792, so this can be closed.
@vnidens sorry that your work will not be merged, but inbetween there was a new idea to combine send and share.

**Comment by tobiasKaminsky** [comment]
My fault, sorry this is not included in #1792.
Once #1792 is merged we should rebase this and review it.

**Comment by tobiasKaminsky** [comment]
👍 
Works for me :-)
Thank you very much for your contribution and sorry for the very long delay.

**Comment by mario** [comment]
👍 

@tobiasKaminsky - rebase and merge :)

**Pull request merged**
