### PR TITLE
Release 2.0.1

### PR DESCRIPTION
**Pull request by AndyScherzinger**
This should fix the account removal on first start of the what's new screen which hasn't made it into 2.0.0 for f-droid (unknown to me if it is in the GPlay version).

It is a cherry pick from the original PR #1676 + the update to the latest gradle plugin (to work) and also sets the version number and code for 2.0.1

cc: @mario for review

The branch is based on the 2.0.0 tag.

**Hotfix Release for f-droid**
- [x] Verify that the new version number is shown in settings
- [x] Verify that logging is disabled
- [x] Tag new version as ```stable-2.0.1```
- [x] Verify that it is shown on f-droid (within 24h)
- [x] Publish APK to https://download.nextcloud.com/android/

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
https://github.com/nextcloud/android/pull/1676#issuecomment-336996249 by @tobiasKaminsky mentioned an removal PR is that one missing or did it refer to the "corrupt account RC message"?

**Comment by mario** [comment]
Removing the corrupt accounts thing.

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
Tag has been created: https://github.com/nextcloud/android/releases/tag/stable-2.0.1 for f-droid to pick it up. This is a f-droid only release since this issue isn't present on the GPlay release. Bug fixed is #1691 code change is https://github.com/nextcloud/android/pull/1696/commits/58db883aa339796395d9c28b3937eef3f3de838b

pinging @Bubu - Just wanted to let you know that we needed to do a hot fix for Nextcloud's f-droid 2.0.0 release.

**Comment by AndyScherzinger** [comment]
Due to @tobiasKaminsky being on vacation and this being a needed hotfix 2.0.1 is release with just 1 review instead of two. I tested the branch/PR and created the tag after testing.

**Comment by tobiasKaminsky** [comment]
Yes, I completely forget fdroid when testing/releasing google play version.
Thank you @AndyScherzinger 👍 

(note for myself: do not try to work on such things whith a newborn next to you <3)

**Comment by mario** [comment]
That is unfortunate and one of the reasons why we have double reviews, but mistakes do happen, especially when in rush so it's fine. :)

And you've got a sweet new reason for the mistake :D

**Comment by AndyScherzinger** [comment]
Yeah, no worries, it got reported and fixed!
Just need someone to put a build on the download page on Nextcloud.

**Comment by blizzz** [comment]
> Yeah, no worries, it got reported and fixed!

Yup!

> Just need someone to put a build on the download page on Nextcloud.

IIRC @rullzer has access to  download.nextcloud.com for putting the package there, if this is an issue.

Otherwise, nextcloud.com points directly to F-Droid and to https://download.nextcloud.com/android/, so nothig needs to be done there.

**Comment by rullzer** [comment]
I do. Let me know what needs to be done.

**Comment by AndyScherzinger** [comment]
@rullzer afaik only @tobiasKaminsky and @LukasReschke can do that since the package needs to be build/signed.

**Comment by mario** [comment]
@AndyScherzinger I can sign the package later and send it to @rullzer .

**Comment by AndyScherzinger** [comment]
Cool @mario 👍

**Comment by xXSTrikeXx** [comment]
@tobiasKaminsky I thought you´ve created a roudmap :D 
enjoy your vacations ;)

**Comment by blizzz** [comment]
> Verify that it is shown on f-droid (within 24h)

After >24h F-Droid still lists only 2.0.0

**Comment by AndyScherzinger** [comment]
Unfortunately the publishing is done manually by the fdroid folks...

**Comment by blizzz** [comment]
OK, didn't know that.

**Comment by AndyScherzinger** [comment]
No worries @blizzz - unfortunately that means that it sometimes takes days :/ (still not published...)

**Comment by xXSTrikeXx** [comment]
just wait until maybe tomorrow ;)

**Comment by AndyScherzinger** [comment]
@blizzz 2.0.1 went live on F–Droid yesterday:)

**Comment by tobiasKaminsky** [comment]
As we have a new branching system (and I am not yet used to it):
we merge this PR and then have a 2.0.x release branch, from which we can backport hotfixes and release them as 2.0.1, 2.0.2, ...?

👍

**Comment by AndyScherzinger** [comment]
Well, in this case, no - We can close this issue.

What imho should have happend but didn't due to limited resources and people being unavailable:
* create fix targeting ```master``` branch
* merge it to ```master``` branch
* cherry pick fix on ```my-backport-branch``` targeting ```release-2.0.x``` branch
* merge it to ```release-2.0.x``` branch
* tag release ```stable-2.0.1```on ```release-2.0.x``` branch

What happened this time:
* create fix targeting ```master``` branch (still open)
* cherry pick fix on ```release-2.0.x``` branch and open PR for documentation/discussion
* tag release ```stable-2.0.1```on ```release-2.0.x``` branch

**Comment by AndyScherzinger** [comment]
So this PR can be closed as soon as someone pusblishes the build on https://download.nextcloud.com/android/ and ticks the last remaining open todo...

Sorry for the confusion...

**Comment by tobiasKaminsky** [comment]
I can publish it on download.nc.com. What do we publish there? Google or Fdroid version?

**Comment by mario** [comment]
@tobiasKaminsky it's already there, just not GPG signed (unless it was done by Lukas later). I actually built a generic version for the download.nc.com.

**Comment by AndyScherzinger** [comment]
To answer your question @tobiasKaminsky I think F-Droid :) As for the signing... no idea.

**Pull request closed without merging**
