### PR TITLE
Move auto upload to settings

### LINKED ISSUE #6793: Move auto upload to settings
Currently we have (too?) many items in sidebar.
We could move auto upload to settings as this is mostly a "one time config and forget" task?

@AndyScherzinger @jancborchardt

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #6793

Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky launching the activity within the settings activity somehow fails while I am clueless atm as to why it is not working, maybe you have an idea?

**Comment by tobiasKaminsky** [comment]
works for me…Strange.

**Comment by tobiasKaminsky** [comment]
Top left back arrow is missing, but otherwise…

**Comment by AndyScherzinger** [comment]
Strange, then I'll have to re-check this since I can't even open the screen... :S

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky works for me too now, must have been some hiccup before. I also fixed the back arrow and removed now unneeded code, so this is ready for review now.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky also the sycned folder screenshot test might need some love :/

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky failing screenshot is unrelated, so are the failing IT tests.

**Pull request merged**
