### PR TITLE
Enhance what's new screen

### LINKED ISSUE #2396: Enhance what's new screen
image

[Feedback](https://github.com/nextcloud/android/pull/1657#issuecomment-375121502) by @jancborchardt:
can you also adjust the layout/whitespace according to the screenshot I posted above?
- More spacing above and below the top header
- As mentioned, top header could be better in non-bold to not fight with the feature header
- Less space between feature header and feature detail text

### PR DESCRIPTION
**Pull request by artem-p**
Fixes #2396 

- make top header is not bold
- more spacing above and below the top header
- less space between feature header and feature detail text

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
For me it is a bit too much space on header, but if @nextcloud/designers agree, I am also fine :-)

**Comment by AndyScherzinger** [comment]
Designers approved :)

@mario @tobiasKaminsky for second dev review/approval

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
Thanks a lot for this contribution @artem-p :tada: 
It is highly appreciated! :heart:

**Pull request merged**
