### PR TITLE
Unit tests for the OwnCloudSession class.

### PR DESCRIPTION
**Pull request by ardevd**
- Added unit tests for the OwnCloudSession class. 
- Restricted access declarations for the OwnCloudSession class. Follow the principle of least privileged.

### CODE REVIEW

**Comment by ezaquarii** [comment]
If `OwnCloudSession` is not used outside the package, it should not be exposed as public interface.

I'd turn that rule off honestly, as I find package scope is very handy in hiding internal package guts (helpers, utils, etc) that should not be used outside.

**Comment by tobiasKaminsky** [comment]
Totally agree. 
We should limit the scope as needed, and then can extend it again if needed.
Package scope is a valid approach and thus we should use if, when it fits.

**Comment by tobiasKaminsky** [comment]
@ardevd I added gpl3+ license to unit tests, I hope this is ok?
I also changed OwnCloudSession to use lombok, so we do not need to take care of boilerplate.
I hope you are fine with my changes.

**Comment by ardevd** [comment]
Looks good to me.

**Comment by tobiasKaminsky** [comment]
@ardevd codacy is complaining about underscore in test method names.
while I really like your naming, maybe a simple camel case is also sufficient? :-)

**Comment by ardevd** [comment]
@tobiasKaminsky Well thanks. I'm just following what I've come to believe is the styling guidelines set my Google for test method names and is what I've used for ages. If you want to please Codacy then I won't object. Ideally I'd have an exception in the Codacy rule for test classes though. 

Up to you guys.

**Comment by tobiasKaminsky** [comment]
> Ideally I'd have an exception in the Codacy rule for test classes though.

@AndyScherzinger is this possible?

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger is this possible?

we can exclude testclasses (via the package) from codacy check in general for _any_ kind of check. Codacy doesn't offer more fine grained ways to disable certain checks for certain naming patterns though. We already ignore anything wihtin the test folders while sometimes codacy goes nuts and uses @dan0xii's codacy accoutn/definition and pushes it into the PRs within this repo. So Warnings in test classes can be ignored since they come from the wrong codacy account.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea why the spoptbugs analysis fails within this PR?

**Comment by AndyScherzinger** [comment]
aaaaaand merged 🎉

**Comment by tobiasKaminsky** [comment]
> while sometimes codacy goes nuts and uses @dan0xii's codacy accoutn/definition

I asked codacy and they created a support ticket for this.
This seems to be indeed a problem, as normally a forked project is not related to the original one…

**Comment by AndyScherzinger** [comment]
Nice, so let's see if this can get resolved 🎉

**Pull request merged**
