### PR TITLE
Opens share by clicking icon in file listing

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Reviving old branch by c&p the changes:

a click on the link/shared icon in the file listing opens now directly the share dialog.
(wished by someone long long time ago)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
that was @jancborchardt if I remember correctly

**Comment by tobiasKaminsky** [comment]
Is this working if we have the three dots on every single line (which is also something jan wants)?

**Comment by jancborchardt** [comment]
Aaaawesome, finally! :) and yeah, would be important that both the share icon and the future 3-dot icon work as being tappable. :)

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger if you feel like this is ok, feel free to merge - I will not be able to review it in a while. Thanks.

**Comment by AndyScherzinger** [comment]
👍 works fine, justed tested it

**Pull request merged**
