### PR TITLE
files: avoid possible dereference of null pointer.

### PR DESCRIPTION
**Pull request by ardevd**
~~itseems the `capability` object can be null. In which case it is probably a bad idea to pass a null object into `getRichDocumentsDirectEditing()`.~~

This might not be necessary but it looks very strange to me when you define a variable `endToEndEncryptionEnabled` based on whether the `capability` object is `null` first and then pass that same object to the `filterOpenAsRichDocument()` method later on. That function seemingly assumes the `capability` argument is not null too so something should be done here.

`capability` object cannot be null. Updated associated method with `@NonNull` annotation and removed unnecessary NPE check.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
> it seems the `capability` object can be null.

Where do you see this? :thinking: 

https://github.com/nextcloud/android/blob/92bbcfb973594f9f0aafa16def97d9f003dcbe54/src/main/java/com/owncloud/android/datamodel/FileDataStorageManager.java#L2026-L2037

Here we create explicitly a new "empty" object if we do not have yet capabilities.

**Comment by ardevd** [comment]
I assumed as much due to this line:

https://github.com/nextcloud/android/blob/b96414d794bc2183765d1928491d36dc956a892f/src/main/java/com/owncloud/android/files/FileMenuFilter.java#L168

If capability is never null, then I can simply remove that check there instead?

**Comment by tobiasKaminsky** [comment]
> I assumed as much due to this line:

This is indeed not neeeded. 

> If capability is never null, then I can simply remove that check there instead?

Yes, please and maybe you want to add @NonNull to the getCapability method in FileDataStorageManager to avoid such confusion (and also have IDE to warn about useless NPE checks)

**Comment by ardevd** [comment]
Sounds good! I'll take care of it.

**Comment by tobiasKaminsky** [comment]
Thanks for the fast change!

**Pull request merged**
