### PR TITLE
Slight design optimizations for the login screen #22 

### PR DESCRIPTION
**Pull request by AndyScherzinger**
PR for #22 originally asked for by @jancborchardt 

* remove card view
* change edit text and icon coloring
* add complete set of icons for _ALL_ resolutions

ready for review @tobiasKaminsky @przybylski @LukasReschke @jancborchardt (most file changes are new/revamped icons!)

device-2016-06-26-225818

device-2016-06-26-225834

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
LGTM
btw, I think that we should not put new things to a release after working on it. So next time this should go to the next release, I think. Otherwise it could happen that we postpone the release with every new PR.

**Comment by AndyScherzinger** [comment]
You're right, moved it to 1.2.0 :)

**Comment by jancborchardt** [comment]
Very nice! :) Only thing to improve would be to make the button white (and the text Nextcloud blue #0082c9). Or is this the disabled state?

**Comment by AndyScherzinger** [comment]
This is the disabled state, while atm by defaukllt the only difference for these material button between enabled and disabled is that enabled hat a button drop shadow... (no idea how they came up with that... but I can check coloring of en/disabled state if you want me to)

**Comment by jancborchardt** [comment]
If there’s only one state, then the button should be white with Nextcloud blue text. :) No need to bother about different states if that’s not default.

**Comment by AndyScherzinger** [comment]
Done :)
device-2016-06-27-163555

**Comment by AndyScherzinger** [comment]
@przybylski @LukasReschke can you do a code review? @tobiasKaminsky has already approved (and @jancborchardt )

**Comment by LukasReschke** [comment]
👍

**Comment by mar1u5** [comment]
Perfect :+1: THX

**Comment by mar1u5** [comment]
@AndyScherzinger can you update the screenshot :grin:

**Comment by AndyScherzinger** [comment]
Noooo, this is scheduled for 1.2.0 so it shouldn't have been merged just yet :(

**Comment by AndyScherzinger** [comment]
It doesn't hurt though since I tested it, but still for the future please check the assigned milestone :)

**Comment by mar1u5** [comment]
Uhmm... Is there no `stable1` branch :scream: I'm so sorry :confused:

**Comment by mar1u5** [comment]
Should we revert :grin:

**Comment by AndyScherzinger** [comment]
Nope, we do GH Flow so all PRs go to master and there is only one release train at a time. 
I thoroughly tested it so reverting is not worth the effort, we are going to release an RC so we should be fine. 

The comment was just for the future so accepted PRs don't get merged prematurely :)

**Comment by AndyScherzinger** [comment]
@mar1u5 here's the corresponding screenshot PR https://github.com/nextcloud/screenshots/pull/11 :grin:

**Pull request merged**
