### PR TITLE
Fix theming: server url input

### LINKED ISSUE #4752: Server input no underline

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
fix #4752

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you remove the now unused theme definition, see lint report. I'd do it but am afk.

**Comment by tobiasKaminsky** [comment]
But this is used here?
https://github.com/nextcloud/android/blob/c1aa005db929d08af4453489de603938e9d0c9c2/src/main/res/layout-land/account_setup.xml#L113

Not sure why lint does not find it?

**Comment by tobiasKaminsky** [comment]
Ah. We then should remove it there also…

**Comment by tobiasKaminsky** [comment]
CI is unrelated.

**Pull request merged**
