### PR TITLE
Use material 3 style for SSO dialog

### PR DESCRIPTION
**Pull request by AlvaroBrey**
| Before | After |
|  --- | --- |
|  Screenshot_1667822281   |  Screenshot_1667822194  |

### CODE REVIEW

**Review by AndyScherzinger — COMMENTED** [review]
@AlvaroBrey the buttons/background(?) need theming after `.show()`

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey the buttons/background(?) need theming after `.show()`

I'm not sure it makes sense; as this activity may be called asking for permission for an user that's not the currently active user.

**Comment by stefan-niedermann** [comment]
Regarding theming I'd recommend white / black text for thr buttons. The default Material You color is not used anywhere I am aware of...

**Comment by AlvaroBrey** [comment]
> did you check on background theming with `surface`

Done. The only difference is that the background for the dark variant is a little darker (I guess for better contrast with the buttons)

**Review by stefan-niedermann — APPROVED** [review]

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
