### PR TITLE
When uploading files to an encrypted folder do not allow to upload entire folders

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [ ] Tests written, or not not needed

### CODE REVIEW

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
@tobiasKaminsky is this still relevant? If so, it should be rebased and  merged

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky is this still relevant? If so, it should be rebased and merged

Yes, rebased and tested.

**Pull request merged**
