### PR TITLE
another try to get rid of vanishing ringtones, but keep storage location

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@skeletor-spills @axheli @elektrikfisch @nateyoung @OlivierS1

Can you please download above QA build and test this feature again.
I figured out that with previous fix ringtones were not disappearing, but also the images are not shown in gallery app.

So please 
- download QA build
- check ringtones
- download an image
- check ringtones again
- see if image pops up in gallery app

**Comment by axheli** [comment]
@tobiasKaminsky  I lost the ringtones with this version when i uploaded files but photos are showing up

**Comment by simonspa** [comment]
@tobiasKaminsky I installed this APK to test whether this solves the issues described in #6150 and it indeed does seem to do the job. At least music starts showing up again in my music player (Shuttle).

I noticed is that 
* suddenly also files from the "regular", normally installed NC client show up?
* the entries in the media store don't seem to be deleted when removing the app. I uninstalled the QA app but its music files still show up in the player, the files however are removed.

Does this help?

**Comment by skeletor-spills** [comment]
Sorry for the late response, just tested and this regressed the ringtone issue for me. 

After install, I uploaded some photos and afterwards, the system notifications were gone again. The images did show up in the Photos folder gallery view.

Hope this helps.

**Comment by tobiasKaminsky** [comment]
Thanks, so this is not the way to go.

**Comment by tobiasKaminsky** [comment]
So approach https://github.com/nextcloud/android/pull/6329 will it be 🤞

**Pull request closed without merging**
