### PR TITLE
i18n: Spelling unification

### PR DESCRIPTION
**Pull request by Valdnet**
Spelling unification in Transifex.

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Review by AlvaroBrey — APPROVED** [review]

**Comment by Valdnet** [comment]
@AlvaroBrey Please merge. Thanks 😉.

**Comment by nickvergessen** [comment]
Breaks translation sync.

**Comment by nickvergessen** [comment]
I guess it should be backported to stable-3.21 and stable-3.20 (other streams which are translated)

**Comment by AndyScherzinger** [comment]
@nickvergessen backports triggered and merged. Can you trigger the backport bot again please 🙏

**Comment by nickvergessen** [comment]
I triggered translation bot :P

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/android/commit/17977f42f0c571637b008580254f417d73bb7753

Worked again

**Pull request merged**
