### PR TITLE
Support notch

### LINKED ISSUE #4437: Site URL is not displayed all
I noticed that in the application 
the URL of the site is cut in half horizontally, 
the characters are not completely visible.  
I am attaching a screenshot.

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #4437 

Left is with notch, right without.

  

@tigernero79 can you test the apk in this PR? It can be installed in parallel

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tigernero79** [comment]
if you tell me where to download apk you the text on my s10 plus let me know if I have to remove apk that I already have or as you say I can install it inparallel

**Comment by AndyScherzinger** [comment]
@tigernero79 see https://github.com/nextcloud/android/pull/4486#issuecomment-529874365

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I vote for backporting while I wouldn't put it into 3.8.0 but 3.8.1 (with an RC)

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky I vote for backporting while I wouldn't put it into 3.8.0 but 3.8.1 (with an RC)

3.8.1 sounds fine, but first let us await @tigernero79 feedback :-)

**Comment by tigernero79** [comment]
I installed apk but same problem on s10 plus as you can see from photo

IMG_20190910_144728

**Comment by tobiasKaminsky** [comment]
Hm. Then I am currently out of idea.
I would need access to such a device to fiddle around with it.
I close this PR, but corresponding bug remains open.

**Pull request closed without merging**
