### PR TITLE
Don't beautify empty inputs

### PR DESCRIPTION
**Pull request by przybylski**
Empty string as twitter handle as well as empty website is invalid. So don't beautify it.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Using multiple whitespaces on twitter are still shown, so we need to trim the input.
As (maybe) other use the library, maybe this is better in library? We could make sure that each string is either "" or has a correct value.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky so how to progress? I'd be fine with this PR while that doesn't render the discussion about doing a library enhancement absolete.

**Comment by tobiasKaminsky** [comment]
> Using multiple whitespaces on twitter are still shown, so we need to trim the input.

This is still a "bug".

Regarding lib/no lib: It was just an idea. I have no strong feelings regarding this.

**Comment by AndyScherzinger** [comment]
👍 

> This is still a "bug".

@tobiasKaminsky @przybylski I added a trimming to the other cases for beautifying URL/twitter-handle. So I am fine with the PR +1 :)

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
Have you tested this?
Using "  " (two whitespaces) on twitter, results in



The twitter handle needs first to get trimmed, before checking for prefix.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky you are right, created an issue for that #2159

**Pull request merged**
