### PR TITLE
Fix bug stop player when delete file

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
@AndyScherzinger what about this branch?

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Should be fine, just needs codacy love and testing

**Comment by tobiasKaminsky** [comment]
From the PR name I do not understand what I shall test
- start playing a file
- delete it (remote, locally, within the app, with a file browser?)
- what do expect: no crash, stop, error message?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky from what I understand from the code changes it is 
* playing a file, 
* remove it locally while playing, 
* playing stops.

**Comment by tobiasKaminsky** [comment]
👍 
Tested and it is working

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger ? :)

**Comment by tobiasKaminsky** [comment]
As @AndyScherzinger did a cherry pick from upstream and 2 devs tested it, we can merge it right away.
I did a rebase, waiting now for ci.

**Pull request merged**
