### PR TITLE
Fix #9842: Run network operations in async task

### LINKED ISSUE #9842: Exception on sharing files stored on nextcloud instance
### Steps to reproduce
1. Share some files stored on nextcloud (either from within an application or file manager)

### Expected behaviour
- Well, a file shared

### Actual behaviour
- Crashes/Files not shared

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version: 10, lineageos, no Gapps

Device model: 
Google PixelXL

Nextcloud app version:
3.19.0 (F-Droid)

Nextcloud server version:
22.2.3

### Logs

[log.txt](https://github.com/nextcloud/android/files/8066935/log.txt)

* Since this did not happen with all applications I´ve opened https://github.com/vector-im/element-android/issues/5236 for element-android.
* I could not reproduce this with `Conversations` xmpp client.

### PR DESCRIPTION
**Pull request by akallabeth**
This pull request fixes running network tasks on UI thread.
Some applications invoke the `DocumentProvider` from `UI` thread. Although that is not really good practice it should not lead to the `DocumentProvider` failing to download files.

### CODE REVIEW

**Review by AlvaroBrey — CHANGES_REQUESTED** [review]
Theoretically, the `DocumentProvider` shouldn't even be making network requests in its API methods, but that's not the point of this PR I guess.

Either way, I don't think its a good idea to make this threading change in the `DownloadFileOperation` itself. `RemoteOperation`s (like that one) are also scheduled in background thread in other parts of the app, so this would be redundant.

Please instead do the threading changes in `DocumentProvider.openDocument`.

**Comment by akallabeth** [comment]
@AlvaroBrey Ok, done.

**Review by AlvaroBrey — APPROVED** [review]

**Comment by akallabeth** [comment]
@AlvaroBrey If I´m not mistaken you can remove my commit as yours completely replaces it.

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey If I´m not mistaken you can remove my commit as yours completely replaces it.

That would not  count your contribution, and there's people who care about that :)  I've instead signed off your commit myself. Thank you!

**Pull request merged**
