### PR TITLE
getServerVersion() can be null, if so, then chunked = false

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Found via google dev console

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by AndyScherzinger** [comment]
pinging @mario for second review :)

**Comment by AndyScherzinger** [comment]
pinging @mario for second review :)

**Comment by mario** [comment]
What versions don't support chunking? Afaik all versions that are not EOL do...

**Comment by tobiasKaminsky** [comment]
Indeed, we check for 4.5.

--> I will enhance this PR to remove all unneeded checks for version <11 as those are end of life.

**Comment by mario** [comment]
Let me know when done.

**Comment by tobiasKaminsky** [comment]
This is done via #2178, therefore this PR can be closed.

**Pull request closed without merging**
