### PR TITLE
Bug-fix Open Image Inside Encrypted Folder

### PR DESCRIPTION
**Pull request by alperozturk96**
- [x] Tests written, or not not needed

**How to Test**

1. create an e2e encrypted folder
2. upload image
3. Try to open that image

**Known Issues**

Uploading another file for previously encrypted folder not working. Aim of this PR is fixing preview and opening media not fixing upload problems.

### CODE REVIEW

**Review by JonasMayerDev — APPROVED** [review]
Fixes the problem for me in quick test

**Review by AndyScherzinger — COMMENTED** [review]
🐘

**Pull request merged**
