### PR TITLE
Codacy

### PR DESCRIPTION
**Pull request by AndyScherzinger**
some housekeeping from time to time

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Nice catches :+1:

**Comment by tobiasKaminsky** [comment]
Hm. Drone failed 5x in a row directly after starting gradlew.
I squashed your commits to get  a new commit, hopefully this helps.

**Comment by AndyScherzinger** [comment]
> Hm. Drone failed 5x in a row directly after starting gradlew.

Same happens for other branches as well, gradle deamon dies for some reason...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you have a look at the analysis script please? Spotbugs score decreased while the script fails saying it increased :/

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky can you have a look at the analysis script please? Spotbugs score decreased while the script fails saying it increased :/

Now it says that lint and spotbugs stay the same.
Would be ok, or?

**Comment by AndyScherzinger** [comment]
Yes, that's fine. It was just before when the scores differed.

**Pull request merged**
