### PR TITLE
Screenshot tests reliability improvements

### PR DESCRIPTION
**Pull request by AlvaroBrey**
- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
I've restarted the screenshot workflow several times and it seems like reliability is greatly improved by slowing down these 4 tests a bit.

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
While sleep is not the best approach, it is a good tradeoff for having more reliable tests 👏👏👏

**Comment by AlvaroBrey** [comment]
> While sleep is not the best approach, it is a good tradeoff for having more reliable tests 

I agree, however `waitForIdleSync` does not seem to be enough for these cases :\

**Pull request merged**
