### PR TITLE
Provide a manual for the DAVDroid sync setup

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @oparoz ;)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1+

One thing though it also works with f-droid client installed  or both (let's you choose)  or none which  will open the browser link ;)

**Comment by MorrisJobke** [comment]
> One thing though it also works with f-droid client installed or both (let's you choose) or none which will open the browser link ;)

Let me adjust the text then.

**Comment by MorrisJobke** [comment]
I updated it and will deploy this to our documentation server :)

**Comment by AndyScherzinger** [comment]
You just wanted to own PR n.o. 500 :tada:

**Comment by MorrisJobke** [comment]
> You just wanted to own PR n.o. 500 🎉

Oh yes 😃  This was my evil master plan 😈

**Pull request merged**
