### PR TITLE
Possible weird lint merge fix

### PR DESCRIPTION
**Pull request by rullzer**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@MorrisJobke do you have an idea why there is a merge commit even though the script is only adding a commit? https://github.com/nextcloud/android/blob/master/scripts/analysis/lint-up.rb#L170-L192

**Comment by MorrisJobke** [comment]
> @MorrisJobke do you have an idea why there is a merge commit even though the script is only adding a commit? https://github.com/nextcloud/android/blob/master/scripts/analysis/lint-up.rb#L170-L192

No idea - looks good to me.

**Comment by MorrisJobke** [comment]
Maybe try the exact same steps locally and check if then a merge commit happens. :/

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/commits/testLintPush

On this branch I did the same steps, except of setting user/email via git config.
There is only a commit.

**Comment by tobiasKaminsky** [comment]
In drone log:
```
revious warnings: 999
error: pathspec 'origin/rullzer-patch-1' did not match any file(s) known to git.
[detached HEAD 91de249] Drone: update Lint results to reflect reduced error/warning count [skip ci]
 1 file changed, 1 insertion(+), 1 deletion(-)
To https://nextcloud-android-bot:692752d9438fbdd44d134b916eb95be72435d50c@github.com/nextcloud/android
   933f66a..91de249  HEAD -> rullzer-patch-1
SUCCESS: count was reduced
```

**Comment by tobiasKaminsky** [comment]
``` 
Merge 933f66a into c4cfd0d

@rullzer
rullzer committed 8 minutes ago
`` 
933f66a is the latest commit into this branch prior drone shows up.
c4cfd0d is the latest commit to master.

So somehow drone is just updating the branch…But why?

**Comment by tobiasKaminsky** [comment]
@rullzer @MorrisJobke do you have an idea why drone is updating the branch?
If not, we have to live with it…

**Comment by MorrisJobke** [comment]
> @rullzer @MorrisJobke do you have an idea why drone is updating the branch?
> If not, we have to live with it…

Really no idea 🙈

**Comment by tobiasKaminsky** [comment]
Closing as no one has ideas. I guess we have to live with the additional merge.

**Pull request closed without merging**
