### PR TITLE
Start working on 2.0.0 changelog

### PR DESCRIPTION
**Pull request by mario**
This will be updated as we go.

Let me know if I forgot something folks!

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Looks good to me so far :)

> Custom external links support

Is this a general feature or is it modified/custom build only?

**Comment by tobiasKaminsky** [comment]
General, but it needs an app on the server side.

**Comment by tobiasKaminsky** [comment]
As the auto upload was enhanced in such a great way by @mario I think we should show this in "Whats New Screen" during update and clarify the expectations of the user (no instant upload, but reliable, less battery consumption, no missing files).
Maybe these 4 points are enough?

**Comment by mario** [comment]
@tobiasKaminsky I agree, however with Android 7+ you get near-instant uploads most of the time for non-custom folders (video and photo). Magic :)

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky 

PRs to review: https://github.com/nextcloud/android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+1.5.0%22

One issue remains to be fixed: https://github.com/nextcloud/android/issues/1248

Also, please start tagging tasks for 1.5.1 and update the changelog stuff if I forgot any.

**Comment by AndyScherzinger** [comment]
I'm raising the question once more: Version?

Looking at the amount of work that has been put into and the amount of features that have been added to the app I'd still vote for going for v2.0.0 since this is quite a large release which imho allows for a major version bump.

**Comment by mario** [comment]
@AndyScherzinger fine with this. If @tobiasKaminsky agrees, please update all things needed.

**Comment by AndyScherzinger** [comment]
@mario of course, will do - depending on @tobiasKaminsky's opinion on this.

**Comment by tobiasKaminsky** [comment]
Ok, fine for me. But then we should add some more slides to whats new.

**Comment by AndyScherzinger** [comment]
> But then we should add some more slides to whats new.

fine by me too :)

Any preferences & opinions on what should be added?

**Comment by AndyScherzinger** [comment]
👍 fine by me, all feature changes are listed so this is completed but needs to wait for the final release before it's merged

**Comment by AndyScherzinger** [comment]
👍 fine by me, all feature changes are listed so this is completed but needs to wait for the final release before it's merged

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please ignore drone. It builds fine but the what's new change introduced a variable/placeholder in an existing string which now leads to errors since the translations don't have the variable just yet. This will be fixed automatically by transifex and our bot.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky important sidenote: after this PR has been merged - transifex bot needs to be triggered (maybe twice) so the changed string get removed (which are causing errors/warnings) at the moment...

**Comment by tobiasKaminsky** [comment]
We have now 7 additional warnings, I will adjust the lint-results manually to get it working again

**Pull request merged**
