### PR TITLE
Change settings background color to white

### LINKED ISSUE #1624: Settings background is greyish instead of white
The background color of the Settings is a slight grey. All background colors (except when viewing images of course) should be white though.

EDIT: Andy -> changed description to all backgrounds should be white.

### PR DESCRIPTION
**Pull request by apicellaj**
Resolves #1624

The slight grey background isn't very noticeable on my device so any confirmation that this solves the issue would be great. Thanks!

### CODE REVIEW

**Comment by mario** [comment]
Hello, thanks for your contribution. This has already been fixed I'm afraid :(

https://github.com/nextcloud/android/pull/1635

**Comment by apicellaj** [comment]
That PR was closed by the submitter. Was the settings change implemented somewhere else?

**Comment by mario** [comment]
Ah sorry. Reopening. cc @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Sweet @apicellaj! I’ll check it out tonight.

**Comment by AndyScherzinger** [comment]
@mario please review, I checked the coloring and now it is correctly set to white :) I'll take care of droneCI builds...

**Comment by AndyScherzinger** [comment]
👍 works like a charm

**Comment by mario** [comment]
👍

**Pull request merged**
