### PR TITLE
Hide download also on folders

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Awaiting confirm of @rullzer that this is in NC15.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky and this would be backwards-compatible out-of-the-box? (since there is no lib change or anthing like that/version check, fallback)

**Comment by tobiasKaminsky** [comment]
There is a capability for this: https://github.com/nextcloud/android/pull/3286/files#diff-1b755bab341231ae1e502b6e5a8784d0R72

**Comment by AndyScherzinger** [comment]
👍 fine by me, @tobiasKaminsky are we still waiting for @rullzer's confirmation?

**Comment by tobiasKaminsky** [comment]
>  fine by me, @tobiasKaminsky are we still waiting for @rullzer's confirmation?

He already confirmed on the server repo, that it is in NC15.

**Pull request merged**
