### PR TITLE
use path separator constant

### PR DESCRIPTION
**Pull request by jmue**
Use already defined path separator constant.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Nice!
But there are even more, if you search for "/" in total project.
So…if you want… :-)

**Comment by jmue** [comment]
> Nice!
> But there are even more, if you search for "/" in total project.
> So…if you want… :-)
I'm unsure how to deal with slashes within uri context. From my point of view they are not logical part of OCFile.PATH_SEPARATOR constant.

**Comment by tobiasKaminsky** [comment]
> But I'm unsure how to deal with slashes within uri context. From my point of view they are not logical part of OCFile.PATH_SEPARATOR constant.

I would keep them, as you are right that they are not related to OCFile/files at all.

**Comment by tobiasKaminsky** [comment]
Thank you very much!

**Pull request merged**
