### PR TITLE
Rotate images functionality

### PR DESCRIPTION
**Pull request by surinder-tsys**
Rotate image functionality added to image files.

**How it works:**

1. Open any image in preview mode.
2. Click on 3 dot menu at top right and then click on Rotate menu option.
3. On clicking Rotate menu option it will rotate the image 90° clockwise.
4. Now the rotated image will be uploaded to cloud under 2 case:
    4.1. When user rotates the screen i.e. configuration changes.
    4.2. When user comes back from the preview screen.
5. We are updating the image thumbnail in cache to give seamless experience to user and also updating the new rotated image file with current one.

**Note: Rotate functionality only applicable to JPG and PNG files.**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Feedback from Oliver/Jens:
- rotate function should not be limited to jpg/png
- when rotating an image that is not yet downloaded, then download it, rotate, re-upload it

**Comment by tobiasKaminsky** [comment]
> Feedback from Oliver/Jens:
> 
>     * rotate function should not be limited to jpg/png
> 
>     * when rotating an image that is not yet downloaded, then download it, rotate, re-upload it

@surinder-tsys can you address these changes?

**Comment by surinder-tsys** [comment]
> > Feedback from Oliver/Jens:
> > ```
> > * rotate function should not be limited to jpg/png
> > 
> > * when rotating an image that is not yet downloaded, then download it, rotate, re-upload it
> > ```
> 
> @surinder-tsys can you address these changes?

@tobiasKaminsky  we are working this on parallelly but with low priority as these are enhancements. Once they are done we will create separate PR.

**Comment by surinder-tsys** [comment]
@tobiasKaminsky Can you please review and merge this PR?
Once the the pending enhancements are developed we will raise the separate PR.

**Comment by tobiasKaminsky** [comment]
> when rotating an image that is not yet downloaded, then download it, rotate, re-upload it

This is needed, as currently otherwise it will overwrite the file, like this:
- open an image that is not downloaded (small preview is shown)
- rotate image (preview is rotated)
- save
--> small preview is uploaded and overwrites real image

So please either fix it or show rotate option only when file is downloaded.

**Comment by surinder-tsys** [comment]
> rotate option only when file is downloaded.

Hi @tobiasKaminsky, for this is it ok if we hide the rotate option for online files?

**Comment by AndyScherzinger** [comment]
@surinder-tsys @tobiasKaminsky @ZetaTom looking at https://github.com/nextcloud/android/pull/11746 which one will be the one to be merged? I guess we won't have both in, no? Just checking so no efforts are wasted.

**Comment by surinder-tsys** [comment]
> @surinder-tsys @tobiasKaminsky @ZetaTom looking at #11746 which one will be the one to be merged? I guess we won't have both in, no? Just checking so no efforts are wasted.

@AndyScherzinger I will check with the Jens if he is ok with the NC edit functionality or MagentCloud rotate functionality.

**Comment by AndyScherzinger** [comment]
Thanks @surinder-tsys for taking care of the clarification 👍

**Comment by surinder-tsys** [comment]
@AndyScherzinger Here is the Jens update  -->  "We as MagentaCloud will be using rotate functionality till NextCloud edit functionality will get stable and merged to master."

**Comment by surinder-tsys** [comment]
Closing the PR as per above discussion.

**Pull request closed without merging**
