### PR TITLE
Any theming call has now context, instead of app context

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
With this any theming call uses now the context from the calling instance.
Only in both service (FileDownloader, FileUploader) getApplicationContext is used.

We are using theming on that many calls that the PR is such big :/

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
Build fails?

**Comment by AndyScherzinger** [comment]
:+1: fine by me, rebased and fixed all api changed and lint warnings

**Comment by mario** [comment]
👍

**Pull request merged**
