### PR TITLE
Npe in get sharees

### LINKED ISSUE #4369: Crash when entering external folder
************ CAUSE OF ERROR ************

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at com.owncloud.android.datamodel.FileDataStorageManager.createFileInstance(FileDataStorageManager.java:1002)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:864)
	at com.owncloud.android.datamodel.FileDataStorageManager.getFolderContent(FileDataStorageManager.java:157)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.swapDirectory(OCFileListAdapter.java:719)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1175)
	at com.owncloud.android.ui.fragment.OCFileListFragment.listDirectory(OCFileListFragment.java:1120)
	at com.owncloud.android.ui.fragment.OCFileListFragment.onItemClicked(OCFileListFragment.java:894)
	at com.owncloud.android.ui.adapter.OCFileListAdapter.lambda$onBindViewHolder$0$OCFileListAdapter(OCFileListAdapter.java:337)
	at com.owncloud.android.ui.adapter.-$$Lambda$OCFileListAdapter$KYFT7zrcMuRQdUdOUJx291OJcIg.onClick(Unknown Source:4)
	at android.view.View.performClick(Unknown Source:15)
	at android.view.View$PerformClick.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:206)
	at android.app.ActivityThread.main(Unknown Source:113)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:224)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30080051
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: htc
Device: htc_imeuhl
Model: HTC U12+
Id: OPR1.170623.032
Product: imeuhl_00401

************ FIRMWARE ************
SDK: 26
Release: 8.0.0
Incremental: 1050003.2

Steps to reproduce: I have several local folders mounted in NC as External storage. Every time app crashes when I try to enter in one specific folder, which is accessible in web portal and webdav. If more info is needed I can provide it.

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Resolves #4369

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
shouldn't this go to master with backport to stable?

**Comment by tobiasKaminsky** [comment]
> shouldn't this go to master with backport to stable?

Totally right. I changed it :+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky strange thing is it reports Detekt and Kotlin warnings while your change is purely java-based...

**Pull request merged**
