### PR TITLE
Remove gcm as we use firebase messaging

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
@mario as you have a lot more experience, especially due to talk, with push notifications.

I read somewhere that GCM and FCM in parallel are generating lots of trouble.

With latest microG and this PR I now get push notifications.
It also still works on Samsung S5 Neo.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by mario** [comment]
Did you make sure to install the app from scratch while testing?

**Comment by tobiasKaminsky** [comment]
Yes. I had to uninstall them both as they were not signed with gplay signature.

**Comment by mario** [comment]
Then merge away.

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky should this be backported for 3.3.0?

**Comment by tobiasKaminsky** [comment]
I rather would like to have this in devVersion first for a while, to see if it is working fine.
I recently had a duplicate push notification with microG.

**Comment by AndyScherzinger** [comment]
> I rather would like to have this in devVersion first for a while, to see if it is working fine.

perfectly fine with me!

**Pull request merged**
