### PR TITLE
Bump drone version

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky v38 of the image isn't available yet on docker hub

**Comment by tobiasKaminsky** [comment]
Yes, it takes quite a time to build: https://hub.docker.com/r/nextcloudci/android/builds/bd3btxoffxuqn3jx68t7kk9/

**Comment by AndyScherzinger** [comment]
docker build failed :/

```
A problem occurred evaluating root project 'gradle'.
Could not read script '/gradle/gplay.gradle' as it does not exist.
```

**Comment by tobiasKaminsky** [comment]
New try. :-)

**Comment by tobiasKaminsky** [comment]
UIautomator makes trouble:
> uses-sdk:minSdkVersion 14 cannot be smaller than version 18 declared in library [com.android.support.test.uiautomator:uiautomator-v18:2.1.3] 
AndroidManifest.xml as the library might be using APIs not available in 14
       
> Suggestion: use a compatible library with a minSdk of at most 14,
                or increase this project's minSdk version to at least 18,
                or use tools:overrideLibrary="android.support.test.uiautomator.v18" to force usage (may lead to runtime failures)

**Comment by tobiasKaminsky** [comment]
Next one https://hub.docker.com/r/nextcloudci/android/builds/buvepgqyyvchjo5ide3libj/

I increased sdk to 18 as it is only for downloading the required files/libs.

**Comment by AndyScherzinger** [comment]
:+1: nice android-40 worked out :tada:

**Pull request merged**
