### PR TITLE
Delete all accounts on first run

### LINKED ISSUE #820: Crash on login
### Actual behaviour
Upon logging in after enabling TOTP, the app crashes. Switching off TOTP hasn't resolved the problem, and I've cleared data/cache for the app as well.

### Expected behaviour
I should be able to login and use my Nextcloud account as I had been.
 
### Steps to reproduce
1. Enable TOTP
2. Create Device Login
3. Press the login button to see crach dialog, or to see the app just close.

### Environment data
Android version: 7.1

Device model: xt1045

Stock or customized system: customized

Nextcloud app version: 1.4.2

Nextcloud server version:11.0.2

### Logs
relevant part of logcat:
ExistenceCheckRemoteOperation: Existence check for https://clove.ele.home/remote.php/webdav/ targeting for  existence finished with HTTP status 200
04-10 18:06:57.158 32000   514 D OwnCloudClient #1: REQUEST GET /ocs/v1.php/cloud/user
04-10 18:06:57.580 32000   514 D GetRemoteUserInfoOperation: Successful response: {"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"enabled":"true","id":"roger","quota":{"free":2791631941632,"used":8274591,"total":2791640216223,"relative":0,"quota":-3},"email":"dawson@engr.ccny.cuny.edu","phone":"","address":"","webpage":"","twitter":"","display-name":"Roger Dawson"}}}
04-10 18:06:57.605 32000 32000 D AuthenticatorActivity: Successful access - time to save the account
04-10 18:06:57.611  1210 31953 W AccountManagerService: insertAccountIntoDatabase: Account {name=roger@clove.ele.home, type=nextcloud}, skipping since the account already exists
04-10 18:06:57.720  1210  2445 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@e139a6a attribute=null, token = android.os.BinderProxy@c06d9bd
04-10 18:06:57.723  1210 21107 I ActivityManager: START u0 {flg=0x4000000 cmp=com.nextcloud.client/com.owncloud.android.ui.activity.FileDisplayActivity} from uid 10086 on display 0
04-10 18:06:57.741  1210 21107 I ActivityManager: moveTaskToBack: TaskRecord{926a790 #528 A=com.nextcloud.client U=0 StackId=1 sz=3}
04-10 18:06:57.747 32000 32000 D AuthenticatorActivity: onPause() ending

### potential clues:
c/o pygi on IRC: https://code.google.com/p/android/issues/detail?id=210992

### PR DESCRIPTION
**Pull request by mario**
This fixes #820

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
Glad you like it :)

**Comment by tobiasKaminsky** [comment]
👍

**Comment by atomspring** [comment]
This is still happening to me, where AccountManagerService is being skipped since the account already exists... but NextCloud isn't listed in Android's settings>>Accounts pane.

**Pull request merged**
