### PR TITLE
showing introduction screen is now customizable by setup.xml

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Enabled by default, of course ;-)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 looks good to me!

**Comment by AndyScherzinger** [comment]
👍 rebased, looks good to me! @mario your turn :) Can imho also be merged since 1.4.2 has been released :)

**Comment by AndyScherzinger** [comment]
@mario your turn :) Can imho also be merged since 1.4.2 has been released :)

**Comment by tobiasKaminsky** [comment]
@mario ping

**Comment by AndyScherzinger** [comment]
👍 rebased and restested successfully, due to vacation situation merging with single approval

**Comment by mario** [comment]
Tobias is on vacation, not me lol. But fine.

**Pull request merged**
