### PR TITLE
Add detekt

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This is based on #4042 to have some kotlin files

TODO
- [ ] add checks for test files
- [ ] upload failing somewhere

image

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
I would suggest that we try to stay directly at 0 issues, so we do not need this increasing/decreasing.

As this is rather new, we will need to adjust some rules, I suppose.
E.g. returnCount is set to 2: I do not mind if we have more…

**Comment by ezaquarii** [comment]
Let's merge it into master ASAP. I'll rebase and fix all my Kotlin work on top of that.

**Comment by AndyScherzinger** [comment]
@ezaquarii this PR is actually targeting your onboarding PR, so we can just merge this PR and you won't have to rebase.

**Comment by ezaquarii** [comment]
> @ezaquarii this PR is actually targeting your onboarding PR, so we can just merge this PR and you won't have to rebase.

I'll bring it in then.

**Comment by ezaquarii** [comment]
This work is already included in #4042

**Comment by ezaquarii** [comment]
@tobiasKaminsky Merged into #4042.

**Comment by tobiasKaminsky** [comment]
I'll have to find out why kotlin files within test/ are not analyzed, but this can also be another PR to your onboarding PR.

**Comment by tobiasKaminsky** [comment]
https://github.com/arturbosch/detekt/issues/1660

**Pull request merged**
