### PR TITLE
Use Material Design 3 for RemoveFilesDialog

### PR DESCRIPTION
**Pull request by alperozturk96**
Remove Folder Before:
remove_folder_before

Remove Folder After:
remove_folder_after

Remove File Before:
remove_file_before

Remove File After:
remove_file_after

- [ Done ] Tests written, or not not needed

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]
@alperozturk96 Looks good and works fine, just the updated screenshots aren't the ones from the removal dialog ;)

**Review by tobiasKaminsky — CHANGES_REQUESTED** [review]
Wrong screenshots :)

**Comment by alperozturk96** [comment]
Screenshots are updated

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
