### PR TITLE
Fix #10405 Context check for ImagePreviewFragment

### LINKED ISSUE #10405: Crash when Clicking through Images
### Cause of error
```java
Exception in thread "main" java.lang.IllegalStateException: Fragment PreviewImageFragment{330cb57} (a10c0a4f-14cf-483f-800e-2a899a2fb06b) not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
    at androidx.fragment.app.Fragment.getResources(Fragment.java:983)
    at com.owncloud.android.ui.preview.PreviewImageFragment.lambda$setErrorPreviewMessage$2$com-owncloud-android-ui-preview-PreviewImageFragment(PreviewImageFragment.java:723)
    at com.owncloud.android.ui.preview.PreviewImageFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
    at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:351)
    at android.view.View.performClick(View.java:7448)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
    at android.view.View.performClickInternal(View.java:7425)
    at android.view.View.access$3600(View.java:810)
    at android.view.View$PerformClick.run(View.java:28309)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7715)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30200390`
* Build flavor: `gplay`

### Device information
* Brand: `Fairphone`
* Device: `FP4`
* Model: `FP4`
* Id: `RKQ1.210503.001`
* Product: `FP4eea`

### Firmware
* SDK: `30`
* Release: `11`
* Incremental: `FP3W`

### PR DESCRIPTION
**Pull request by Tiam-Abderezai**
Show only error snackbar if context is available

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
@Tiam-Abderezai can you rebase this on master, please?

**Comment by Tiam-Abderezai** [comment]
@AlvaroBrey Please forgive me, I'm not certain if my attempt was successful. Can you please provide me with instructions to achieve this? I assure you it won't happen again.

**Comment by Tiam-Abderezai** [comment]
@AlvaroBrey Thank you. I followed your steps. Please review.

**Comment by Tiam-Abderezai** [comment]
@AlvaroBrey fixed the DCO issue.

**Comment by AlvaroBrey** [comment]
Thanks @Tiam-Abderezai !

**Pull request merged**
