### PR TITLE
Improvement loading error views

### PR DESCRIPTION
**Pull request by mario**
This fixed bug #455, and bears the stamp of approval of @jancborchardt xD

### CODE REVIEW

**Comment by mario** [comment]
This is gonna get another commit or two in like half an hour.

**Comment by AndyScherzinger** [comment]
;D

Can you briefly describe how we can achieve/provoke this error? :)

**Comment by mario** [comment]
Create mario.txt. Rename it to mario.jpg. Try to open :P

**Comment by mario** [comment]
One more commit pending - tomorrow, sorry!

**Comment by AndyScherzinger** [comment]
take your time @mario - no hurry, the ```master``` is frozen anyways!

**Comment by mario** [comment]
This is now ready for ready @AndyScherzinger @przybylski @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Have you changed the background of the images if they do not fill the complete display? 
In this PR it is white, whereas it is black on my beta.
Or do we have decided to use white and I forgot?

**Comment by mario** [comment]
@tobiasKaminsky it's black. You just need to merge all my PRs and then it's gonna be all good :)

**Comment by mario** [comment]
It's complicated because both touch same parts of the code. Please test only bits relevant to the PR :)

**Comment by AndyScherzinger** [comment]
@mario can you also rebase this one? It also has conflicts with the master

**Comment by mario** [comment]
This one is irrelevant, use integration branch which has this inside of it.

**Comment by tobiasKaminsky** [comment]
Clones added
============
- src/com/owncloud/android/ui/preview/PreviewMediaFragment.java  1
- src/com/owncloud/android/ui/preview/PreviewTextFragment.java  1
         

But maybe you can have a look here? (if it is your added code, otherwise it should be a new PR)

**Pull request closed without merging**
