### PR TITLE
Re-use second fragment if available

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #984 

Please test it very extensive as I am not 100% sure about any side-effects!

(also did some minor code formatting changes during debug. Always leave code in a better state ;-))

### CODE REVIEW

**Comment by mario** [comment]
@AndyScherzinger will test this :P

**Comment by tobiasKaminsky** [comment]
Better to have it tested by both of you and all the users that use dev version.

**Comment by AndyScherzinger** [comment]
👍 code looks good and fixes the rotation bug, downside I found out testing the PR is that for some reason we seem to have lost the "audio layout" somewhere before this PR since an audio file is now also using the standard video preview while before we had a nicer version for audio with a styled progressbar :(

**Comment by AndyScherzinger** [comment]
Screenshots

1.4.2 stable
device-2017-05-15-230043

1.5.0-master
device-2017-05-15-224721

**Comment by MorrisJobke** [comment]
@aleister09 Could you test and review this as well? I think you also noticed this recently.

**Comment by aleister09** [comment]
With rotation is working fine but if you turn off the screen and then turn on the music starts again

**Comment by tobiasKaminsky** [comment]
> With rotation is working fine but if you turn off the screen and then turn on the music starts again

I could reproduce this on master but not on this branch.
What I did:
- start song
- pause song
- switch off display
- turn display on
--> still song paused

**Comment by AndyScherzinger** [comment]
👍 Looks good!

**Comment by mario** [comment]
👍

**Pull request merged**
