### PR TITLE
Prevent copy/move into encrypted folder

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
As this is done via webdav calls (move/copy) this is a lot trickier than uploading.
Needs also handling directories, so postponing to M2 of E2E.

Steps to test:
Select a file and try to copy it to 
- encrypted folder -> Snackbar showing info
- unenecrypted folder -> working

Signed-off-by: tobiaskaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
> postponing to M2 of E2E.

so that seems to point to 3.1 while the issue has been assigned to 3.0?!

**Comment by tobiasKaminsky** [comment]
Well this PR remove ability of copying/moving files into an encrypted folder.
The real fix (if possible) is scheduled for 3.1.

**Comment by AndyScherzinger** [comment]
👍 looks good to me

**Comment by mario** [comment]
👍

**Pull request merged**
