### PR TITLE
Incorporated Checkstyle, findbugs, pmd and lint

### PR DESCRIPTION
**Pull request by djubreel**
Incorporated checkstyle, findbugs, pmd and lint for code quality. Most rules are not set yet as that would be needing a lot of changes in the code base so the rules can be added bit by bit and corresponding changes effected in codebase.  @AndyScherzinger

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Awesome work @djubreel :+1: 

@tobiasKaminsky please also have a look and if you are okay with it please merge. I did a dry run locally (gradlew.bat check) and I also set ```ignoreFailures = true``` in build.gradle so the build runs through and all checks get executed and reported (plus the build doesn't fail that way). Imho this is ready to merge. Then we should start new issues to resolve the reported issue (mainly findbugs and pmd so the build doesn't fail) and then activate this in our CI builds.

**Comment by tobiasKaminsky** [comment]
Code is :+1: 
Can we merge it? Or do we have to change "ignoreFailures" to true before merging?

**Comment by tobiasKaminsky** [comment]
One minor thing:
- This should be mentioned in some readme/documentation

**Comment by AndyScherzinger** [comment]
I would say let's wait with the "documentation" until the fails are fixes, then activate it in the builds and put it into the documentation.

We can merge right away since the checks will fail if you execute them, but they aren't activated in our builds just yet.

**Comment by AndyScherzinger** [comment]
@djubreel The PR has been merged! :tada: Thank you very much for this contribution!!! :rocket:

**Pull request merged**
