### PR TITLE
Further codacy fixes

### PR DESCRIPTION
**Pull request by AndyScherzinger**
work in progress

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky please review and potentially merge this one, I fixed a bunch of codacy warning categories (introduced one new issue which I probably will set to ignore is codacy itself...). I'd like to merge it since I cna then continue on master with a new report to do another round some time in the (near) future.

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
Merging since @tobiasKaminsky approved it before.

**Pull request merged**
