### PR TITLE
Files drop

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
according to #111 

TODO:

- [x] check for capabilities: https://github.com/nextcloud/server/pull/888 
- [x] show compatibility pop up #188

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
This is an incompatible feature, right?
So we need some kind of feature detection for this if we want the app to still work well with oC backends. (which of course we could decide not to, but for now I would try to stay compatible).

**Comment by tobiasKaminsky** [comment]
This is nextcloud app for nextcloud server so it is fine for me ;-)
What is your opinion? @jancborchardt @przybylski

**Comment by tobiasKaminsky** [comment]
IMPORTANT: Do we need a server version check for nextcloud? When was this feature introduced...? @schiessle

**Comment by mar1u5** [comment]
It was introduced with 9.0.50 ...

**Comment by tobiasKaminsky** [comment]
Ah, great :)
For me there is no need to have a version check against ownCloud.
If user should ever use the nextcloud app with an ownCloud server they should know that things can be broken.

**Comment by mar1u5** [comment]
I agree with you @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
Found one (minor) issue:

1. choose folder to share
2. activate "share link"
3. activate "allow editing"
4. activate "hide file listing"
5. deactivate "share link"

Issue: all "sub options" get hidden except for "hide file listing" which is still visible and set to active. This is just a UI thing though. In the background the folder got properly un-shared!

**Comment by Spacefish** [comment]
I would display a warning during the initial account adding inside the app,
which tells the user, that owncloud might be incompatible and that he may
want to upgrade his server to next cloud.. however we loose all the users
which may use the next cloud app but can't control the server installation
(coorporate or educational users mainly)

Am 02.08.2016 17:11 schrieb "Andy Scherzinger" <notifications@github.com>:

**Comment by AndyScherzinger** [comment]
Issue https://github.com/nextcloud/android/pull/141#issuecomment-236935431 has been fixed

**Comment by AndyScherzinger** [comment]
found it and fixed it in https://github.com/nextcloud/android/pull/141/commits/0faa786b2eae1df7307b79e9f34be5decc45a180

**Comment by AndyScherzinger** [comment]
So tested and code reviewed: :+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky do you think we can get a compatibility pop up done before the release so we can also ship this one? as in implement #188

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger ready for test. 
You will need https://github.com/nextcloud/android-library/pull/16

**Comment by AndyScherzinger** [comment]
android lib has been merged, published via jitpack and referenced in this PR, see my latest commit.

Can test it right now since Android Studio went nuts and corrupts the installation on the phone atm... :(

**Comment by AndyScherzinger** [comment]
Got it installed but never reached the check you implemented (not sure what is happening on my phone...). So my tests are negative at the moment :(

Will give it another try tomorrow.

**Comment by AndyScherzinger** [comment]
Code review and tests successful, waiting for the build to complete.

**Pull request merged**
