### PR TITLE
Iteration 4 for file detail & new sharing

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Iteration 1 can be found here: #2533 :ballot_box_with_check:
Iteration 2 can be found here: #2573 :ballot_box_with_check:
Iteration 3 can be found here: #2671

WiP for #2485 and collab with @tobiasKaminsky for adding commenting.

This PR/branch stack on top of ```fileDetails-3``` until that one has been merged.

**TODOs**:
* [x] add comment box UI
* [ ] send new comments to server (right away)
* [ ] update activities list after comment has been send to server (async)
* [ ] update activities list after comment could not be saved on server (error handling)

My idea behind the described to dos is to update the UI right away while reverting that in case the server couldn't store the comment. For starters I guess it'd be fine if it works synchronously to have it working and then improve upon that.

@tobiasKaminsky would you fancy taking on the part of client/server communication? :heart:

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
I already have a branch for comments, which is in top of file versions.
To not have too much confusion, can you simply remove the comment part from here?

**Comment by AndyScherzinger** [comment]
> I already have a branch for comments, which is in top of file versions.
neither of these branches seems "visible" to me

> To not have too much confusion, can you simply remove the comment part from here?
That is the only part of this PR, so you can just kill mine

On a general note
Why aren't the branches on GH plus opened PRs tagged as "1. developing"?

**Comment by tobiasKaminsky** [comment]
They will come one by one, but I have to polish them a bit, before putting them public ;-)

**Comment by AndyScherzinger** [comment]
terminated by any to come PR by @tobiasKaminsky

**Pull request closed without merging**
