### PR TITLE
Small modifications

### PR DESCRIPTION
**Pull request by JohnAzedo**
Just comments in layout

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Hey,
first thank you that you took the time to contribute to this project.

Indeed AndroidStudio claims that "Theme" cannot be resolved, but however if you click on "Theme.Appcompat" it is working.

Instead of "just" commenting it, do you have an idea how we can fix this?

**Comment by artem-p** [comment]
I don't see any error here. Maybe it depends on Android Studio version?

**Comment by artem-p** [comment]
screenshot from 2018-05-17 15-32-07

AS 3.1.1

There is [stackoverlow question](https://stackoverflow.com/questions/40822173/cannot-resolve-symbol-theme-in-styles-xml-android-studio) with different ways how to solve it.

**Comment by JohnAzedo** [comment]
Hey, my bad, i am so sorry. The error is in my Android Studio version.

2018-05-17 1:49 GMT-03:00 Tobias Kaminsky <notifications@github.com>:

**Comment by tobiasKaminsky** [comment]
As this seems more to be an error in AS, and not in our code, I suggest that we do not put too much energy in fixing this.
@JohnAzedo are you fine with closing this? There are some other [starter issues](https://github.com/nextcloud/android/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22), if you want to help us :tada:

**Comment by AndyScherzinger** [comment]
@JohnAzedo @tobiasKaminsky closing the issue for now. Like Tobias mentioned feel free to checkout other [starter issues](https://github.com/nextcloud/android/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22), if you want to help with development and if you have any questions regarding Nextcloud Android dev, feel free to ask, we are here to help :+1:

**Pull request closed without merging**
