### PR TITLE
Update libs to latest versions to satisfy lint

### PR DESCRIPTION
**Pull request by AndyScherzinger**
@mario @tobiasKaminsky Google released new versions of their libs we use for push notifications and that are referenced for testing so lint added some warnings.

This PR updates to the new lib versions and resolves the lint matter.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
I would rather postpone this as it is currently working and it can only getting worser ;-)

**Comment by AndyScherzinger** [comment]
fine by me. Postpone to 2.0.1? (moved it already, feel free to re-assign to another release).

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky @mario for review :)

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
rebased! pinging @mario for second approval

**Comment by mario** [comment]
👍

**Pull request merged**
