### PR TITLE
Convert Authenticator to Kotlin

### PR DESCRIPTION
**Pull request by alperozturk96**
- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
> AuthenticatorUrlUtilsTest.java:41: error: non-static method normalizeScheme(String) cannot be referenced from a static context
            String normalized = AuthenticatorUrlUtils.normalizeScheme(url);

**Review by tobiasKaminsky — DISMISSED** [review]
Tests are failing

**Comment by alperozturk96** [comment]
@tobiasKaminsky Tests are failing due to (AbstractOnServerIT.java:139)

**Review by JonasMayerDev — APPROVED** [review]
Login in and app seem to work like on master

**Review by JonasMayerDev — APPROVED** [review]
Approve again since nothing has changed

**Pull request merged**
