### PR TITLE
Add support for web login

### PR DESCRIPTION
**Pull request by mario**
Just needs updating for new structure. Thanks @AndyScherzinger

### CODE REVIEW

**Comment by mario** [comment]
@AndyScherzinger can you update this and merge please?

**Comment by AndyScherzinger** [comment]
@mario sure, how would I have to resolve the conflict?

> **Conflicting files**
src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java

**Comment by AndyScherzinger** [comment]
👍 code is fine by me, default internal app login successfully tested -> merging

**Comment by aleister09** [comment]
@mario I found an issue 

When you're adding another account with Web-Login and introduce the same account the AuthenticatorActivity is not closing

**Comment by mario** [comment]
@aleister09 I'm not sure I understand the second part of the sentence?

The first is known and is because only single-account is enabled (as desired).

**Comment by mario** [comment]
(You should not be able to add another account anyway?)

**Comment by aleister09** [comment]
I'm able to add another account but if I add the same account the AuthenticatorActivity is not closing 

I saw the code and it is because the account is already registered but the app doesn't show a message to notify that the account is already registered,

**Comment by mario** [comment]
Interesting. Will evaluate. I assume you come to the web view screen via the change password for the current account option?

**Comment by aleister09** [comment]
No, I enable the Web-Login option so in my first login and when I add another account I go to web view screen

**Comment by MorrisJobke** [comment]
As I understood it should be for now only one login.

**Pull request merged**
