### PR TITLE
Update welcome url, fixes #16

### LINKED ISSUE #16: small setup screen improvement
I just installed the Nextcloud app, great work from everybody!

When I start the app for the first time it ask for the usual stuff like URL, username and password. Below the input fields there is a "Do you know Nextcloud?" link (don't know the exact wording because I installed it on a German environment). This points to Nextcloud.com/news. Wouldn't it be better to link to Nextcloud.com/about? Might be more useful to learn more about Nextcloud than the blogs.

### PR DESCRIPTION
**Pull request by AndyScherzinger**
see #16 simply using the top level url for nextcloud

### CODE REVIEW

**Comment by przybylski** [comment]
👍

**Comment by tobiasKaminsky** [comment]
What is the best behaviour for the changelog?
Do we want to change it all in one on release day or do we want to add the change on every merge?

**Comment by tobiasKaminsky** [comment]
Beside that: LGTM

**Comment by AndyScherzinger** [comment]
I would say do it for the release.

**Comment by tobiasKaminsky** [comment]
:+1: ok, then go :)

**Comment by mar1u5** [comment]
👍

**Comment by AndyScherzinger** [comment]
LGTM seems broken atm?!

**Pull request merged**
