### PR TITLE
Use account.hashCode instead of name as account switching value

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
To test you need an account where display name is not the same like user Id, e.g:
tobi in settings->users
"Tobias K" in display name -> setting of my user

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Score issues :/

**Comment by AndyScherzinger** [comment]
Backport?

**Comment by sten-schmidt** [comment]
In 9236.apk you can only add one account , nothing happens when AddAccount-Command is selectet in the Menü for adding the second account.

**Comment by tobiasKaminsky** [comment]
@sten-schmidt thank you for testing :tada: 

I indeed forgot to change add/manage behaviour.

Once there is a new version, can you please give it a try again?

**Comment by sten-schmidt** [comment]
@tobiasKaminsky with 9288.apk the AccountSwitch works well. :)

**Pull request merged**
