### PR TITLE
Bump google libs

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
I tested push notifications with gplay flavor, both on an existing account and a new installation (to get new keys).
Both is working for me.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the CI keeps crashing on the gplay build flavor!

**Comment by tobiasKaminsky** [comment]
https://android-developers.googleblog.com/2018/05/announcing-new-sdk-versioning.html

they changed something meanwhile, so I adjusted it to their recommendations…
Let's see.

**Comment by mario** [comment]
Rebase.

**Comment by tobiasKaminsky** [comment]
Rebase is done :+1:

**Comment by AndyScherzinger** [comment]
Drone still turns red :(

**Comment by tobiasKaminsky** [comment]
Waiting for response to https://github.com/nextcloud/android/pull/2618#issuecomment-395102494

**Comment by tobiasKaminsky** [comment]
Successor is #2825

**Pull request closed without merging**
