### PR TITLE
Bugfix Disable focus change via tap

### PR DESCRIPTION
**Pull request by alperozturk96**
Users are capable of inadvertently changing focus through tapping, which can result in accidental input and lead to confusion for App passcode enter.

- [ Done ] Tests written, or not not needed

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
Great so far.
One small thing: When I enter last digit, higlighted bar is then again at first one.
After a very short timespan then the app is unlocked.
I think it should remain on 4th position.

**Review by tobiasKaminsky — CHANGES_REQUESTED** [review]
Do not jump to 1st position after entering 4th digit

**Comment by tobiasKaminsky** [comment]
Hm. I just tested it with master and this is the already existing behaviour.
Can you nevertheless check if this is quickly possible?
If not, we can keep it this way and directly merge your PR.

**Comment by alperozturk96** [comment]
@tobiasKaminsky Done

**Review by ZetaTom — COMMENTED** [review]
In my tests, actual input worked well with the virtual keypad and an external keyboard. However, the backspace key on the virtual keypad didn't work. Pressing the backspace key on the external keyboard resulted in one, or sometimes several, inputs being deleted.

**Comment by tobiasKaminsky** [comment]
I think external keyboard cannot be used for testing with an emulator.

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
