### PR TITLE
Dim disabled Save button in custom folder sync prefs dialog

### LINKED ISSUE #3664: Active "Save" button in set up a custom folder
### Actual behaviour
- `Save` button is active at all times in `Set up a custom folder`.
obraz

### Expected behaviour
- `Save` button **only** active after selecting the folder `Set up a custom folder` and `Remote folder` in the `Set up a custom folder`.
obraz
obraz
obraz
 
### Steps to reproduce
1. Select from the menu `Auto upload`.
2. Select: `:` -> `Set up a custom folder`.
3. Select only: `Set up a custom folder`.
4. Enter: `Save`.

**No reaction by the application. This is confusing for the user.**

### Environment data
Android version: 6

Nextcloud app version: 3.5.0 and bf99c2d

### PR DESCRIPTION
**Pull request by ezaquarii**
fixes #3664

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### CODE REVIEW

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger This 3-liner fix was so trivial that I skilled design phase. Pls check if this is how we'd like to handle disabled button.

**Comment by tobiasKaminsky** [comment]
Nice work.
https://material.io/design/components/buttons.html#text-button --> states shows
image

So I would also go for this and set text to grey when disabled.

**Comment by AndyScherzinger** [comment]
I agree wiht you both, and like @tobiasKaminsky mentioned it should be greyed out too.

Other than that nice work as always @ezaquarii 🎉

**Comment by ezaquarii** [comment]
This fix is invalid.

**Pull request closed without merging**
