### PR TITLE
Use grid_item view for gridview in upload filepicker

### PR DESCRIPTION
**Pull request by NilsGriebner**
This is the next attempt to solve  #2526. Solution is based on @AndyScherzinger 's advice in  #2983. Let me know what you think :)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
cc @tobiasKaminsky @ardevd @mario since I likely won't find the time to review/test today, not sure about tomorrow

**Comment by tobiasKaminsky** [comment]
The footer item seems to be also a GridView, but should be a LocalFileListFooterViewHolder.

@AndyScherzinger do we want to remember the state of this? I am not sure about it. I would also be fine that list view is always default and one has to manually enable grid view.

**Comment by AndyScherzinger** [comment]
> do we want to remember the state of this? I am not sure about it. I would also be fine that list view is always default and one has to manually enable grid view.

I'd be fine with not remembering the state grid/list for now and see what we get in regards to user feedback and in case people want it to be remembered add that part in a later PR.

**Comment by NilsGriebner** [comment]
@AndyScherzinger I can work on footer items. IMHO a separate PR is cleaner for this.

**Comment by tobiasKaminsky** [comment]
@NilsGriebner a separate PR is always a good idea. 
Then we can merge this one.

Thank you very much for your contribution! :tada:

**Comment by AndyScherzinger** [comment]
Thanks for the contribution @NilsGriebner :heart:

**Pull request merged**
