### PR TITLE
Fixes auto upload

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by AndyScherzinger** [comment]
@mario you assigned this to 3.0.0, so does that mean we also need a backport?

cc @tobiasKaminsky

**Comment by mario** [comment]
Yes please do it

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you take care of backporting since I likely won't be able to today, in case you approve this PR?

**Comment by tobiasKaminsky** [comment]
I do not see why this would make a difference. As of my understanding there is nothing in the function that would be affected by static.
@mario, is the PR complete? ;-)
If yes, I will approve, merge and backport it tomorrow and right after that to 3.0 release.

**Comment by mario** [comment]
I dont see why either... but this fixes it

**Comment by AndyScherzinger** [comment]
> If yes, I will approve, merge and backport it tomorrow and right after that to 3.0 release.

👍  but don't forget to fetch the last transifex commits :)

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
