### PR TITLE
Revert "Added confirmation before exit (Fixed #2276)"

### LINKED ISSUE #2276: Add confirmation before exit
### Actual behaviour

Currently the app closes if the user hits the back button. 

### Expected behaviour

The user should be prompted for exit if s/he hits the back button because the user might happen to hit the back button by chance which leads to an unintended exit form the app. 
 A toast could be displayed, say "Press again to exit', so as to avoid unintended exit from the app.

### Steps to reproduce
1. Open the app or log into you account
2. Press the back button
3. The app closes in a single hit of back button

### Environment data
Android version: 7.0

Device model: Xiaomi Redmi Note 4

### PR DESCRIPTION
**Pull request by arundhati24**
Reverts nextcloud/android#2283

As per the discussion on issue #2276 pull request #2283  needs to be reverted.

### CODE REVIEW

**Comment by arundhati24** [comment]
@mario @jancborchardt @AndyScherzinger Would you please review this :)

**Comment by jancborchardt** [comment]
Thank you @arundhati24 and sorry again for the miscommunication. :) In the future, for any issues or pull requests which are related to design, feel free to mention the @nextcloud/designers team for review. :)

**Comment by arundhati24** [comment]
@jancborchardt It's okay :)
Would do that for sure from next time. :)

**Comment by AndyScherzinger** [comment]
:+1: code change is fine by me

**Comment by tobiasKaminsky** [comment]
:+1: 
And also sorry from my side @arundhati24 
I hope you will still contribute :-)

**Comment by arundhati24** [comment]
@tobiasKaminsky Yes, I will definitely contribute. ;)

**Pull request merged**
