### PR TITLE
Add GCM to gplay/modified

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #1353 

Needs approval by @mario!

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Will this then be re-added for the gplay build and is is necessary for the gplay build?

**Comment by AndyScherzinger** [comment]
👍 code looks fine, open issue is the question above and the feedback of @mario

**Comment by mario** [comment]
I would strongly recommend to not merge this branch. What needs to be done instead is find a separate dependency (previously, we used to include whole play services) that ships GCM network manager and put it in gradle for Modified and Gplay flavours. The reason is that we indeed want to rely on GCM when it's available, and since we use other play services functionality it's absolutely fine to use this one as well.

For F-droid build you don't need to ship this at all because we never shipped play services there.

**Comment by tobiasKaminsky** [comment]
@mario I added gcm as an explicit dependency for gplay/modified.
After compiling I could access class "GcmTaskService", which was previously missing.
On "fdroid" build this class is not available, as expected.

**Comment by mario** [comment]
Good. Feel free to merge.

**Comment by tobiasKaminsky** [comment]
Merging regardless as we now get a new error which will be fixed via transifex.

**Pull request merged**
