### PR TITLE
Delete Branch stable-3.1.x

### PR DESCRIPTION
**Pull request by AndyScherzinger**
@tobiasKaminsky since we released 3.2.0 I think we can delete this branch, right (housekeeping FTW) :smiley:

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Let us add this as a point to the release roadmap and then we can also directly delete the branch at https://github.com/nextcloud/android/branches/all?utf8=%E2%9C%93&query=stable

**Comment by AndyScherzinger** [comment]
I updated the release template issue :+1:

**Comment by tobiasKaminsky** [comment]
I already did this in https://github.com/nextcloud/android/issues/150, which is the place/time to do it, I think.
At minor releases (https://github.com/nextcloud/android/issues/2287) it is not needed (we do not have a bugfix branch).

**Comment by AndyScherzinger** [comment]
Right :+1:

**Pull request closed without merging**
