### PR TITLE
Bump QRCodeScanner

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@jkrude maybe you want to test this? :-)

**Comment by jkrude** [comment]
Sure I can give it a try. What exactly do you have in mind? Testing this change in particular (vibration permission) or the qr-code scanning functionality in general ([onScan()](https://github.com/nextcloud/android/blob/f6d14856a45e2d46d0e7d8fae6003a80fe533b5a/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java#L1314))?

**Comment by tobiasKaminsky** [comment]
Both, vibrate and external storage permission.

**Comment by tobiasKaminsky** [comment]
@jkrude there is now an APK you can install in parallel.

**Comment by tobiasKaminsky** [comment]
Superseed by https://github.com/nextcloud/android/pull/8442

**Pull request closed without merging**
