### PR TITLE
Upload when charging

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Toggle if instant upload only starts when device charging.

Depends on: https://github.com/nextcloud/android-library/pull/7

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@schnello I saw your feature request on owncloud.
As I had developed it already there back in 11/2014 I have ported it to nextcloud.
It will be soon in our beta version, if you might give it a try?

**Comment by AndyScherzinger** [comment]
Code looks good: :+1: 

I can't test it anymore since instant upload is broken for Android N in general :(

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you rebase (or merge) this one to latest master?

**Comment by AndyScherzinger** [comment]
Tested on an Android M emulator: works :+1:

**Comment by andykvakk** [comment]
Is this change the reason why videos is not uploaded at all before charging? 

I have unchecked "Upload when charging only" in Nextcloud Beta client on my Galaxy S7 . I tried to tap the videofiles in upload queue,  but needed to connect charger and then tap the files in upload queue to trigger the upload.
screenshot_20160923-123712
screenshot_20160923-123704


My phone has 73% power so powersaving is not the issue.

**Comment by tobiasKaminsky** [comment]
@andykvakk there was a bug in it, which I fixed.
Do you still have this problem?

**Comment by andykvakk** [comment]
Yes, it seems to be working now.

**Pull request merged**
