### PR TITLE
background image for background in top of sidebar

### PR DESCRIPTION
**Pull request by AndyScherzinger**
added the background image to the drawer header as requested in #210 

device-2016-08-14-223504

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
please review @tobiasKaminsky @nextcloud/designers

**Comment by mar1u5** [comment]
How complicated would it be to fetch the picture from the theming app 😁

**Comment by AndyScherzinger** [comment]
@mar1u5 if the server side offers an interface for it, it is technically possible. As discussed in #54 we can't support launcher icons and coloring would be a problem here and there but for the background image here, it would be possible, yes.  I which version of Nc server would this feature/api be available?

**Comment by Bugsbane** [comment]
This is a good step forward, but as @mar1u5 suggested, it really should use the theming app image to be consistent.

**Comment by mar1u5** [comment]
I think @juliushaertl is the right person to give Information about the APIs :grin:

**Comment by juliushaertl** [comment]
@mar1u5 @AndyScherzinger By now there is no public api for getting theming values, but that shouldn't be much work. I guess such an API would absolutely make sense, as other external apps might use theming values as well.

**Comment by tobiasKaminsky** [comment]
This PR is :+1: 
For setting the background image via public theming API please open a  new issue and link it to the corresponding server issue.

**Comment by MorrisJobke** [comment]
You rock! This is amazing :) I like it 👍

**Comment by jancborchardt** [comment]
Looks slick as hell! :tada:  Now we only need to add it to the connection screen as well @AndyScherzinger ;) Wanna play around with that as well?

**Comment by AndyScherzinger** [comment]
@jancborchardt Connection screen as in the login screen? Do we really want to do this? I do like the simplicity of the uni-colored background and not having the image. How would we design it? simply putting in the image isn't enough since all the input fields are "just lines" (as in lovely native!)

**Comment by AndyScherzinger** [comment]
@jancborchardt please see the screenshots, as before strongly advising against it...

- Yes - this can be done
- Yes - it is ugly as hell
- No - we shouldn't do this
- No - this is not a webapp on a 24" screen

device-2016-08-17-164111

device-2016-08-17-164132

@nextcloud/android please say NO - you can do it

**Comment by enoch85** [comment]
I'll say YES actually. Anyone else?

Maybe just make the background a bit darker??

**Comment by AndyScherzinger** [comment]
@enoch85 Did you open the image on an actual phone or just on a PC?

**Comment by enoch85** [comment]
@AndyScherzinger Just looked at the pics here in this PR.

**Comment by AndyScherzinger** [comment]
Please look at it on an Android phone. Imho this really far away from a material design experience.

**Comment by Bugsbane** [comment]
To me it seems that if the admin has chosen to theme their install by replacing the Nextcloud mountains image, that we shouldn't still be pushing that image on them anywhere.

If we're concerned about readability issues though, like what happens if they choose an image that's almost all white, then possibly we could opt to go with the chosen theme colour instead of the theme image? We've already talked elsewhere about limiting the theme colour to only the darker colours so we don't make the web header unreadable (although personally I'd prefer that we just automatically flip text colour from white to black if the chosen background is too light).

**Comment by jancborchardt** [comment]
@AndyScherzinger yeah, good point. It just looks very off in this case, and distracts from simply logging in. Let’s not do it. :)

**Comment by AndyScherzinger** [comment]
> If we're concerned about readability issues though, like what happens if they choose an image that's almost all white, then possibly we could opt to go with the chosen theme background colour instead of the theme image?

That is the point (or one point)... we can't because that would mean (while technically possible) we would have to do a color analysis of the background image being used and we will run into large problems with no solution yet which is the next demand that will come up which is the logo... And the transparency issue is yet unresolved, like with PNG avatars, we simply calculate a background color (white), so no transparency here!

> @AndyScherzinger yeah, good point. It just looks very off in this case, and distracts from simply logging in. Let’s not do it. :)

:heart: :heart: :heart: :heart: :heart: :heart:

**Comment by tobiasKaminsky** [comment]
We should discuss this in a new issue ;)

**Comment by Bugsbane** [comment]
> we can't because that would mean (while technically possible) we would have to do a color analysis of the background image being used

I wasn't suggesting Nextcloud automatically uses background colour where the image is nearly all white. I was suggesting using the users chosen background colour, period, and thus avoiding problems *such as* when their image is almost all white.

Using their chosen background *colour* instead of image, ensures that we're using their theme, not ours, while still keeping things readable (if we only allow darker colours to be chosen, anyway)

**Comment by AndyScherzinger** [comment]
As mentioned by tobias, let's discuss this in a new issue while being aware that the theming capabilities are targeting the web interface _not_ native mobile interfaces (!). that being that the theming on Nc server doesn't have a input field for a system bar coloring present on Lollipop and later, plus you cannot change the color of the folder icons nor the check boxes nor the radio buttons at the moment, at least not consistently. This will be possible at some point (as soon as Google get vector support right and backwards compatible).

So...
1. let's discuss this in a new issue
2. let's postpone theming until this can be done easily and decide if we want to do such things (also keeping in mind day/night mode introduces in the Android 6 or 7...)

**Pull request merged**
