### PR TITLE
Feature/add exclude hidden file or folder option when create custom media folder type

### PR DESCRIPTION
**Pull request by BBBOND**
- [X] Tests written, or not not needed

Adding a synchronization directory of custom file types will synchronize all files to the cloud. However, many useless hidden files are often written into the directory by third-party software, causing conflicts in synchronization. Therefore, an option to exclude hidden files has been added. to solve this problem.

image

### CODE REVIEW

**Comment by joshtrichards** [comment]
Related: #3418 & #3500

**Review by jancborchardt — DISMISSED** [review]
Except a minor wording nitpick a general question I can’t tell from the code:
Is this on by default?

And @tobiasKaminsky @AndyScherzinger would this be something we want to have on by default? (I assume no and everything should be synced, but you are more knowledgeable about specifics.)

**Comment by AndyScherzinger** [comment]
I would say `off`by default too, yes

**Comment by AndyScherzinger** [comment]
@BBBOND you might want to use git fetch and rebase to pull in latest changes from our master branch so the changeset in this PR only shows the things you actually changed and not merged commits from master branch.

**Comment by BBBOND** [comment]
Hello @AndyScherzinger, How long will it take to review this code? The rebase code will always produce some conflicts. For example, we have all changed the database structure, lead to the generated json files in the `com.nextcloud.client.database.NextcloudDatabase` directory has changed.

**Comment by BBBOND** [comment]
@AndyScherzinger I have rebased it.

**Comment by AndyScherzinger** [comment]
Should have happened for a while. Sorry about this 😔

@JonasMayerDev @tobiasKaminsky @alperozturk96 @ZetaTom please review and merge!

**Comment by alperozturk96** [comment]
@BBBOND Hey. Could you [sign off](https://github.com/nextcloud/android/pull/12323/checks?check_run_id=21216881517) your commits?

**Review by alperozturk96 — CHANGES_REQUESTED** [review]
Crashed on Android 14 emulator.

 **Logcat file**

[Android-14-Android-14_2024-02-05_095459.logcat.zip](https://github.com/nextcloud/android/files/14162708/Android-14-Android-14_2024-02-05_095459.logcat.zip)

<details open>
  <summary>Log</summary>
  2024-02-05 09:50:46.589 11679-11679 SQLiteLog               com.nextcloud.client                 E  (1) duplicate column name: end_to_end_encryption_api_version in "ALTER TABLE `capabilities` ADD COLUMN `end_to_end_encryption_api_version` TEXT DEFAULT NULL"
2024-02-05 09:50:46.590 11679-11679 AndroidRuntime          com.nextcloud.client                 D  Shutting down VM
2024-02-05 09:50:46.591 11679-11679 AndroidRuntime          com.nextcloud.client                 E  FATAL EXCEPTION: main
                                                                                                    Process: com.nextcloud.client, PID: 11679
                                                                                                    java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteException: duplicate column name: end_to_end_encryption_api_version (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE `capabilities` ADD COLUMN `end_to_end_encryption_api_version` TEXT DEFAULT NULL
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7003)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: android.database.sqlite.SQLiteException: duplicate column name: end_to_end_encryption_api_version (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE `capabilities` ADD COLUMN `end_to_end_encryption_api_version` TEXT DEFAULT NULL
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1069)
                                                                                                    	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673)
                                                                                                    	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
                                                                                                    	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
                                                                                                    	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2088)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2010)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.kt:246)
                                                                                                    	at com.nextcloud.client.database.NextcloudDatabase_AutoMigration_77_78_Impl.migrate(NextcloudDatabase_AutoMigration_77_78_Impl.java:19)
                                                                                                    	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.kt:90)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.kt:253)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
                                                                                                    	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:234)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
                                                                                                    	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getReadableDatabase(FrameworkSQLiteOpenHelper.kt:107)
                                                                                                    	at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:468)
                                                                                                    	at android.content.ContentProvider.query(ContentProvider.java:1596)
                                                                                                    	at android.content.ContentProvider.query(ContentProvider.java:1692)
                                                                                                    	at android.content.ContentProvider$Transport.query(ContentProvider.java:292)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1229)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1161)
                                                                                                    	at android.content.ContentResolver.query(ContentResolver.java:1117)
                                                                                                    	at com.owncloud.android.datamodel.FileDataStorageManager.getCapabilityCursorForAccount(FileDataStorageManager.java:2031)
                                                                                                    	at com.owncloud.android.datamodel.FileDataStorageManager.getCapability(FileDataStorageManager.java:2058)
                                                                                                    	at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:84)
                                                                                                    	at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForUser(MaterialSchemesProviderImpl.kt:50)
2024-02-05 09:50:46.593 11679-11679 AndroidRuntime          com.nextcloud.client                 E  	at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForCurrentUser(MaterialSchemesProviderImpl.kt:68)
                                                                                                    	at com.nextcloud.client.di.ThemeModule$Companion.provideMaterialSchemes(ThemeModule.kt:55)
                                                                                                    	at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.provideMaterialSchemes(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:46)
                                                                                                    	at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:36)
                                                                                                    	at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:13)
                                                                                                    	at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:38)
                                                                                                    	at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:12)
                                                                                                    	at com.owncloud.android.MainApp.onCreate(MainApp.java:294)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998)
                                                                                                    	... 9 more
</details>

**Comment by BBBOND** [comment]
> Crashed on Android 14 emulator.
> 
> **Logcat file**
> 
> [Android-14-Android-14_2024-02-05_095459.logcat.zip](https://github.com/nextcloud/android/files/14162708/Android-14-Android-14_2024-02-05_095459.logcat.zip)
> 
> Log
> 2024-02-05 09:50:46.589 11679-11679 SQLiteLog com.nextcloud.client E (1) duplicate column name: end_to_end_encryption_api_version in "ALTER TABLE `capabilities` ADD COLUMN `end_to_end_encryption_api_version` TEXT DEFAULT NULL" 2024-02-05 09:50:46.590 11679-11679 AndroidRuntime com.nextcloud.client D Shutting down VM 2024-02-05 09:50:46.591 11679-11679 AndroidRuntime com.nextcloud.client E FATAL EXCEPTION: main Process: com.nextcloud.client, PID: 11679 java.lang.RuntimeException: Unable to create application com.owncloud.android.MainApp: android.database.sqlite.SQLiteException: duplicate column name: end_to_end_encryption_api_version (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE `capabilities` ADD COLUMN `end_to_end_encryption_api_version` TEXT DEFAULT NULL at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7003) at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:205) at android.os.Looper.loop(Looper.java:294) at android.app.ActivityThread.main(ActivityThread.java:8177) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) Caused by: android.database.sqlite.SQLiteException: duplicate column name: end_to_end_encryption_api_version (code 1 SQLITE_ERROR): , while compiling: ALTER TABLE `capabilities` ADD COLUMN `end_to_end_encryption_api_version` TEXT DEFAULT NULL at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method) at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1069) at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673) at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590) at android.database.sqlite.SQLiteProgram.(SQLiteProgram.java:62) at android.database.sqlite.SQLiteStatement.(SQLiteStatement.java:34) at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2088) at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2010) at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.kt:246) at com.nextcloud.client.database.NextcloudDatabase_AutoMigration_77_78_Impl.migrate(NextcloudDatabase_AutoMigration_77_78_Impl.java:19) at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.kt:90) at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.kt:253) at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416) at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:340) at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:234) at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:190) at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151) at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getReadableDatabase(FrameworkSQLiteOpenHelper.kt:107) at com.owncloud.android.providers.FileContentProvider.query(FileContentProvider.java:468) at android.content.ContentProvider.query(ContentProvider.java:1596) at android.content.ContentProvider.query(ContentProvider.java:1692) at android.content.ContentProvider$Transport.query(ContentProvider.java:292) at android.content.ContentResolver.query(ContentResolver.java:1229) at android.content.ContentResolver.query(ContentResolver.java:1161) at android.content.ContentResolver.query(ContentResolver.java:1117) at com.owncloud.android.datamodel.FileDataStorageManager.getCapabilityCursorForAccount(FileDataStorageManager.java:2031) at com.owncloud.android.datamodel.FileDataStorageManager.getCapability(FileDataStorageManager.java:2058) at com.owncloud.android.utils.theme.CapabilityUtils.getCapability(CapabilityUtils.java:84) at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForUser(MaterialSchemesProviderImpl.kt:50) 2024-02-05 09:50:46.593 11679-11679 AndroidRuntime com.nextcloud.client E at com.owncloud.android.utils.theme.MaterialSchemesProviderImpl.getMaterialSchemesForCurrentUser(MaterialSchemesProviderImpl.kt:68) at com.nextcloud.client.di.ThemeModule$Companion.provideMaterialSchemes(ThemeModule.kt:55) at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.provideMaterialSchemes(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:46) at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:36) at com.nextcloud.client.di.ThemeModule_Companion_ProvideMaterialSchemesFactory.get(ThemeModule_Companion_ProvideMaterialSchemesFactory.java:13) at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:38) at com.owncloud.android.utils.theme.ViewThemeUtils_Factory.get(ViewThemeUtils_Factory.java:12) at com.owncloud.android.MainApp.onCreate(MainApp.java:294) at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6998) ... 9 more

@alperozturk96  I find the reason, because of we have all changed the database structure. It only crashed when update app. And now I fixed it. See [[feature] keep file same with master branch](https://github.com/nextcloud/android/pull/12323/commits/99df1e3374e4a68671964fc30512d007cdc57a6a).

**Review by alperozturk96 — APPROVED** [review]
I tested it, it works. @tobiasKaminsky @ZetaTom @JonasMayerDev Can we get another approval and merge it asap? So we can avoid from merge conflicts.

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
❗ REBASED ❗

**Review by ZetaTom — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Thanks for the contribution @BBBOND 🎉 

Happy to have it in 💯 

Just sent you an invite for the Github organization so you can work on branches within the repository and won't have to work on a fork. This should make your life easier in the future for contributions.

**Comment by ofrias** [comment]
Could you please add this "Exclude hidden" setting to autodetected folders too?  IMO they should behave in the same way and have the same settings as custom folders.

**Comment by joshtrichards** [comment]
@ofrias Would you please handle your request via Issues as an enhancement idea? I'm afraid your suggestion will get lost here as this PR itself is already merged so there's no development going on here.

**Comment by ofrias** [comment]
Thanks a lot for the suggestion.  I have created the Feature Request:  https://github.com/nextcloud/android/issues/13648

**Pull request merged**
