### PR TITLE
Fixed folder content visibility

### PR DESCRIPTION
**Pull request by abdusalamApps**
Signed-off-by: abdusalamApps <abdusalam.yabrak@tutanota.com>

- [x] Tests written, or not needed

### CODE REVIEW

**Comment by abdusalamApps** [comment]
Origin Issue https://github.com/nextcloud/android/pull/10989

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Thanks @abdusalamApps ! I just merged master into this branch. I'll merge this after CI finishes.

**Comment by abdusalamApps** [comment]
Great! It feels really good to make my first Open Source contribution 😁

**Comment by AlvaroBrey** [comment]
> Great! It feels really good to make my first Open Source contribution grin regardless of how tiny the PR is

Congrats on your first contribution!

**Comment by abdusalamApps** [comment]
> Congrats on your first contribution!
Thanks!

**Pull request merged**
