### PR TITLE
disable handling broadcast on Nougat and better

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
completely disable broadcast receiver on Nougat or better, no log, nothing

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
LGTM

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky might this then kill some user's instant uploads see https://help.nextcloud.com/t/instant-upload-no-longer-works/5980/24 ?

**Comment by tobiasKaminsky** [comment]
This just disables handling of broadcast completely on >= Android N, as we use AutoUpload.
This should mainly remove those odd "Instant picture upload disabled, ignoring new picture".

**Comment by ncyclon** [comment]
Samsung Galaxy s6 edge, Android 6.0.1, beta 20161231.

2016/12/31 10:06:56
com.owncloud.android.files.InstantUploadBroadcastReceiver : Received: android.hardware.action.NEW_PICTURE

2016/12/31 10:06:56
com.owncloud.android.files.InstantUploadBroadcastReceiver : New photo received

2016/12/31 10:06:56
com.owncloud.android.files.InstantUploadBroadcastReceiver : Instant picture upload disabled, ignoring new picture

2016/12/31 10:06:56
com.owncloud.android.files.InstantUploadBroadcastReceiver : OFFICIAL processed: android.hardware.action.NEW_PICTURE

2016/12/31 10:06:59
LogHistoryActivity : onPause() ending

**Pull request merged**
