### PR TITLE
Use magical vectors

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

This fixes distorted SVGs on Androids lower than 6.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: tested on Android 8 device (where obviously nothing should be triggered anyways ;) and on Android 5 emulator.

cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Do you have an SVG which was not working? I am using lots of SVG and never had a problem with them...

**Comment by mario** [comment]
No, not really. Do you remember the Talk logo example though?

**Comment by tobiasKaminsky** [comment]
No not really ;-) 
Can we test it with the talk logo?

**Comment by mario** [comment]
@tobiasKaminsky you reported that bug xD

https://github.com/nextcloud/talk-android/issues/31

See how the left logo is cut off on Android 5 :(

**Comment by tobiasKaminsky** [comment]
So I can use the talk icon for testing? Or did you changed it since then?

**Comment by mario** [comment]
You can, yes

**Comment by tobiasKaminsky** [comment]
I tried https://raw.githubusercontent.com/nextcloud/talk-android/master/drawable_resources/icon-background.svg on an 5.0 emulator and it was showing only a whit screen.
On emulator 8, I get this:


Can someone confirm this? If so, this is is on 8.x a different bug, but still I cannot test it on 5.x with this file.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky viewing SVG files is not related to this since the svg preview part is done with an svg library to support advanced SVG features like shadows, etc... and on Android 8 it shows the exact SVG, since this is what it looks like opening it in inkscape...
2018-03-15 14_44_03-icon-background svg - inkscape

**Comment by mario** [comment]
So what do we do with this?

**Comment by AndyScherzinger** [comment]
Well, I think @tobiasKaminsky needs to comment. I just posted the Screenshot to make it clear that this PR is not related to the preview Activity which uses a svg rendering Lib for advanced rendering while this PR is about showing svg images in other places like activities and notifications.

**Comment by tobiasKaminsky** [comment]
:+1: 
@AndyScherzinger thanks for clarifying this.

**Comment by tobiasKaminsky** [comment]
Merging as @AndyScherzinger already approved.

**Pull request merged**
