### PR TITLE
Rename "remove" to "delete"

### LINKED ISSUE #655: Rename "remove" to "delete"
"Delete" is a standard word to describe this action and I know what it does already. "Remove" is something new that I have to think about what it does. 

I suspect this wording was used so that "remove from server" and "remove from device" can be options in the dialog, but I think "Delete from device" is just as clear. 

As an added benefit, "Delete" is a lot more visually recognizable in the menu compared to "Remove", which is easy to mix up with "Rename".

Tangentially related: #109

### PR DESCRIPTION
**Pull request by AndyScherzinger**
resolves #655

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks good! :) @smichel17 please also review as it resolves an issue you reported.

**Comment by smichel17** [comment]
Looks good to me :)

**Comment by smichel17** [comment]
Hmm. On second thought, I don't actually like "Delete" when used with accounts, since it does not delete the account on the server. So, I think I would use "delete" for files and "remove" for accounts.

**Comment by comradekingu** [comment]
@smichel17 Sounds like a "deactivate" to me.

**Comment by smichel17** [comment]
Android uses "Remove account" in the online accounts section of the settings.

**Comment by comradekingu** [comment]
@smichel17 Makes sense if what you are removing is the attachment to the device. "Unlink account" would be an option, but far worse. "Remove" seems preferable if nothing is deleted.

**Comment by AndyScherzinger** [comment]
That is why I preferred to use Remove nearly everywhere since remove is non-destructive while delete is destructive and in nearly all cases on the client it should be remove (except when you delete files on the server). But I stopped taking on these discussions with designer since it is frustrating so I carefully pick my fights that is UI/graphic/behavior-related only...

**Comment by jancborchardt** [comment]
@AndyScherzinger it’s fine by me to use »Remove« for users, as that is more accurate. :) However, files should be Delete as that is the wording we use in the server menu too.

**Comment by AndyScherzinger** [comment]
@jancborchardt @smichel17 @comradekingu fixed. Now remove is used for accounts and delete for files. 👌

**Comment by tobiasKaminsky** [comment]
👍

**Comment by AndyScherzinger** [comment]
pinging @mario for review

**Comment by mario** [comment]
👍

**Pull request merged**
