### PR TITLE
color nav bar

### LINKED ISSUE #6240: FirstRunActivity (and follow up while login): white navigation bar, should be blue

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #6240 

 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
> And the navigation bar color is in api21.

According to Android Studio "windowLightNavigationBar" is API 27.

**Comment by JorisBodin** [comment]
> > And the navigation bar color is in api21.
> 
> According to Android Studio "windowLightNavigationBar" is API 27.

Only if you set "true" (by default is false), change the navigation button color, white to grey. And only this. If you set "navigationBarColor" in white.

"navigationBarColor" is API 21 !
Show my commit

**Comment by tobiasKaminsky** [comment]
> > > And the navigation bar color is in api21.
> > 
> > 
> > According to Android Studio "windowLightNavigationBar" is API 27.
> 
> Only if you set "true" (by default is false), change the navigation button color, white to grey. And only this. If you set "navigationBarColor" in white.
> 
> "navigationBarColor" is API 21 !
> Show my commit

Sorry, I do not get it.
Feel free to change it directly in this branch :+1:

**Comment by tobiasKaminsky** [comment]
:exclamation: Rebased :exclamation:

**Comment by JorisBodin** [comment]
> > > > And the navigation bar color is in api21.
> > > 
> > > 
> > > According to Android Studio "windowLightNavigationBar" is API 27.
> > 
> > 
> > Only if you set "true" (by default is false), change the navigation button color, white to grey. And only this. If you set "navigationBarColor" in white.
> > "navigationBarColor" is API 21 !
> > Show my commit
> 
> Sorry, I do not get it.
> Feel free to change it directly in this branch 👍

I understand why you did what you did.
This is in case you already have an account and you add a new one. 👍

It's ok for me now :D

**Comment by tobiasKaminsky** [comment]
Thanks @JorisBodin :+1:

**Pull request merged**
