### PR TITLE
Redesign file actions menu as a BottomSheet

### LINKED ISSUE #6239: Update actions menu style to Material 3
Instead of the small popover we can use the proper bottom sheet which is nicely reachable with the thumb. It should of course show the file in question on top so you know what the action will be carried out on.

### PR DESCRIPTION
**Pull request by AlvaroBrey**
⚠ Don't merge without squashing

Fixes #6239

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
Sneak peek:

<details>

Screenshot_1668162603


</details>

**Comment by tobiasKaminsky** [comment]
Is it much work to add the placeholder/icon in front of text in bottom sheet?
I think this makes it look way nicer.

**Comment by AlvaroBrey** [comment]
> Is it much work to add the placeholder/icon in front of text in bottom sheet? I think this makes it look way nicer.

Done

<details>

<summary> Screenshots </summary>

Screenshot_1668600029

Screenshot_1668600042

Screenshot_1668600052


</details>

**Comment by AlvaroBrey** [comment]
Rebased on `master` and fixed conflicts

**Comment by AndyScherzinger** [comment]
@AlvaroBrey can you fix the alignment of the headline text and push it a bit to the right, see:
202177228-3a1f094a-af94-4bb6-8a61-fea444164e75

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey can you fix the alignment of the headline text and push it a bit to the right

That is intentionally unaligned, as the icon and text sizes are (intentionally) different for the headline it didn't make much sense to me. See example:

<details>

Screenshot_1668629257

</details>

It just looks kinda bad.

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
@AlvaroBrey fair enough. The issue then is rather that the headline has a different size for icon and text, below how it looks on GDrive:
Screenshot_20221116_211504

**Comment by AndyScherzinger** [comment]
So I'd say fine to merge, maybe @jancborchardt coudl also provide some feedback and if polishing is needed it can be doen in a follow-up PR - happy to help with that. PLus I need to check out the code to adopt some stuff for the Talk bottom sheets :)

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey fair enough. The issue then is rather that the headline has a different size for icon and text, below how it looks on GDrive:

I personally think it looks nicer and has better visual separation with the different sizes vs. the same size + a divider :shrug: Maybe @nextcloud/designers can weigh in on this.

However,  I will be merging this tomorrow for RC1, so we can get this properly tested before release. We can iterate on the design during the RC cycle if needed.

**Comment by AndyScherzinger** [comment]
Sounds great 👍 
Yeah I get your point, also unsure what would be best from a desing/UX perspective :S

**Comment by szaimen** [comment]
🎉🎉🎉🎉

**Pull request merged**
