### PR TITLE
CRC32 magic

### PR DESCRIPTION
**Pull request by mario**
Further hardens file changes detection.
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
Dunno what's up with lint, pls check.

**Comment by AndyScherzinger** [comment]
👍 code looks good to me while the PR needs a rebase to the latest master to resolve the droneCI build error due to the translation changes that are on master now. cc @tobiasKaminsky

**Comment by mario** [comment]
@AndyScherzinger  can you rebase pls?

**Comment by AndyScherzinger** [comment]
@mario rebased :)

**Comment by tobiasKaminsky** [comment]
On E2E branch I included md5sum, having two different checksums is maybe too much?
Is there a benefit of crc over md5sum or vice vera? 

On your code you add crc to each file, but I cannot see where it is read/used?

**Comment by mario** [comment]
@tobiasKaminsky it depends on the use case. I'm happy with MD5 for encryption branch, but CRC32 is faster and good enough(tm) for this use case, that's why I opted to do this.

As for how it works, check lines after:
 +                if (data.getCrc32() == null || (newCrc32 != -1 && !data.getCrc32().equals(Long.toString(newCrc32)))) {

**Comment by tobiasKaminsky** [comment]
👍 
(I over read setting FILESYSTEM_FILE_SENT_FOR_UPLOAD)

Then let us keep both. md5sum is only used in unit tests.

**Comment by mario** [comment]
Thanks for the quick review guys!

**Comment by mario** [comment]
@jasonbayton  once this is in daily build, please test if remove/insert SD card still triggers reupload.

**Comment by jasonbayton** [comment]
woop woop will do!

**Pull request merged**
