### PR TITLE
FileDisplayActivity: Replaced duplicate subexpression in if statement with instantVideoUploadEnabled preference.

### PR DESCRIPTION
**Pull request by ardevd**
It makes no sense to have identical expressions on both side of the binary operator, but I guess this is pretty self explanatory.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@ardevd @tobiasKaminsky not sure about this change since I'd say instead of removing the duplicate check it should check for `instantVideoUploadEnabled` since it checks for legacy instant upload.

**Comment by ardevd** [comment]
But the check is still there?

**Comment by AndyScherzinger** [comment]
@ardevd doesn't the check only contain the instant _image_ upload preference check instead of image _and_ video preference check? cc @tobiasKaminsky

**Comment by mario** [comment]
The second one should be instantVideoUploadEnabled @ardevd. Dunno how this bug persisted here for so long...

**Comment by tobiasKaminsky** [comment]
this should indeed be:
```
if (PreferenceManager.instantPictureUploadEnabled(this) ||
                PreferenceManager.instantVideoUploadEnabled(this)) {
...
}
```

**Comment by AndyScherzinger** [comment]
Thanks @ardevd :)

@jancborchardt can you add @ardevd to the oraginaztion please? :heart:

**Comment by ardevd** [comment]
Guess my code cleanup hunting revealed a sneaky bug then. :) It should be good now!

**Comment by AndyScherzinger** [comment]
:+1: looks good to me :)

> Guess my code cleanup hunt revealed a sneaky bug then. :)

Looks like, yes :+1:

**Comment by tobiasKaminsky** [comment]
It is not a real bug, as this does not harm anything, but the app is not working as expected, so all in all it is very good that you found it :tada:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky so is your comment an approval? :grinning:

**Comment by mario** [comment]
👍 

@AndyScherzinger merge.

**Pull request merged**
