### PR TITLE
Fixed issue relative to Properties from ImagePreview

### PR DESCRIPTION
**Pull request by Shagequi**
Hi,

it fixes : https://github.com/nextcloud/android/issues/4847

have a nice day

### CODE REVIEW

**Comment by Shagequi** [comment]
@tobiasKaminsky @AndyScherzinger Hello !

Could you please review this PR ? Thanks :D

**Comment by AndyScherzinger** [comment]
Works like a charm 👍

**Comment by AndyScherzinger** [comment]
@Shagequi Tobias said he'll take a look tomorrow. 👍

**Comment by Shagequi** [comment]
Perfect, thanks ❤️

**Comment by tobiasKaminsky** [comment]
Thanks for this fix :tada:

**Pull request merged**
