### PR TITLE
Further codacy fixes

### PR DESCRIPTION
**Pull request by AndyScherzinger**
*  codacy: don't create same object in a loop
*  codacy: don't assign null
*  codacy: remove useless parentheses
* codacy: avoid declaring a variable if it is unreferenced before a possible exit point
* codacy: avoid using redundant field initializer
* codacy: replace literals with constants
* codacy: using varargs for methods or constructors which take an array the last parameter
* codacy: all methods are static. Consider using a utility class instead.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
PR is now ready for review, fixing 135 codacy warnings :tada:
codacy warnings have been fixed mostly via 1 commit per category except for later commits where newly introduced warnings needed to be fixed :)

pinging @tobiasKaminsky @mario @ardevd for review :heart: 

PS: Have fun at the conference :+1:

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
lint score will go down again after net transifex update

**Comment by AndyScherzinger** [comment]
> Shouldn't findbug be reduced?

In my opinion no, since the codacy issues I fixed aren't matching any findbugs checks

**Pull request merged**
