### PR TITLE
hide user account from upload view items for single account setups

### LINKED ISSUE #1943: Uploads view doesn't need a user info line if only one account is in the app
The row with the username for every upload is only necessary as soon as there are at least 2 accounts in the app.

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #1943

e.g.
device-2019-08-19-140634

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky as described by @jancborchardt - I am aware that this is a starter issue but since nobody took care of it since beginning of 2018 I thought it's fine for me to pick-up the task and it helps with the UI since most people probably only have one account anyways :)

**Comment by tobiasKaminsky** [comment]
I just added a whitespace in "if(showUser)" and formatted all parameters to be in one line each, if line > 120 chars.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky any idea why tests keep failing (imho unrelated to the PR's changes)?

**Comment by tobiasKaminsky** [comment]
No idea. In both cases they were different tests, so… just merge ;-)

**Pull request merged**
