### PR TITLE
Support gplay/free also for versionDev

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
These changes lead to a 2x2 matrix:
mode: generic, versionDev
google: free, gplay

gradle will build then all 4 variants out of it, eg. genericFree, genericGplay.
It can also build for each 4 variants a debug/release version, leading to max 8 different apks.

I am not satisfied with the naming…

This then will also need some testing for fdroid/metadata and additional changes of build targets, ….

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Prior working on drone/fdroid/… I want to know if you are fine with this approach?

**Comment by AndyScherzinger** [comment]
In general, yes I am fine with this. what is the outcome of the free/gplay variant?

**Comment by tobiasKaminsky** [comment]
Do you mean the apk file names?

``` 
./build/outputs/apk/genericFree/debug/generic-free-debug-30040000.apk
./build/outputs/apk/genericFree/release/generic-free-release-30040000.apk
./build/outputs/apk/genericGplay/debug/generic-gplay-debug-30040000.apk
./build/outputs/apk/genericGplay/release/generic-gplay-release-30040000.apk
./build/outputs/apk/versionDevFree/debug/versionDev-free-debug-20180905.apk
./build/outputs/apk/versionDevFree/release/versionDev-free-release-20180905.apk
./build/outputs/apk/versionDevGplay/debug/versionDev-gplay-debug-20180905.apk
./build/outputs/apk/versionDevGplay/release/versionDev-gplay-release-20180905.apk
```

**Comment by AndyScherzinger** [comment]
Ah! Now I got it! Sounds good! :+1:

**Comment by tobiasKaminsky** [comment]
So, do we wanna change this?
Then I can adapt drone and fdroid and stuff like that.

**Comment by tobiasKaminsky** [comment]
Edit: thinking of it. It then needs to be changed / remembered, if manually updating versionDev is using gplay or free version…

**Comment by tobiasKaminsky** [comment]
I fear that this will cause too much confusing, when we have too much flavors.
VersionDev is only for testing and there it is fine to have it only without gplay.

**Pull request closed without merging**
