### PR TITLE
remove evernote

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed
- [x] base on master after merge of #5895

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
#5895 has been merged so PR can be rebased targeting `master`

**Comment by tobiasKaminsky** [comment]
> #5895 has been merged so PR can be rebased targeting `master`

Done.

Before merging, I would like to have a review by @ezaquarii, especially on the Kotlin stuff :-)

**Comment by ezaquarii** [comment]
Eee... I didn't notice it and did similar thing here: https://github.com/nextcloud/android/pull/5986

On the upside, my PR also sanitized the connectivity and power manager APIs a bit.

Let me know which one you'd like to have.

**Comment by tobiasKaminsky** [comment]
Closed in favor of #5986

**Pull request closed without merging**
