### PR TITLE
Gradle wrapper validation

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
See: https://github.com/gradle/wrapper-validation-action

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
cc @hannesa2 created/merged on the Nc repo (for obvious security reasons as stated by you). Thanks for the inspiration ❤️

**Comment by hannesa2** [comment]
Gerne !
I see you are _much_ faster then the others 👍

**Comment by hannesa2** [comment]
Is the NC app compatible with OC ?

**Comment by tobiasKaminsky** [comment]
> Is the NC app compatible with OC ?

I have not tried it the last half year, but judging from bug/gplay reports it seems to still work.
(we do not really aim for it, but as many things are still the same, it should work).

**Pull request merged**
