### PR TITLE
2.0.0 RC1

### PR DESCRIPTION
**Pull request by AndyScherzinger**
manifest changes for release of RC 1 for version 2.0.0

pinging @mario @tobiasKaminsky

### CODE REVIEW

**Comment by mario** [comment]
Shouldn't it be 2.0.0RC1 ? :)

**Comment by AndyScherzinger** [comment]
@mario: fixed :)

**Comment by mario** [comment]
👍 
Please merge this.

**Comment by AndyScherzinger** [comment]
I'll now test drive the master! @mario @tobiasKaminsky

**Comment by mario** [comment]
k. let me know when done. I will build rc1 today (don't forget to tag btw!
:D)

**Comment by AndyScherzinger** [comment]
@mario make sure you upgraded to Android Studio 3.0 Beta 1 and you need to do a gradle clean first due to the IDE update!

**Comment by AndyScherzinger** [comment]
Smoke test ist successfull 🎉 

RC1 tag is: https://github.com/nextcloud/android/releases/tag/rc-2.0.0-01

cc @mario @tobiasKaminsky 

Congrats and thank you to everyone involved in this great, new mayor release! 🚀

**Pull request merged**
