### PR TITLE
Lint: Add Plural strings

### LINKED ISSUE #1513: Footer text wrong in languages with multiple plurals
### Actual behaviour
OCFileListFragment.generateFooterText doesn't honor languages with multiple plurals. In those languages, translations are limited (and wrong). For example, "file_list__footer__files" is not plural resource and as such, will not make sense in those languages

### Expected behaviour
Use plural resource to show files and folders in footer. Ideally, logic of this method could be simplified greatly.
 
### Steps to reproduce
1. Change language of phone to language with multiple plurals (Serbian is example I know)
2. Notice that generated translations are nonsensical and weird

### Environment data
Android version:
Dev

### PR DESCRIPTION
**Pull request by AndyScherzinger**
converting Strings which need to be available in different quantities into plurals.

While it is a lot of changed files you only need to check the Java classes since anything else are the ```strings.xml``` files, maybe check the default one from ```values```.

resolves #1513

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario While it is a lot of changed files you only need to check the Java classes since anything else are the ```strings.xml``` files, maybe check the default one from ```values```.

**Comment by AndyScherzinger** [comment]
Would love to have this in 2.0.1 to get this to master :)

**Comment by AndyScherzinger** [comment]
beware that we should not merge this PR before transifex hasn't fixed their plurals bug because else the fixed warnings will turn into errors as soon as they have been translated to Ukrainian...

@tobiasKaminsky do you have any news from them regarding this issue?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky do you have any news from them regarding this issue?

I asked them once again via mail.

**Comment by tobiasKaminsky** [comment]
Reply from transifex: no new news :/

**Comment by AndyScherzinger** [comment]
pinging @mario @tobiasKaminsky for review :)

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
> beware that we should not merge this PR before transifex hasn't fixed their plurals bug because else the fixed warnings will turn into errors as soon as they have been translated to Ukrainian...

I think we should merge this now and then adjust the error count as otherwise this PR will stay there forever...

**Comment by mario** [comment]
Do it

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky everything green, just awaiting your approval 😃

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
