### PR TITLE
Add SPDX header

### PR DESCRIPTION
**Pull request by AndyScherzinger**
- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @starypatyk @AlvaroBrey @ezaquarii 
sorry to bug you, but in an effort to add standardized SPDX license/copyright headers to the source files of Nextcloud Android Files I spotted some classes (not limited to the ones ion this PR I guess) that are mislabelled as GPL3+ instead of AGPL3+ as mentioned in the projects readme file. So I wanted to get your feedback if you are fine we changing it from GLP3+ to AGPL3+

Thanks in advance for a brief feedback and sorry to bother you.

**Comment by ezaquarii** [comment]
I'm ok.

**Comment by starypatyk** [comment]
Sorry for delayed response - I have been travelling lately. Fine for me as well. :+1:

**Comment by AlvaroBrey** [comment]
I'm fine with this too, sorry for the late reply!

**Comment by AndyScherzinger** [comment]
Thanks everyone for the replies 🙏 Highly appreciated - now possible to get merged 🚀

**Pull request merged**
