### PR TITLE
Theme edit text status message

### PR DESCRIPTION
**Pull request by AndyScherzinger**
follow-up to #7172 also theming the edit text field accordingly

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
For some reasons this is not working…

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/blob/d6a02ce765e3b6cc4bec643180a1c7f8dda4b647/src/main/java/com/owncloud/android/utils/ThemeUtils.java#L571

This does not at all use server colors?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky you are right! 👍 Just pushed a fix, locally tested against your server and works for me 👍

**Pull request merged**
