### PR TITLE
Remove unused translations from values/strings.xml

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Before we used lint we removed many code references without removing the strings, so this is only a cleanup.
When we merge this some time ahead of next release we can see in dev version if some translations are missing.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
As I am too lazy to remove all already translated strings by hand, I would like to let transifex do the work.
The downside is, we have to merge this without lint is green.
But right after the merge to master I can trigger transifex bot and all translations should be removed.

**Comment by AndyScherzinger** [comment]
:+1: fine by me, pinging @mario for 2nd review :)

**Comment by AndyScherzinger** [comment]
pinging @mario for 2nd review :)

**Comment by AndyScherzinger** [comment]
pinging @mario for 2nd review :)

**Comment by mario** [comment]
Approved

**Pull request merged**
