### PR TITLE
fix wrong show of sort/list group and FAB in details or text preview

### LINKED ISSUE #6437: Preview View shows Sorting/grid/list element and FAB while it shouldn't
See screenshot, beware that the same applies for the details view

cc @tobiasKaminsky @JorisBodin @Shagequi 

💡 I guess it is due to #6262 ... but that is just a guess

**->** IMHO we should not release 3.13.0 without having this matter fixed

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #6437

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
> I'll create an issue for that if I don't find an existing related one. Or maybe should I add it to #6360? Or both?

Hi @eneiluj, in this case best would be to create a separate one since nested scroll views were there probably before so that problem just got worse but has somewhat existed before :/ Thanks ❤️

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky partially fixed the issue. While the fab/sorting isn't shown anymore the details view is scrolled-down to the activity/share tabs and you need to scroll-up to see the toolbar etc. again. Even in case the tabs are more or less empty.

**Comment by AndyScherzinger** [comment]
further issue:  #6448

**Comment by tobiasKaminsky** [comment]
> details view is scrolled-down at the beginning

This is independent from this PR, or?
I guess Android remembers the last "scroll state".

**Comment by tobiasKaminsky** [comment]
> details view is scrolled-down at the beginning

I will track this in a new issue.

**Pull request merged**
