### PR TITLE
Update Support, Test libraries and gradle plugin

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* update support library to 25.4.0
* update test libraries to latest version
* update Android gradle plugin to alpha->beta

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
pinging @mario @tobiasKaminsky for review :)

**Comment by mario** [comment]
👍 

Please rebase before merging, but perfect.

**Comment by AndyScherzinger** [comment]
pining @tobiasKaminsky for approval

**Comment by mario** [comment]
@AndyScherzinger in the mean time please do a PR updating manifest for RC. Thanks.

**Comment by AndyScherzinger** [comment]
@mario: #1299 :)

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario can one of you re-trigger the transifex bot? :)

**Comment by mario** [comment]
Tobias will have to, not near computer atm...sorry

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
