### PR TITLE
Removing uploads from account when logout

### PR DESCRIPTION
**Pull request by imjarp**
This PR will remove the uploads when the user logout from it´s account. Because when you login with another account you will see the previous uploaded file.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 @mario code looks good to me, haven't had the time to test it, but the PR includes a unit test. Kudos for that @imjarp 🎉

**Comment by AndyScherzinger** [comment]
👍 re-approval due to commit fixing codacy issues 👍

**Comment by mario** [comment]
This happens because you see uploads of all accounts, rather than just the one you're logged in with :P cc @tobiasKaminsky @AndyScherzinger 

But yes, looks very good - thanks.

**Comment by mario** [comment]
👍

**Pull request merged**
