### PR TITLE
Power saving crash

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix https://github.com/nextcloud/android/issues/13404

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by joshtrichards** [comment]
Should we backport this to 3.30.x or is 3.30.6 the end of the line for 3.30.x?

**Comment by CodeSteph** [comment]
> Should we backport this to 3.30.x or is 3.30.6 the end of the line for 3.30.x?

Yes please, this bug is very annoying. Can someone review it ?
It is blocking auto-upload for already selected directories and I haven't found any workaround to reactivate it (deselecting/reselecting, changing config, ...). Manually disabling power saving is not working either, thus, no more auto-upload for me. Please help, I'm convinced many users encounter the same issue

**Comment by tobiasKaminsky** [comment]
Good idea :+1:

**Comment by tobiasKaminsky** [comment]
We will then release a new version on monday.

**Pull request merged**
