### PR TITLE
authentication: Added missing variable assignment.

### PR DESCRIPTION
**Pull request by ardevd**
The `mAuthTokenType` variable is declared and assigned a null value but no value is subsequently assigned, making the null check later on redundant. The `AccountAuthenticator.KEY_AUTH_TOKEN_TYPE` extra value should therefore be assigned the `mAuthTokenType` value I'm assuming.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@ardevd fancy signing the commit? 😁

**Comment by ardevd** [comment]
@AndyScherzinger ok, I need to figure this out. I did GPG sign them before pushing them and GitHub shows them as verified. *confused*

**Comment by AndyScherzinger** [comment]
> EDIT: ah, you want me to sign off on them. Gotcha.

Yes, sorry for the confusion, I should have been clearer 🙈

**Comment by tobiasKaminsky** [comment]
Indeed, nice catch!
I have no idea why I removed this when adding #3383…

**Pull request merged**
