### PR TITLE
Fix bug firstlogin

### PR DESCRIPTION
**Pull request by aleister09**
@mario @tobiasKaminsky I created this PR to fix the [Bug #823 ](https://github.com/nextcloud/android/issues/823)

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Great, thank you for this bug fix.
It seems that you have also included a bug fix for #810 .
If you have time, can you please revert this commit? If not, I am happy to do this for you.

**Comment by mario** [comment]
@tobiasKaminsky please make sure this doesn't break search on-rotation, resume, etc. Thanks.

**Comment by aleister09** [comment]
@tobiasKaminsky  Done! 
I reverted it

**Comment by tobiasKaminsky** [comment]
👍 
@aleister09 thank you!

@mario search is not working for me atm, even on master. But as this is just about the first start and "refreshList(true)" is also used in onRefresh() I think it is fine.
But latest check is up to you.

**Comment by mario** [comment]
Tobias v12 master? What is not working?

**Comment by mario** [comment]
👍

**Pull request merged**
