### PR TITLE
Fix for autoupload

### LINKED ISSUE #2000: Retrying failed uploads stops the app
### Actual behaviour
- Retrying failed uploads stops the app

### Expected behaviour
- The failed uploads are retried
 
### Steps to reproduce
- Open Nextcloud
- Go to "Uploads" from sidebar
- Notice some uploads failed
- Select "retry failed uploads" from the `...` menu
- Get an Android system message "Nextcloud has stopped" with options to open again, send feedback,e tc.

### Environment data
Android version: 7.1.2

Device model: HTC One M9

Stock or customized system: Custom (LineageOS 14.1)

Nextcloud app version: 3.0.0 RC1

Nextcloud server version: 12.0.4

### Logs

No app logs.

#### Web server error log/Nextcloud log (data/nextcloud.log)

Omitted because it's probably not relevant, but I'll add it if you want.

Note that the uploads *do* still eventually happen if I re-launch the app and just let it run in the background.

### PR DESCRIPTION
**Pull request by mario**
Fixes #2000  and others.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@mario could you do a rebase/conflict resolve right away please? :)

**Comment by mario** [comment]
@AndyScherzinger already done. Can't be that fast :p

**Comment by tobiasKaminsky** [comment]
👍 working on 8.1

**Comment by AndyScherzinger** [comment]
I did 

* uninstall
* reboot
* remove any files left on device by Nc
* installed the branch
* activated auto upload for camera folder, wifi-only
* deactivated wifi
* took pictures
* activated wifi
* nothing happens (not even after 15 minutes)
* took pictures (wifi still active)
* they get uploaded, the older, queued one stay there forever

Android 8 on OP3T :/

**Comment by mario** [comment]
You sure you pulled latest code?

**Comment by AndyScherzinger** [comment]
👍  Ah, my mistake. This is a different issue. I retested it but clicking on "Retry" doesn't do anything (except hiding the menu item). Can't say why but if it works for Tobias, then let's merge it.

**Comment by AndyScherzinger** [comment]
> You sure you pulled latest code?

Yes I am running this branch :/

**Comment by mario** [comment]
Well lets wait for tobias to test the retry button?

**Comment by AndyScherzinger** [comment]
> Well lets wait for tobias to test the retry button?

Well, he did and it works for him: https://github.com/nextcloud/android/pull/2062#issuecomment-361188041

**Comment by mario** [comment]
Could you try to debug? Look at retryFailedUploads in FileUploader and see if it runs after you click Retry failed uploads.

**Comment by AndyScherzinger** [comment]
Ah, that might be the issue ;) The method gets called but since my uploads are "waiting for wifi" the are not "failed" and so nothing happens xD

**Comment by mario** [comment]
So the functionality is correct :P

**Comment by AndyScherzinger** [comment]
Yes :)

**Comment by mario** [comment]
My only issue with retry is that it retries all accounts. Shall I limit it only to active one?

**Comment by mario** [comment]
Merging this, while I wait for you to answer :P

**Comment by mario** [comment]
Btw @AndyScherzinger:

- get off wifi
- take pictures
- get on wifi
- pictures should be uploaded right away :)

**Comment by mario** [comment]
If not, even after this PR (I'm not sure we understand each other correctly) I can look into it!

**Comment by tobiasKaminsky** [comment]
> My only issue with retry is that it retries all accounts. Shall I limit it only to active one?

I think this is fine as an user wants to have all uploads working / retried.
Imagine you have 3 accounts with each failing uploads and you would have to cycle through all three accounts and manually resume them...
(Also as the retry upload function on network change is retrying all uploads, this should be kept this way)

**Comment by mario** [comment]
@tobiasKaminsky yes, network change is a different thing - that MUST retry all accounts)

**Comment by detly** [comment]
Retrying failed uploads used to retry even the uploads waiting for wifi. Will this not happen any more? Currently (3.0.0 RC2) I have almost 100 failed uploads that have been sitting in the queue for a week. How should I restart them (eg. when the fix is released)?

**Comment by detly** [comment]
Maybe this belongs on #2055?

**Comment by AndyScherzinger** [comment]
The next RC and the next nightly dev build will ship this fix which should fix the restart menu item issue.
The auto restart on wifi connection for wifi only still exists and is something we need to look at and fix but hasn't been resolved yet. So no release info but I also hope it can be fixed for 3.0.

**Comment by AndyScherzinger** [comment]
@detly 2055 is only about the restart menu item for failed queue items.

**Comment by detly** [comment]
Thanks for the update!

**Pull request merged**
