### PR TITLE
Improve Navigation Header Layout

### LINKED ISSUE #3689: Drawer: account name cut of due to notch
### Actual behaviour
- Display issue with the domain/server name

### Expected behaviour
- The text must be displayed correctly
 
### Steps to reproduce
1.  Just deploy the hamburger menu

### Environment data
Android version: Android 9

Device model: POCOPHONE F1

Stock or customized system: MIUI 10 (Xiaomi Android version)

Nextcloud app version: 3.5.0

Nextcloud server version: 15.0.4

### Image
screenshot_2019-02-28-23-58-10-403_com nextcloud client

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #3689

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky maybe release it to the dev build by merging to master and maybe also make it a backport?

**Comment by tobiasKaminsky** [comment]
Then let us first merge it to master for dev version.
And maybe @RavengamerSpace can test it.

**Comment by AndyScherzinger** [comment]
Sounds like a plan!

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky we could think about backporting this to 3.5.1 for a RC2 if you want. I'll leave this decision to you, nothing critical I think.

**Comment by tobiasKaminsky** [comment]
Sorry, I overlooked this and did a RC2 one hour ago.
I think it is not that critical.  We should only backport UI critical fixes and fixes that lead to data loss or other serious fixes.

**Comment by AndyScherzinger** [comment]
I overlooked it too. So, yes fine to just have this in 3.6.0 👍

**Pull request merged**
