### PR TITLE
improving app translation

### PR DESCRIPTION
**Pull request by AbdulrhmanSayedAli**

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @AbdulrhmanSayedAli thank you very much for your PR. Unfortunately we can't merge it since translations are purely handled via transifex, see https://www.transifex.com/nextcloud/nextcloud/translate/#ar/android/91098483 these translations get pulled via our bot every night, so if you improve the translation there, then it will be in master the next day :)

Else if you are finished with the translations for now I can upload your file to transifex to save you the time :)

**Comment by AndyScherzinger** [comment]
So I just uploaded your changes to transifex and they will be on our master by tomorrow morning :)

Thanks for taking the time and making an effort in improving the app's translation, this is highly appreciated 🙏

**Comment by AbdulrhmanSayedAli** [comment]
ok @AndyScherzinger it is my pleasure to help improving this app , I didn't know that I have to use transifex for translation
next time I will upload the file my self :)

**Comment by AndyScherzinger** [comment]
No worries, all good! Again happy to help 😊

**Pull request closed without merging**
