### PR TITLE
Fix text in option menu within image preview

### LINKED ISSUE #4976: White text in options menu for image preview
### Actual behaviour
- white text

### Expected behaviour
- text should be black (or white text on dark background in dark mode)
 
### Steps to reproduce
1.  open an image
2.  open option menu

Happens on latest master, dev version

@dan0xii do you have an idea where I have to look at?

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #4976

I failed to find the reason, so we are doing this now programmatically…

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky dark mode seems fine now while light mode now has white text on white background. (Tested the QA build)

**Comment by AndyScherzinger** [comment]
it does show the wrong build number though :/ (so something might be off)

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky dark mode seems fine now while light mode now has white text on white background. (Tested the QA build)

This sounds to be the old behaviour.

**Comment by AndyScherzinger** [comment]
Retried and works just fine.

**Pull request merged**
