### PR TITLE
Update strings.xml file

### PR DESCRIPTION
**Pull request by Valdnet**
Fix full sentences.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@nextcloud/designers @jancborchardt can you have a look at this one? I am not sure if we finish single-sentence strings with a fullstop/dot.

**Comment by Valdnet** [comment]
@AndyScherzinger If there is another punctuation mark in the sentence, e.g. comma, then the sentence must end with a dot. Descriptions for functions that are a complex sentence should also end with a dot.

But the final decision belongs to: @nextcloud/designers @jancborchardt :wink:.

**Comment by tobiasKaminsky** [comment]
`
<string name="file_list_empty_favorites_filter_list">Files and folders you mark as favorites will show up here.</string>
`
Is fine for me, as this this is similar to


But 
`
<string name="end_to_end_encryption_passphrase_title">Make note of your 12 word encryption password.</string>
`

is a title/caption in a dialog.

**Comment by Valdnet** [comment]
> `<string name="end_to_end_encryption_passphrase_title">Make note of your 12 word encryption password.</string>`
> 
> is a title/caption in a dialog.

@tobiasKaminsky Dot removed. I relied on translating another team translator.

**Comment by tobiasKaminsky** [comment]
Fine from my side.
Let us wait for designer :-)

**Comment by Valdnet** [comment]
@tobiasKaminsky @AndyScherzinger What about changes in the descriptions?

**Comment by AndyScherzinger** [comment]
@Valdnet I am not an expert on this, so still hoping for @nextcloud/designers feedback

**Comment by tobiasKaminsky** [comment]
@jancborchardt if is not okay, why did you then approve it?

**Comment by jancborchardt** [comment]
> @jancborchardt if is not okay, why did you then approve it?

I said it's ok unless in headings. All of them are sublines as far as I can see, no?

**Comment by Valdnet** [comment]
@tobiasKaminsky There is approval from @jancborchardt and the merger is still missing.

_My opinion:_
PR was issued on February 24, corrected March 2, until today, May 11 is still not merged. Such a pace discourages the issuing of "Commits" by translators for Android Nextcloud.. In other sections it is done very quickly. I can say "day by day" and even within an hour.

I know there are more important things for developers, but remember that users first evaluate the app for its appearance and translation.

This is just my opinion and I don't want to offend anyone here.

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky There is approval from @jancborchardt and the merger is still missing.

There is currently no approval. In top right you can see a "pending".

But I now do see that I partially misread his reply.
So, as indeed this is only subtext, no headlines we can merge this.

Sorry for the delay. And every PR is important, especially UX/UI, as you said.
(but with corona and other tasks I am a bit overwhelmed and sometimes loose track…:/)

**Pull request merged**
