### PR TITLE
Fix external storage permission

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
With this contacts backup is not working as the app does not have the permission to read/write contacts.
Although the permissions are asked during runtime on API >22 we still need them in AndroidManifest.

https://github.com/nextcloud/android/blob/61cbe88bd056ec1ec2f3933a8175cdc6a4252c6c/src/main/java/com/owncloud/android/ui/fragment/contactsbackup/ContactsBackupFragment.java#L372-L372

Doc says:
> Requests permissions to be granted to this application. These permissions must be requested in your manifest, ...

So we can keep maxSDK for USE_CREDENTIALS, MANAGE_ACCOUNTS, AUTHENTICATE_ACCOUNTS as these get removed on API 23.

But GET_ACCOUNTS, READ_CONTACTS, WRITE_CONTACTS needs to be in Manifest without SdkVersion as far as I understand.

**Comment by mario** [comment]
I have removed it from READ and WRITE CONTACTS now. But are we sure we need to remove it from GET_ACCOUNTS too?

**Comment by tobiasKaminsky** [comment]
https://developer.android.com/reference/android/Manifest.permission.html#GET_ACCOUNTS

our code says:
> GET_ACCOUNTS is needed for API <= 22.
        For API >= 23 results in the addition of CONTACTS group to the list of permissions that may be
        dynamically disabled or enabled by the user after installation; but it is not important,
        since GET_ACCOUNTS is an special case, the permission is not really needed to access accounts
        owned by the app, our use case.

Doc says:
> Allows access to the list of accounts in the Accounts Service.
>
> Note: Beginning with Android 6.0 (API level 23), if an app shares the signature of the authenticator that manages an account, it does not need "GET_ACCOUNTS" permission to read information about that account. On Android 5.1 and lower, all apps need "GET_ACCOUNTS" permission to read information about any account.

Not sure. It seems to work even with maxSDK.

**Comment by mario** [comment]
Yup, because we put in READ and WRITE contacts manually. I'm fine with this now, since we do not read accounts of other apps.

**Comment by tobiasKaminsky** [comment]
👍 
Then let us rebase and merge it this way :-)

**Comment by tobiasKaminsky** [comment]
Please wait for Codacy and Drone.
It can happen that due to rebase some problems arise and thus we should wait for those checks.
(I know that waiting for Drone is sometimes pain ;-) )

**Comment by mario** [comment]
I know, was too fast. I am waiting on other approved PRs :)

**Pull request merged**
