### PR TITLE
Show SVG images

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Successor of #465

This PR adds support for viewing SVG images as requested in #457.

Unfortunately for the time being the complete background is black since I haven't found a way to influence the background the way @mario did it for PNGs.
What do you think @mario @tobiasKaminsky @jancborchardt 

device-2017-04-05-174311

### CODE REVIEW

**Comment by mario** [comment]
👍 

@AndyScherzinger I've implemented the background changes like I did for PNG - hope you don't mind. I consider this approved, and will wait for @tobiasKaminsky to approve as well.

**Comment by mario** [comment]
@eppfel can you please approve?

**Comment by AndyScherzinger** [comment]
@mario fine with me, @eppfel might need a screenshot though ;)

**Comment by AndyScherzinger** [comment]
Thanks for side wining this PR @mario :)

**Comment by mario** [comment]
screenshot_20170411-012217

**Comment by mario** [comment]
@AndyScherzinger screenshot up!

**Comment by AndyScherzinger** [comment]
@mario thanks :) 

@eppfel @jancborchardt fine with you?

**Comment by tobiasKaminsky** [comment]
👍 cool stuff :-)

**Comment by mario** [comment]
Anyone from @nextcloud/designers  please? :)

**Comment by eppfel** [comment]
How is the position of content determined?  In your Screenshot @mario, is the redhat logo positioned like this inside the svg itself or do we align to the left?

**Comment by mario** [comment]
@eppfel we don't do aligning - this is how it is in the original svg.

**Comment by AndyScherzinger** [comment]
@eppfel are you fine with this PR (also looking at Mario's response that the alignment is within the SVG file)?
@tobiasKaminsky can you review/approve/merge after Felix' approval?

**Comment by mario** [comment]
@eppfel poke :p

**Comment by tobiasKaminsky** [comment]
👍 for me

**Comment by AndyScherzinger** [comment]
shall we just merge it? 0_o

**Comment by AndyScherzinger** [comment]
I vote yes :)

**Comment by eppfel** [comment]
Yes, yes. Not a deal breaker LGTM!

**Comment by AndyScherzinger** [comment]
@jancborchardt SVG will be shipped with the next release 💃

**Comment by jancborchardt** [comment]
Aaaawesome! :) Thanks a lot everyone! :kiss:

**Pull request merged**
