### PR TITLE
Minor improvements to participate view

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
- Use contribute url from setup.xml
- Escape quote signs

Ref: #998

### CODE REVIEW

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
lint reports
`../../../src/main/res/values/strings.xml:567: Inconsistent number of arguments in formatting string participate_contribute_github_text; found both 0 and 1`

which is due to the fact that it is not translated correctly right now.

If you both agree, I will increase the error count to 75 and then we can merge it.

**Comment by AndyScherzinger** [comment]
Agreed! 👍

**Comment by AndyScherzinger** [comment]
👍 successfully tested 👍 

@mario your turn ;)

**Comment by mario** [comment]
👍

**Pull request merged**
