### PR TITLE
fix(l10n): grammar fixes for plural usage

### PR DESCRIPTION
**Pull request by roliverio**
- Tests written, or not not needed

Fix plural usage and word positioning on the changed strings. Hinders translation on some verb forms in other languages.

### CODE REVIEW

**Review by ZetaTom — COMMENTED** [review]
Firstly, thank you for taking the time to implement these changes.

All the changes to the log messages look good. I've also left a few comments with some suggestions.

**Comment by roliverio** [comment]
@ZetaTom  I've reverted the changes on values-*, implemented your suggestion also on the other file. Let me know if it looks right!

**Review by alperozturk96 — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Thanks a lot @roliverio 🎉 - merged and backported 👍

**Pull request merged**
