### PR TITLE
Fix wrongly sized png thumbnail after download #6006

### LINKED ISSUE #6006: Thumbnail is cropped after download
Hello :)

I click "download" on item menu

Screenshot_20200505-162325_Nextcloud (2)

Nextcloud 3.11.1

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #6006

removed TODO as we agreed to have a white checker background always, even on dark mode.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by JorisBodin** [comment]
@tobiasKaminsky It's having another undesired effect
Capture d’écran 2020-05-05 à 18 08 55
Capture d’écran 2020-05-05 à 18 07 51

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky It's having another undesired effect

True. I tested it only with square image.

**Comment by tobiasKaminsky** [comment]
Another try…
Thanks for testing!

**Comment by JorisBodin** [comment]
@tobiasKaminsky it's not good :(

**Comment by tobiasKaminsky** [comment]
@JorisBodin hopefully/maybe I finally found a solution…
Can you test it again please? :-)

**Comment by JorisBodin** [comment]
@tobiasKaminsky It's fine :D

**Pull request merged**
