### PR TITLE
Properly show default/generated avatar if there is no one yet

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
To test
- clean installation (without any cache)
- have an avatar
- put ` Thread.sleep(10000); ` in ThumbnailsCacheManager:885
- start app
- see first icon with char, e.g. N
- after ~10s see your avatar

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by JorisBodin** [comment]
@tobiasKaminsky 👌
But now "AsyncAvatarDrawable" is not use. We can remove all reference?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky ok_hand
> But now "AsyncAvatarDrawable" is not use. We can remove all reference?

True, I will remove it :)

**Comment by tobiasKaminsky** [comment]
Removed and rebased :-)

**Comment by JorisBodin** [comment]
@tobiasKaminsky You can merge it :D

**Pull request merged**
