### PR TITLE
Allow to upload whole folders.

### PR DESCRIPTION
**Pull request by Ich5003**
This PR aims to implement the long and often requested feature to upload whole folders: #184

A few notes on the implementation:
- Also show checkboxes beside folders
- Edited the LocalFileListFragmentInterface, which now has an additional onItemCheckboxClicked, beside the already existing onItemClicked:
    - onItemCheckboxClicked: Selects the respective file or folder (as the old onItemClicked implementation for files)
    - onItemClicked:
        - For Files: Calls onItemCheckboxClicked for the respective file to select it
        - For Folders: Opens the directory as in the old onItemClicked implementation
- getCheckedFilesPath() in LocalFileListAdapter returns all selected files and all files in the selected directories recursively.
- UploadFilesActivity onFinish addtionally puts the local path within which files were selected to the Intent. This is needed to calculate the correct subdirectories on upload.
- Changed requestUploadOfFilesFromFileSystem in FileDisplayActivity to calculate remotePath based on the difference between the localBasePath and the selected files.
- Changed the FileUploader settings in requestUploadOfFilesFromFileSystem to create missing directories. This is needed to create the subdirectories recursviely.

### Testing 
- [x] Tests written, or not not needed

Added Unit test for the added StringUtils.
For everything else there did not seem to exist similar tests yet which would require edits, extensions or enhancements.

### CODE REVIEW

**Comment by Ich5003** [comment]
I just added a few notes on the implementation in the first post.

**Comment by Ich5003** [comment]
Is there any action required by me at the current point?

**Comment by AndyScherzinger** [comment]
@Ich5003 No, all good. I hope @tobiasKaminsky finds the time to review the PR since my day job keeps me busy these days.

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
Sorry for coming back this late to you.
This is really a great enhancement!

I tested it and worked without any problems :tada: 

Once CI is green, I'll merge it.

**Comment by Ich5003** [comment]
Thanks for checking it out @tobiasKaminsky 
CI seems to have finished successfully.

I'm looking forward to have this in the a public release version.

**Comment by tobiasKaminsky** [comment]
> I'm looking forward to have this in a public release version.

It will be in tomorrow's daily version and then in 3.17 :shipit:

**Comment by Myridium** [comment]
Okay but how? On version 23.0.0 and there is no option to upload a directory when clicking the plus button to upload.

**Comment by Ich5003** [comment]
You simply need to press "Upload files" and then mark the specific folders

**Comment by Myridium** [comment]
> You simply need to press "Upload files" and then mark the specific folders

The file picker dialog does not allow it. Can only select files.

**Pull request merged**
