### PR TITLE
check walled garden only on wifi

### LINKED ISSUE #2349: Check if internet is walled only on wifi
Am I right that we can assume that any mobile data is not walled?

So then we could change the check of this to only wlan connections:
https://github.com/nextcloud/android/blob/b71c302db83dbce593195f43d7d196b9571ee8b8/src/main/java/com/owncloud/android/utils/ConnectivityUtils.java#L49-L51

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #2349 as it is was quite quick and I wanted to test it in conjunction with #2214 ;-)
Hopefully my assumption is correct ;-)

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by mario** [comment]
All good, except this won't work on VPN. So let's make sure you iterate all networks and check if we're connected to wifi.

**Comment by tobiasKaminsky** [comment]
Can you explain this a bit more? 
The active network is VPN, but you want to check if another connected network is wifi?

**Comment by mario** [comment]
Yes, because if VPN is active, it'll be active network (as you can only have one on Android really), but you're connected to VPN via wifi. So you have to check if ANY of the networks you're on is Wifi and if you're connected.

**Comment by tobiasKaminsky** [comment]
I guess I understood it and hopefully implemented it correctly

**Comment by mario** [comment]
OK. You don't need isOffline method. 

Instead use: Device.getNetworkType(context).equals(JobRequest.NetworkType.ANY)

If this is true, you're offline.

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger ping :-)

**Comment by AndyScherzinger** [comment]
:+1: here! ;)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky all green just needs a rebase&merge :)

**Pull request merged**
