### PR TITLE
[resized images] Send multiple files

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
It allows to send multiple resized images to another apps.

depends on https://github.com/nextcloud/android/pull/69

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you rebase this one to master? :) That'll help me with the review :)

**Comment by tobiasKaminsky** [comment]
This one depends on #69, so I hope that rebasing there should help also here ;)

**Comment by AndyScherzinger** [comment]
Only if you rebase this on on the then rebased #69 ;)

**Comment by tobiasKaminsky** [comment]
Strange. This branch seems to be very very old and outdated...
I hope I will find some time to update it...

**Pull request closed without merging**
