### PR TITLE
Crash when sending non-existing log

### PR DESCRIPTION
**Pull request by AndyScherzinger**
PR for #283 

cc @tobiasKaminsky

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please review (and merged in case you approve the changes) since this fixes some crashes reported by users

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky also here needs a +1 :wink:

**Comment by AndyScherzinger** [comment]
Pinging @tobiasKaminsky --> also here needs a +1 :wink:

**Comment by tobiasKaminsky** [comment]
LGTM

**Pull request merged**
