### PR TITLE
Dev version as flavor

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This introduces dev version as flavor and builds from master, as described in #1523.
Flavor is called "versionDev" to have "generic" still as first.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky all build flavors fail atm :/

**Comment by tobiasKaminsky** [comment]
Fixed, please review, so we then can do dev version based on master 👍 
@mario @AndyScherzinger

**Comment by tobiasKaminsky** [comment]
https://drone.nextcloud.com/nextcloud/android/2346/13
> 1209 To run dex in process, the Gradle daemon needs a larger heap.
1210 It currently has 1024 MB.
1211 For faster builds, increase the maximum heap size for the Gradle daemon to at least 4608 MB (based on the dexOptions.javaMaxHeapSize = 4g).
1212 To do this set org.gradle.jvmargs=-Xmx4608M in the project gradle.properties.

Asked Morris if we can increase this on the drone workers.

**Comment by tobiasKaminsky** [comment]
@mario @AndyScherzinger please review so we can get dev version back running 👍

**Comment by AndyScherzinger** [comment]
👍 looks good only minor thing which is not that important is the usage of Toast instead of snackbar the new Android promoted way to show short information stuff.

**Comment by tobiasKaminsky** [comment]
Nice catch 👍

**Comment by AndyScherzinger** [comment]
😃👍

**Comment by mario** [comment]
👍 


Rebase.

**Pull request merged**
