### PR TITLE
Iteration 4 for File detail & new sharing - email share

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
* [x] https://github.com/nextcloud/android-library/pull/151

This allows to enter a valid email address and then share the file/folder to it.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Strange, AS should have done this automatically, but anyways thanks @AndyScherzinger

**Comment by AndyScherzinger** [comment]
> Strange, AS should have done this automatically, but anyways thanks @AndyScherzinger
Happy to help :)

**Comment by AndyScherzinger** [comment]
:+1: successfully tested, minor issues I found have been fixed along the review :)
Permissions set during creation are correct :+1:

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
I vote for this to be backported :+1: 3.2.1

**Comment by Bertel3** [comment]
Does this solve this [issue](https://github.com/nextcloud/android/issues/794)?

**Comment by AndyScherzinger** [comment]
No it solves the issue of correctly set permissions for mail shares. The one you are referring to solves the creation of mail shares.

**Comment by AndyScherzinger** [comment]
My mistake, misread it, yes it does

**Pull request merged**
