### PR TITLE
Backport #3207: Fix fingerprint bug

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 looks good, lint warnings need to be raised to 97, since master is now at 97 not 94 anymore which is what breaks the builde @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Hm. This is against stable-3.3.x, so master lint should not be relevant.
I guess there is a bug in the lint script…

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please also see the master targeting PR, there are two newly introduced lint warnings (unused resources) that should be fixed

**Comment by tobiasKaminsky** [comment]
To be honest, I do not really care if a backport is increasing lint.

So let us merge it, if you are fine with it.

**Comment by AndyScherzinger** [comment]
Also my opinion. Merged!

**Pull request merged**
