### PR TITLE
Replaced legacy custom ImageView and ViewPager class with PhotoView and stock ViewPager

### LINKED ISSUE #2583: Replace legacy and stale custom ImageView and ViewPager classes with a better alternatives
We currently include a `com.ortiz.touch.ExtendedViewPager` class that provides zooming/scrolling functionality for preview images. It's only used in the `PreviewImageActivity`.

The code is seemingly not maintained anymore and the source is pretty clunky. 

As @AndyScherzinger recommended, let's look for a replacement in form of a third party library that will remove the need to maintain old code nobody knows how to work with and perhaps give a better user experience as well.

I'll be happy to look into this. @AndyScherzinger proposed [PhotoView](https://github.com/chrisbanes/PhotoView) which looks good to me. I'll see if I can dig up other alternatives too though and play around with them to see what works.

### PR DESCRIPTION
**Pull request by ardevd**
I have removed all code related to the custom ImageView and ViewPager that's been in use and replaced it with PhotoView and the ViewPager from the Android support library.

Some immediate benefits include:

- Getting rid of legacy code that nobody wants to deal with
- Double-tap-to-zoom now has two zoom levels instead of one. The first double tap zooms in a bit, which is often the actual zoom level you want, while the next double tap zooms in further. The legacy custom ImageView just zooms all the way in immediately.

Animated gifs are not supported yet, but if we use Glide to load the image we could achieve that. I'd be happy to do it but I reckon that should be a separate PR.

Please test it out and let me know if there's anything that doesnt work as it's supposed to.

This closes #2583

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Coding wise it looks good to me while I found some issues while testing:

* svg files aren't previewed anymore
* the snack bar is shown behind the navigation bar (probably due to full screen previews?)
* I think whenever I zoom into a previewed images a snack bar should come up asking me to download the file (@tobiasKaminsky is this assumption correct?)

device-2018-05-19-161337

**Comment by AndyScherzinger** [comment]
Download a gif file and trying to open it now leads to a NPE:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setCallback(android.graphics.drawable.Drawable$Callback)' on a null object reference
        at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:141)
        at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:119)
        at com.owncloud.android.ui.preview.PreviewImageFragment$LoadBitmapTask.showLoadedImage(PreviewImageFragment.java:667)
        at com.owncloud.android.ui.preview.PreviewImageFragment$LoadBitmapTask.onPostExecute(PreviewImageFragment.java:632)
        at com.owncloud.android.ui.preview.PreviewImageFragment$LoadBitmapTask.onPostExecute(PreviewImageFragment.java:502)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6809)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by ardevd** [comment]
Thanks guys! I'll look into the issues you've noted and take care of them!

**Comment by ardevd** [comment]
- Downloaded gifs now load properly
- SVGs are now displayed as expected.

**Comment by AndyScherzinger** [comment]
That is awesome @ardevd :heart: 

Just checked with the latest commit that 
* the opening of gifs is working :)
* the opening of downloaded svgs is working :)

Do you have any idea about:
* the snack bar is shown behind the navigation bar (probably due to full screen previews?)
* I think whenever I zoom into a previewed images a snack bar should come up asking me to download the file (@tobiasKaminsky is this assumption correct?)

Else we wait for @tobiasKaminsky's feedback (not before Tuesday I guess)

**Comment by ardevd** [comment]
@AndyScherzinger I dont think I get any messages asking to download the file on the current stable version. I only get it if I try to open a svg where a preview image cant be loaded.

I'm trying to figure out why the navigation bar overlaps the snackbar now. No immediate idea what the problem is but I'll figure it out by Tuesday I hope :)

**Comment by AndyScherzinger** [comment]
@ardevd any idea why the downloaded GIF isn't animated? (at least not on my phone while this worked with the legacy implementation).

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger It's because PhotoView does not support animated gif's. However, if I load the images with Glide it's supposed to work so I'm going to look into it.

Sweet! :)

> Furthermore, I notice that on the current stable version of the app, the snackbar appears behind the navigation bar also, so that can be noted as a bug.

Yeah, then we can target that separately :)

**Comment by ardevd** [comment]
@AndyScherzinger Showing downloaded animated gif's now work. I'm using the [android-gif-drawable](https://github.com/koral--/android-gif-drawable) library which seems to work very well.

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger Added support for showing animated gifs. I'm using the android-gif-drawable library which seems to work very well.

Sweet! From my testing before this PR and @tobiasKaminsky's comment, Android should be able to play animated gifs and also the implementation was able to do so (for downloaded gifs of course).

@tobiasKaminsky can you have a look/check please? :)

**Comment by ardevd** [comment]
@AndyScherzinger Yes, animated gif's worked before but the issue is that the [PhotoView](https://github.com/chrisbanes/PhotoView) library doesnt support animated gifs. The normal [ImageView](https://developer.android.com/reference/android/widget/ImageView) doesnt support it either.

**Comment by mario** [comment]
Checkered support for svg + proper pre-M handling, and I'll approve. Maybe it technically shouldn't be part of this PR, but one of them is a bug introduced by this PR, and the other is a bug introduced by @tobiasKaminsky earlier which can be relatively easily fixed, so please do it :)

**Comment by ardevd** [comment]
@mario Good catch. I'll fix checkerboard support for svg's asap!

**Comment by ardevd** [comment]
Checkerboard effect for svg's are in.

**Comment by AndyScherzinger** [comment]
Quick test:
* animated, downloaded gifs are working/animated
* svg files do also have the checkered background logic - working
* png files checkered background logic - working
* double-tap / pinch-to-zoom - working

Great Job @ardevd, will review the code now

**Comment by AndyScherzinger** [comment]
:+1: feature works nicely and code looks good to me :+1: 

(As always :heart:) Great job @ardevd ! :1st_place_medal:

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
Awesome Job @ardevd :100: 

Your PRs are really helping pushing the code base forward, especially with things like this one or the (MVP) refactorings :+1:

**Pull request merged**
