### PR TITLE
Use context instead of static getAppContext

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Found via google console that at some point getAccountType had a NPE, which comes from getAppContext, I think.
As we somewhere discussed to get rid of these static calls, this is a first step.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: fine by me

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
Build failed?

**Comment by AndyScherzinger** [comment]
> Build failed?
@mario I'll have a look, it failed because the lint warnings count is higher than on master

**Pull request merged**
