### PR TITLE
remove dividers

### PR DESCRIPTION
**Pull request by AndyScherzinger**
as discussed in #2927 remove last remaining dividers from list layouts

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Cool so far.

What about? I am fine with removing them there, too…

**Comment by AndyScherzinger** [comment]
The account list is still a list view so we'd need to rewrite it to be a recyclerview to get rid of the dividers (can be done and should be done of course).

As for the account details, yes I'd also say let's remove it :)

**Comment by AndyScherzinger** [comment]
> Can you do this in this PR?
--> https://github.com/nextcloud/android/pull/2944/commits/fb5206f6e8990215caa47b53b6ffc6c9fee90b3b :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I also removed the divider from the lsit view :D https://github.com/nextcloud/android/pull/2944/commits/d102e64f9b5b41aac144ea9e690c3b8e58010150 while the proper solution in the end will be to use a recyclerview while this way we will at least be visually consistent with the other lists :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky fixed the issues you mentioned in https://github.com/nextcloud/android/pull/2944#issuecomment-418125097 and also fix the alignment issues in these two screenshots :tada:

**Comment by AndyScherzinger** [comment]
:exclamation: sorry for the rebase :hand:

**Comment by tobiasKaminsky** [comment]
:+1: 
Great PR as always :tada:

**Comment by AndyScherzinger** [comment]
I'll then rebase and check if the PR checks turn green :)

**Pull request merged**
