### PR TITLE
RC7

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Version bump.
After merge, I will create a tag and release RC7, later this afternoon.

### CODE REVIEW

**Comment by mario** [comment]
OK, so RC8 will hopefully just be LDAP fix?

**Comment by AndyScherzinger** [comment]
I thought there is no open LDAP issue anymore?

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
@AndyScherzinger https://github.com/nextcloud/android/issues/1419

**Comment by tobiasKaminsky** [comment]
One of the two LDAP issues was resolved and for the other response is missing.
So I would put this rather in 2.0.1 than in 2.0...

**Pull request merged**
