### PR TITLE
Comment out adding all new downloaded files to folder observer

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #435 

Please @mario @AndyScherzinger test this *really* properly as I do not fully understand the background of the comment near the changed line.

### CODE REVIEW

**Comment by mario** [comment]
@AndyScherzinger if you feel like this is ok, feel free to merge - I will not be able to review it in a while. Thanks.

**Comment by mario** [comment]
@AndyScherzinger also this for 1.5?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky what do you think? Reading your comment it seems we should postpone it for risk mitigation...

**Comment by tobiasKaminsky** [comment]
Postponing is fine. 
It is not that much change (in terms of lines) so it should be easy to rebase.

**Comment by mario** [comment]
After thinking about this:

Proper fix would be to check if file is marked as available offline and not already being observed, observe. Otherwise do nothing.

**Comment by tobiasKaminsky** [comment]
FileObserverService does not longer exist, so closing.

**Pull request closed without merging**
