### PR TITLE
Fix NullPointerException in PreviewMediaFragment.

### PR DESCRIPTION
**Pull request by florian-f**
Added null-checks for mVideoPreview and mMediaServiceBinder.

    Resolves: #252

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky code/fix looks good to me! Due to the Hacktoberfest starting on Saturday we probably shouldn't merge hacktoberfest labelled issues before that date so they get counted correctly :rocket:

**Comment by florian-f** [comment]
@AndyScherzinger I just checked and apparently only pull requests made after October 1st will be counted for Hacktoberfest. So, no need to hold back on my account.

**Comment by AndyScherzinger** [comment]
@florian-f good to know and sorry to hear that :(

**Comment by tobiasKaminsky** [comment]
LGTM

**Comment by tobiasKaminsky** [comment]
@florian-f thank you very much for your contribution :+1: :tada:

**Pull request merged**
