### PR TITLE
Fix crashes

### PR DESCRIPTION
**Pull request by mario**
This fixes two crashes - one with regular, and one with local search (that we didn't touch for this release). It also releases 1.4.2 RC3 :D

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 fine code wise and RC3-wise :)

**Comment by AndyScherzinger** [comment]
For Bugfix RC reasons I talked to Mario and we will do a straight RC3. No 2 reviews though, but I hope you are still fine with this @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Fine for me.
Thanks for the real fast fixes. Glad to have this only for the google play store beta users.

**Comment by AndyScherzinger** [comment]
All credit belongs to @mario 🚀

**Pull request merged**
