### PR TITLE
Textfield design

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Using container-style for text fields (initially just for the login screen since it has a specific set of colors)

Also:
* for testing updated notes dialog to native view binding
* move login activity to native view binding

### Screenshots (German)

| Empty with hint  | Focused | With Text |
| ------------- | ------------- | ------------- |
| device-2021-02-11-124429  | device-2021-02-11-124440  | device-2021-02-11-124521  |

### Sidenote
* I am aware that there is also a design issue with the QR code part but that should go into a separate PR since it is not related to the changes needed for the text field.
* The overall styling is "Material Standard" so we only changed the colors (as in "use white color"), all semi-transparencies, text sizes etc. are material's defaults.

### Testing 

- [x] Tests written, or not not needed

### CODE REVIEW

**Review by tobiasKaminsky — APPROVED** [review]
Great job!

**Comment by AndyScherzinger** [comment]
more screenshots for @jancborchardt 
|  1  |  2  |  3  |  4  |
|  --  |  --  |  --  |  --  |
|  device-2021-02-11-150544  |  device-2021-02-11-150601  |  device-2021-02-11-150615  |  device-2021-02-11-150700  |

**Comment by jancborchardt** [comment]
@AndyScherzinger thanks! Yeah, those warnings are there too – I would say it’s fine if below that warning container we have another block of text (which also shows when the warning is not there of course) saying:
> The link to your Nextcloud web interface when you open it in the browser.

This can be in a bit subdued text, like 70% opacity white. We use that wording for the new desktop client flow as well: https://github.com/nextcloud/desktop/pull/2895#issuecomment-772565474

**Comment by AndyScherzinger** [comment]
@jancborchardt see screenshots below. I put the error container below because there could actually be 2 lines so that would come with a large blue-space™️ 

|  1  |  2  |  3  |
|  --  |  --  |  --  |
|  device-2021-02-11-180024  |  device-2021-02-11-180058  |  device-2021-02-11-180109  |

**Comment by jancborchardt** [comment]
Noice @AndyScherzinger! Only design adjustment would be to make sure the text is flush left with the "Server address" field label and content, as well as having some more line-height, like so:
107670694-49dacb00-6c93-11eb-85e6-4c3092f75df9

**Comment by AndyScherzinger** [comment]
@jancborchardt alignment fixed and line-multiplier=1.2 added 👍 

|  1  |  2  |  3  |
|  --  |  --  |  --  |
|  device-2021-02-11-184143  |  device-2021-02-11-184206  |  device-2021-02-11-184217  |

**Review by jancborchardt — APPROVED** [review]
Looks great design-wise, nice work @AndyScherzinger! :)

**Pull request merged**
