### PR TITLE
Codacy

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Fixing PMD warnings detected due the its activation

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario @ardevd ready for review, still many issues open, but quite some fixed to keep the balance between reducing warnings while keeping the complexity of the PR at a certain, low-ish level :)

**Comment by tobiasKaminsky** [comment]
:+1: 
Shouldn't the change somehow be reflected in any of our analytics output?

**Comment by AndyScherzinger** [comment]
> Shouldn't the change somehow be reflected in any of our analytics output?

--> https://github.com/nextcloud/android/pull/2808#issuecomment-404425301
It is in codacy. Since all changes are pmd fixes you won't see any changes for lint/findbugs scores ;)

**Comment by mario** [comment]
👍

**Pull request merged**
