### PR TITLE
Add release badge

### PR DESCRIPTION
**Pull request by AndyScherzinger**
to link to latest stable release tag.

cc @mario @tobiasKaminsky

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by tobiasKaminsky** [comment]
Postpone it to a later milestone as it is not relevant for 2.0

**Comment by AndyScherzinger** [comment]
since it is just a readme.md change it isn't related to any release at all 😝

**Comment by tobiasKaminsky** [comment]
:+1: 
Oh. Drone is now satisfied...Strange it crashed previously.

**Pull request merged**
