### PR TITLE
test: added unit tests for the PowerUtils class.

### PR DESCRIPTION
**Pull request by ardevd**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
```
<rule ref="rulesets/java/naming.xml/MethodNamingConventions">
        <properties>
            <property name="violationSuppressXPath" value="//ClassOrInterfaceDeclaration[matches(@Image, '.*Test$')]"/>
        </properties>
    </rule>
```
in pmd-ruleset.xml and executing ./gradlew pmd will ignore all classes which end with "Test" and where a "_" is in a method name.
Now the big question is how to include this in Codacy…

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky let's give it a try. Codacy is capable of detecting/picking-up the config file so it should work if it is included in the repo :)

**Comment by AndyScherzinger** [comment]
pmd config needs to be in the root folder to be detected

**Comment by tobiasKaminsky** [comment]
> pmd config needs to be in the root folder to be detected

It is there since quite a long time, but maybe naming is wrong…?

**Comment by tobiasKaminsky** [comment]
https://github.com/codacy/codacy-pmdjava/issues/43#issuecomment-369248152 seems that it needs to be named only ruleset.xml
--> I'll give it a try on a new PR.

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/3879

**Pull request merged**
