### PR TITLE
Move last seen version preference to AppPreferences interface

### PR DESCRIPTION
**Pull request by ezaquarii**

### CODE REVIEW

**Comment by ezaquarii** [comment]
CI failed:

```
+ emulator -avd android-27 -no-window -no-audio &
+ ./wait_for_emulator.sh
Couldn't statvfs() path: No such file or directory
(0) * daemon not running; starting now at tcp:5037
* daemon started successfully
error: no emulators found
(1) error: no emulators found
(2) error: no emulators found
(3) error: no emulators found
Failed to start emulator
```

Since I don't see any issues with compilation, I'd assume it's a flaky emulator. Is it possible to restart the CI somehow from GitHub?

**Comment by ezaquarii** [comment]
> nk we should get rid of the direct use of SharedPreferences in MainApp.
> 
> What do you think?

This is definitely on my radar, but that would probably require a bit more QA. I'd make it a a separate, focused change. No brain bandwidth for this today, sadly. :(

**Comment by ezaquarii** [comment]
IT tests failed again, this time for Play version.

```
com.android.builder.testing.ConnectedDevice > No tests found.[android-27(AVD) - 8.1.0] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations)
```

I'm not sure how to approach this. Each failure in this PR has a different reason: gradle deps issue, emulator not started, no tests... I definitely do **no** want to merge it wihout tests passing. Maybe they need to be run manually?

**Comment by tobiasKaminsky** [comment]
The CI is definitivly a bit flacky right now :/
I restarted the job.

**Pull request merged**
