### PR TITLE
 New android sharing view #1229

### PR DESCRIPTION
**Pull request by jsrck**
This pull request enables the chooser dialog requested in #1229. In contrast to the previous version it doesn't exclude the Nextcloud-App from sharing.

### CODE REVIEW

**Comment by mario** [comment]
Thanks for the contribution. Screenshots? :)

**Comment by jsrck** [comment]
It looks like on first the screenshot tobiasKaminsky posted in #1229.

On my emulator (without WhatsApp/contacts) it looks like:
send

I tried it also on my smartphone with WhatsApp installed and it looks like on tobiasKaminskys screenshot. Is it possible to test the developed version from Android Studio without uninstalling version 1.4.3 on my phone? I couldn't find out how, yet.

**Comment by tobiasKaminsky** [comment]
>  Is it possible to test the developed version from Android Studio without uninstalling version 1.4.3 on my phone

No as both apps use the same package id :-/

**Comment by tobiasKaminsky** [comment]
The old implementation was filtering the nextcloud app itself. 
Is this also possible with the new view?

**Comment by jsrck** [comment]
> The old implementation was filtering the nextcloud app itself. Is this also possible with the new view?

I tried that as described e.g. here: https://stackoverflow.com/questions/9730243/how-to-filter-specific-apps-for-action-send-intent-and-set-a-different-text-for

But the result
1. Contains duplicates of the ES File Explorer (somehow the different titles get lost...),
2. Doesn't include the contacts. I didn't find an other solution including the contacts...

So with excluding Nextcloud the result is:
excluded

With the version I commited:
with-nextcloud

**Comment by tobiasKaminsky** [comment]
Then I vote for "not filtering nextcloud".
What do you think? @mario @AndyScherzinger

**Comment by AndyScherzinger** [comment]
I also vote for "not filtering nextcloud" :)

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky do you want to ship this with 1.5 if it passes review?

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky I say it depends on how fast Google fixes the build tools. If it takes to long then I'd say we ship it.

**Comment by mario** [comment]
👍 

Hope you guys do not mind, but I've fixed the PR by disabling NC inside of it. Please test.

Unfortunately, it does not include contacts, but all other things are shown properly. We could maybe look into this for 1.5.1, if it's all all possible without resorting to a custom view?

Thanks for the awesome contribution.

**Comment by tobiasKaminsky** [comment]
> Unfortunately, it does not include contacts 

This was discussed in this issue and we agreed that it is better to have contacts (and nextcloud) in it than having no contacts, but filtered nextcloud...

**Comment by mario** [comment]
@tobiasKaminsky I got the impression that this is because of the duplicate entries which I fixed.

Anyway, if @AndyScherzinger feels the same feel free to revert my commits and merge as-is.

**Comment by tobiasKaminsky** [comment]
Right as said in https://github.com/nextcloud/android/pull/1244#issuecomment-319156043 

> Doesn't include the contacts. I didn't find an other solution including the contacts...

@AndyScherzinger revert to get the contacts back again?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky  @mario I'd say revert if this brings back the contacts _and_ if sharing with contacts actually works :)

**Comment by tobiasKaminsky** [comment]
:
Reverted and merged master.

**Comment by mario** [comment]
Then merge

**Comment by tobiasKaminsky** [comment]
Waiting for codacy ;-)

**Pull request merged**
