### PR TITLE
Revert local search

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
- when closing local search, all files are now shown, with correct checked files
	- click "upload a file"
	- filter the directory
	- close search
	- see all files agian

- some minor code enhancements
	- add annotations, needed also to be done in base methods
	- comment formatting
	- typo

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
I found a UI glitch, just when being the default folder after click "upload a file", filter the list for e.g. a single entry: The Fab button jumps to the top, remove the search/filter - Fab stays at the top

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger thanks for noticing.
I fixed it :-)

**Comment by AndyScherzinger** [comment]
Another minor issue, the behavior of the back arrow action bar button differs from the one in the remote file list.

* Remote: search active, click back arrow: search closes
* local/upload chooser: search active, click back arrow: search/filter still active and open, browsing up into parent folder

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
:+1:

**Pull request merged**
