### PR TITLE
if no internet connection, abort sync

### LINKED ISSUE #3535: Opening PDF document on the phone delete the file if no internet connection present.
### Actual behaviour
- Tell us what happens:
When I am trying to read a PDF document from within Nextcloud which has been already downloaded on the phone, trying to open the file when the phone doesn't have internet connection will cause the PDF document to be deleted from the folder it resides.

### Expected behaviour
- Tell us what should happen:
Nextcloud would normally ask the server if the file on the phone is the latest one. In absence of internet connection, the operation would proceed to having the document opened from the phone and not being deleted.
 
### Steps to reproduce
1. With internet (wifi) connection enabled, download a PDF document.
2. Disable internet (wifi) connection on the phone.
3. Open file from Nextcloud with Adobe reader or possibly default viewer.
4. Two messages are going to pop-up:
- Checking latest version of the file present on server...
- File doesn't exist....
Adobe will close and the PDF document will be removed from the phone.

### Environment data
Android version: 4.4

Device model: Samsung Galaxy S III

Stock or customized system: Stock

Nextcloud app version:
3.5.0.RC1

Nextcloud server version:
14.6 and 15.2

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
No longer showing the "LOG" option within Nextcloud app.

Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #3535 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by echismACLP** [comment]
Is the fix for this in released in the newest Android App?
If not, is there an estimated timeframe available?
I downloaded the nextcloud app from both the play store and from F-Droid and the problem appears to still exist.
The version listed in the Settings of the app is 3.5.0.
Thanks!

**Comment by AndyScherzinger** [comment]
It is assigned to the upcoming 3.5.1. I don't know of any exact release date, maybe @tobiasKaminsky can provide an estimate.

**Comment by tobiasKaminsky** [comment]
I'll have a look at the other two outstanding bugs, but for fixing them I do need access to the problematic server.
At latest I'll do a 3.5.1 RC1 tomorrow afternoon and then 3.5.1 stable release mid of next week (if things got fixed & verified).

**Comment by tobiasKaminsky** [comment]
@echismACLP however, if you want to test it, you can always use our dev version in parallel and provide feedback :-)

**Comment by echismACLP** [comment]
Thank you for the very quick responses. 
Currently our nextcloud server is not accessible outside of our local network.
I will download the dev version, give it a try, and post back with my results.
Thanks again.

**Comment by AndyScherzinger** [comment]
That would be really nice and help us a lot to confirm if the fix is working. Other than that, I created a release issue which you can track to be in the llop when we are closing in/releasing 3.5.1: #3720

**Comment by echismACLP** [comment]
I have downloaded and installed the Nextcloud dev latest.apk version20190307 and it appears to be working as expected. Files are accessible via local storage in the app when there is no connection to the server.
Thank you again for the work you are putting into this app.

**Comment by AndyScherzinger** [comment]
You are very welcome and thanks a lot for your feedback @echismACLP. ❤️ 
Thanks a lot for the fix @tobiasKaminsky 👍

**Pull request merged**
