### PR TITLE
Fixed unknown error while encrypting empty shared folder.

### PR DESCRIPTION
**Pull request by surinder-tsys**
**Precondition:**
User is logged in
Files / Folders available

 
**Steps:**

1. Start the app
2. Create a folder 

3. share the folder
4. set encryption to the shared folder
 

**Actual result:**

unknown error appears as an in app notification

**Expected result:**

error is displayed that shared folders cannot be encrypted

error_screenshot
**"Unknown error" screenshot**

fixed_screenshot
**Correct error message screenshot**

- [ ] Tests written, or not not needed

### CODE REVIEW

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Thanks @surinder-tsys !

**Comment by AlvaroBrey** [comment]
We should also hide the `Encrypt` item from the file actions menu, not just show an error, but that's out of the scope of this PR. I'll create a new issue for that.

**Comment by surinder-tsys** [comment]
@AlvaroBrey By hiding "Encrypt" menu options the current PR changes will be invalid right?

**Comment by tobiasKaminsky** [comment]
Superseeded by #11052 as we do not show options if they are not allowed.
This is better UX than showing all options with various reasons why it is not allowed.

**Pull request closed without merging**
