### PR TITLE
Change changelog for dev version to master commits as we do not have …

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Change changelog for dev version to master commits as we do not have any special changelog anylonger

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Doesn't that mean we basically don't have a dev changelog anymore? Since the changelog is usually only up-to-date right before a release starting with RC1... :/

**Comment by tobiasKaminsky** [comment]
Well, it links to the commit history of master, so it should be always up to date...
The real changelog.md is independent from that.

**Comment by AndyScherzinger** [comment]
👍 right! ....Argh... misread the URL...

**Comment by mario** [comment]
👍

**Pull request merged**
