### PR TITLE
Bump to 3.0.3

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiaskaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by mario** [comment]
👍

**Comment by xXSTrikeXx** [comment]
@tobiasKaminsky Why is the changelog only updated only in the branch stable-3.0.x and not in master? I think this confuse people when they want to see the changelog and in master there is only the "big" changelog 3.0.0

**Comment by tobiasKaminsky** [comment]
Indeed this is missing.
@mario @AndyScherzinger do we want to have changelog still in github or can we put it into wiki? So then we could avoid porting from 3.x branch to master.
Pointing changelog to wiki instead of github file should make no big difference.

**Comment by AndyScherzinger** [comment]
I am fine either way while I think @jancborchardt urged us in the beginning to not make use of the GH wiki since we then depend on GH.

**Comment by tobiasKaminsky** [comment]
Ok, good point. So it will be a "backport" ;-)

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/2338

**Pull request merged**
