### PR TITLE
Improvements in sync conflict resolution

### LINKED ISSUE #7905: Cannot get rid of file upload conflict notification
### Steps to reproduce
1. Get a notification like this

Screenshot_20210128-155456

2. Click it and end up at a dialog like this:

Screenshot_20210128-120617

3. Whatever I do (choose original file, choose the new file, or cancel) doesn't make any difference, within a minutes or so (or even less) I get the exact same notification about the exact same conflict again. Again, and again, and again

### Expected behaviour
- Choose which file to keep, then not get the notification again.

### Actual behaviour
- I keep getting the same notification about the same file conflict over and over and over again.

### Environment data
Android version:

8.1.0

Device model: 

Wileyfox Swift 2 Plus

Stock or customized system:

Stock

Nextcloud app version:

3.14.3

Nextcloud server version:

20.0.6

Reverse proxy:

?

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Rebased and fixed version of #9036

Fixes #7905

Thanks @wknds

- [x] Tests written, or not not needed

### CODE REVIEW

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by Dulanic** [comment]
Seems to cause new issues. Now it sends notifications but if you press to resolve, it says can't open conflict resolution. 
Screenshot_20220117-190237
Screenshot_20220117-190247

**Comment by AlvaroBrey** [comment]
> Seems to cause new issues. Now it sends notifications but if you press to resolve, it says can't open conflict resolution. 
> 
> 
> [logs.txt](https://github.com/nextcloud/android/files/7885422/logs.txt)

That is most likely a separate issue (#9337 or #9026). Do you have app protection enabled? Anyway please open a bug report if needed rather than commenting on the PR. Thank you!

**Pull request merged**
