### PR TITLE
Run unit tests in GH actions

### PR DESCRIPTION
**Pull request by AlvaroBrey**
- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Benefit of having it all (unit and IT) in Drone is that codacy has combined test codeCov.
I am unsure how to solve this…

**Comment by AlvaroBrey** [comment]
> Benefit of having it all (unit and IT) in Drone is that codacy has combined test codeCov. I am unsure how to solve this…

Codecov is already taking results from both tests and merging them; they are uploaded separately but Codecov waits for all CI to finish and takes both into account.

**Comment by AlvaroBrey** [comment]
> > Benefit of having it all (unit and IT) in Drone is that codacy has combined test codeCov. I am unsure how to solve this…
> 
> Codecov is already taking results from both tests and merging them; they are uploaded separately but Codecov waits for all CI to finish and takes both into account.
> 
> Check https://app.codecov.io/gh/nextcloud/android/compare/10113/overview for this PR's overview; even though `unittests`is only 3.27% coverage, total coverage is 30.84% as it uses the integration test data too.

I've added a flag to the integration tests upload too, so we can see both coverages separately in the codecov report. Let's wait for CI to finish and see what that looks like.

**Comment by tobiasKaminsky** [comment]
Ah. Cool. Either this is new, or I misunderstood it back then, as I spent a lot of work to have this as a combinded test result:
https://github.com/nextcloud/android/blob/master/app/build.gradle#L390

Great to learn that this is not needed!

**Review by tobiasKaminsky — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
See overview with coverage by test type at https://app.codecov.io/gh/nextcloud/android/compare/10113?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr%20comments&utm_term=nextcloud

**Pull request merged**
