### PR TITLE
MainApp: Fixed auto upload state check.

### PR DESCRIPTION
**Pull request by ardevd**
This is almost certainly a mistake. Using the same value on either side of a binary operator makes no sense. It should check whether photo uploads or video uploads are enabled.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
I was sure that we fixed this at some point...
Correct is: 
`
if (PreferenceManager.instantPictureUploadEnabled(context) ||
                            PreferenceManager.instantVideoUploadEnabled(context)) {
`
as we previously had instant upload for picture and video.
And if one of both is set, it should be updated to auto upload (our current system).

**Comment by ardevd** [comment]
@tobiasKaminsky I was also certain we fixed this previously. However, you are probably referring [to this](https://github.com/nextcloud/android/pull/2427). Same issue, different file. Will update this PR with correct fix.

**Comment by AndyScherzinger** [comment]
:+1: looks good to me :1st_place_medal:

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
@ardevd thanks for pointing me to the other PR :+1:

**Pull request merged**
