### PR TITLE
Development guideline

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
@nextcloud/android it is a first draft, please review and comment

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the actual labels we have are
1. to develop
2. developing
3. to review
4. to release

should we use them instead of the ones mentioned in this PR? I vote for for that since these are probably the ones used in the others repos too :)

**Comment by tobiasKaminsky** [comment]
PR label changed

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by przybylski** [comment]
:+1

**Comment by jancborchardt** [comment]
@AndyScherzinger so can we remove that wiki page https://github.com/nextcloud/android/wiki/Development-Guide (cause this PR has everything, right?) and deactivate the wiki again? :)

**Comment by AndyScherzinger** [comment]
Yes we can :)

**Comment by jancborchardt** [comment]
Done :)

**Pull request merged**
