### PR TITLE
Changed the community_testing_version_text

### LINKED ISSUE #5930: Changing information in the "Community"
### Describe the solution you'd like
Information found in "Community":
- Interested in helping out by testing what will be the next version?

In my opinion, information should not be as a question.

obraz

### Describe alternatives you've considered
Change to e.g.

- Help us test the next version.

### PR DESCRIPTION
**Pull request by Marius1501**
- [x] Tests written, or not not needed

Fixes #5930

Changed in English and in German.

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
Hey @Marius1501 , as discussed in #5930 , we'd rather remove this sentence altogether. Do you want to do that, or shall we close this PR and I'll do it?

**Comment by Marius1501** [comment]
I would do it if it's ok for you.

**Comment by Marius1501** [comment]
Should I also delete all the "community_testing_version_text"-strings?

**Comment by AlvaroBrey** [comment]
> Should I also delete all the "community_testing_version_text"-strings?

@tobiasKaminsky how do we handle this with Transifex? just delete them in English is enough? and also does it need to be backported?

**Comment by tobiasKaminsky** [comment]
Removing it in English is enough.
I think no backport is needed, as this is then just an additional string in 3.23.

**Review by AlvaroBrey — APPROVED** [review]

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
