### PR TITLE
Update master.html only on master branch

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Try for #1754: if on master branch, then update master.html.
On master is 
- each merge commit (when mergin a PR)
- transifex update

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by AndyScherzinger** [comment]
pinging @mario for review :)

**Comment by tobiasKaminsky** [comment]
Added "if lint fails on master branch, name lint file: master-$date", please @AndyScherzinger have a review again.

**Comment by AndyScherzinger** [comment]
Looks fine while lint is still unhappy ;)

**Comment by tobiasKaminsky** [comment]
Merging this right now to see the lints problem with current transifex.

**Pull request merged**
