### PR TITLE
Fix opening files

### LINKED ISSUE #751: Edit on the fly possible (*.xlsx, *.docx, *.txt ...)?
Hello,

I've encountered following ...

Opening an excel-file from nc-android-app, editing and saving to cloud works directly on Android 6.0.1

The same procedure with Android 7.0 doesn't work anymore, 'cause the document is opened as "write-protected". Are privileges changed in 7.0??

Cheers,

Tom

Tested with Android App 1.4.2 on Android 6.0.1 & Android 7.0

### PR DESCRIPTION
**Pull request by mario**
Some apps are stupid and won't allow us to open files in write mode. This fixes it.

I think this is important for 2.0, but you decide...

resolves #751

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by kangaroo72** [comment]
Is it available in beta?

**Comment by mario** [comment]
No, but it works. :P Hopefully we'll have it in 2.0.

**Comment by kangaroo72** [comment]
I don't see it on my mobile. I'm not at a Computer... Do you have a way to do or a working apk?

**Comment by AndyScherzinger** [comment]
👍 test on my Android 7.1.1 device is fine, can't say anything about older Android versions.

**Comment by kangaroo72** [comment]
I can report several devices, but I'm unable to code ... If someone can integrate this in the rc-version from store or delivering an apk, I will check. Thanks to all - extreme good work!!!!!!

**Comment by AndyScherzinger** [comment]
@mario as for 2.0.0 I'd prefer if we just release 2.0.0 and put this into a 2.0.1 via a bugfix branch 2.0.x to not having to do another RC and not postpone 2.0.0 (due to golden master). Just my opinion though!

**Comment by mario** [comment]
Sure

**Comment by tobiasKaminsky** [comment]
Yes, same opinion as Andy.
It seems not to be a regression, but "just" a regular bugfix. So either 2.0.1 which we then can do very shortly after 2.0 or 2.1 which I would like to start RC by end of October with all the Hacktoberfest PRs in it.

**Comment by mario** [comment]
2.1 needs to have all we agreed on, so against it for October.

But super fast 2.0.1 is fine since I need those two fixes, especially since
one is for a customer.

**Comment by AndyScherzinger** [comment]
Well, for 2.1 I'd also be fine with just Hacktober + open PRs

**Comment by AndyScherzinger** [comment]
I'd also be fine with having two releases within 2 month or so, like putting the rest into 2.2 but getting back to a release schedule of 4-6 weeks for bugfix/feature releases maybe 2 month tops sometimes.

**Comment by mario** [comment]
KO, whatever you two decide, but I need this FAST. Same with other PR I'm gonna open.

**Comment by kangaroo72** [comment]
I don't want to hurry. But I would also be very thankful if someone can provide me a apk-file for testing. I can check it on several Android-Systems-/Devices and will report results. Thanks, Team

**Comment by mario** [comment]
@kangaroo72 it's gonna be in the next daily build on f-droid.

**Comment by kangaroo72** [comment]
@mario cool - I'll check - thank you!!!!

**Comment by kangaroo72** [comment]
@mario - Wenn the next daily build on f-droid arrives, is it the "nextcloud-dev" app?

**Comment by mario** [comment]
Yes.

**Comment by mario** [comment]
@kangaroo72 news? :)

**Comment by kangaroo72** [comment]
eeeh - not yet? F-Droid shows Version 20170930 ...

**Comment by kangaroo72** [comment]
@mario am I right? There's no updated version with this fix now available on F-Droid yet?

**Comment by mario** [comment]
You're right - no idea. cc @tobiasKaminsky

**Comment by jospoortvliet** [comment]
This didn't make it in 2.0 afaiks, but will be in 2.0.1 I guess 💯

**Comment by mario** [comment]
Well, we won't have 2.0.1 unless something major happens - 2.1 is the next release! :)

**Comment by mario** [comment]
(but F-droid Dev should have built it, but I'm no F-droid expert)

**Comment by kangaroo72** [comment]
Isn't it possible to submit your apk?

**Comment by AndyScherzinger** [comment]
No, f-droid builds the app from source themselves...

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky for review, see tested successfully on my OPT3 - https://github.com/nextcloud/android/pull/1651#issuecomment-335618786

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by fhempeter** [comment]
Downloaded the latest developer Version apk file today, issue is still there. Can you please advise where to download an apk that includes this fix ? Thank you !

**Comment by tobiasKaminsky** [comment]
This will be available as soon as https://github.com/nextcloud/android/pull/1775 is merged and run.

**Pull request merged**
