### PR TITLE
Release 3.2.1 preparation

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* updated changelog
* updates app version

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
If you opened up the PR to the wrong branch (master instead of stable-3.2.x) you can change this within this PR: click on "edit" on the same line of the title, then you can select the base branch.
So you do not have to open up a new PR.

**Comment by AndyScherzinger** [comment]
Nope, DroneCI won't pick it up then :/

**Comment by tobiasKaminsky** [comment]
Ping me please once it happen again.
As drone is using .drone.yml from within the PR, it should work.

**Comment by AndyScherzinger** [comment]
Will do, thanks!

**Pull request closed without merging**
