### PR TITLE
Codacy: remove unused code

### PR DESCRIPTION
**Pull request by AndyScherzinger**
removing unused code to get rid of the last two remaining codacy issues for unused code.

@mario @tobiasKaminsky I didn't assign it to any milestone since I leave it to you to either merge it for 2.0.0 or postpone it to a future release. Since it is simply removing dead code it should imho be safe to merge at any time.

### CODE REVIEW

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky for review

**Comment by AndyScherzinger** [comment]
pinging @tobiasKaminsky for review :)

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
