### PR TITLE
check and show notification bell

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
For https://github.com/nextcloud/android/issues/13051

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
image

Click on it leads to known notification view.

**Comment by tobiasKaminsky** [comment]
I think with this approach we can remove the entry from drawer.

**Comment by tobiasKaminsky** [comment]
@alperozturk96 can you help me and try to change the hamburger icon to "back <-" icon?
I tried to use similar approach like SettingsActivity.

**Review by alperozturk96 — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
@alperozturk96 can you test it with a notification? :fearful:

**Comment by alperozturk96** [comment]
> 
> 
> @alperozturk96 can you test it with a notification? 😨


Seems like after shifting top layout, it's not looking good. I will check it today.

**Comment by alperozturk96** [comment]
@tobiasKaminsky Now, it should look good for both low-resolution and high-resolution devices, whether there is a notification present or not.


https://github.com/user-attachments/assets/255e8166-9af3-427e-b87c-9afb524911b5

https://github.com/user-attachments/assets/b18ed4b9-0b0a-41d6-8b2e-6a38a2cf13b5

**Pull request merged**
