### PR TITLE
Use same color detection as in server

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
https://github.com/nextcloud/server/pull/5953/files#diff-3de1769d04fcc4f13f8d546d9fbdac19

### CODE REVIEW

**Comment by nickvergessen** [comment]
Works, switches from black to white in my light green theming 👍

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger approve pls and merge.

**Comment by AndyScherzinger** [comment]
👍 fine by me!

**Pull request merged**
