### PR TITLE
Error image: color action bar again

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #812 

@AndyScherzinger can you help me here with the status bar, please :heart:

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
I'll see what I can do 👍

**Comment by AndyScherzinger** [comment]
Need to revert this PR I think. It messes up the Toolbar (turns it blue all the time also for images that work where it should be semi transparent...)

**Comment by AndyScherzinger** [comment]
Not sure why though...

**Comment by tobiasKaminsky** [comment]
Is this still valid anymore? I remember that there were changes recently...?

**Comment by AndyScherzinger** [comment]
Action bar doesn't need to be colored anymore due to the Hacktoberfest PR. At some point we should bring back the system bar imho. So yes, can be closed.

**Pull request closed without merging**
