### PR TITLE
3.3.0RC1

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Changes for 3.3.0RC1 release

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky maybe you can help, the script is failing during the build:
```
export BRANCH=$(scripts/analysis/getBranchName.sh $GIT_USERNAME $GIT_TOKEN $DRONE_PULL_REQUEST)
/bin/sh: 17: export: stable-3.3.x: bad variable name
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky Drone turned green now, while codacy doesn't work and can't analyze the PR (some hiccup again it seems)

**Comment by tobiasKaminsky** [comment]
:+1: 
So after merging this, we can continue pushing new stuff to master and only backport fixes to 3.3.x :tada:

**Comment by AndyScherzinger** [comment]
> So after merging this, we can continue pushing new stuff to master and only backport fixes to 3.3.x

excactly, except for cherry picking transifex pushes from master to stable (at least at the moment)

**Pull request merged**
