### PR TITLE
Enable coverage only in CI

### PR DESCRIPTION
**Pull request by Unpublished**
See https://jeroenmols.com/blog/2016/09/01/coveragecost/

This is just unnecessary for local builds.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
> Merging [#4068](https://codecov.io/gh/nextcloud/android/pull/4068?src=pr&el=desc) into [master](https://codecov.io/gh/nextcloud/android/commit/a42fd3b471d2e64816e62b30051d4fe2e78ae82c?src=pr&el=desc) will **decrease** coverage by `1.61%`.

I guess this means that coverage is also disabled on CI…
Let me have a look how to enable this on CI only.

**Comment by Unpublished** [comment]
> > Merging [#4068](https://codecov.io/gh/nextcloud/android/pull/4068?src=pr&el=desc) into [master](https://codecov.io/gh/nextcloud/android/commit/a42fd3b471d2e64816e62b30051d4fe2e78ae82c?src=pr&el=desc) will **decrease** coverage by `1.61%`.
> 
> I guess this means that coverage is also disabled on CI…
> Let me have a look how to enable this on CI only.

Now it is disabled...(createGplayDebugCoverageReport task cannot be found).

Let us re-run drone without your changes because these lines aren't covered in master as well. (https://codecov.io/gh/nextcloud/android/src/fcb5738a85b53b94ba77669df81a4c117d787ebc/src/main/java/com/owncloud/android/operations/GetUserProfileOperation.java)

**Comment by tobiasKaminsky** [comment]
> Now it is disabled...(createGplayDebugCoverageReport task cannot be found).

I guess that the flag must be available on each gradlew command.

**Comment by Unpublished** [comment]
Therefore I used the environment variable, so it is set in every command.

**Comment by tobiasKaminsky** [comment]
Right, I totally got the environment property wrong…

**Comment by Unpublished** [comment]
No worries, had to look it up at the gradle docs as well :D

Both PRs should be fine now :+1:

**Comment by tobiasKaminsky** [comment]
Thank you for your help :-)

**Pull request merged**
