### PR TITLE
remove all prebuilt jars

### PR DESCRIPTION
**Pull request by Bubu**
This will be required for fdroid when this is merged: https://gitlab.com/fdroid/fdroidserver/merge_requests/325

This gets rid of all prebuilt jars in the repo.

* libs/disklrucache-2.0.2.jar doesn't seem to be used anymore, app builds
  fine when removing it.
* libs/touch-image-view.jar is indeed required but is not anywhere available
  via gradle. So instead we include the source of this long unmaintained
  library directly.

It builds fine but I'm not sure if this repo structure is  prefered by you. There are of course a few different ways to sole this problem.

### CODE REVIEW

**Comment by Bubu** [comment]
One question: there is already `/third_parties/michaelOrtiz/TouchImageViewCustom.java` in the repo? Can this just be used by `ExtendedViewPager` so we don't need to include another copy of `TouchImageView`?

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you have a look at this? TouchImage I'd also say should be replaced anyways by the third_party classes already in the repo. As for the disk cache, I would have guess this is used by the image cache implementation (in places where we haven't yet moved on to glide).

**Comment by AndyScherzinger** [comment]
nevermind... the cache comes in via ```implementation 'com.jakewharton:disklrucache:2.0.2'```, and yes the other classes can/should be put into the codebase like done by @Bubu imho.

**Comment by AndyScherzinger** [comment]
All codacy issues to be ignored since this is c&p third party code we had in the code base via the jar before. I'll put these two classes on the ignore list once the PR got merged.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this PR will generate 3 new lint warnings due to the TouchImage implementation which I'd say we need to ignore (raise the lint score on master) for now and for a later release probably patch the thrid party (not maintained anymore) implementation. What do you think?

cc @mario

**Comment by Bubu** [comment]
@AndyScherzinger Thanks for looking at this. I noticed the docs in `THIRD_PARTY.txt` need an updated regarding the jar files. I'll see if I can come up with anything useful.

**Comment by AndyScherzinger** [comment]
@Bubu sounds great! Always a pleasure to help :)

**Comment by AndyScherzinger** [comment]
@Bubu is this PR mandatory for the 2.0.0 stable/final release? Just asking to know if it needs to be scheduled for 2.0.0

cc @mario @tobiasKaminsky

**Comment by mario** [comment]
Not really, no.

**Comment by Bubu** [comment]
@AndyScherzinger Not necessary for 2.0.0 I guess :-).

**Comment by AndyScherzinger** [comment]
@Bubu thanks for the update/info 👍

**Comment by Bubu** [comment]
Added a commit updating the THIRD_PARTY.txt file.

**Comment by AndyScherzinger** [comment]
Nice fix @Bubu! 
One thing since this PR "fixes" the referenced libs documentation. Should we add the missing libs here too? If so I can also take care of adding them, in case I have write permissions in your fork.

**Comment by Bubu** [comment]
@AndyScherzinger I just wanted to add that this is not up-to-date with the build.gradle file :-)

I think you can add to this PR ' Allow edits from maintainers. ' is checked

**Comment by AndyScherzinger** [comment]
Nice! Thanks @Bubu - I'll see that I add them this week

**Comment by AndyScherzinger** [comment]
@Bubu can you rebase to latest master please? Lint has a better score on master due to the latest merges which is why this build fails (code metrics FTW 😉)

**Comment by Bubu** [comment]
Done.

**Comment by tobiasKaminsky** [comment]
Great stuff :-)
I scheduled this for 2.0.1 to have focus on "only" bug fixing for 2.0.

**Comment by Bubu** [comment]
https://gitlab.com/fdroid/fdroidserver/merge_requests/325 has now been merged into fdroid master.

It will probably take a bit until deployed. Let's hope v2.0 can still slip through. ;-)

**Comment by Bubu** [comment]
Any news on this? :-)

**Comment by AndyScherzinger** [comment]
Can I rebase it (as in you are done and I take over) and review for merge :) If that is fine by you.

**Comment by AndyScherzinger** [comment]
❗️ rebase, waiting for the bots and their check results :)

**Comment by Bubu** [comment]
> Can I rebase it (as in you are done and I take over) and review for merge :) If that is fine by you.

Sure!

**Comment by AndyScherzinger** [comment]
pinging @mario @tobiasKaminsky for review :) Please ignore the codacy issues since they will be gone as soon as this is on master because then I can set the TouchImage classes to ignore since they are 3rd party sources of the removed jar (due to F-Droid rules). I also fixed some lint issues to get the score down again.

**Comment by tobiasKaminsky** [comment]
:+1:
Many thanks @Bubu 🎉

**Comment by mario** [comment]
👍

**Pull request merged**
