### PR TITLE
List bug fixes

### PR DESCRIPTION
**Pull request by MorrisJobke**
See #3199

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Sweet! @tobiasKaminsky usually we only list the "text" not any references to actual PRs. We could use this and for the store releases strip away that part since we only have 500 characters for store changelogs

**Comment by tobiasKaminsky** [comment]
Those individual PR description are in my opinion not needed in any release info.
I am more into linking the milestone within changelog, so that interested people can have a look.
(And yes, for next time we  (and most myself) should create a more meaningful changelog.
For 3.3.1 it could have been
Bugfix 
- fix crash on shared folder/file via Talk
- fix crash on Notification activity

**Comment by MorrisJobke** [comment]
> For 3.3.1 it could have been

Yes - then also do it, because there is nothing more useless than a release with "Bug fixes" as release notes. Only "we changed something" would be worse.

**Comment by tobiasKaminsky** [comment]
Are you fine with this? 
https://github.com/nextcloud/android/pull/3201

**Pull request closed without merging**
