### PR TITLE
Do Not Throw An Exception in SyncOperation

### PR DESCRIPTION
**Pull request by alperozturk96**
- [x] Tests written, or not not needed

I returned an ACCOUNT_EXCEPTION for testing purposes, and as can be seen in the video, only the capabilities cannot be updated.

https://github.com/user-attachments/assets/b279536f-6c9e-4dd5-8a32-30f4728b345a

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Accordin to exception message this is to prevent running a sync operation with a file data storage manager on a wrong/null account.
Have you tested such an operation?

**Comment by alperozturk96** [comment]
> Accordin to exception message this is to prevent running a sync operation with a file data storage manager on a wrong/null account. Have you tested such an operation?

I'm not sure what you mean. I tested switching accounts, and the correct FileDataStorageManager was used.

https://github.com/user-attachments/assets/5f045bfd-b981-4a88-a253-b3986b9ffbd4

**Comment by tobiasKaminsky** [comment]
The message you removed:
"Trying to execute a sync operation with a storage manager for an anonymous account"

So you have you tried it with a non-existing account, e.g. during first setup and when removing last account?

**Comment by alperozturk96** [comment]
> Accordin to exception message this is to prevent running a sync operation with a file data storage manager on a wrong/null account. Have you tested such an operation?

I logged in and removed the same account. After pressing the back button, the login screen appeared again. Later, I logged in with the same account and created a folder with two files in it. I did not encounter any problems.

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
