### PR TITLE
Fix registration of second account on first run

### LINKED ISSUE #4234: Adding an account results the first account disappearing
### Actual behaviour

I logged in, and from the left sidebar added an account by clicking the id and selecting "Lisää tili" ("Add account" in Finnish). After logging in, I only see the recently added account and the first one seems to have gotten forgotten entirely. I don't see it in "Tilien hallinta" ("Credential/account" manager?).

### Expected behaviour

- I expected I could switch between my two accounts (and when I logged into a third one) from the sidebar on the left.
 
### Steps to reproduce

1. Install Nextcloud and login to get to the main screen 
2. Select "Lisää tunnus" (Add account) from the sidebar on the left
3. Login
4. The first account disappears from the left sidebar.

### Environment data

Android version: Android 9 Go Edition (2019-06-05 security patches)

Device model: Nokia 1 TA-1047

Stock or customized system: stock

Nextcloud app version: 3.7.0 from Play Store

Nextcloud server version: I don't know either

### Logs

I don't think I have access to them on either instance.

### LINKED ISSUE #4529: Accounts added by token does not work
### Actual behaviour
I tried to add my 3 Nextcloud accounts using an app token to the client.
1. Added first account by token. App reloaded, I had to enter it again. Then it worked.
2. Added first account by token. App reloaded, I had to enter it again. Then it worked., but first account is gone.
3. Added third account by token. App reloaded, I had to enter it again. Then it worked., but also second account is gone.
-> only the last added account is now in the app

### Expected behaviour
Three accounts added by token.
 
### Steps to reproduce
Don't know. Try to add 3 accounts by token to a fresh installed Nextcloud client.

### Environment data
Android version: 9

Device model: OnePlus 7 Pro

Stock or customized system: Oxygen OS

Nextcloud app version: 3.8.0

Nextcloud server version: 3 different Nextcloud server. Don't know the version.

#### Web server error log
Don't have any logs.

#### Nextcloud log (data/nextcloud.log)
Can not find a `nextcloud.log` file on my device.

### PR DESCRIPTION
**Pull request by ezaquarii**
Fixes #4234
Fixes #4529

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### CODE REVIEW

**Comment by ezaquarii** [comment]
@tobiasKaminsky @AndyScherzinger IMO this should be backported to 3.8 asap.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you give it a spin? I tagged it for the backport bot already 👍

**Comment by tobiasKaminsky** [comment]
Can you explain the changes to me? I am fairly new to Kotlin. ;-)

adding private val means that we now have a new property/variable in class OnboardingServiceImpl instead of using the referenced accountProvider directly?

Specifying getter explicitly means that the "currenAccount == null" check is done when getting isFirstRun?
Previously this was computed on class creation and never changed, right?

**Pull request merged**
