### PR TITLE
Add monochrome icon

### PR DESCRIPTION
**Pull request by Sandelinos**
Added monochrome icon for Android 13 "Themed icons" support.

Signed-off-by: Sandelinos <3103376-Sandelinos@users.noreply.gitlab.com>

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Can you post a screenshot of this running?
I could imagine that only having the foreground (circles) is a bit less, and we would need kind of background?

**Comment by tobiasKaminsky** [comment]
image

Looks good, I think

**Review by jancborchardt — APPROVED** [review]
Yep looks great, thanks for the contribution @Sandelinos! :)

**Comment by tobiasKaminsky** [comment]
Thanks @Sandelinos :tada: :tada: :tada: :tada:

**Pull request merged**
