### PR TITLE
Backport mail share creation

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Backport of #2700 (create an email share)

Backport tested sucessfully

cc @tobiasKaminsky @mario for review

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky Tried close/reopen but for some reason DroneCI doesn't detect this PR and thus doesn't trigger a build :(

**Comment by tobiasKaminsky** [comment]
I re-checked every settings and they seem ok, @MorrisJobke?

**Comment by MorrisJobke** [comment]
The CI job itself ran fine: https://drone.nextcloud.com/nextcloud/android/5122

Let me retrigger it on CI - the status will update once it's done.

**Comment by tobiasKaminsky** [comment]
I removed "backport-request" as this label is for those PRs, that need to be backported.
For this one it is totally fine to add it to the milestone and to the release overview, as you already did :-)

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
