### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by ogasser**
Don't forget to update the changelog when doing a new release.
Otherwise the changelog link in f-droid does not show you the features for the new release.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@LukasReschke can you give this one a :+1: :)

**Comment by LukasReschke** [comment]
LGTM

**Pull request merged**
