### PR TITLE
PassCodeManager cleanup

### PR DESCRIPTION
**Pull request by ardevd**
Just a quick cleanup of the PassCodeManager class. Simplified some hard-to-read if-statements and adjusted a couple variable access declarations.

### CODE REVIEW

**Comment by mario** [comment]
Cool, but since we're cleaning up let's remove the "s" and "m" :)

**Comment by ardevd** [comment]
@mario I agree, they are annoyingly similar. I pushed a proposed simplification that looks a lot more readable imo.

**Comment by mario** [comment]
@ardevd good, with one change:
hasAuthenticationTimeoutExpired() && passCodeIsEnabled());  

->

 passCodeIsEnabled() && hasAuthenticationTimeoutExpired()

Same with fingerprint.

**Comment by ardevd** [comment]
@mario cool!

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
:+1: and can be merged while this will be replaced by #1657 in the future I guess :)

**Comment by AndyScherzinger** [comment]
:1st_place_medal: merged :heart: 

Thanks @ardevd :heart:

**Pull request merged**
