### PR TITLE
Privacy webview

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
added privacy webview
restructured setup.xml
adapted modified/setup.xml to general/setup.xml

Webpage enhancement is in: https://github.com/nextcloud/nextcloud.com/issues/465

### CODE REVIEW

**Comment by mario** [comment]
What is privacy webview and who requested it?

**Comment by tobiasKaminsky** [comment]
Google requires nearly all apps to have this. 
It needs to be set in play store (we have this already) and it must be in the app, either as link  or something like that. 
But as we already have this fancy web view, I used it ;-)

**Comment by mario** [comment]
@tobiasKaminsky can you link me up please?

**Comment by tobiasKaminsky** [comment]
You man where the need is explained? http://www.iubenda.com/blog/privacy-policy-for-android-app/

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
👍

**Pull request merged**
