### PR TITLE
Move account choice from startup to menu item. Add subtitle for account name

### LINKED ISSUE #344: Uploader: don’t make the account choice a blocking popup
I have 2 accounts configured in my Nextcloud mobile app. There is a blocking account chooser popup every time I want to upload something.

This isn’t great beacuse most of the time I use my personal instead of my company account anyway. So:
- we should directly show the file list, defaulting to the account last used
- put a switcher dropdown in the top bar

Ok @tobiasKaminsky @AndyScherzinger? (As already discussed in the old repo ;)

### PR DESCRIPTION
**Pull request by esafirm**
resolves #344

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@esafirm can you rebase to latest master please (should fix the failing CI build)? ❤️

**Comment by AndyScherzinger** [comment]
👍 reviewed and tested successfully
device-2017-10-18-210647

**Comment by AndyScherzinger** [comment]
@esafirm beware that I rebased your branch so you need to clone the repo again for a local copy

**Comment by AndyScherzinger** [comment]
pinging @mario for a review

**Comment by AndyScherzinger** [comment]
@esafirm I also changed the license header to Nextcloud and to AGPL3+ https://github.com/nextcloud/android/pull/1684/commits/ece81e22776285ca5b633ac74730f573a70c5d37 Hope that is fine with you since all contributions to the Nextcloud Android app are added under AGPL3+

**Comment by mario** [comment]
👍  if @esafirm confirms AGPL3 thing.

**Comment by AndyScherzinger** [comment]
@esafirm can you please confirm that you are fine with AGPL3+ licensing?

**Comment by jancborchardt** [comment]
Just to confirm:
- When there is only one account, there is no subtitle needed.
- How to change the account? In the 3-dot-menu would probably be best, but additionally if it's possible to invoke by clicking on the header that would be a great enhancement. :)

**Comment by esafirm** [comment]
@AndyScherzinger @mario I have no problem with AGPL3+ licensing 👍 
And thanks for fixing all that stuff!

**Comment by AndyScherzinger** [comment]
@jancborchardt header click can probably be implemented via a new PR. 
@esafirm would you like to tackle that issue too?

**Comment by jancborchardt** [comment]
Cool, sounds good @esafirm! Good contribution which will make the default flow much nicer! :)

(The account chosen by default will be the currently active one in the app, I assume. :)

**Comment by AndyScherzinger** [comment]
> The account chosen by default will be the currently active one in the app, I assume. :)

That is correct, while like before this PR choosing another account will make the choice the currently active one. If this is to be changed it should be done via an follow up issue + PR.

**Comment by esafirm** [comment]
@AndyScherzinger sure thing 😁 

Is it like this? 

screen shot 2017-10-19 at 6 34 36 pm

Should i create the issue?

**Comment by xXSTrikeXx** [comment]
I think it will fixes this, too:
#79

**Comment by AndyScherzinger** [comment]
@esafirm yes, a spinner is probably the easiest way to do this while it should then still be title+subtitle :)

**Comment by AndyScherzinger** [comment]
🎉 merged! Thanks for this nice contribution! 🥇 
Looking forward to the next contributions 😃

**Pull request merged**
