### PR TITLE
Update screenshot test results for E2E strings

### PR DESCRIPTION
**Pull request by AndyScherzinger**
follow-up for #11097

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@AlvaroBrey see #11097 all backports failed

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey see #11097 all backports failed

commented there, the strings are not present in 3.22 or 3.23 so that's normal I think

**Review by AlvaroBrey — APPROVED** [review]
Beat me to it!

**Comment by AndyScherzinger** [comment]
> Beat me to it!

Not a competition :) ❤️

**Pull request merged**
