### PR TITLE
Fix crashes when receiving external files and last upload folder was deleted

### LINKED ISSUE #11207: Crash when sharing to Nextcloud from other app, and the last used folder does not exist anymore
### Cause of error

Not reproducible but some facts about what happened:

- Nextcloud Android srt up with 3 accounts
- Downloaded a PDF file, opened the file in a PDF viewer
- Pressed "Share", Nextcloud Files app opemed with location chooser
- Pressed "Up" multiple times quickly because the location chooser was in a wrong directory
- Crash

```java
Exception in thread "Thread-435" java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.owncloud.android.datamodel.OCFile.getRemotePath()' on a null object reference
    at com.owncloud.android.operations.RefreshFolderOperation.run(RefreshFolderOperation.java:229)
    at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:399)
    at java.lang.Thread.run(Thread.java:920)

```

### App information
* ID: `com.nextcloud.client`
* Version: `30230190`
* Build flavor: `generic`

### Device information
* Brand: `Xiaomi`
* Device: `beryllium`
* Model: `POCO F1`
* Id: `SQ3A.220705.004`
* Product: `beryllium`

### Firmware
* SDK: `32`
* Release: `12`
* Incremental: `6f4e1ac54a`

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Fixes #11207

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@AlvaroBrey many thanks for helping here again :)

Shall I rebase it? Seems there is a bit of problem right now.

**Comment by AlvaroBrey** [comment]
> Shall I rebase it? Seems there is a bit of problem right now.

Go ahead! I tried autorebasing and failed

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Thanks @AlvaroBrey 🤩

**Pull request merged**
