### PR TITLE
[WIP] Extend instant upload

### PR DESCRIPTION
**Pull request by AndyScherzinger**
This allows to choose any folder on the phone to sync in one direction to owncloud, just like the instant upload does this for images.
This can fix the problem of not using the correct ```NEW_PHOTO``` Action and it can also help to "backup" important folders (like WhatsApp Images).
__________________
Original discussion can be found in oC 1650

PR has been created by @tobiasKaminsky

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @tobiasKaminsky 
I revived the branch: just rebased to master, fixed the conflicts to my best knowledge and did some very minor polishing on the UI part for now. :smiley: 
Still from my understanding some work to be done here and probably some discussion on how this works / should work in the context of multi accounts.

**Comment by AndyScherzinger** [comment]
cc @nextcloud/android - reviving another branch for improving instant uploads (this is a work in progress PR though!)

**Comment by tobiasKaminsky** [comment]
Tricky one as the whole instant upload have to be changed for android N.
So, I want to postpone it to the conference where we can brainstorm a whole new concept for it.

**Comment by tobiasKaminsky** [comment]
Closing as we will soon have a better approach.

**Pull request closed without merging**
