### PR TITLE
Change icon according to dark mode

### LINKED ISSUE #7656: Invisible icon in an energy saving message
### Steps to reproduce

1. Launch the app.
2. Set a dark theme.
3. Select `Auto upload` from the menu.
4. Select a directory to auto upload photos.

### Expected behaviour
Visible icon in the message that power saving is disabled for a dark theme.

### Actual behaviour
Invisible icon in power saving message for dark theme.

Dark Theme:
obraz

Light theme:
obraz

### Environment data
Android version: 10

Nextcloud app version: 3.14.1

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #7656 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the "better" way would be to add the corresponding icon in the drawable-night folder ;) day/night should use the matching resource folders not tint black/white images

**Review by AndyScherzinger — CHANGES_REQUESTED** [review]
see comment add dark/light image variants

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger test is not working correctly, as it does not screenshot the dialog, but only the underlying activity.

I did not yet found a way to correctly screenshot an AlertDialog.

**Comment by AndyScherzinger** [comment]
> @AndyScherzinger test is not working correctly, as it does not screenshot the dialog, but only the underlying activity.

> I did not yet found a way to correctly screenshot an AlertDialog.

@tobiasKaminsky I know, so should we then drop the test and merge? I guess this is the best option atm.

**Pull request merged**
