### PR TITLE
test for #5039

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
#5039

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

### CODE REVIEW

**Comment by AndoKarim** [comment]
APK not available. 
Tried to redo a PR to trigger android-bot #7625 but it didn't.

**Comment by AndyScherzinger** [comment]
@AndoKarim I just did a rebase, so here is the latest APK based on this PR: https://github.com/nextcloud/android/pull/7504#issuecomment-740157563

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I think this PR is obsolete and has been replaced by: #7694 and #7691

**Comment by AndyScherzinger** [comment]
Fixed on master already and shipped so closing since 3.14. is obsolete

**Pull request closed without merging**
