### PR TITLE
Use M3 for CreateFolderDialog

### PR DESCRIPTION
**Pull request by alperozturk96**
Before:

create_folder_before

After: 

create_folder_after

- [ Done ] Tests written, or not not needed

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]
looks good, tested on all OS themes 👍

**Review by tobiasKaminsky — APPROVED** [review]
:+1: let's wait for screenshot test

**Comment by alperozturk96** [comment]
Screenshots are updated

**Comment by tobiasKaminsky** [comment]
Rebase did not worked due to conflict, you need to do it manually.

**Comment by alperozturk96** [comment]
@tobiasKaminsky I did it manually but there are some inconsistencies in the screenshots tests. Could you check it and maybe create another PR to fix them?

**Pull request merged**
