### PR TITLE
Fix some crashes and weird behaviours when clearing data

### LINKED ISSUE #8985: Android: Clear storage crashes app
************ CAUSE OF ERROR ************

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:890)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1806)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1752)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:650)
	at com.owncloud.android.providers.FileContentProvider.update(FileContentProvider.java:632)
	at android.content.ContentProvider.update(ContentProvider.java:1830)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:457)
	at android.content.ContentResolver.update(ContentResolver.java:2381)
	at android.content.ContentResolver.update(ContentResolver.java:2343)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUpload(UploadsStorageManager.java:132)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadInternal(UploadsStorageManager.java:174)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateUploadStatus(UploadsStorageManager.java:209)
	at com.owncloud.android.datamodel.UploadsStorageManager.updateDatabaseUploadResult(UploadsStorageManager.java:580)
	at com.owncloud.android.files.services.FileUploader.uploadFile(FileUploader.java:661)
	at com.owncloud.android.files.services.FileUploader$ServiceHandler.handleMessage(FileUploader.java:1402)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: Redmi
Device: begonia
Model: Redmi Note 8 Pro
Id: RP1A.200720.011
Product: begonia_eea

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: V12.5.2.0.RGGEUXM

### PR DESCRIPTION
**Pull request by AlvaroBrey**
Note: to see the actual changes look at the list of commits, as the class has been converted to Kotlin

 - Remove user accounts when clearing data
 - Kill the app after clearing data
 - Convert class to kotlin since we're already modifying it

Fixes #8985 

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Purpose of this whole custom manage space thing was to preserve every user/settings, but only remove local files.
With removing account it is now the same like uninstall and re-install it, right?

**Comment by AlvaroBrey** [comment]
> Purpose of this whole custom manage space thing was to preserve every user/settings, but only remove local files. With removing account it is now the same like uninstall and re-install it, right?

The manage space message says the opposite of that: 

Screenshot_20220126-155303_Nextcloud

This implies that everything is deleted _except_ files, unless I'm understanding it wrong

**Comment by tobiasKaminsky** [comment]
> This implies that everything is deleted _except_ files, unless I'm understanding it wrong

Oh boy… I just remembered it the other way around and was too lazy to check. Sorry!

Then I am fine, of course 👍

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
