### PR TITLE
Enhance activity list design

### LINKED ISSUE #1639: Activity section design details
Currently the Activity section looks like this:
screenshot_2017-10-03-19-25-35

To make it look more in line with the Nextcloud style, here’s some detail fixes:
- [x] The big headings should not repeat the small detail timestamp. The first one is »Today« (if any), followed by »Yesterday« (if any), followed by the date like »Saturday, October 7«, then »Friday, October 6« etc and so on (also include the year as soon as the event history goes to last year)
- [x] The links should have no underline, bolding is enough
- [x] The link color can be black instead of the Nextcloud blue / primary color as it looks quite out of place. What do you think @nextcloud/android?
- [x] In the web interface we have 50% opacity on all of the action icons on the left since they are a bit too overpowering otherwise.
- [ ] Of course it would be great to have avatars of the other people in this view left next to their name. :)

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
fixes #1639

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
All solved, as you wished, master of design ;-)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @jancborchardt looks good to me, looking at the web UI though the items' date info is relative dates, so that part should be changed/reverted or will this change on the server with Nc13?

**Comment by jancborchardt** [comment]
True, good catch. The small info should be relative, otherwise it's just repeating the header.

Or alternatively, since even that additional info is a bit useless/duplicate, how about we show the timestamp `hh:mm` (no seconds) there? That would give good context and show what we can show on hover in the web interface.

**Comment by AndyScherzinger** [comment]
👍 fine by me

**Comment by jancborchardt** [comment]
Lovely, @tobiasKaminsky, no further remarks. ;) :+1:

**Comment by AndyScherzinger** [comment]
@mario please review :) I'll take care of rebase/drone etc... 🚀

**Comment by AndyScherzinger** [comment]
pinging @mario for review :)

**Comment by mario** [comment]
👍 
Rebase.

**Comment by AndyScherzinger** [comment]
@ldmpub the issue you reported to oC (but is Nc) has been fexied already and will ship with the next stable release :)

**Comment by ldmpub** [comment]
@AndyScherzinger many thanks for your assistance to find the good direction!

**Comment by AndyScherzinger** [comment]
Happy to help @ldmpub :)

**Comment by mario** [comment]
@AndyScherzinger what's up with this PR?

**Comment by AndyScherzinger** [comment]
@mario nothing... @ldmpub just reported the issue resolved by this PR to the oC issue tracker, so I referenced his nick in this PR to make him aware that we already fixed it for the next release. :)

**Pull request merged**
