### PR TITLE
Further lint fixes

### PR DESCRIPTION
**Pull request by tobiasKaminsky**

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky anything else to be done here, or is this ready to review?

**Comment by tobiasKaminsky** [comment]
Please wait, I wanted to wait for feedback on the last remaining transifex error.
If this cannot be solved, then I will exclude the lint check.
In either cays then we have 0 errors on lint.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky the ruby script seems to be running into trouble again...

```
BUILD SUCCESSFUL in 14m 30s
86 actionable tasks: 86 executed
scripts/lint/lint-up.rb:76:in `block (2 levels) in <main>': invalid byte sequence in US-ASCII (ArgumentError)
	from scripts/lint/lint-up.rb:76:in `each'
	from scripts/lint/lint-up.rb:76:in `find'
	from scripts/lint/lint-up.rb:76:in `block in <main>'
	from scripts/lint/lint-up.rb:75:in `open'
from scripts/lint/lint-up.rb:75:in `<main>'
```

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky follow up error:
```
BUILD SUCCESSFUL in 8m 13s
86 actionable tasks: 86 executed
scripts/lint/lint-up.rb:83:in `<main>': undefined method `match' for nil:NilClass (NoMethodError)
```

**Comment by tobiasKaminsky** [comment]
Label "1. Developing" means that I am working on it and I am aware of this ;-) ;-)
The problem is that the regex is searching for "errors" and with cannot cope with "1 error"

**Comment by AndyScherzinger** [comment]
Didn't want to be pushy, just saw the broken build and c&p'ed the info :)

**Comment by AndyScherzinger** [comment]
can we please use rebase 💘 

😉

**Comment by mario** [comment]
And I hope we can merge this today :P

**Comment by tobiasKaminsky** [comment]
I got feedback from transifex.
It is indeed a problem on their side: they only support 3 instead of 4 plurals in ukrainian.
So I would like to keep the remaining 1 error to remind us that there will sooner or later be an upgrade by transifex.

**Comment by tobiasKaminsky** [comment]
On https://github.com/nextcloud/android/pull/1284/commits/c9af721aa6fc8b08d6fe89cc25e1b866ab636a26 we already had only 1 error remaining.
Why are there now 2...?

**Comment by AndyScherzinger** [comment]
Strange.... Can you run it locally to see the 2 errors. This can be done within AS

**Comment by AndyScherzinger** [comment]
Now the build should turn really green 😆

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger let's see if this helps *finger-crossing*

**Comment by tobiasKaminsky** [comment]
Yeaaaah :-D

**Comment by AndyScherzinger** [comment]
👍 pinging @mario

**Comment by AndyScherzinger** [comment]
Nice fix @tobiasKaminsky

**Comment by mario** [comment]
👍

**Pull request merged**
