### PR TITLE
Shows favorite state in share overview

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Uses: https://github.com/nextcloud/android-library/pull/968

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Hm. there is something not compiling.
Let me check that.

**Comment by tobiasKaminsky** [comment]
Seems that rebase of library was a bit too late

**Review by AlvaroBrey — APPROVED** [review]

**Pull request merged**
