### PR TITLE
Basic kotlin

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
@Doomsdayrs I found this stale branch without any PR, therefore I created one to ask what the status/purpose is :)

- [ ] Tests written, or not not needed

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
I do not know who you are, how this is on the main repository, or what I was doing last year

**Comment by tobiasKaminsky** [comment]
🙈 Then I guess it is fine to close this branch/PR.

**Comment by Doomsdayrs** [comment]
No seriously why is this on the main repo?

**Comment by AlvaroBrey** [comment]
> No seriously why is this on the main repo?

Looks like this branch comes from https://github.com/nextcloud/android/pull/7767

Guessing someone copied it over to the main repo for some testing/CI and then forgot about it.

**Pull request closed without merging**
