### PR TITLE
3.8.1 release notes

### PR DESCRIPTION
**Pull request by AndyScherzinger**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Nice!
I should really automate this.

**Comment by tobiasKaminsky** [comment]
Do you think it is really needed to have it also in stable-3.8 branch?
There we have the changelogs

**Comment by AndyScherzinger** [comment]
> Do you think it is really needed to have it also in stable-3.8 branch?

Not mandatory I guess, but still nice in case someone is looking at the stable branch

> I should really automate this.

Sure, but please do it after thet Hacktoberfest 😉

**Comment by tobiasKaminsky** [comment]
I will merge this as soon as 3.8.1 is released

**Pull request merged**
