### PR TITLE
Resize log-in input fields so they don't span 100% width

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>

as a follow-up to the latest changes discussed on the android-talk client

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Review by tobiasKaminsky — APPROVED** [review]
👏 for tests :+1:

**Comment by tobiasKaminsky** [comment]
https://www.kaminsky.me/nc-dev/android-integrationTests/7994-Screenshot-White-Light-17-13/images/com.nextcloud.client.AuthenticatorActivityIT_loginLandscape_light_white.png

This should then also be white input text, or?

**Comment by AndyScherzinger** [comment]
> This should then also be white input text, or?

Yes, just pushed the missing change 👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky fixed: https://www.kaminsky.me/nc-dev/android-integrationTests/7994-Screenshot-Blue-Dark-08-59/images/com.nextcloud.client.AuthenticatorActivityIT_login_dark_blue.png

**Pull request merged**
