### PR TITLE
Photos -> Media/Gallery

### LINKED ISSUE #6795: Show videos in Photos View
### Is your feature request related to a problem? Please describe.
The new Photo View looks very nice, it would be awesome if videos show up there, too. Like in the photos app in the browser.

### Describe alternatives you've considered
Open the activity tab, look if someone uploads a video
Open nextcloud in the mobile browser an navigate to the photo app

### Additional context
Is this hard todo? If not, maybe I can try to do this?

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #6795 

removed outdated search enums
changed photos -> media/gallery

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by jakobroehrl** [comment]
This should fix https://github.com/nextcloud/android/issues/1269, too

**Review by AndyScherzinger — APPROVED** [review]

**Comment by jakobroehrl** [comment]
@tobiasKaminsky 
Tested this version and I see the media section. But there are only videos shown, no photos. 
Could you show videos and photos in the media section?

**Comment by tobiasKaminsky** [comment]
> But there are only videos shown, no photos.

🙈🙈🙈 This should not be the case…

**Comment by jakobroehrl** [comment]
Tested on try.nextcloud.com there it's working. So it seams to be a problem on my side. 
I think we could merge and do some beta tests. 
What do you think?

**Comment by jakobroehrl** [comment]
It's working. 
But I see older pics. Mybe it's only on my setup.
How should it be sorted?

**Comment by axheli** [comment]
was doing some testing and this seems to work a lot better with loading the media and photos. Looks like this might fix #7182

**Comment by axheli** [comment]
only thing i noticed was when view the photos from the folders they load correctly. If you go under the media tab they dont load in the correct order maybe add an option to sort by and it only load 133 photos and then it dosent update

**Review by AndyScherzinger — APPROVED** [review]

**Comment by axheli** [comment]
@tobiasKaminsky when clicking the media tab it only populates 134 photos and they are not categorize properly

**Comment by AndyScherzinger** [comment]
@axheli does it load the next bunch of files when you scroll to the bottom and can you elaborate what you want by categorization? (we just show whatever the server returns)

**Comment by axheli** [comment]
@AndyScherzinger it will not load more when I go to the bottom it only loads 134 and under the media tab there's no option to categorize by date etc under the file tab ive already seclcted by newest first

**Comment by AndyScherzinger** [comment]
@axheli Thanks for the info. Could you maybe open a new issue referencing this PR? That would be great ❤️

**Comment by axheli** [comment]
@AndyScherzinger You're Welcome! just created the ticket ❤️

**Pull request merged**
