### PR TITLE
Add whats new screen for version 2.0.0

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
On upgrade:

On first run: (changed wording from instant upload to auto upload)

Do we want to add another slide for 1.5?
Big features that are not immediately visible are in my opinion:
- search
- contact backup

### CODE REVIEW

**Comment by mario** [comment]
Well, Photo & Video folders are instant on Android 7+ with the new code. Custom folders are not however.

**Comment by tobiasKaminsky** [comment]
I thought about how to explain this on a more generic level and came to the conclusion to "lower" the expectation from "instant" to "it may take some time, but it is reliable"...

But it is only a first suggestion..

**Comment by mario** [comment]
Yup, it's good to downplay advantages :P

Except "What's new in 1.5" is just strangely aligned, but otherwise ok.

**Comment by mario** [comment]
Also are we only going to show this 1 screen on upgrade?

**Comment by tobiasKaminsky** [comment]
> Also are we only going to show this 1 screen on upgrade?

in first post I asked this question also:

>  Do we want to add another slide for 1.5?
>Big features that are not immediately visible are in my opinion:
> - search
> - contact backup

At least 3 items, max 5, I would say.

**Comment by AndyScherzinger** [comment]
For What's new I'd say we just mention the new auto upload enhancement and leave the 3 for the initial introduction. So I am fine as is content-wise but also think the headline is a bit strange. Since everything is centered I'd say the headline should also be centered :)

**Comment by tobiasKaminsky** [comment]
-> 

I think for such a big release two more slides would be really cool.
Especially promoting the search feature is worth it.

**Comment by mario** [comment]
I'm fine with adding search. But mention it's 12+.

**Comment by tobiasKaminsky** [comment]
I will later add some new slides, but currently my inkscape is broken :-/

**Comment by mario** [comment]
Possible further options:

- Search (for NC12+)
- Favorites (same, NC12+)
- Fingerprint security
- Push notifications !!! (NC12+)

**Comment by AndyScherzinger** [comment]
I'd say leave out push notifications since they aren't available on non GPlay releases but would then still be shown on these installations.

**Comment by mario** [comment]
@AndyScherzinger you can do IFs based on the flavour ;) But you guys decide, do it and merge!

**Comment by tobiasKaminsky** [comment]
My ideas...I am not a real pro at graphics, so feedback is always welcome, also on the text.

**Comment by mario** [comment]
"Not only in current folder" -> "Across entire account"
"Use color to distinguish accounts" -> "Use color to distinguish between accounts"

**Comment by mario** [comment]
Let me know when this is corrected and can be merged!

**Comment by AndyScherzinger** [comment]
* Search: Show listing in large without the phone (which was used to illustrate the camera for auto upload)
* Notification: mix it with activity icon (flash)

other than that it is fine.

@mario beware that this can only be merged to the changelog branch (as configured in this PR) and that the changelog branch cannot be merged before final release since it bumps the version to FINAL.

**Comment by mario** [comment]
@AndyScherzinger that's fine. Are we only missing lint branch for RC? What else is missing for RC? (Manifest changes?)

**Comment by AndyScherzinger** [comment]
It's the lint branch*s*, the lib update and version bump.

I'll pipng you on all PRs as soon as the have gone through droneCI 🚀

**Comment by tobiasKaminsky** [comment]
> beware that this can only be merged to the changelog branch (as configured in this PR)

You can easily rebranch if you click on "edit" (where you can change the title of the PR).

**Comment by AndyScherzinger** [comment]
> You can easily rebranch if you click on "edit" (where you can change the title of the PR).

My point was rather "only allowed to be merged to the changelog branch because else you would bump zhe master to the final version (manifest wise). 😉

**Comment by jasonbayton** [comment]
I can make some more wording suggestions later - can see some potential improvements but stuck on mobile in a bus atm

**Comment by tobiasKaminsky** [comment]
Thanks @jasonbayton, I changed the wording

**Comment by AndyScherzinger** [comment]
👍 fine by me

**Comment by tobiasKaminsky** [comment]
For translation via transifex we need to get this soon into master:
- using versionCode instead of string
- changed branch that it is mergeable into master

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I'll rebase it and merge it to the changelog branch. AS seen in the commits this branch isn't mergeable to master since it is based on changelog, not on master...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky whatever happened this branch is now a rebase hell!!! :/

**Comment by tobiasKaminsky** [comment]
Closing in favor of #1363

**Pull request closed without merging**
