### PR TITLE
refactor(ui): coroutine based user status retrieval.

### PR DESCRIPTION
**Pull request by ardevd**
Replaced ancient async task with a coroutine based alternative. This comes with numerous advantages.

- Improved performance due to the nature of coroutines and the reduced overhead associated with AsyncTasks and threads. Approx a %50 performance increase was measured during testing.
- Passing references to fragment lifecycle context to an AsyncTask is generally a bad idea.
- Improved decoupling of UI and backend logic.
- Less boilerplate code.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @ardevd - long time no see 😃 
Hope you have been good!

PR looks good to me, just one minor thing regarding the template license header, else 👍

**Comment by ardevd** [comment]
@AndyScherzinger glad to see you're still around :) Fixed the license header now, I think.

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Yes I am - Also happy to keep being around while I don't have much time these days for coding work :/
Hence looped in Tobias and Alper

**Review by tobiasKaminsky — APPROVED** [review]

**Review by alperozturk96 — APPROVED** [review]
Tested working. Thank you 💯

**Pull request merged**
