### PR TITLE
Grid view: default to 4 columns

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: https://github.com/nextcloud/android/issues/1081#issuecomment-331407930

### CODE REVIEW

**Comment by mario** [comment]
Didn't @AndyScherzinger say we want 4 columns? :)

**Comment by AndyScherzinger** [comment]
Yes, but I did this 26 minutes _after_ this PR was created 😁

**Comment by mario** [comment]
OK, can we change this to 4 columns then? :D

**Comment by AndyScherzinger** [comment]
:+1: nice!

**Comment by mario** [comment]
👍

**Pull request merged**
