### PR TITLE
Add proper error message to user info screen

### LINKED ISSUE #1540: User information screen issues
screen shot 2017-09-05 at 10 04 15

Why would I ever have this shown is beyond me o.o So please make it look nicer :P

### PR DESCRIPTION
**Pull request by AndyScherzinger**
resolves #1540 adding a proper error message

before:
screen shot 2017-09-05 at 10 04 15

after:
device-2017-09-13-183054

cc: @mario @tobiasKaminsky for review/merge - The detail message can't be changed that easily since thins is what we get from out lib-project and I'd vote for keeping it this way, at least until my error feedback PR has been merged. After that we can go for nicer, mapped http error messages (to some extend).

### CODE REVIEW

**Comment by mario** [comment]
Shouldn't R.drawable.ic_list_empty_error be tinted?

**Comment by AndyScherzinger** [comment]
> Shouldn't R.drawable.ic_list_empty_error be tinted?
Afaik no, only folder icons should be tinted from what I understood from @jancborchardt. Maybe Jan can re-confirm this :)

**Comment by AndyScherzinger** [comment]
@jancborchardt / @nextcloud/designers can you approve (:+1:) the UI change? Point of discussion was if the icon should be tinted blue, imho no since only the folder icon is blue-ish...

**Comment by tobiasKaminsky** [comment]
:+1: 
If I remember correctly only folders and fav icon (star) is colored.

**Comment by MorrisJobke** [comment]
I like the design 👍  And yes, only folder icon should be tinted.

**Comment by AndyScherzinger** [comment]
Merging since we have the designer's approval 🚀

**Comment by jancborchardt** [comment]
Yup, confirming what @MorrisJobke said :)

**Comment by jancborchardt** [comment]
I would even remove the http status code info. It’s really  technical information and not helpful to users. Rather there should be a retry button (like on every error view).

**Comment by AndyScherzinger** [comment]
@jancborchardt do you have a screenshot for me (I guess webUI) since the Android client doesn't have any retry buttons (yet)? :)

**Comment by jancborchardt** [comment]
@AndyScherzinger actually we don’t have that anywhere yet – it is planned in the Mail app only https://github.com/nextcloud/mail/issues/314 :)

It would be a nice new enhancement. Simply a centered button below the text saying »Retry« and using ic_refresh as icon: https://material.io/icons/#ic_refresh

**Pull request merged**
