### PR TITLE
Remove locking

### PR DESCRIPTION
**Pull request by mario**
Removes powerlocks on platforms where we can use jobscheduler.
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
@tobiasKaminsky  here we go.

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
Merge @AndyScherzinger ?

**Comment by AndyScherzinger** [comment]
@mario jupp, just did the merge :+1:

**Pull request merged**
