### PR TITLE
Avatar cache

### PR DESCRIPTION
**Pull request by mario**
This is a temporary solution to improve how we handle avatars. Basically, it'll refresh them every 24 hours if you are in the app.

Long term solution - etags! yay!

Untested did not even compile, but I trust it works :P

If there are Codacy complaints (I already see one, but it complains without a reason *shrug*), please fix it.
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Nice @mario , 24h cache :)

 Hope to find the time to check it out tomorrow.

**Comment by AndyScherzinger** [comment]
Installed the branch and changed the avatar. Let's see what happens tomorrow night :)

**Comment by mario** [comment]
@AndyScherzinger why didn't you just modify the branch to refresh cache every 2 minutes? xD

**Comment by AndyScherzinger** [comment]
Ah, just did, nice idea!
Unfortunately I doesn't work

```(avatarTimestamp = arbitraryDataProvider.getLongValue(account, AVATAR_TIMESTAMP)) != -1``` is always ```false```

**Comment by AndyScherzinger** [comment]
So the avatar doesn't get fetched at all xD

**Comment by mario** [comment]
Checking right away...

**Comment by mario** [comment]
@AndyScherzinger can you check if these lines ever get executed...

                    ArbitraryDataProvider arbitraryDataProvider = new ArbitraryDataProvider(
                            MainApp.getAppContext().getContentResolver());
                    arbitraryDataProvider.storeOrUpdateKeyValue(mAccount.name, DisplayUtils.AVATAR_TIMESTAMP,
                            Long.toString(System.currentTimeMillis()));
(in ThumbnailsCacheManager)

**Comment by AndyScherzinger** [comment]
Doesn't seem to get called, put in a log statement which never gets printed. Just removed/re-added an account with a changed avatar and it shows the old one again.

**Comment by mario** [comment]
@AndyScherzinger pushed changes. please try.

**Comment by AndyScherzinger** [comment]
arbitraryDataProvider.getLongValue(account, AVATAR_TIMESTAMP) is still -1 so it doesn't get triggered and the 24h don't matter

**Comment by mario** [comment]
Strange :( I'll investigate...

**Comment by AndyScherzinger** [comment]
Sorry for all the bad news 😢

**Comment by mario** [comment]
Fixed @AndyScherzinger.

**Comment by matiasdelellis** [comment]
Hello everyone,
One thing .. IHMO, would be more important to save/cahe the image of the server's login brackground since it is bigger, and today it is downloaded every time the application is opened ..
Regards,
And thanks for all..

**Comment by AndyScherzinger** [comment]
👍 
@mario refreshes work fine now and arbitraryDataProvider.getLongValue(account, AVATAR_TIMESTAMP) is not -1 👍

**Comment by AndyScherzinger** [comment]
I created a separate issue for the background image, see #1623

**Comment by mario** [comment]
Thanks!

**Comment by AndyScherzinger** [comment]
whele there is also  #1595

**Comment by tobiasKaminsky** [comment]
We already have Etags when downloading avatar via the current url:
ETag	"0ba7722746d74e81c5b67d60f216c1f0"

So I vote for doing it directly with etag.
If you do not have the time, just reply and I'll take care of it.

**Comment by mario** [comment]
@tobiasKaminsky feel free.

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky feel free to kill this PR once @tobiasKaminsky does etags-based solution.

**Comment by tobiasKaminsky** [comment]
Implementation with etags is #1658, but it is not yet working 100%.
Maybe some of you can have a look?

**Pull request closed without merging**
