### PR TITLE
White theming

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix https://github.com/nextcloud/android/issues/2539

 

There is still a glitch with the overflow menu.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Or do we want to try to have it still complete white, but change text to black/grey?

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by MorrisJobke** [comment]
> Or do we want to try to have it still complete white, but change text to black/grey?

cc @nextcloud/designers

**Comment by MariusBluem** [comment]
> Or do we want to try to have it still complete white, but change text to black/grey?

I'd vote for that 👍

**Comment by tobiasKaminsky** [comment]
Damn Marius… :rofl: I feared that someone wanted this ;-)

**Comment by tobiasKaminsky** [comment]
On the right, it confuse me a bit that the primary button is less visible than the secondary one…

**Comment by MariusBluem** [comment]
Make the primary button black :)

google-drive-app-device-backups-840x744

**Comment by AndyScherzinger** [comment]
> On the right, it confuse me a bit that the primary button is less visible than the secondary one…

Primary button should be black, whith the white action bar all menu icons + text + back arrow should be black (or at least instead of black it should be a dark grey tone like the folder icons)

**Comment by tobiasKaminsky** [comment]
The primary button is now grey, as otherwise we could not use font color (which is black), but we would have to create an additional logic for font on primary colors, when white.

Please just play a bit with the app, I hope I found every white / non readable font/background.

Some samples:

**Comment by jancborchardt** [comment]
Yeah, agree with Marius that proper white is the way to go, just like it looks on the server. :) And the newest screenshots look good! :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky  manual upload has a white title ;)
device-2018-05-07-135320

**Comment by tobiasKaminsky** [comment]
Nice finding @AndyScherzinger :+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky found two other minor issues: 
* The spinner in the action bar of your screenshot is white with a white action bar background (the triangle), see your last screenshots
* the "report an issue on Github" on the participate page isn't colored like the primary action button (e.g. like now for the manual upload)

**Comment by tobiasKaminsky** [comment]
I could not fix the spinner, all I found on the internet only changed the background, but not the triangle. Maybe you have an idea?

Issue 2 is fixed

**Comment by AndyScherzinger** [comment]
> Maybe you have an idea?

My guess is that this is then again related to Androids theming. In contrast to the action bar theme the spinner has a `dark` theming since also the opened spinner has a dark background thus the triangle is white. only thing I can think of would be to apply a different, fallback Android theme to the spinner in case of a light action bar background.

**Comment by mario** [comment]
What's the status here?

**Comment by tobiasKaminsky** [comment]
Triangle of spinner is still white.
I tried to solve it programatically, but this did not worked out, yet.

@AndyScherzinger idea to use a fallback theme would be an option.
@mario/@ardevd maybe you have another idea how to solve this programatically?

**Comment by tobiasKaminsky** [comment]
I finally found a way to tint the spinner :tada: 

 

So this is finally complete and ready to review again.

**Comment by mario** [comment]
👍 
Rebase.

**Comment by AndyScherzinger** [comment]
:+1:

**Pull request merged**
