### PR TITLE
Prevent NPE on absolutePath

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: #1336 

NPE in 
`
if (!mediaFolder.absolutePath.startsWith(dataPath))
`

maybe it is also in dataPath, but this would be way more critical:
`
String dataPath = MainApp.getStoragePath() + File.separator + MainApp.getDataFolder();
`
and then many other things would also crash.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 perfect :) As I stated in the issue...ufortunately ```mediaFolder.absolutePath``` can be ```null``` as seen in the locs above but it is not checked.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky we should probably add the same logic for the videos... :/
Sorry I missed that part during the original implementation...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I hardened the video part accordingly https://github.com/nextcloud/android/pull/1355/commits/00d28a18a56c4d1840d7b1d34c601a9a1ea6e572

**Comment by AndyScherzinger** [comment]
👍 I tested it on my phone to check if the video hardening works fine

**Comment by tobiasKaminsky** [comment]
:+1: for your addition ;-)

**Comment by AndyScherzinger** [comment]
so just awaiting @mario's review/approval

**Comment by AndyScherzinger** [comment]
👍 rebased to update the lint score - cc @tobiasKaminsky

**Comment by AndyScherzinger** [comment]
👍 rebased to update the lint score - cc @tobiasKaminsky

**Pull request merged**
