### PR TITLE
Use spotbugs for analytics

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Follow up of #3813, thanks to @ezaquarii!

SpotBugs finds a few more warnings, so I manually increased our results.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky raise score and merge?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky raise score and merge?

Score is already updated, otherwise SpotBug would have shown an error.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky merged, does this have to be backported to 3.6? I guess so, right?

**Comment by tobiasKaminsky** [comment]
No, I do not think so, as all the config/changes are within build.gradle / drone config and thus it should remain consistent.

**Pull request merged**
