### PR TITLE
New design (UI) - Replaced some icons

### PR DESCRIPTION
**Pull request by Shagequi**
Replaced some icons by Material ones.

about `ic_unshared.xml` icon, it's not in 24dp but in 20dp, it's due to the size of the "shared" icon which is too massive compared to the "three dots icon".

- [X] Tests written, or not not needed

Relative to : https://github.com/nextcloud/android/issues/5207
Based on this : https://github.com/nextcloud/android/issues/5207#issuecomment-617270183

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Since I haven't been involved in the discussions offline (don't worry). Beware that this PR also replaces the "Nextcloud icons" (e.g. for the empty screen), this would mean that the empty screens of web and Android differ (which in general is fine with me, I just don't know if this is clear to everyone involved in the revamp discussions, like @jancborchardt for example)

**Comment by jancborchardt** [comment]
I'm in trains today all day, screenshots would be appreciated to review quicker. :)

(Just as a note, we are also considering switching to Material Design icons for the server, see https://github.com/nextcloud/nextcloud-vue/issues/1051 )

**Comment by tobiasKaminsky** [comment]
> (Just as a note, we are also considering switching to Material Design icons for the server, see [nextcloud/nextcloud-vue#1051](https://github.com/nextcloud/nextcloud-vue/issues/1051) )

Nice idea, but what about iOS?
Material icons might look not well integrated there…?
And having on web/Android material design, but other icons on iOS is also strange.

**Comment by Shagequi** [comment]
About iOS, I let you watch with @immortal79 
And about screenshots, i'll create some comparison screenshots for quicker/better review.

**Comment by jancborchardt** [comment]
> > (Just as a note, we are also considering switching to Material Design icons for the server, see [nextcloud/nextcloud-vue#1051](https://github.com/nextcloud/nextcloud-vue/issues/1051) )
> 
> Nice idea, but what about iOS?
> Material icons might look not well integrated there…?
> And having on web/Android material design, but other icons on iOS is also strange.

Everything is a trade-off. Just like with the fonts, it's best to use the native stuff for the platform. Alas there's no "native" icons for web, so we just have to choose the best ones, which happen to be Material Design.

**Comment by Shagequi** [comment]
Before : 
Capture d’écran 2020-04-30 à 11 39 31

After :
Capture d’écran 2020-04-30 à 11 58 01


___

Before : 
Capture d’écran 2020-04-30 à 11 40 52

After : 
Capture d’écran 2020-04-30 à 11 58 43

**Comment by AndyScherzinger** [comment]
@Shagequi took the liberty to reformat your screenshot post using tables for a side-by-side visual diff :)

**Comment by Shagequi** [comment]
Thank you @AndyScherzinger  <3

**Comment by Shagequi** [comment]
Hi @jancborchardt , 

I followed the mockups : https://infomaniak.invisionapp.com/share/3VWA11OK9E8#/410365622_App_Nextcloud_-_Drive_2 present in this issue : https://github.com/nextcloud/android/issues/5207 

Concerning the "favorite icon" (star), the SVG used with the "white halo" is not the one from the Material library, and I don't find the current icon unreadable. If you want me to put the old one back it's possible but don't recommand it, or I recommand to find another way to display the folder as a "favorite". 

About the "share" icon, I'll ask the person who made the mockups to find a solution, and to be honest, I didn't know what was the purpose of the low opacity before you told me 😅

I come back as soon as I get some answers ! Don't hesitate to tell me if you have some ideas to transmit

**Comment by Shagequi** [comment]
@jancborchardt I just wanted to check something before going to talk to the UX about it... 
When the file is shared with an user, the icon/pp of the user is shown directly instead of the "share icon". 

So, when you share the file with someone on your cloud, you see this : 
Capture d’écran 2020-05-04 à 05 12 59

When you share with link, you see this : 
Capture d’écran 2020-05-04 à 05 13 23

When you do both, you see this : 
Capture d’écran 2020-05-04 à 05 10 11

We don't need to make the opacity lower, because the icon "share" is no longer displayed once the file shared.
What do you think about it ?

**Comment by tobiasKaminsky** [comment]
> We don't need to make the opacity lower, because the icon "share" is no longer displayed once the file shared.
> What do you think about it ?

I assume that Jan is mixing this up with server, where there are some shares which are shown with the "share icon" only.

As Kilian pointed out correctly, we do not have any "greyed out share" symbol anymore.
So we can keep it in 100% black.

**Comment by AndyScherzinger** [comment]
I agree with @Shagequi and @tobiasKaminsky while the icon color is rather grey600, not black 😀

**Comment by Shagequi** [comment]
@jancborchardt Hi, do you have some news ? :D

**Comment by Shagequi** [comment]
@tobiasKaminsky Good morning, may we merge this please?

**Comment by tobiasKaminsky** [comment]
Unrelated errors on drone.

**Comment by tobiasKaminsky** [comment]
@Shagequi where did you get the svg from?
We store in /drawable_resources the svgs and now I need to use the new folder icon as sources for our encrypted folder icon.
But these files are outdated?

**Comment by Shagequi** [comment]
@tobiasKaminsky 
These icons provide from Android Studio clip arts.

When you create a vector asset, instead of selecting one on your computer, you choose "Clip Art", this will give you access to the recent Material icons.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @Shagequi I'll take care of the folder icon and will see that I add the svg versions.

**Comment by Shagequi** [comment]
Okay, tell me if you need more informations ^_^ @AndyScherzinger

**Comment by AndyScherzinger** [comment]
@Shagequi I guess I am fine, only thing would be: Did you add any "non-standard" material icons?

**Comment by Shagequi** [comment]
@AndyScherzinger 
I only took the clip arts provided by Google and watched the mockups : https://github.com/nextcloud/android/issues/5207
So, I'd say no ;)

**Pull request merged**
