### PR TITLE
Use unicode elipsis instead of html one -> desired behaviour on transifex

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
I talked with @rakekniven and the desired behaviour is to use the unicode character for ellipsis instead of html code.
He will soon make an announcement for this.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by rakekniven** [comment]
@tobiasKaminsky We do not use a space between a word and ellipsis for nearly all strings I have seen the last month.

**Comment by tobiasKaminsky** [comment]
"nearly all" or "really all"? ;-)
I am just asking how to decide, when a space should be used and when not.

According to https://practicaltypography.com/ellipses.html it is said
> Should you put word spaces around an el­lip­sis? As with the em dash (see hy­phens and dashes), that’s up to you. Typ­i­cally you’ll want spaces be­fore and af­ter, but if that looks odd, you can take them out.

So I set a whitespace in front everywhere.
But if you think we should not use a whitespace, I am happy to change it.
Just confirm it please :-)
(then we should also put it on wiki page as a common project rule)

**Comment by AndyScherzinger** [comment]
I vote against this since Android lint wants the code not the Unicode character so I think Transifex is just wrong... Just my opinion though...

**Comment by AndyScherzinger** [comment]
:+1: fine by me then!

**Comment by tobiasKaminsky** [comment]
I removed the leading whitespace and I must say it looks a lot nicer in my opinion.

@rakekniven would be cool if you can do the announcement to use unicode character (https://github.com/nextcloud/server/wiki/Translation-knowledge-(valid-for-whole-nextcloud-project)#common-rules).

**Comment by comradekingu** [comment]
@rakekniven My view of space before ellipsis is not NC policy, and therefore errors and inconsistencies run rampant. Norwegian Bokmål works, because i saw too it, I have checked to see that the current situation doesn't work. It doesn't matter what arguments are presented, so I can't hope to win support for my view.

However, if "…" can be used, a lot of errors are avoided, because translators, myself included, don't have every code memorized. To the degree they are memorized, one is also likely to bring up the wrong connotation, remembering one thing as something else, and using it to that effect.
Worst case that changes the content significantly.

**Comment by rakekniven** [comment]
@tobiasKaminsky Announcement is done. See https://www.transifex.com/nextcloud/nextcloud/announcements/8627/

**Pull request merged**
