### PR TITLE
Fix exception when running CommentFileOperation

### LINKED ISSUE #8735: 3.17.0 RC2: crash while posting comment
### Steps to reproduce
1. open the detail view of a file
2. fill in a comment
3. post it, app will crash

************ CAUSE OF ERROR ************

java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$4.done(AsyncTask.java:415)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalArgumentException: Trying to execute a sync operation without storage provider! Please use execute(OwnCloudClient client, FileDataStorageManager storageManager) instead
at com.owncloud.android.operations.common.SyncOperation.execute(SyncOperation.java:154)
at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:479)
at com.owncloud.android.ui.fragment.FileDetailActivitiesFragment$SubmitCommentTask.doInBackground(FileDetailActivitiesFragment.java:460)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30170052
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: OnePlus
Device: OnePlus7T
Model: HD1903
Id: RKQ1.201022.002
Product: OnePlus7T_EEA

************ FIRMWARE ************
SDK: 30
Release: 11
Incremental: 2105071636

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #8735 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky this are been "accidentially fixed" via https://github.com/nextcloud/android/pull/8756/files#diff-1c5c151ec33d6cf1c52015aab90d9cd9d686bc337fe0c9b26662485a6bfe1768 so th ebackport is as empty as this one. is #8756 "backportable"?

**Comment by tobiasKaminsky** [comment]
No, this is then something we have to fix on stable-3.17 on our own, I fear

**Pull request merged**
