### PR TITLE
fix missing / in contributing link

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Ref: https://github.com/nextcloud/android/issues/1186

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you push this to transifex via the bot please? 👍

**Comment by tobiasKaminsky** [comment]
Done, although I would have been there this night automatically ;-)

**Comment by AndyScherzinger** [comment]
thx, tonight is a bit late ;)

**Pull request merged**
