### PR TITLE
Replace video player by ExoPlayer

### LINKED ISSUE #3061: Media Streaming Doesn't Work
### Actual behaviour
- Tell us what happens
When tapping on a media file in the latest version of the app(3.3.0), it opens a player in the app, and then says in a little popup "Could not play the file using the builtin media player" and then it gives up.
### Expected behaviour
- Tell us what should happen
 It should play mp3 and mp4 files when selecting them.
### Steps to reproduce
1.  Tap a media file in the Nextcloud app
2.  Media Player opens and produces the error

### Environment data
Android version: 8.0

Device model: LG V30

Stock or customized system: Stock

Nextcloud app version: 3.3.0

Nextcloud server version:14.0

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### LINKED ISSUE #3064: Video Media streaming with the built in video player doesn't always works (mostly)
### Actual behaviour
- Tap a video, the video player launches but most times fails to show the video, the screen stays black. Sometimes the length of the video is shown, but mostly shows 0:00. Sometimes it shows an error that the built in player is unable to play the video.

Note that 
- if i use the "Stream with..." option and have VLC installed, the streaming works via VLC.
- smaller video files seem to have bigger chances to be played.
- even if a video starts succesfully, most times it just freezes after a few seconds (after initial caching?)
- this happens even if the device is on wifi on the same LAN as the NC server

### Expected behaviour
- The video should be played every time. Or, if there are issues, an appropriate message to be shown.
 
### Steps to reproduce
1. Tap a video
2. 
3. 

### Environment data
Android version:
8.1.0
Device model: 
Lenovo K6 Power
Stock or customized system:
Lineage OS
Nextcloud app version:
3.3.0
Nextcloud server version:
14.0.0

### LINKED ISSUE #3601: The built-in media player is unable to play the media file
I guess I found some useful information about this behavior because many people are suffering from this issue I posted at the end of this message where I think the solution is.

### Actual behaviour
- When clicking on a media file in app (mp3, mp4, mov, etc.) the message 'The built-in media player is unable to play the media file' is displayed.

### Expected behaviour
- You'd expect clicking a media file would play the file. Now you have to click on the three dots and select 'stream with' such that it will play with VLC. But you have to do this for all songs in the containing folder which is a bore. You can't listen to an album since you'd have to repeat these steps when a song finishes..
 
### Steps to reproduce
1. Open the app
2. Browse to a media file
3. Click on it to try to play the file.

### Environment data
Android version:
Android 7.1.2
Stock or customized system:
Customized system
Nextcloud app version:
3.4.2
Nextcloud server version:
15.0.2
#### Nextcloud log (data/nextcloud.log)
```
2019/02/05 05:27:00
PreviewMediaFragment: onCreateView

2019/02/05 05:27:01
PreviewMediaFragment: onActivityCreated

2019/02/05 05:27:01
PreviewMediaFragment: onStart

2019/02/05 05:27:01
PreviewMediaFragment: Binding to MediaService...

2019/02/05 05:27:01
PreviewMediaFragment: onResume

2019/02/05 05:27:01
PreviewMediaFragment: Media service connected

2019/02/05 05:27:01
PreviewMediaFragment: starting playback of null

2019/02/05 05:27:01
MediaServiceBinder: Loading and starting through binder...

2019/02/05 05:27:01
PreviewMediaFragment: Successfully bound to MediaService, MediaController ready

2019/02/05 05:27:01
FileDisplayActivity: Media service connected

2019/02/05 05:27:01
OwnCloudClient #3: REQUEST POST /ocs/v2.php/apps/dav/api/v1/direct

2019/02/05 05:27:02
MediaService: Error in audio playback, what = -38, extra = 0

2019/02/05 05:27:03
PreviewMediaFragment: onPause

2019/02/05 05:27:03
PreviewMediaFragment: onStop

2019/02/05 05:27:03
PreviewMediaFragment: Unbinding from MediaService ...

2019/02/05 05:27:03
PreviewMediaFragment: onDestroy

2019/02/05 05:27:04
ExtendedListFragment: Setting selection to position: 0; top: 0; index: 2

```

I believe the main problem is the error
```
2019/02/05 05:27:02
MediaService: Error in audio playback, what = -38, extra = 0
```
I think below is some useful information to resolve this issue.
http://bighow.org/questions/21660098/android-mediaplayer-error-38-0-
https://stackoverflow.com/questions/9008770/media-player-called-in-state-0-error-38-0

### LINKED ISSUE #4204: Video playback stops once buffer underflows
### Actual behaviour
Tapping on a video, it starts to buffer and starts to play a moment later. After a few seconds the playback buffer seems to be underflowing and the video stops for ever. It's not possible to make it play anymore.

### Expected behaviour
The video player should wait for buffer to fill and continue automatically, when there is enough data to play again. It should also be possible to navigate back and play the video within the available data range.
 
### Steps to reproduce
1. Tap on a video.

### Environment data
Android version: 9

Device model: OnePlus A6003

Stock or customized system: stock

Nextcloud app version: 3.7.0 RC4

Nextcloud server version: 16.0.1 (FreeBSD)

### Logs

Please tell me if you look for something particular in logs, I'll provide it. It looks like the relevant URI in the remote.php HTTP request (used for streaming?) contains sensitive information.

### LINKED ISSUE #5800: Performance issues on playing videos in app
### Steps to reproduce
1. Play video from the app

### Expected & actual behaviour
Loading time is expected to be comparable or faster than if user played the same video using their browser app. In reality, the loading time (for a particular mp4 video that I had in my cloud) was 7-11 seconds (a very long time until the video even started playing) but if I played the same video using my web browser, it started playing instantly.

Picture- loading the video. Usually at least 5 seconds, sometimes the file never even loads. The videos I used for testing are low to mid bitrate and 1080p.
Screenshot_20200403-114502

### Environment data
Android version: 9

Device model:  Oneplus 5T

Nextcloud app version: 3.11.0

Nextcloud server version: 17

### LINKED ISSUE #5917: I can't play video file mp4 on app nextcloud
### Steps to reproduce
1. Upload file Video mp4
2. Install nextcloud on mobile 
3. Login and grant permission and play video file

### Expected behaviour
- Tell us what should happen
I will can watch video on app nextcloud
### Actual behaviour
- Tell us what happens
I can't watch video on app nextcloud

### Can you reproduce this problem on https://try.nextcloud.com?
- Please create a test demo account and see if this still happens there.
- If yes, please open up a bug report
- If not, please verify server setup and ask for help on forum

### Environment data
Android version:
9
Device model: 
G8142 Sony Xperia XZ Premium
Stock or customized system:
Stock 47.2.A.10.107
Nextcloud app version:
3.11.0
Nextcloud server version:
16.0.3
Reverse proxy:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### LINKED ISSUE #7647: streaming with vlc or other independent apps doesn't work
after logging to the server, picking a video (tried many different formats of video), I am unable to "stream with" any app I have on the android (8.0) phone (tried mx player, vlc, and more). No error is seen, it only tries forever...

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #5917 
Fix #5800 
Fix #4204
Fix #3601 
Fix #7647 
Fix #3061 
Fix #3064 

TODO:
- [x] show fullscreen in options menu
  - [x] stop video when stopping fullscreen
  - [ ] maybe better: https://medium.com/@danyalstd/adding-a-fullscreen-button-to-exoplayer-87f685279cae
- [x] play audio, pause/"stop" audio, go back, notification still visible, should then be stopped 
- [x] on streaming audio show placeholder, or can we retrieve artwork?

Built in video player is known to having problems with streaming, buffering, etc.
Exoplayer should perform better: https://github.com/google/ExoPlayer

I invite every user reporting streaming/playback issues to test this via provided apk.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [ ] Tests written, or not not needed

### CODE REVIEW

**Comment by lftsy** [comment]
I am interested in alpha testing the apk too with the new player, we just reuploaded our full nextcloud to reset old encryption, and video playing on android is still buggy. Working perfectly on Chrome/Firefox Mobile
Where can we find the apk to test with Exoplayer ? I could provide feedback or adb debugs too
Best Regards

**Comment by tobiasKaminsky** [comment]
> Where can we find the apk to test with Exoplayer ?

I removed it for now, but will update this PR soon and then there is a new version to test.

**Comment by kvn1351** [comment]
Any updates on this?

**Comment by szaimen** [comment]
@tobiasKaminsky any update here? :)

**Comment by jakobroehrl** [comment]
Working very nice, videos are starting instandly

**Comment by szaimen** [comment]
> Working very nice, videos are starting instandly

For me the same, also with local external storage on the server side.

**Comment by lftsy** [comment]
Thanks, I tested it and it starts indeed smoothly, and changing orientation of the phone is also working smoothly, BUT, I do cope with 3 problems
- Fullscreen: How can we enable fullscreen ?
- Crash : When trying to use the back button to exit the movie, it leaves the app
- Crash: If I try to browse the movie, it also crashes

But thanks for your effort, it is already super nice to see the movies starting so quickly !

Best Regards

**Comment by tobiasKaminsky** [comment]
@lftsy thanks for your feedback. 
Can you check newest apk and give us a stracktrace, when it crashes:
https://github.com/nextcloud/android/blob/master/README.md#getting-debug-info-via-logcat

Fullscreen is for now shown in option menu.

**Comment by jakobroehrl** [comment]
> APK file: https://www.kaminsky.me/nc-dev/android-artifacts/8132.apk
> 
> qrcode
> 
> To test this change/fix you can simply download above APK file and install and test it in parallel to your existing Nextcloud app.

"Stream with" out of the player menu doesn't have any effect.

**Comment by thibaultmol** [comment]
Will this pullrequest also make it possible to cast content to chromecast and such?
https://medium.com/android-news/sending-media-to-chromecast-has-never-been-easier-c331eeef1e0a

**Comment by jakobroehrl** [comment]
> Will this pullrequest also make it possible to cast content to chromecast and such?
> https://medium.com/android-news/sending-media-to-chromecast-has-never-been-easier-c331eeef1e0a

I don't think. But you can very easy use cromecast if you stream to vlc, bubbleupnp oder allcast

**Comment by lftsy** [comment]
Good evening everybody and sorry for the delay in answering

** Actions**
1) I have tested your last version @tobiasKaminsky and I am not able to reproduce the 2 crashes I had browsing the movie and using the back button ! And I also see that arrows keys to browse the movie do not appear twice
    => Thanks for the fixes !!
2) Fullscreen is also working indeed from the option menu, sorry if I missed this one on the older version ! 


** Problems I coped with**
1) Audio in bg: I did cope several times with the "Known issue right now is that it does not stop playing, even when closing the app." 
    => Let me know if you need an output of this one ?
2) Playing old .avi not working and no error displayed : I was tying to play an old .avi file Fantomas.avi and on the app, it doesn't start playing and do not display any error, I do see "" in the adb logcat "Unsupported RIFF format: 1096173856" + "Playback error" , cf [adb-logcat-nextcloud-qa-8132-avi-not-playing-no-error-visible.log](https://github.com/nextcloud/android/files/6496540/adb-logcat-nextcloud-qa-8132-avi-not-playing-no-error-visible.log)
    => when there is an error, it might be helpful here to display a generic error that format is not supported


@all 
1) Thank you very much for your work on this problem, I will keep testing it and provide steps to reproduce + logcat if I cope with other problems related to ExoPlayer integration

Best Regards

**Comment by tobiasKaminsky** [comment]
I'll merge this now, after CI.

@lftsy thanks for your feedback, can you create new issues once this happen again?

**Comment by szaimen** [comment]
🎉

**Comment by gkjcv** [comment]
# 7647

**Comment by BartAgterbosch** [comment]
Honestly exoplayer is way worse than the original player, at least with the original player when it was unable to process either the video format or the audio format, it would stop player when you closed it, exoplayer just starts spinning up processes like its' life depends on it, is there really no better alternative than this? Video player is essentially broken 99% of the time

**Pull request merged**
