### PR TITLE
Delete accounts only on first start

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This is required for 2.0.0 as we show there (for the very time) our what's new screens during upgrade, and during upgrade we should not delete our accounts ;-)

I have already created a 2.0.0 gplay release with this fix. The tag is still old. I can tag it again after merge of this PR. But as I am tomorrow not really available, I did a 2.0 release manually.

### CODE REVIEW

**Comment by mario** [comment]
@tobiasKaminsky did you remember to put google config in + remove the "Your accounts might be corrupted bla bla"? :)

**Comment by tobiasKaminsky** [comment]
google conf is in.

Account warning is still in, but only enabled for <2.0.0. We can remove this soon.
https://github.com/nextcloud/android/blob/0f38520417b30a178f87686632a70af5a9f46758/src/main/java/com/owncloud/android/ui/activity/FileDisplayActivity.java#L336-L336

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
Thought it's gonna be gone with 2.0, but yea ... :)

**Comment by tobiasKaminsky** [comment]
No one cared of removing it ;-)
I can do a PR tomorrow. Then we can merge this one and the removal PR and after that I can tag.
But now I am cuddling with Lu <3

**Comment by mario** [comment]
So unprofessional, this cuddling :D But I'll let you get away with it just this once :P

**Comment by AndyScherzinger** [comment]
I am on vaca but will be back Wednesday :)
And can do a PR then if that is early enough and it helps me with the Hacktoberfest challenge :)

**Comment by enoch85** [comment]
I won't press "Update branch" this time, but shouldn't 2.0.0 be released today?

**Comment by AndyScherzinger** [comment]
👍 fine by me

which one is the removal PR?

**Pull request merged**
