### PR TITLE
Fix NPE regression in FileDownloader

### LINKED ISSUE #9349: NPE in FileDownloader
### Steps to reproduce
1. Install app from master
2. Try to download any file

### System info
API 30 emulator, any server

### Logs
```
2021-11-23 14:39:46.641 13876-13931/com.nextcloud.client E/FileDownloader: Error downloading
2021-11-23 14:39:46.642 13876-13931/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: FileDownloaderThread
    Process: com.nextcloud.client, PID: 13876
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.nextcloud.java.util.Optional.get()' on a null object reference
        at com.owncloud.android.files.services.FileDownloader.downloadFile(FileDownloader.java:486)
        at com.owncloud.android.files.services.FileDownloader.access$500(FileDownloader.java:87)
        at com.owncloud.android.files.services.FileDownloader$ServiceHandler.handleMessage(FileDownloader.java:422)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

This is probably a consequence of https://github.com/nextcloud/android/pull/9073. @ezaquarii any thoughts?

### PR DESCRIPTION
**Pull request by ezaquarii**
Fixes #9349

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### CODE REVIEW

**Comment by ezaquarii** [comment]
@AlvaroBrey This fix should just work, but I cannot build the app atm due to missing library dependency. CI is also failing.

**Comment by AlvaroBrey** [comment]
@ezaquarii Just tested this locally, the crash is gone but downloads were still failing, which I traced back to another NPE in http://github.com/nextcloud/android/blob/155db1796b65828d2776c0a775f01b214e76f2f3/src/main/java/com/owncloud/android/files/services/FileDownloader.java#L462-L462 (`currentUser` is null here on the first download).  

I took the liberty to fix it in https://github.com/nextcloud/android/pull/9350/commits/1492b4d123736f2cffae8ca32fb44d35e69e3a1c.

Builds are currently broken because Jitpack seems to not want to serve `master-SNAPSHOT` since yesterday. If you need to test something locally, you can just change `androidLibraryVersion` to `2.8.0` in `build.gradle`, as all other versions except `master-SNAPSHOT` seem to be working.

**Comment by AlvaroBrey** [comment]
Thank you!

**Pull request merged**
