### PR TITLE
Fix avatars

### PR DESCRIPTION
**Pull request by mario**
Signed-off-by: Mario Danic <mario@lovelyhq.com>

This fixes avatars for LDAP accounts. Keep in mind our avatars handling is rather poor atm - even if you update the avatar on the web, it would NOT be updated in the app :(

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 code looks good, will test it tomorrow for non ldap accounts

**Comment by AndyScherzinger** [comment]
Tested for non-LDAP, still works fine 😃

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you look into this one please? :)

@tobiasKaminsky @mario does this lead to an 2.0.0RC9?

**Comment by mario** [comment]
If this is all that is left I would merge and release 2.0. But do we have
anything else that needs to be fixed for 2.0?

**Comment by AndyScherzinger** [comment]
This is the only remaining ticket, while an RC9 this week would give the ldap users a chance to test and provide us with some feedback if it works. So we could then do a final beginning of next week.

**Comment by mario** [comment]
Tobias isn't around this week...

**Comment by AndyScherzinger** [comment]
I know but he told me he'll look into GH and respond.

**Comment by tobiasKaminsky** [comment]
👍

**Comment by AndyScherzinger** [comment]
* I just rebased waiting for drone and will then merge (contains the 2.0.0RC9 version bump)
* also to be merged for RC9 and to be reviewed by Tobias is #1627

**Pull request merged**
