### PR TITLE
Document provider: allow copy/move of file/folder

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
- copy or move file or folder

Rebase of #3437

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky could you rebase & resolve conflicts please ❤️

**Comment by AndyScherzinger** [comment]
❗️ rebased, going to test it now

**Comment by tobiasKaminsky** [comment]
I have a look now why the test "creating a folder" is failing.

**Comment by AndyScherzinger** [comment]
👍 thanks @tobiasKaminsky did the tests for move/copy within Nextcloud and Nextcloud->Phone - All have been successful 🎉

**Comment by tobiasKaminsky** [comment]
Locally it is working, so let us merge it and hope the best ;-)

**Pull request merged**
