### PR TITLE
Suppress fatal SecurityException crash when removing sticky intent

### LINKED ISSUE #4229: Crasher after giving permission to storage
**Note:** It is only on my Pixel 3 the NextCloud app does not work everything work on my Nexus 5X

### Steps to reproduce
1. Uninstall the Nextcloud (Dev) app
2. Installing Nextcloud (Dev) from F-Droid
3. Login in to my NextCloud server
4. Get prompt to allow access to storage
5. the NextCloud app crasher and keeps doing so every time I start it

### Expected behaviour
I expected it to show me the files on my server

### Actual behaviour
After login in to my NextCloud instance, the NextCloud app crasher and keeps doing so every time I start it

## Server configuration detail

**Operating system:** Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64

**Webserver:** nginx/1.14.0 (fpm-fcgi)

**Database:** mysql 10.4.6

**PHP version:** 

7.3.7
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 15.0.10 - 15.0.10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** https://hub.docker.com/_/nextcloud

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - camerarawpreviews: 0.7.0
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - dav: 1.8.2
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_fulltextsearch: 1.2.8
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.4.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - fulltextsearch: 1.2.9
 - fulltextsearch_elasticsearch: 1.2.6
 - gallery: 18.2.0
 - group_everyone: 0.1.2
 - groupfolders: 3.0.2
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - onlyoffice: 2.4.0
 - password_policy: 1.5.0
 - previewgenerator: 2.1.0
 - provisioning_api: 1.5.0
 - richdocuments: 3.3.13
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - support: 1.0.0
 - survey_client: 1.3.0
 - systemtags: 1.5.0
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - admin_audit
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.best.aau.dk"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "15.0.10.0",
    "overwrite.cli.url": "https:\/\/nextcloud.best.aau.dk",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "updater.release.channel": "production",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "maintenance": false,
    "loglevel": 2
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Firefox

**Operating system:** Linux

## Logs

<details><summary>Web server error log</summary>

```
I am not sure what log you want here, just everything from nginx?
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: 0 tag entries for deleted tags have been removed.","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: 0 tags with no entries have been removed.","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair invalid shares","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Remove shares of a users root folder","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Move .step file of updater to backup location","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Fix potential broken mount points","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: No mounts updated","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair invalid paths in file cache","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Add log rotate job","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Clear frontend caches","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:57+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Image cache cleared","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:38:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: SCSS cache cleared","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: JS cache cleared","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Clear every generated avatar on major updates","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Add preview background cleanup job","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Queue a one-time job to cleanup old backups of the updater","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Repair pending cron jobs","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: No need to repair pending cron jobs.","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Extract the vcard uid and store it in the db","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::step: Repair step: Remove potentially over exposing share links","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: No need to remove link shares.","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:00+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:14+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"15.0.8.1"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:14+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"15.0.10.0"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:14+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"--","version":"15.0.10.0"}
{"reqId":"ycHAlvEIhZoPaywByB6K","level":1,"time":"2019-07-12T17:39:14+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"15.0.10.0"}
{"reqId":"9KTiubc5sggpG6wV5dYx","level":2,"time":"2019-07-13T18:59:50+00:00","remoteAddr":"10.16.2.1","user":"--","app":"fulltextsearch","method":"GET","url":"\/cron.php","message":"Exception while cronIndex: OCA\\FullTextSearch\\Exceptions\\RunnerAlreadyUpException - Index is already running","userAgent":"Lge Nexus 5X","version":"15.0.10.0"}
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:
No quite sure how to do this
</details>

### PR DESCRIPTION
**Pull request by ezaquarii**
Fixes #4229

Signed-off-by: Chris Narkiewicz <hello@ezaquarii.com>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
We have this in total 10x. Is this happening only there? Or do we should change this everywhere?

Regarding exception, doc says:
> You must hold the BROADCAST_STICKY permission in order to use this API. If you do not hold that permission, SecurityException will be thrown.

Which we have in AndroidManifest.xml.

**Comment by ezaquarii** [comment]
> We have this in total 10x. Is this happening only there? Or do we should change this everywhere?
> 
> Regarding exception, doc says:
> 
> > You must hold the BROADCAST_STICKY permission in order to use this API. If you do not hold that permission, SecurityException will be thrown.
> 
> Which we have in AndroidManifest.xml.

Yeah, and it still throws this exception on some phones. I guess this is a platform bug in deprecated code path that is poorly maintained.

Sadly, I don't have idea how to remove this legacy solution yet.

I don't want to advocate landing this PR too much as I don't understand what will happen if we don't unbroadcast the intent and I expect some edge issues. I hope that those will be less catastrophic that a fatal exception, but this is only wild speculation. I tried to contact the original author but there is no response yet.

@tobiasKaminsky @AndyScherzinger maybe you have better access to them?

**Comment by mario** [comment]
I can tell you why this happens. It happens if you install and use the app in your Work profile :)

**Comment by ezaquarii** [comment]
> I can tell you why this happens. It happens if you install and use the app in your Work profile :)

Are you able to reproduce it? 

Fixing it won't be trivial.

**Comment by tobiasKaminsky** [comment]
> Work profile

Can you give us a hint how to do this? Is this possible with G-Suite?

**Comment by mario** [comment]
> > I can tell you why this happens. It happens if you install and use the app in your Work profile :)
> 
> Are you able to reproduce it?
> 
> Fixing it won't be trivial.

Yes, I can reproduce this.

**Comment by mario** [comment]
> > Work profile
> 
> Can you give us a hint how to do this? Is this possible with G-Suite?

I use Device policy to manage it all, but Work profile is a different thing in general which - https://support.google.com/work/android/answer/6191949?hl=en

**Comment by ezaquarii** [comment]
I think this solution wont work well.

**Pull request closed without merging**
