### PR TITLE
Fix send share crash

### LINKED ISSUE #1918: DEV-20171230 Send/Share crashes from within preview
1. Open an image
2. Open menu
3. Click Send/Share
4. :boom:

All works as expected if I click on the share icon in the file list next to the same image.

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
use interface
fix #1918

Signed-off-by: tobiaskaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by mario** [comment]
@tobiasKaminsky please rebase.

**Comment by tobiasKaminsky** [comment]
@mario rebased and ready for review & test

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
Merging with only one approval as @AndyScherzinger is on vacation.

**Pull request merged**
