### PR TITLE
Contact list improvement

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
fix some lint errors/warnings

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
> Use explicit scoping instead of the default package private level

Android Studio says I am allowed to remove it, codacy says I shall add something...

**Comment by mario** [comment]
@tobiasKaminsky yea, well ... :D

**Comment by mario** [comment]
So are you gonna put the scoping back in or?

**Comment by tobiasKaminsky** [comment]
Yes

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky Drone lint checks fail probably due to the branch not being up to latest master ;)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky can you please rebase and cleanup ;) this branch contains the participate branch... :P

**Comment by AndyScherzinger** [comment]
👍 fine by me

**Comment by mario** [comment]
@tobiasKaminsky can you please rebase since you know how to do it and then I can test and approve?

**Comment by tobiasKaminsky** [comment]
@mario rebase is done.

**Comment by AndyScherzinger** [comment]
👍 fine by me, your tunr @mario 🗡 

@tobiasKaminsky I shortened one some code and also fixed the license header comment

**Comment by AndyScherzinger** [comment]
👍  fine by me, your turn @mario :D

@tobiasKaminsky I shortened one some code and also fixed the license header comment

**Comment by mario** [comment]
👍

**Pull request merged**
