### PR TITLE
bump to latest SDK

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky massive lint score increase likely due to changed rules because of the sdk bump

**Comment by tobiasKaminsky** [comment]
``` 
../../../src/main/java/com/owncloud/android/datamodel/MediaProvider.java:53: Field requires API level Q (current min is 14): android.provider.MediaStore.MediaColumns#BUCKET_ID
``` 

https://developer.android.com/reference/android/provider/MediaStore.MediaColumns.html#BUCKET_ID

This just seems to be wrong. We have this since ages…

**Comment by AndyScherzinger** [comment]
> This just seems to be wrong. We have this since ages…

Yes and no ;) They have been in place for ages, now Google decided to move them up into the interface (via v29) and they are inherited from there, unfortunately this means that now you end up with lint warnings...

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky Dies on Android Q Emulator. Take some pictures and then open the Auto Upload

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextcloud.client/com.owncloud.android.ui.activity.SyncedFoldersActivity}: java.lang.IllegalArgumentException: Invalid column Distinct bucket_id
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Invalid column Distinct bucket_id
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.owncloud.android.datamodel.MediaProvider.getImageFolders(MediaProvider.java:81)
        at com.owncloud.android.ui.activity.SyncedFoldersActivity.load(SyncedFoldersActivity.java:249)
        at com.owncloud.android.ui.activity.SyncedFoldersActivity.setupContent(SyncedFoldersActivity.java:236)
        at com.owncloud.android.ui.activity.SyncedFoldersActivity.onCreate(SyncedFoldersActivity.java:162)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by tobiasKaminsky** [comment]
> Invalid column Distinct bucket_id

This is concatenated here:
https://github.com/nextcloud/android/blob/750bfbc3c465c8c0c19c3ee98d3cd9939408f701/src/main/java/com/owncloud/android/datamodel/MediaProvider.java#L54-L55

I do not find a way how to do it better than to remove "distinct" and manually do a distinct…

**Comment by AndyScherzinger** [comment]
This is only happening due to the sdk bump, can distinct be set via api? If so can it be limited to the column?

Else I also have no idea how to do this properly except doing it like you said, manually afterwards.

**Comment by tobiasKaminsky** [comment]
I do the distinct part now manually.
Hopefully this will not take too much additionally time.

However, this is very rarely used and so it is acceptable to wait a bit longer.

**Comment by tobiasKaminsky** [comment]
After merging this, we can also merge the PR on library

**Comment by tobiasKaminsky** [comment]
Lint is only about: https://www.kaminsky.me/nc-dev/android-lint/11823.html#InlinedApi

**Comment by tobiasKaminsky** [comment]
This works also on Android 6.
Android 4/5 is failing due to other reasons for me at the moment…

**Comment by tobiasKaminsky** [comment]
> Lint is only about: https://www.kaminsky.me/nc-dev/android-lint/11823.html#InlinedApi

@AndyScherzinger what do you think? Increase lint/spotbugs for this or try to get rid of it with annotations?

**Comment by AndyScherzinger** [comment]
> what do you think? Increase lint/spotbugs for this or try to get rid of it with annotations?

I'd say so, yes 👍 It is documented and we can fix it over time but it shouldn't block development/merge :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky you asked the backport bot for 3.8 while that  should be 3.9 by now or none since I am unsure if you want to release this for 3.9.3+ or just 3.10+

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky you asked the backport bot for 3.8 while that should be 3.9 by now or none since I am unsure if you want to release this for 3.9.3+ or just 3.10+

backport label was remove, so I hope that nothing gets backported, as we do not need it.
I hope there will be no 3.9.3, so 3.10 is fine :-)

**Comment by AndyScherzinger** [comment]
Just tested, works fine

**Pull request merged**
