### PR TITLE
Trashbin: do UI changes of async only if activity is still up and running

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix https://github.com/nextcloud/android/issues/3035
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
I'm sure we could use lifecycle observers here, but ... if it makes you happy :)

👍

**Comment by tobiasKaminsky** [comment]
> use lifecycle observers

Good idea, I'll have a look into this, but for a quick bugfix it is fine, I hope.

**Pull request merged**
