### PR TITLE
use drone for all flavours

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
use only on master and PR push
use google stuff only on gplay, modified

@Mario this will fail due to problems in modified and gplay.
Please have a look there. As it is push related I am unsure how to solve this.

### CODE REVIEW

**Comment by mario** [comment]
@tobiasKaminsky sure, will look. Can you clarify why we do this only for master? (From what I understand, not a Drone expert)

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/502 and all other PRs are currently starting two drones, one for PR and one for the push to the branch.
With the limitation to master every new PR will trigger only one Drone job, as only the PR will cause the trigger.
But on master it will be triggered via branch changes, e.g. if Transifex pushes something.

**Comment by mario** [comment]
👍  @tobiasKaminsky - but please add new line at the end before I can merge this.

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by mario** [comment]
👍

**Comment by tobiasKaminsky** [comment]
> but please add new line at the end before I can merge this.

You have merged it, how important (and why) is this new line?

**Comment by mario** [comment]
I will make a new PR just with newline.

As I explained earlier, all files need to have newline - otherwise you will
see Github and various lint magicians complain.

**Pull request merged**
