### PR TITLE
enlarged icon

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Before
before

after
after

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

Larger icon FTW :)

**Comment by jancborchardt** [comment]
Looking good! :) If you want you can also do one with »Beta« text below (in Open Sans Light or Semibold ideally ;) for the beta app so it fits.

**Comment by AndyScherzinger** [comment]
@jancborchardt DONE: https://github.com/nextcloud/android/pull/169/commits/da93fff35deebef0366bda3af602e2ebf8749f62

**Comment by tobiasKaminsky** [comment]
:+1: @AndyScherzinger Do you have saved it in /promo?

**Comment by AndyScherzinger** [comment]
Not yet, but will :)

**Comment by AndyScherzinger** [comment]
--> https://github.com/nextcloud/promo/pull/4

**Pull request merged**
