### PR TITLE
Backport #2449: prevent NPE via null check

### PR DESCRIPTION
**Pull request by tobiasKaminsky**

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1: looks good to me

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky I fixed the base for the backport PRs since they need to point to `stable-3.1.x`not `master` ;)

**Comment by AndyScherzinger** [comment]
@mario please review n' merge (if fine with the backport)

**Comment by mario** [comment]
👍 fine by me

**Pull request merged**
