### PR TITLE
LGTM config + renamed Android ID

### PR DESCRIPTION
**Pull request by AndyScherzinger**

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@LukasReschke can you approve this --> :shipit: , :+1: or LGTM

**Comment by LukasReschke** [comment]
LGTM

**Comment by AndyScherzinger** [comment]
Just FYI: The MAINTAINERS list now contains the following people:
* @LukasReschke 
* @jancborchardt 
* @przybylski 
* @tobiasKaminsky 
* me

So each PR gets blocked for merging until at least two of us commented the PR with LGTM, :shipit: or :+1: --> see .lgtm for the pattern to be matched

**Pull request merged**
