### PR TITLE
workflows/qa: Skip NDK install if PR is not from this repo

### PR DESCRIPTION
**Pull request by AlvaroBrey**
We already do this for the rest of steps, I forgot to add it when I added the NDK install

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Why is this needed? Forked repo would still benefit from this to have a reduced QA size?

**Comment by AlvaroBrey** [comment]
> Why is this needed? Forked repo would still benefit from this to have a reduced QA size?

QA already is skipped for forks, due to missing secrets. See https://github.com/nextcloud/android/pull/8861

**Comment by AlvaroBrey** [comment]
> > Why is this needed? Forked repo would still benefit from this to have a reduced QA size?
> 
> QA already is skipped for forks, due to missing secrets. See #8861

Let me add: if we do want QA builds for forks, it can technically be done (using `pull_request_target` instead of `pull_request`). Let me know what you think.

**Comment by tobiasKaminsky** [comment]
> if we do want QA builds for forks

This would be great, as community do great PR and this way they can be tested more easily.

**Comment by AlvaroBrey** [comment]
> > if we do want QA builds for forks
> 
> This would be great, as community do great PR and this way they can be tested more easily.

OK, I will do this instead in a new PR

**Pull request closed without merging**
