### PR TITLE
Warning for corrupt accounts for 2.0.0RC users

### PR DESCRIPTION
**Pull request by AndyScherzinger**
As requested by @mario here is a (simple) implementation of a warning dialog which will show up on the file list respecting the following points:

* only shown when version is >1.4.3
* only shown when version is <2.0.0FINAL
* only shown when not shown ever before

Screenshot
device-2017-09-08-173144

PS: This is a solution to be displayed until the 2.0.0RCs end so effort to implement this has been kept at a minimum!

cc @tobiasKaminsky

### CODE REVIEW

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
Thanks!

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by doits** [comment]
Can you please give us a ref to an issue or commit for further information? Just want to understand what happened (how they got corrupted and what this means) and how it was fixed.

**Comment by AndyScherzinger** [comment]
@mario @tobiasKaminsky can you answer this question? I just implemented the pop-up upon your request.

**Comment by mario** [comment]
@doits https://github.com/nextcloud/android/pull/1505

One of the previous PRs upgraded username to userID. And while that should have been correct, unfortunately, it was not and there was no way back. So I created a PR that properly adds new accounts, and @AndyScherzinger did a PR to warn you that you need to re-add the account.

**Comment by doits** [comment]
Thanks for the info

**Comment by mario** [comment]
You're welcome, and sorry for the trouble!

**Comment by chrisi-taylor** [comment]
Please, can you give more detail?
In what way does the corrupted account malfunction?
Does the upload/sync for the account not work anymore?
Does the login at app start-up fail?
**Background:**
I am pretty sure I had several rc-releases installed.
I am not quite sure if I started the nextcloud client in the past two months.
Now I started rc8 and the warning popped up.
But the app seems to function well:
I tested upload and sync of files...
Music-Player works fine...

Is my app/login affected by the "bug"?
(Do I have to re-login and resync all data?)

All hints welcome...

Thank you for the brilliant app!

Kind regards

    Chris

**Pull request merged**
