### PR TITLE
Add numeric buttons on PassCodeActivity

### PR DESCRIPTION
**Pull request by zmatsuo**
This PR is the same as PR #497, but it is PR to master.
PR #497 was PR to beta.

### CODE REVIEW

**Comment by zmatsuo** [comment]
> how to switch back from "small" to "big" keyboard.

@tobiasKaminsky
Push back button (◁key or ↵key)
to close small(soft)keyboard and switch "big" keyboard

I will add codes to save state of keyboard or/and change the size of the keyboard.

**Comment by zmatsuo** [comment]
The coding was completed (I had a hard time with Codacy).
However, the discussion at Issue #618 has not ended.
This PR may be rejected...  :cry:

**Comment by tobiasKaminsky** [comment]
> This PR may be rejected... 😢

I do not know the current state of the discussion you mentioned, but to avoid this is in future best would be to stay with our process: feature idea -> discuss, modify & approve -> develop -> code review -> merge

But please do not feel discourage if this PR will not be merged. It is still a great contribution and we are always happy if you can/will help us with some nice features 👍

**Comment by zmatsuo** [comment]
I am testing this PR on my device (Android 5.0.1 Galaxy S4) few days.
It looks good.
And, I tried to test with Android 7.1.1, 7.0, 6.0 using emulator.
But, emulator on my PC is very very slow and is not stable.
Emulator is Something's wrong :(

Will you test this PR? @AndyScherzinger @mario @tobiasKaminsky
I beleve there is no simple bug :)

**Comment by zmatsuo** [comment]
Thank you, Thank you.

This PR got bigger. I changed most of the source.
I think it was better to fix/modify with a small step.
Next time I will do so.

If there is not a big bug in this PR,
On issue #618, I will get advice on PR's design side.

**Comment by zmatsuo** [comment]
I added hardkeyboard related code.

I add onConfigurationChanged(), but this function has not been tested.
onConfigurationChanged() was not called
when I connect/disconnect keyboard to my device with bluetooth :-(

onConfigurationChanged() may be called when device is clamshell type ?
( like is01
    http://www.umpcportal.com/2010/03/sharp-is01-5-android-clamshell-tick-tick-and-tick/
  But we cannot see display when device is closed ...)

And emulator on my PC comes back.
I tested on 4.1(16), 4.4(19), 6.0(23), 7.0(24), 7.1.1(25).
This PR works well :-)

**Comment by zmatsuo** [comment]
It is difficult to detect hard(physical) keyboard.
I can not test perfectly with my own device and emulator.  :sweat_smile:

**Comment by zmatsuo** [comment]
I found two issues on my device

1. statusbar color
2. U+232B is not displayed

My device is galaxy s4 sc-04e, android 5.0.1
Emulator used in development is 7.1.1



statusbar is blue on 7.1.1.
U+232B (⌫) is displayed with default web browser, firefox and chrome on my device.

It is not good.
I will check.

**Comment by zmatsuo** [comment]
I fix StatusBar color.

but U+232B (⌫) is not displayed.
Please someone help this issue.

**Comment by zmatsuo** [comment]
I implemented del button using imagebutton (del button png image is temporal :-)
I feel that the vector image is better. I will think more about the button..

I guess progressbar implementation is below.
- setIndeterminate(true)  
  show progressbar, progressbar is activep
- setIndeterminate(false)
  hide progressbar, progressbar is inactive

I will Investigate more about progressbar.

**Comment by zmatsuo** [comment]
I added font, so delete button can be displayed on all device.

**Comment by zmatsuo** [comment]
I'd like to make progressbar related fixes.
However, it seems necessary to investigate in a wide range.
I think it is good to close this PR once. :simple_smile:
Please review.

**Comment by zmatsuo** [comment]
I'm sorry. It seems that I pressed the wrong (Close and comment) button.

**Comment by zmatsuo** [comment]
I found handling callbacks around snackbar. I fixed and pushed.
I must go bed.

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky what to do with this PR?

**Comment by tobiasKaminsky** [comment]
I am unsure this is a rather edge case as normally android pops up it virtual keyboard.

**Comment by AndyScherzinger** [comment]
Also unsure since the PR for using device credentials will probably the mostly used one when shipped. So I'd also say close. :/

**Comment by zmatsuo** [comment]
I used normal release of nextcloud app from google play for about half a year.
Virtual Keyboard sometimes does not appear on my device.
But Almost no problem.
I came to think that problems is in my device and this PR is not need.
I will close this PR (#620) and #618.
Thank you.

**Pull request closed without merging**
