### PR TITLE
unify empty string compare

### PR DESCRIPTION
**Pull request by jmue**
Unify string test on emptyness, use string `Textutils.isEmpty()`. This shortens written code and improves readability.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
This change led our unit tests fail: https://www.kaminsky.me/nc-dev/android-integrationTests/8869/

As unit test run without Android SDK there is no TextUtils.
So ErrorMessageAdapterUnitTest and TestSorting needs to be moved within /src/androidTest

**Comment by jmue** [comment]
> This change led our unit tests fail: https://www.kaminsky.me/nc-dev/android-integrationTests/8869/
> 
> As unit test run without Android SDK there is no TextUtils.
> So ErrorMessageAdapterUnitTest and TestSorting needs to be moved within /src/androidTest

Thank you for helping out with that.

**Comment by AndyScherzinger** [comment]
One question: Why the change / rearrangement in the gradle build file?

Anything else looks good to me :+1:

**Comment by tobiasKaminsky** [comment]
> One question: Why the change / rearrangement in the gradle build file?

With this PR Mockito was added, but on a different place and thus dependancies for instrumentationTests and unit tests were mixed.

So now everything should be in its own area and if we add new dependencies we should obey these categories :-)

**Comment by AndyScherzinger** [comment]
well, merging then :)

❤️ @jmue thanks a lot for this PR 🎉

**Pull request merged**
