### PR TITLE
Check CSR

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
@AlvaroBrey 
it seems that with gplayDebug flavor we have:
```
java.lang.ClassCastException: com.google.android.gms.org.conscrypt.OpenSSLRSAPublicKey cannot be cast to org.conscrypt.OpenSSLRSAPublicKey
at com.owncloud.android.util.EncryptionTestIT.testModulus(EncryptionTestIT.java:187)
```

but it runs fine locally on genericDebug.

I do not see/understand why conscrypt is behaving differently on geplay/generic flavor.

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey it seems that with gplayDebug flavor we have:
> 
> ```
> java.lang.ClassCastException: com.google.android.gms.org.conscrypt.OpenSSLRSAPublicKey cannot be cast to org.conscrypt.OpenSSLRSAPublicKey
> at com.owncloud.android.util.EncryptionTestIT.testModulus(EncryptionTestIT.java:187)
> ```
> 
> but it runs fine locally on genericDebug.
> 
> I do not see/understand why conscrypt is behaving differently on geplay/generic flavor.

At this line: http://github.com/nextcloud/android/blob/71f16d6e978141d58a6d92d5ee3616ddcae13379/app/src/main/java/com/owncloud/android/utils/EncryptionUtils.java#L690-L690 , `KeyPairGenerator.getInstance` returns different classes (`org.conscrypt...` in generic, `com.android.gms.org.conscrypt...` in gplay).

We install the Conscrypt provider [here in `MainApp`](http://github.com/nextcloud/android/blob/71f16d6e978141d58a6d92d5ee3616ddcae13379/app/src/main/java/com/owncloud/android/MainApp.java#L417-L417). But in the `gplay` flavor, `ProviderInstaller` is [called](http://github.com/nextcloud/android/blob/71f16d6e978141d58a6d92d5ee3616ddcae13379/app/src/main/java/com/owncloud/android/MainApp.java#L289-L289) [later](http://github.com/nextcloud/android/blob/71f16d6e978141d58a6d92d5ee3616ddcae13379/app/src/gplay/java/com/owncloud/android/utils/SecurityUtils.java#L29-L29),  installing the `gms` provider and overriding the previous one.

`ProviderInstaller` installs up-to-date conscrypt security providers patched by Google Services regularly ([documentation](https://developer.android.com/training/articles/security-gms-provider)). 

The solution to all this should be  to use the `RSAPublicKey` interface instead of the implementation-specific `OpenSSLRSAPublicKey`. Pushed 19c60959cfe6c7bb6157808f6334cea5271685ce to do just that, let's see how that goes.

**Review by AlvaroBrey — APPROVED** [review]
Needs rebase & conflict resolution, otherwise looks fine

**Comment by AlvaroBrey** [comment]
Exception is `java.lang.ClassCastException: com.google.android.gms.org.conscrypt.OpenSSLRSAPublicKey cannot be cast to org.conscrypt.OpenSSLRSAPublicKey`, we already saw this in a previous test, it needs to be the common interface instead

**Comment by AlvaroBrey** [comment]
> Exception is `java.lang.ClassCastException: com.google.android.gms.org.conscrypt.OpenSSLRSAPublicKey cannot be cast to org.conscrypt.OpenSSLRSAPublicKey`, we already saw this in a previous test, it needs to be the common interface instead

Fixed in https://github.com/nextcloud/android/pull/10713/commits/59b225feccc739db3f463b6ebb824c1e3ac7c92a

**Review by AlvaroBrey — APPROVED** [review]

**Pull request merged**
