### PR TITLE
FolderPickerActivity: disable copy/move to the same folder

### PR DESCRIPTION
**Pull request by AlvaroBrey**
It's a no-op anyways, right now, and causes bad UX

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
It works with
- move file in root folder
- see that root folder is not allowed
- go into subfolder
- see that it is allowed

But when I start within a subfolder
- create folder 1
- create empty file.md
- move file
- see that it is allowed in root folder and in folder 1

**Comment by AlvaroBrey** [comment]
> It works with
> 
> * move file in root folder
> * see that root folder is not allowed
> * go into subfolder
> * see that it is allowed
> 
> But when I start within a subfolder
> 
> * create folder 1
> * create empty file.md
> * move file
> * see that it is allowed in root folder and in folder 1

Fixed!

**Comment by tobiasKaminsky** [comment]
Now this works again:
-create /testFolder
- move this folder
- go to /testFolder
--> it is allowed

**Comment by tobiasKaminsky** [comment]
> You mean moving a folder inside itself is allowed?

It is within this PR right now possible, but it should not be allowed.

Similar, it should not be possible to move /TestFolder to /TestFolder/1/ or any other subfolder of its own.

**Comment by AlvaroBrey** [comment]
> > You mean moving a folder inside itself is allowed?
> 
> It is within this PR right now possible, but it should not be allowed.
> 
> Similar, it should not be possible to move /TestFolder to /TestFolder/1/ or any other subfolder of its own.

This was out of the scope of this PR, but fixed anyway in https://github.com/nextcloud/android/pull/11092/commits/6d4a65b45ccf67801dba90d7da1c8856c5968c4f

**Comment by tobiasKaminsky** [comment]
Great one!

**Review by tobiasKaminsky — APPROVED** [review]

**Pull request merged**
