### PR TITLE
Fix 4g retry

### PR DESCRIPTION
**Pull request by mario**
Will now retry sooner than 15 minutes in some cases if you go from no connection to 4g.

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
@AndyScherzinger @tobiasKaminsky would be cool to get this in RC7.

**Comment by tobiasKaminsky** [comment]
I understand that this is only for restarting jobs. Each job will then verify if an unmetered connection is available and will only upload it then, so
:+1:

**Comment by tobiasKaminsky** [comment]
Rebased, waiting for checks and then I'll merge it.
(silently assuming that @AndyScherzinger is fine with it)

**Comment by AndyScherzinger** [comment]
👍 I am totally fine with it,just sick slightly sick so don't wait for my replies this next week

**Pull request merged**
