### PR TITLE
show/hide toolbar on scroll

### PR DESCRIPTION
**Pull request by AndyScherzinger**
initial work / prototyping of #190

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Is this still valid if we (you) switch to recyclerview?

**Comment by AndyScherzinger** [comment]
Yes :) 
I will work on this as soon as I moved to recyclerview which will make this PR more reliable with the event handling :)

**Comment by tobiasKaminsky** [comment]
Shall we try to integrate this now, as recycler view will take quite some time?

**Comment by AndyScherzinger** [comment]
No, this one needs the recyclerview to work properly. to not spam the notifications on GH all the time I could close the PR for now but would keep the branch. What do you think?

**Comment by tobiasKaminsky** [comment]
I do not mind the notifications, but think it results in a lot of duplicate work as you need to rebase it from time to time...

**Comment by AndyScherzinger** [comment]
Or I don't and just keep it as a code reference for later when I can actually implement it :)

**Comment by AndyScherzinger** [comment]
removed since the scroll implementation would be different for a recycler view and has been added as a separate PR for the auto upload already, thus closing

**Pull request closed without merging**
