### PR TITLE
new background icon

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
TODO
- [x] @jancborchardt I need a background image for drawer: 984x656 as PNG

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
also using this as new background, if server is >= 18 and theming app is disabled.

**Comment by jancborchardt** [comment]
Background image for the drawer looks good! :+1: :)

**Comment by AndyScherzinger** [comment]
I'll give it a spin in a second, mom

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky looks good to me, only thing I find strange is that with this change the launcher xml-drawables move from v26 down to v24 which I am unsure will work (but might have been auto-gerenated by AS, so it is fine)?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky looks good to me, only thing I find strange is that with this change the launcher xml-drawables move from v26 down to v24 which I am unsure will work (but might have been auto-gerenated by AS, so it is fine)?

Yes, this was done by AS, so I assume they know what they do :rofl:

**Pull request merged**
