### PR TITLE
Set package name on all sticky intents

### PR DESCRIPTION
**Pull request by mario**
Please approve.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by tobiasKaminsky** [comment]
Rejected 
Download an image. It should be directly shown in gallery (due to MediaScanner), but it is not.

**Comment by mario** [comment]
Which gallery? Default android app?

**Comment by tobiasKaminsky** [comment]
Yes

**Comment by mario** [comment]
@tobiasKaminsky issue fixed.

**Comment by AndyScherzinger** [comment]
👍 
tested also the bug reported by @tobiasKaminsky and it works.

**Comment by tobiasKaminsky** [comment]
👍

**Pull request merged**
