### PR TITLE
Add dark screenshots

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/android/pull/6572/files?short_path=6da5b02#diff-6da5b024a398f120874671da2be95d73
image


This seems to be wrong, Settings needs to be in white font.

**Comment by tobiasKaminsky** [comment]
Cause is that settings uses "appFont", which is dynamically changed by Android.
So if Android is set to light, but in settings it is changed to dark theme, this will look wrong.

**Comment by AndyScherzinger** [comment]
> Cause is that settings uses "appFont", which is dynamically changed by Android.
So if Android is set to light, but in settings it is changed to dark theme, this will look wrong.

Nice catch @tobiasKaminsky 👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky while it is wrong for the light screenshots too: https://www.kaminsky.me/nc-dev/android-integrationTests/15208-Screenshot-master-dark-blue/images/recorded/com.nextcloud.client.SettingsActivityIT_open.png

**Comment by tobiasKaminsky** [comment]
Hm. It seems that the way we tint our Settings action bar just does not work.
I tried to tint it with Color.RED, but it is not visible at all…🤷‍♂️

**Comment by tobiasKaminsky** [comment]
> Hm. It seems that the way we tint our Settings action bar just does not work.
> I tried to tint it with Color.RED, but it is not visible at all…man_shrugging

This only happens during tests, e.g. when launching via IntentsTestRule…

**Comment by tobiasKaminsky** [comment]
I saw that preferences should be replaced with androidx.preferences: https://developer.android.com/guide/topics/ui/settings

Is it is then only a Fragment, hopefully tinting title is more easy.
For now I would keep it this way, as it is only within tests.

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
