### PR TITLE
Server unavailable

### LINKED ISSUE #894: App should give a notification when server is not reachable
My internet is down and my Nextcloud not reachable.
I think a nice enhancement of the app would be to notify me when the server is not reachable or hasn't been reachable for a certain time without me checking.

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #894 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
lib pr merged ❗️

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky increased findbugs score, my guess would be missing default block in switch/case statement

**Comment by tobiasKaminsky** [comment]
Merge "master"? No rebase? ;-)

**Comment by AndyScherzinger** [comment]
Did this on the phone... ;)

**Pull request merged**
