### PR TITLE
Implement folder structure

### LINKED ISSUE #1263: AutoUpload: upload also subfolder
Via email:
Currently a list of directories with pictures is presented. My camera app creates subdirectories, I'd like to add the parent directory and all its subdirectories.

I think this should be the default to watch the folders also recursively.
Maybe for 1.5.1 @mario?

### LINKED ISSUE #2045: Auto-Upload completely messes up the nextcloud file base
### Actual behaviour
You can set up a custom auto upload folder. You can do so by selecting the local nextcloud data folder, hoping to get something resembling the two-way sync the windows client has been able do perform for years.
Actual behavior: the android client does upload the whole folder structure, **ignoring** folder names in the process. You end up with millions of files in the ROOT folder.

After deleting the messed up crap, I can sync as often as I want, the millions of files remain on the android client. I have to delete the account completely and re-setup everything

### Expected behaviour
Any behavior other than what is happening in the 3.0.0 RC2
Best guesses: don't accept the nextcloud data folder, if keeping the folder structure is such a big deal
 
### Steps to reproduce
1. using windows set up some files in subfolders
2.  sync everything to the android client. You have to select EVERY subfolder manually to do so.
3.  set up auto-upload to upload the /sdcard/0/nextcloud/user@server/ folder to /
4. sit back and watch the android client up- and downloading all the files

Nextcloud app version:
3.0.0 RC2
Nextcloud server version:
12

### PR DESCRIPTION
**Pull request by mario**
There were so many requests for this :)

Fix #1263 
Fix  #2045

This properly implements folder structure when auto uploading files.
Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by mario** [comment]
Fixes #1263

**Comment by AndyScherzinger** [comment]
Sweet! Will have to give it a spin when I get back to my laptop.

**Comment by kaefert** [comment]
If I understand this correctly, it should also fix https://github.com/nextcloud/android/issues/2045

**Comment by mario** [comment]
Yes :)

**Comment by tobiasKaminsky** [comment]
Nice one :+1: 
Hopefully people will like it ;-)

**Comment by AndyScherzinger** [comment]
👍

**Comment by kaefert** [comment]
I've installed the nextcloud-dev version from fdroid on my device and switched the auto upload for my whatsapp folder to this version. It works as hoped, thank you!

**Comment by mario** [comment]
Awesome! :D  Thanks for reporting back @kaefert .

**Pull request merged**
