### PR TITLE
Participate apk image

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
https://github.com/nextcloud/android/issues/646

add image
rewrite nightly text
fixed url

screenshot_1488702038

### CODE REVIEW

**Comment by ldmpub** [comment]
It looks good. I will review the french translation and test the nightly build.

Many thanks !

**Comment by AndyScherzinger** [comment]
👍 Looks awesome!

@ldmpub the changed translation will not show up before this gets merged to Master!

**Comment by AndyScherzinger** [comment]
👍 Looks awesome!

@ldmpub the changed translation will not show up before this gets merged to Master!

**Comment by mario** [comment]
I think we can make the text nicer, but that's not a priority right now.

What bothers me is the name of the svg that includes the spaces. Can we turn them into "_" please? :)

**Comment by tobiasKaminsky** [comment]
The text in the image is open sans, which is often used in nextcloud.
The svg file is never used directly, but of course I can change this.

**Comment by mario** [comment]
👍 

Just has to wait for merging...

I did not mean the font, but the actual text.

Thanks for changing the filename.

**Comment by AndyScherzinger** [comment]
👍 Looks awesome!

@ldmpub the changed translation will not show up before this gets merged to Master!

**Comment by tobiasKaminsky** [comment]
@jancborchardt @eppfel please confirm? :D

**Comment by ldmpub** [comment]
@tobiasKaminsky as far as I understand whre are 1 step (code-review/pullapprove) before the merge to master?

**Comment by AndyScherzinger** [comment]
@ldmpub the PR is technically approved to be merged, we don't merge it at the moment since we have a code freeze on our master since we are already shipping the release candidates for the next release and during that time no changes except hot/bugfixes for the actual release are allowed to be merged.
If everything goes according to plan and no new bug or crashes come up the final will be release in ~2 week and then this one will be merged.

**Comment by tobiasKaminsky** [comment]
And one of @nextcloud/designers has to approve it.
...and @AndyScherzinger and @mario again as somehow pullapprove needs it again...

**Comment by AndyScherzinger** [comment]
Since we don't merge it before 1.4.2 is out the door (from what I understand) approval won't make sense since the PR will get updated again anyways (likely via a rebase)...

**Comment by ldmpub** [comment]
Hi, I'm running the last apk, and I noticed a strange behaviour:
- the new button is ok
- but it's still the old string which is displayed and it's not possible to change / improve it in Transifex (ckecked failed "%2" parametrer is missing).

How is it suppose to work?

**Comment by eppfel** [comment]
LGTM

**Comment by tobiasKaminsky** [comment]
@ldmpub Transifex is only using the strings values from master branch, so this PR must be merged first before you can see the correct version of a translated language.

**Comment by AndyScherzinger** [comment]
👍 rebased and imho ready to merge, cc @mario

**Comment by AndyScherzinger** [comment]
@mario your turn :) Can imho also be merged since 1.4.2 has been released :)

**Comment by tobiasKaminsky** [comment]
@mario ping

**Comment by AndyScherzinger** [comment]
👍 rebased and retested successfully, see above all necessary approvals, so merging

**Comment by ldmpub** [comment]
Participate screen (download images and text) are ok in dev version 20170427, can we close this issue?

**Comment by mario** [comment]
This is a PR - if you have an issue number related, I can close it - sure.

**Comment by ldmpub** [comment]
Sorry for my misunderstanding, my original issue is #646 and is already closed. Thanks.

**Pull request merged**
