### PR TITLE
Remove account use from ManageAccountsActivity

### PR DESCRIPTION
**Pull request by ezaquarii**

### CODE REVIEW

**Review by AlvaroBrey — APPROVED** [review]

**Comment by ezaquarii** [comment]
@AlvaroBrey i think CI failed due to server issues. Please make sure the test suite is run.

**Comment by AlvaroBrey** [comment]
> @AlvaroBrey i think CI failed due to server issues. Please make sure the test suite is run.

Only failing on server master, due to a version update in server that the `text` and `end_to_end_encryption` apps have not yet matched. I've opened https://github.com/nextcloud/android/pull/10095 to address that.

However the test suite passed for this PR in the stable server branch, and I don't believe server version would have any effect on these changes. We can merge this.

That being said, can you merge the `if` statements indicated by the new Codacy issues?

**Comment by ezaquarii** [comment]
@AlvaroBrey fixed codacy warnings

**Comment by AlvaroBrey** [comment]
Thanks @ezaquarii !

**Pull request merged**
