### PR TITLE
Use user id returned by server instead of entered username

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Scenario:
- Server <NC12 (or no weblogin flow)
- user enters email-adress as username and password (or others, like ldap propertiers)
- user id returned by server is now used, instead of username login field value

### CODE REVIEW

**Comment by mario** [comment]
Have you tested favorites, login, search on regular and LDAP logins?

Because Afaik (at least how I figured it out) is that entered username is
for login, but ID is for all other APIs. Hopefully :)

**Comment by tobiasKaminsky** [comment]
My only ldap server ist NC12, so this uses weblogin flow.
But I tested it on NC11 via email and there favorite is working, search is not available on NC11.

**Comment by AndyScherzinger** [comment]
👍 I only tested it with my only instance Nc12 no LDAP: login, seach, favs, photos, etc. worked fine for me

**Comment by mario** [comment]
This should have nothing to do with NC12 at all though :P

**Comment by AndyScherzinger** [comment]
I know, just provided the feedback I can give due to the limitations of my server setup :)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @mario so is this then ready to merge or does it need further changes? Just asking since it is the last remaining open PR for RC6.

**Comment by mario** [comment]
I am testing atm

**Comment by mario** [comment]
👎 
This will not fix anything. Let me try to create a solution.

**Comment by mario** [comment]
@tobiasKaminsky can we delete this?

**Pull request closed without merging**
