### PR TITLE
Add storage path chooser for local file picker

### LINKED ISSUE #3419: After uploading a file from external memory, can't upload from internal memory anymore.
### Actual behaviour
Cannot access to internal card content from the navigation/path bar in the dialog to add files to NC.
This happens after I uploaded content from external SD card.
The only workaround now for me is to move files to external memory (using a file manager app) and then uploading from NC client.

### Expected behaviour
NC to be able to access/select internal SD content from the navigation bar (e.g. `/storage/emulated/...`).
- Tell us what should happen
 
### Steps to reproduce
1. Select NC File view;
2. add new content by pressing the `+` floating button;
3. browse the external SD card (`/storage/3799-3C6C/...` in my case);
4. select and upload a file.
5. close NC client / reboot device.
6. try to add new content by pressing the `+` floating button;
3. try to browse the internal SD card: at this step, from path /storage/ 3 folders are listed: `3799-3C6C` (the external card), `emulated` (no content if selected) and `self` (no content if selected).

### Environment data
Android version: 8.0.0

Device model: 
FRD-L09 - Honor 8

Stock or customized system:
stock

Nextcloud app version:
3.4.1

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

### LINKED ISSUE #3449: App allows to go out of ../emulated , but not to come back
When selecting files, it is possible to go to /. However once being there, it shows no files found and you cannot go back in the tree anymore

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #3449
Resolves #3419

**Open Issue**
* [x] dropdown in actionbar is broken (just choose several storage paths and they just pile up in the dropdown instead of dislaying the hierachy), cc @tobiasKaminsky for help/collab
* [x]  distinguish sd-cards/storage path via the shown name (show part of the storage path?)

**Screenshots, themed**

| Chooser | Toolbar-Icon |
| --- | --- |
| device-2019-02-19-161223 | device-2019-02-19-125817 |

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
As discussed with Andy on IRC, we want to enhance this cool addition in such a way:
- on opening this FilePicker directly show dialog
- after selecting any storage, this is the topmost folder you can browse into: e.g. Music is /storage/emulated/0/Music, so you can browse into any subfolder of Music, but not in /storage/emulated/0.
- when in topmost folder, e.g. Music and one click back, the storage dialog will shown again.

**Comment by AndyScherzinger** [comment]
In addition to https://github.com/nextcloud/android/pull/3653#issuecomment-465630119
we then also need to "save" the picked "storage location" since the picker saves the lasat used folder we now also need to now for which storage location since on re-opening the picker we navigate to this folder but need to limit navigation up based on the storage location.

**Comment by tobiasKaminsky** [comment]
> In addition to [#3653 (comment)](https://github.com/nextcloud/android/pull/3653#issuecomment-465630119)
> we then also need to "save" the picked "storage location" since the picker saves the lasat used folder we now also need to now for which storage location since on re-opening the picker we navigate to this folder but need to limit navigation up based on the storage location.

this is now outdated again :rofl:

**Comment by tobiasKaminsky** [comment]
Dialog crashed when:
- open UFA
- open dialog
- suspend app
- start app again
```
  Process: com.nextcloud.client, PID: 8501
    java.lang.IllegalStateException: Bindings already cleared.
        at com.owncloud.android.ui.dialog.LocalStoragePathPickerDialogFragment_ViewBinding.unbind(LocalStoragePathPickerDialogFragment_ViewBinding.java:29)
        at com.owncloud.android.ui.dialog.LocalStoragePathPickerDialogFragment.onStop(LocalStoragePathPickerDialogFragment.java:127)
```

Fixed via closing the dialog on suspending.

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I added the remaining part and from my side it is ready now.

**Comment by AndyScherzinger** [comment]
👍 @tobiasKaminsky changes look fine to me, feel free to merge 😃

**Comment by tobiasKaminsky** [comment]
Let us wait for Codacy and hopefully they are faster now :-)

**Comment by AndyScherzinger** [comment]
> Let us wait for Codacy and hopefully they are faster now :-)

sure thing :-)

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky it seems codacy won't work properly...

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky it seems codacy won't work properly...

Indeed this is strange:
In https://github.com/nextcloud/android/pull/3653#issuecomment-467010802 the link points to:
https://app.codacy.com/app/Nextcloud/android/pullRequest?prid=3129792&bid=11428607

But on checks **Codacy/PR Quality Review ** — Not up to standards… points to https://app.codacy.com/app/dan0xii/android/pullRequest?prid=3128094

which then seems to have different settings and thus fails.

**Comment by tobiasKaminsky** [comment]
I re-setup codacy webhook.

**Comment by tobiasKaminsky** [comment]
Squashed all commits to re-trigger checks.

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky Codacy still not working

**Comment by tobiasKaminsky** [comment]
Now codacy seems to point to the right Codacy project.
We should monitor this closely if it works now as intended.

**Comment by tobiasKaminsky** [comment]
Merged, @AndyScherzinger nice collaboration :-D

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky absolutely, as always 🎉

Unfortunately the backport bot fails, could you manually create a backport? ❤️

**Comment by AndyScherzinger** [comment]
Backport is #3677

**Pull request merged**
