### PR TITLE
Implement webview welcome pages

### PR DESCRIPTION
**Pull request by mario**

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Code wise 👍 
But for me the blue border on top and bottom is way too much?
It looks better if the border is just as big as the regular header in our app? 
Also "skip", "dots" and "right arrow" should be centered vertically 

screenshot_1492531430

**Comment by mario** [comment]
a) This is the same as our regular welcome view
b) centered how? This is also the same as our regular welcome view. I have no intention of centering it to the web page itself since the page might change. (also, not sure how I'd do that - well, I am, but it is magic then)

**Comment by mario** [comment]
@tobiasKaminsky if you agree with my comments, please let me know and I'll merge.

**Comment by tobiasKaminsky** [comment]
Not centering the website itself, only the text elements.

An idea

 -->

**Comment by mario** [comment]
@tobiasKaminsky will do it like that.

**Comment by tobiasKaminsky** [comment]
I have already done it, so I can push the changes ;-)

**Comment by mario** [comment]
Do it and I will check

**Comment by mario** [comment]
Merging.

**Comment by jancborchardt** [comment]
What about the top bar? Will there be text in it like the app name? Or should we remove it?

**Comment by tobiasKaminsky** [comment]
@jancborchardt It is up to you :-D
Just open up a new issue with your wish and I am happy to do it.

**Pull request merged**
