### PR TITLE
Hide provider when changing password

### LINKED ISSUE #1518: Change password: hide "get new provider"
If user wants to change a password, one gets following screen:

Only password is editable.
--> If server url is fixed, do not show "do you net have a server yet..." 

This is only valid for Server <12 as >=12 will use weblogin flow.

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
fixes #1518 
This is only if the old login method is used.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by mario** [comment]
Would love to also hide the arrow in the server entry please :)

**Comment by tobiasKaminsky** [comment]
@mario @AndyScherzinger I hide now also the arrow, please re-approve.

**Comment by AndyScherzinger** [comment]
👍

**Comment by mario** [comment]
👍

**Pull request merged**
