### PR TITLE
Implement other interface functions regarding file upload for upload worker

### PR DESCRIPTION
**Pull request by JonasMayerDev**
Reimplements the existing interface functions like get upload status or add transfer progress listener for new upload worker.
Fixes: https://github.com/nextcloud/android/issues/10954 and probably a lot of other issues where code used that functions but just did nothing

- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by TobiPeterG** [comment]
This fixes #11974 for me (and likely related issues)

**Comment by TobiPeterG** [comment]
> @TobiPeterG are you sure you mean this PR? I mean it's totally possible in the end it also should fix some bugs regarding uploading but it's a little bit random that you found this PR? Are you sure you don't mean this PR I mentioned in the Issue:  https://github.com/nextcloud/android/pull/12246

All I can say is: with the original app I got the notification spamming
With this version, no issues appear at all (really, no conflict issue at all)
However, it might be completely unrelated. Maybe something else was merged that fixed it
I'll try the original app again

**Comment by JonasMayerDev** [comment]
@TobiPeterG nice and thanks but just to be completely sure, there is a similar PR from me that is about reducing the notification spamming: https://github.com/nextcloud/android/pull/12246.
This one, where we are right now #12247 could also fix the issue but it would be a little surprising to me :)

**Comment by TobiPeterG** [comment]
> @TobiPeterG nice and thanks but just to be completely sure, there is a similar PR from me that is about reducing the notification spamming: https://github.com/nextcloud/android/pull/12246.
> This one, where we are right now #12247 could also fix the issue but it would be a little surprising to me :)

Well, I don't know what solved it, I just checked the official app again. Still the notification spamming (and errors at all)
With this version, I don't get any issues (though that could mean that the error isn't being shown?)

**Comment by TobiPeterG** [comment]
> @TobiPeterG if really this PR changed it and not https://github.com/nextcloud/android/pull/12246 I think this could maybe fix the root cause (I don't know how exactly).


Hmm the issue also doesn't appear with the other app version.
However, it didn't seem to upload any of the images yet

**Comment by brentobi** [comment]
@JonasMayerDev
A laymans idea as to why this PR could resolve the sync error from https://github.com/nextcloud/android/issues/11974:

Is the following assumption true for your change to [`FieldUploader::isUploading`](https://github.com/nextcloud/android/pull/12247/files#diff-3bd067a5809ebf045c846e5baeb5cd2628c83471ccf76ec39adde1601d650361L1251)?

**Previous behaviour(?)**: Only pending uploads were detected, which were triggered by the same instance of FileUploader. (`mPendingUploads` is private)
**New behaviour(?)**: Pending uploads of all instances of FileUploader are detected because `mUploadsStorageManager` seems to read from DB.

**If that assumption is true**, it would explain what I think causes the sync errors on my device. Key observation was that `FileSyncWork::doWork` was running twice in parallel, triggering a second `FileUploader::uploadNewFile` before the first upload even started.

If I understand this PR correctly the second instance of the FileUploader would now detect a pending upload of the first one because it is read from db instead of a private field. (unless there is a very close-call race condition between checking and scheduling uploads)

I posted my reduced and annotated **log files here** some time ago: https://github.com/nextcloud/android/issues/11974#issuecomment-1765444062

P.S.: Thanks for your work!

Kind regards

**Comment by JonasMayerDev** [comment]
> > @TobiPeterG if really this PR changed it and not https://github.com/nextcloud/android/pull/12246 I think this could maybe fix the root cause (I don't know how exactly).
> 
> 
> Hmm the issue also doesn't appear with the other app version.
> However, it didn't seem to upload any of the images yet

@TobiPeterG did uploading work with this PR or are both versions not uploading?

**Comment by TobiPeterG** [comment]
> > > @TobiPeterG if really this PR changed it and not https://github.com/nextcloud/android/pull/12246 I think this could maybe fix the root cause (I don't know how exactly).
> > 
> > 
> > Hmm the issue also doesn't appear with the other app version.
> > However, it didn't seem to upload any of the images yet
> 
> @TobiPeterG did uploading work with this PR or are both versions not uploading?

Both haven't yet, but I don't know if I'll have to wait a bit longer

**Comment by JonasMayerDev** [comment]
@brentobi currently there are 2 methods of uploading files. For Android i think it was 10 and older we use a Service that runs the upload task in the background. For newer android versions we use a Worker (FileUploadWorker.tk) to do the upload. The changes here implement old functions that worked for Upload Service now also for the upload worker. The variable you mentioned is not used when the Worker is used for upload so i think it's sadly more complicated. What could be the case is that as you said the hopefully now also for the worker working implementation of isUploading fixes the issue? But im not sure if really this PR fixes the issue or master already fixes the Issue or if the issue is even solved at all by any changes we made or if just uploading is broken with this PR xd I think testing is now needed maybe also from people that have the issue... Thanks for looking into it :)

**Review by alperozturk96 — APPROVED** [review]

**Pull request merged**
