### PR TITLE
i18n: Change to a capital letter

### PR DESCRIPTION
**Pull request by Valdnet**
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
Does this trigger some kind of updated notice in Transifex? So that other translators are aware and fix this too

**Comment by Valdnet** [comment]
@AlvaroBrey Translators receive information about an untranslated text string. They will have to translate it again, but they can use the translation suggestion 😉.

**Comment by AndyScherzinger** [comment]
Important part for dev is that changes in existing strings need to be backported to all `stable-*` branches, else the transifex automation won't work and translations don't get pushed to this repo anymore. (This is just an info, I already labeled it for the backports, of course the merged would still need to be done after the bot created the backports)

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Thanks @Valdnet !

**Pull request merged**
