### PR TITLE
Add support for photo urls in vCards

### PR DESCRIPTION
**Pull request by rhari991**
fixes: #1564 

(edited by Tobias, so github will automatically close the related issue)

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
👍 
Thank you very much for this contribution!
I have tested it and it is working fine 🎉 

Just to be curious, why do you already download it in convertPhotos()?

**Comment by rhari991** [comment]
In order to insert the picture into the contacts, you need to download it locally first - I don't think you can give an image url.

**Comment by AndyScherzinger** [comment]
👍 code looks good, rebased to latest master.

**Comment by AndyScherzinger** [comment]
👍 code looks good, rebased to latest master...merged

Awesome work @rhari991 🎉

**Pull request merged**
