### PR TITLE
add transparency to navigation bar for image preview

### PR DESCRIPTION
**Pull request by apicellaj**
Adds transparency to the navigation bar when viewing an image.

Fixes: #1638

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @apicellaj,

thanks for another Hacktoberfest session and PR 😃 

One small issue is that now the bar is transparent even when the image can be display (jsut use a text file and rename the file extension to .jpg an open it:

device-2017-10-11-004008

In that case the bar should not be transparent 😀 

cc: @jancborchardt for later approval from designers since you opened the issue itself.

**Comment by apicellaj** [comment]
Hi @AndyScherzinger ,

I'm glad to be back! 😃 Thanks for pointing out this issue. I went ahead and pushed the transparency change to the theme which is probably the way I should have done it initially.

**Comment by AndyScherzinger** [comment]
Hi @apicellaj,

happy to have you back ❤️ 
As for the corrupt version, could you paint it black please? :)
device-2017-10-11-115001

**Comment by jancborchardt** [comment]
Thanks a lot @apicellaj! :) Also @AndyScherzinger’s remarks make sense. Good otherwise!

**Comment by apicellaj** [comment]
@AndyScherzinger Is there a particular way you would recommend painting the navigation bar black? Making programmatic changes to the navigation bar seems like the way to go but the ViewPager makes it difficult to paint properly when swiping into the corrupt image. I'm also assuming that we want to keep the background white when an image fails to load.

Should the Action Bar be made black as well?

**Comment by AndyScherzinger** [comment]
Hi @apicellaj,

I’d also say programmatically is the way to go. The action bar for a corrupt image should actually be colored in the primary color,the being retrieved via the theme utility class since it can be dynamically themed via the server. Background for corrupt images should stay white if possible.

**Comment by jancborchardt** [comment]
Maybe the background for corrupt images should also be black (like when viewing and loading too). Otherwise the change of black to white to black is very jarring when swiping through your images.

**Comment by AndyScherzinger** [comment]
Then let's go for a black background which basically solves the navigation bar coloring for corrupt images :)

**Comment by AndyScherzinger** [comment]
And then we also don't need to change anything for the action bar coloring too :)

**Comment by AndyScherzinger** [comment]
👍 fine and tested successfully! 🎉

**Comment by AndyScherzinger** [comment]
pinging @mario for review/approval

**Comment by mario** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/nextcloud/android/pull-request/1643/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=nextcloud/android)

**Comment by mario** [comment]
@AndyScherzinger merge when Drone is done.

**Comment by AndyScherzinger** [comment]
merged!
Thanks @apicellaj for yet another great hacktoberfest contribution! :)

**Comment by jancborchardt** [comment]
Yep, thanks a lot for the fix @apicellaj! :)

**Pull request merged**
