### PR TITLE
Retry upload in thread

### LINKED ISSUE #1975: NetworkOnMainThreadException
```
android.os.NetworkOnMainThreadException: 
  at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork (StrictMode.java:1273)
  at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read (OpenSSLSocketImpl.java:794)
  at java.io.BufferedInputStream.fillbuf (BufferedInputStream.java:175)
  at java.io.BufferedInputStream.read (BufferedInputStream.java:234)
  at org.apache.commons.httpclient.HttpConnection.isStale (HttpConnection.java:506)
  at org.apache.commons.httpclient.HttpConnection.closeIfStale (HttpConnection.java:431)
  at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.closeIfStale (MultiThreadedHttpConnectionManager.java:1313)
  at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry (HttpMethodDirector.java:382)
  at org.apache.commons.httpclient.HttpMethodDirector.executeMethod (HttpMethodDirector.java:171)
  at org.apache.commons.httpclient.HttpClient.executeMethod (HttpClient.java:397)
  at org.apache.commons.httpclient.HttpClient.executeMethod (HttpClient.java:323)
  at com.owncloud.android.lib.common.OwnCloudClient.executeMethod (OwnCloudClient.java:232)
  at com.owncloud.android.utils.ConnectivityUtils.isInternetWalled (ConnectivityUtils.java:68)
  at com.owncloud.android.files.services.FileUploader$UploadRequester.retryFailedUploads (FileUploader.java:385)
  at com.owncloud.android.ui.activity.UploadListActivity.onOptionsItemSelected (UploadListActivity.java:213)
  at android.app.Activity.onMenuItemSelected (Activity.java:3204)
  at android.support.v4.app.FragmentActivity.onMenuItemSelected (FragmentActivity.java:368)
  at android.support.v7.app.AppCompatActivity.onMenuItemSelected (AppCompatActivity.java:195)
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected (WindowCallbackWrapper.java:108)
  at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected (WindowCallbackWrapper.java:108)
  at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick (ToolbarActionBar.java:65)
  at android.support.v7.widget.Toolbar$1.onMenuItemClick (Toolbar.java:202)
  at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected (ActionMenuView.java:780)
  at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected (MenuBuilder.java:822)
  at android.support.v7.view.menu.MenuItemImpl.invoke (MenuItemImpl.java:171)
  at android.support.v7.view.menu.MenuBuilder.performItemAction (MenuBuilder.java:973)
  at android.support.v7.view.menu.MenuPopup.onItemClick (MenuPopup.java:127)
  at android.widget.AdapterView.performItemClick (AdapterView.java:345)
  at android.widget.AbsListView.performItemClick (AbsListView.java:1547)
  at android.widget.AbsListView$PerformClick.run (AbsListView.java:3821)
  at android.widget.AbsListView$3.run (AbsListView.java:5843)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:158)
  at android.app.ActivityThread.main (ActivityThread.java:7225)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

This happens when clicking on "retry failed uploads" (on expert mode I guess).
I cannot reproduce it.

Here we use IsInternetWalled() and this is maybe on main thread:
https://github.com/nextcloud/android/blob/45bcdebd9dd51c60ce7870dbe0547d2243cfe54c/src/main/java/com/owncloud/android/files/services/FileUploader.java#L384-L385

@mario do you have an idea how we can do this in thread/async task?

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #1975 

Signed-off-by: tobiaskaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by mario** [comment]
Since the method could be called from other places, maybe instead put the thread directly inside the method?

**Comment by tobiasKaminsky** [comment]
Both of the calling occurences are already in thread and 
https://github.com/nextcloud/android/blob/c3889f2afc40f12f4967d6304eb44c15ff42c212/src/main/java/com/owncloud/android/utils/FilesSyncHelper.java#L232-L237

still needs a thread as it is checking "internetWalled" as an early exit, I guess.

**Comment by mario** [comment]
k

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
👍 fine by me

**Pull request merged**
