### PR TITLE
delay instant upload when metered wifi is used

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
ref: #154

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Code looks good to me. You wrote delay but I couldn't find one. Did you mean postpone until you are connected to an unmetered wifi network?

**Comment by tobiasKaminsky** [comment]
Just have a look where the isAppConnectedViaUnmeteredWiFi() function is used.
There the delay is set.

**Comment by AndyScherzinger** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
Merge? :smiley:

**Pull request merged**
