### PR TITLE
Auto upload: Prioritize Screenshots Folder

### LINKED ISSUE #1493: Auto upload: Screenshots folder should have priority sorting
Currently there’s two folders important for me to auto-upload: Camera and Screenshots.

Camera is correctly sorted up top. Screenshots however is all the way on the bottom between folders of album covers and such on the SD card. It should be given priority sorting and put to the top, even when not synced.

What do you think @tobiasKaminsky @AndyScherzinger?

### PR DESCRIPTION
**Pull request by tilosp**
Closes #1493

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tilosp thanks for the PR, but it is unfortunately not that is while still easy ;) Basically the sorting needs to do a compare in case both folder names are _in_ the priority list because then you need to do a 
```
f1.getFolderName().toLowerCase(Locale.getDefault()).compareTo(
-                            f2.getFolderName().toLowerCase(Locale.getDefault()));
```
simply because it should just prioritize the special folders over the other while still internally sort all prioritized folders (since it is now a list of possible values) because also the prioritized folders should be sorted alphanumerically :)

Sorry for the complication :(

**Comment by tobiasKaminsky** [comment]
As a related question: we are sure that on every language "Camera" and "Screenshot" is used for the folders?

**Comment by tilosp** [comment]
@AndyScherzinger sure i will change it.

I thought it makes more sense to use the order of the array, to let the developer define the order. This would be useful if we later prioritize a folder starting with a or b and we want camera to stay at the top.

**Comment by AndyScherzinger** [comment]
> I thought it makes more sense to use the order of the array, to let the developer define the order. This would be useful if we later prioritize a folder starting with a or b and we want camera to stay at the top.

Right! Haven't thought about that. So sorry again for the confusion but yes, it makes sense to leave it as it just in case a different sorting than alphanumerically is needed at some point! 👍 

> As a related question: we are sure that on every language "Camera" and "Screenshot" is used for the folders?
Don't know but I'd guess so, since your phone is German, what are the folder names on your phone? But yes, strings isn't bulletproof since any oem would have the power to change this, but then it just won't be a non-prioritized folder anymore, no harm in that.

**Comment by jancborchardt** [comment]
Awesome stuff @tilosp, thank you for picking this up! :)

**Comment by mario** [comment]
@tobiasKaminsky we are not and I don't think they are.

**Comment by jancborchardt** [comment]
@tobiasKaminsky @mario even if, it's a good starting point and we can add/fix others as we go along, right?

**Comment by mario** [comment]
Sure @jancborchardt. 👍 
@AndyScherzinger ? :)

**Comment by AndyScherzinger** [comment]
Sure!
Haven't tested it yet so can't approve right away since it else might get merged by accident and @tobiasKaminsky wanted to do a RC3 release tomorrow.
Other than that, code-wise fine as already stated 👍

**Comment by tobiasKaminsky** [comment]
👍 Working fine for me.
I created https://github.com/nextcloud/android/tree/stable-3.0.x which is our new stable-3.0.x branch as discussed.
So we can now go on with master and merge stuff.
If we want to do bug fixing (hopefully not that much), we have to backport this.

**Comment by AndyScherzinger** [comment]
:+1: all fine by me.
For the 3.0 final we then still need to backport the translations

**Comment by tobiasKaminsky** [comment]
> For the 3.0 final we then still need to backport the translations

Right, added/changed this to #1884 and #150, so we do not forget.

**Pull request merged**
