### PR TITLE
Changelog for 3.3.1

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍

**Comment by MorrisJobke** [comment]
That would be the log, that the changelog script creates from the PR titles. It checks stable-3.3.0...stable-3.3.1 and shows then all PRs that where merged in there (pure commits to the branch are not fetched - only the merges):


* [android#3066](https://github.com/nextcloud/android/pull/3066) Backport #3033: quickfix for unknown SharingTypes
* [android#3100](https://github.com/nextcloud/android/pull/3100) Backport #3097: base uri was retrieved too early
* [android#3154](https://github.com/nextcloud/android/pull/3154) Backport #3153:Notification: move client creation to thread
* [android#3156](https://github.com/nextcloud/android/pull/3156) 3.3.1 RC1
* [android#3169](https://github.com/nextcloud/android/pull/3169) 3.3.1 RC2
* [android#3172](https://github.com/nextcloud/android/pull/3172) Backport #3114: create a task for each button
* [android#3195](https://github.com/nextcloud/android/pull/3195) Backport #3189: use another svg as source for talk icon. previous got corrupted on 6.0
* [android#3198](https://github.com/nextcloud/android/pull/3198) Bump to 3.3.1

**Comment by MorrisJobke** [comment]
I also can adjust the script to strip some parts from the title (like the "Backport #NUMBER").

**Comment by MorrisJobke** [comment]
Added: https://github.com/nextcloud/github_helper/commit/e3fccc9f1b0df12c445ede6c0e10ce1245c007cc


```
php android.php generate:changelog stable-3.3.0 stable-3.3.x
```

This will now generate:

* [android#3066](https://github.com/nextcloud/android/pull/3066) Quickfix for unknown SharingTypes
* [android#3100](https://github.com/nextcloud/android/pull/3100) Base uri was retrieved too early
* [android#3154](https://github.com/nextcloud/android/pull/3154) Notification: move client creation to thread
* [android#3156](https://github.com/nextcloud/android/pull/3156) 3.3.1 RC1
* [android#3169](https://github.com/nextcloud/android/pull/3169) 3.3.1 RC2
* [android#3172](https://github.com/nextcloud/android/pull/3172) Create a task for each button
* [android#3195](https://github.com/nextcloud/android/pull/3195) Use another svg as source for talk icon. previous got corrupted on 6.0
* [android#3198](https://github.com/nextcloud/android/pull/3198) Bump to 3.3.1

**Pull request merged**
