### PR TITLE
Remove modified flavor

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
This is not needed any more as the brander is working with gplay flavor.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky now it needs a rebase ;)

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
Rebase pls and merge.

**Comment by AndyScherzinger** [comment]
👍

**Pull request merged**
