### PR TITLE
Extract html code and make it non-translatable

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Some translator had problems with the html code in the translation strings and added a whitespace after "<", resulting in seeing html code instead of the real link.
So this extracts the html code and makes it non translatable.

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 looks good to me

**Comment by mario** [comment]
Please resolve the conflicts so I can approve.

**Comment by AndyScherzinger** [comment]
resolved :)

**Comment by AndyScherzinger** [comment]
👍 pinging @mario :)

**Comment by mario** [comment]
👍

**Pull request merged**
