### PR TITLE
Reduce apk size by ~20 MB

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed
- [ ] Test also manually, maybe @AndyScherzinger

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by AndyScherzinger** [comment]
Works like a charm

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky lablled it backport since we would have a longer RC phase than the bugfix releases and I think cutting down the APK size by 20MB is something we should do right away, not adding it with 3.14.0 and cutting it down with 3.14.1 or 3.15.0 respectively

**Comment by tobiasKaminsky** [comment]
Good :+1:

**Pull request merged**
