### PR TITLE
codacy: remove unused code

### PR DESCRIPTION
**Pull request by AndyScherzinger**
get rid of the last two remaining "unused code" warnings in codacy 🎉

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky @MorrisJobke any idea about the duplication of the codacy reports?

There is now https://app.codacy.com/app/nextcloud-android-bot/android/dashboard while we always used and organization structure which is https://app.codacy.com/app/Nextcloud/android/dashboard (and is imho the one that should be used...)

**Comment by MorrisJobke** [comment]
> @tobiasKaminsky @MorrisJobke any idea about the duplication of the codacy reports?

No idea - never worked with codify

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky @MorrisJobke any idea about the duplication of the codacy reports?

I tried to move the commit message away from "you" to our bot: AndyScherzinger (Andy Scherzinger) deleted a comment from codacy-bot 3 hours ago

But maybe I failed somehow...?

**Comment by AndyScherzinger** [comment]
> But maybe I failed somehow...?

I wouldn't say that it is just that the bot and I have the projects configured on codacy. Can you add the bot (needs the email address) to the organization on codacy? After that I can probably delete my account and re-register (being invited by you to the organization on codacy).

**Comment by tobiasKaminsky** [comment]
I removed the projects from nextcloud-android-bot and added nextcloud-android-bot to nextcloud organization.

**Comment by tobiasKaminsky** [comment]
:+1: 
(codacy now runs with nextcloud-android-bot rights)

**Comment by AndyScherzinger** [comment]
Sweet! :) cc @mario for second review :)

**Comment by AndyScherzinger** [comment]
New week, new ping :grin: @mario please :heart:

**Comment by mario** [comment]
👍

**Pull request merged**
