### PR TITLE
Sync file before opening

### PR DESCRIPTION
**Pull request by mario**
This makes sure we sync the file before opening.

Since this is requested by a client of ours, I'd like it in 2.0.0.

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@mario I force the download only for "document" typefile not for all files (already in cache)

**Comment by AndyScherzinger** [comment]
doesn't work for me...

* created a txt
* downloaded, opened
* closed
* changed on server
* opened on client
* still seeing the older version

**Comment by mario** [comment]
Will investigate....

**Comment by mario** [comment]
Closing. There'll be another version soon.

**Pull request closed without merging**
