### PR TITLE
Lint: fix UnknownIdInLayout: use correct reference to an id that is in the current layout

### PR DESCRIPTION
**Pull request by AndyScherzinger**
fixed all (4) UnknownIdInLayout lint issues

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
pinging @mario @tobiasKaminsky for review :)

**Comment by tobiasKaminsky** [comment]
👍

**Comment by AndyScherzinger** [comment]
rebased! pinging @mario for second approval

**Comment by mario** [comment]
👍

**Pull request merged**
