### PR TITLE
Release 1.1.0 stable

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Version number bumped accordingly, version name "1.1.0" and updated changelog.

Please review @tobiasKaminsky @przybylski @jancborchardt @LukasReschke 

PS: Please +1 if changes are fine with you, merge will be done prior to releasing 1.1.0 stable which is in the near future since the RCs are very stable and no crashes&ANRs have been reported on Google Play or in the forums that haven't been fixed yet. Btw the changelog now only documents stable releases since I don't think documenting all RCs for eternity doesn't make sense.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by przybylski** [comment]
👍

**Comment by AndyScherzinger** [comment]
Thank guys! @ LGTM plugin if you could start to properly work again that would be great....

**Comment by jancborchardt** [comment]
Awesome! It's really cool having you folks pushing the Android development. :)

**Pull request merged**
