### PR TITLE
Stop file only if removed file is an audio file

### LINKED ISSUE #7457: Error
************ CAUSE OF ERROR ************

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2691f5b u0 com.nextcloud.client/.media.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2188)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

************ APP INFORMATION ************
ID: com.nextcloud.client
Version: 30140090
Build flavor: gplay

************ DEVICE INFORMATION ************
Brand: samsung
Device: beyond0
Model: SM-G970F
Product: beyond0lteeea

************ FIRMWARE ************
SDK: 29
Release: 10
Incremental: G970FXXU9DTJA

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #7457 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### Testing 
Writing tests is very important. Please try to write some tests for your PR. 
If you need help, please do not hesitate to ask in this PR for help.

[unit tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#unit-tests)
[instrumented tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#instrumented-tests)
[UI tests](https://github.com/nextcloud/android/blob/master/CONTRIBUTING.md#ui-tests)

- [x] Tests written, or not not needed

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]

**Comment by InfamousUser** [comment]
Should we test this or will it delete our kittens?

**Comment by AndyScherzinger** [comment]
Yes, for even ones, don't check the odd numbers

**Comment by InfamousUser** [comment]
I'm sorry, what? Don't check odd kittens?

**Comment by axheli** [comment]
@AndyScherzinger @tobiasKaminsky  Installed the apk when under the media tab selected a photo and was about to delete the photo with no error. Only problem i see if that the media tab only populates about 166 photos and they are not in the correct order.

**Comment by InfamousUser** [comment]
Still crashes here, not sure what is causing them now.

**Comment by AndyScherzinger** [comment]
@axheli thanks for testing. Since you mentioned the ordering can you elaborate on it as in how the ordering is wrong or unexpected?

**Comment by axheli** [comment]
Okay so in the main page have selected order by Newest first.
image
Then i go into Media tab the files are all over the place and not listed in the correct order.
image
When i leave the media tab and go back into the main tab the option to list files is gone. 
image


Also, the media tab only shows a max of 166 photos and i have over 2K. I hope this helps. let me know if you need anything else @AndyScherzinger

**Comment by AndyScherzinger** [comment]
as for the sorting header that is fixed via: #7289
as for the sorting, afaik the images are shown ordered by date (don't know if newest first or oldest first, @tobiasKaminsky might know) so they are shown in the way the server provides them. So whatever you chose on the file list doesn't have any impact on the media view.

**Comment by axheli** [comment]
sorting header that is fixed: okay cool so im guessing that will be out on the next verzion? 

hmmm idk the ios app works a different when you select the media tab it lists all the files as you choose them but it concerns me that when you go into the media tab and go back in the mail files tab the categorize option is gone

**Comment by axheli** [comment]
image

**Comment by AndyScherzinger** [comment]
The link refers to the iOS solution for loading media files for the media screen, yes. For the header, sorting stuff the me mentioned #7289 will ship with 3.15 so it won't ship with a bugfix release but the next feature release (except in case you get @tobiasKaminsky to do another bugfix release after the actual one)

**Comment by tobiasKaminsky** [comment]
please continue in a new / fitting issue.
This has nothing to do with this PR.

**Pull request merged**
