### PR TITLE
First run: make buttons bold

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fixes https://github.com/nextcloud/android/issues/3304

Before & after
 

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 looks good to me

**Comment by AndyScherzinger** [comment]
👍

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky just asking your opinion on this: should we backport this for 3.4.0? Small change, we probably do a RC2, what is released is released :)

**Comment by tobiasKaminsky** [comment]
I would go with the same idea for our dot releases: only backport fixes that are critical.
Just to avoid too much work.
Maybe we can change this once the backport bot is working for us too…

**Comment by AndyScherzinger** [comment]
> Maybe we can change this once the backport bot is working for us too…

Nice, a backport bot would be awesome :)

Fine by me!

**Comment by jancborchardt** [comment]
Thanks a lot! :) Backport not necessary here.

**Pull request merged**
