### PR TITLE
Use LeakCanary in debug mode

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
See: https://square.github.io/leakcanary/fundamentals/

### CODE REVIEW

**Review by AlvaroBrey — APPROVED** [review]

**Comment by AlvaroBrey** [comment]
Nice, but tests are failing for some reason. I seem to remember that LeakCanary freezes the app to take memory snapshots, so that may mess with our CI tests. Let's see if they keep failing after the rebase.

**Comment by AlvaroBrey** [comment]
Apparently LeakCanary is disabled by default  only in tests that use androidx `InstrumentationTestRunner`: https://github.com/square/leakcanary/pull/1436/files
For all other tests, we could probably disable it manually in `@Before` with something like this: https://github.com/square/leakcanary/pull/1436/files#diff-5021ef7717778dad8ab1d9befeeb28d40c2435286b6d9e9f22db2f1542c363bbR98

**Comment by tobiasKaminsky** [comment]
Can we have this "implementation" based on whether we are on CI or not? 
We already have ciBuild in build.grade

**Comment by AlvaroBrey** [comment]
> Can we have this "implementation" based on whether we are on CI or not? We already have ciBuild in build.grade

That seems to have worked. @tobiasKaminsky feel free to merge if it looks right

**Review by AlvaroBrey — APPROVED** [review]

**Pull request merged**
