### PR TITLE
fix quota display

### PR DESCRIPTION
**Pull request by AndyScherzinger**
fixing the fetching of quota information from server via https://github.com/nextcloud/android-library/pull/28 (v 1.0.10) 
- Big Thanks to @mario for the library patch 🎉 

@tobiasKaminsky has also been merged to beta (20170117) and should imho be part of 1.4.1. What do you think?

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
shipped with beta 20170117 via the android-library dependency

**Comment by AndyScherzinger** [comment]
@mario do you have a server v9 running with which this patch could be tested?

**Comment by mario** [comment]
@AndyScherzinger no, but I will get it running for you later today :)

**Comment by AndyScherzinger** [comment]
I just need two users then one with unlimited and one with limited quota to check if this still works for the two given scenarios :)

Thanks a lot!!!! ❤️

**Comment by AndyScherzinger** [comment]
Just testdrove this PR against @mario's Nc9 installation and the quota is displayed as expected. @tobiasKaminsky @mario can be merged after review to be part on 1.4.1 RC4 :)

**Comment by tobiasKaminsky** [comment]
I'll trust you ;)
:+1:

**Pull request merged**
