### PR TITLE
Fix NPE

### LINKED ISSUE #1511: RC4/5: NPE in FilesSyncHelper.scheduleNJobs
```
java.lang.RuntimeException: 
  at android.app.job.JobService$JobHandler.handleMessage (JobService.java:147)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6688)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
Caused by: java.lang.NullPointerException: 
  at com.owncloud.android.utils.FilesSyncHelper.scheduleNJobs (FilesSyncHelper.java:258)
  at com.owncloud.android.jobs.NContentObserverJob.onStartJob (NContentObserverJob.java:59)
  at android.app.job.JobService$JobHandler.handleMessage (JobService.java:143)
```

LoC:
```
SyncedFolderProvider syncedFolderProvider = new 
SyncedFolderProvider(MainApp.getAppContext().getContentResolver());
```
I'd say ```MainApp.getAppContext()``` in ```null```

### PR DESCRIPTION
**Pull request by mario**
resolves #1511

Signed-off-by: Mario Danic <mario@lovelyhq.com>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
❗️ rebased to check if CI turns green

**Comment by AndyScherzinger** [comment]
👍 tested if creating / changing auto upload still works, code change looks good

@tobiasKaminsky this PR should, in case you are fine with the code change, also be part of the RC since it is one of the remaining reported crashes for 2.0.0RCx

**Comment by tobiasKaminsky** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
rebased, please merge after checks turned green, I'll be afk...

**Pull request merged**
