### PR TITLE
Feedback link is removed from setting ang participate is changed to c…

### PR DESCRIPTION
**Pull request by rajput2122**
Resolves: #4112 
Changes: removed feedback link from setting and changed participate to community in drawer and also changed the required in ParticipateActivity 
Screenshot_20190902-171901_Nextcloud QA
Screenshot_20190902-172039_Nextcloud QA

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @rajput2122, the changes look fine! 👍 Just one small thing. Could you remove the changes from the `strings.xml`files except for the `vales/strings.xml` file. The reason is that we are using transifex (and a bot for fetching) for the translations so such files get overridden every night plus it keeps the PR small and tidy so it is easier to review for the developers. Other than that it looks fine too me, pinging @tobiasKaminsky and @jancborchardt for reviews :)

Again thanks for making an effort and contributing to Nextcloud ❤️

**Comment by jancborchardt** [comment]
Seems good! Not sure if that should be tackled in this PR or separately, but the "Participate" view could use some design enhancement too, like for example add some whitespace above the headings.

**Comment by rajput2122** [comment]
> Seems good! Not sure if that should be tackled in this PR or separately, but the "Participate" view could use some design enhancement too, like for example add some whitespace above the headings.

sir is this pull request is wrong?

**Comment by rajput2122** [comment]
if any issue related to this pull request kindly tell me.DCO is showing cross sign and i don't get any approval for this request

**Comment by AndyScherzinger** [comment]
@rajput2122 the PR is fine, Jan just found further issues that have been present before this PR and asked if they should be resolved in your PR or in a new one. To keep this PR simple I'd say any further changes should be done in an extra PR.

**Comment by rajput2122** [comment]
> @rajput2122 the PR is fine, Jan just found further issues that have been present before this PR and asked if they should be resolved in your PR or in a new one. To keep this PR simple I'd say any further changes should be done in an extra PR.

Thanks sir . Actually i got worried because as you and @jancborchardt sir reviewed this but it is showing review required . So i asked is there any issue.

**Comment by AndyScherzinger** [comment]
No worries, any pr gets this label so it'll show up on review lists for all developers. So no particular reason 👍

It's already late in Germany, so I hope that @tobiasKaminsky can get it merged tomorrow 😊

**Comment by AndyScherzinger** [comment]
@rajput2122 Thanks for your contribution ❤️ I did a rebase and removed all unnecessary changes.
@jancborchardt I took the liberty to already include top-spacing for the headlines, feel free to open an issue for further improvements (to be done in a new PR) :)
device-2019-09-03-174939

**Pull request merged**
