### PR TITLE
Make auto upload light working again

### PR DESCRIPTION
**Pull request by tobiasKaminsky**

### CODE REVIEW

**Comment by mario** [comment]
👍 

Looks decent :)

**Comment by mario** [comment]
Let's get this into 2.0.0 @AndyScherzinger

**Comment by AndyScherzinger** [comment]
of course :) While it needs to hide the expert mode I guess ;)

**Comment by mario** [comment]
I agree. Can we disable expert mode option to show at all if light auto upload is present?

**Comment by mario** [comment]
Hm, without compiling it looks like you don't remove the "Expert mode" entry from preferences, but just don't set what happens when you click?

**Comment by tobiasKaminsky** [comment]
Right, thank you!
I was just too fast and did not even teste it as I thought it is just a minor one... :S

**Comment by mario** [comment]
👍 

Decent enough, thanks for the correction!

@AndyScherzinger please ;)

**Comment by AndyScherzinger** [comment]
👍 fine by me :)

**Pull request merged**
