### PR TITLE
Add SPDX header

### PR DESCRIPTION
**Pull request by AndyScherzinger**
- [x] Tests written, or not not needed

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Hi @binsky08 👋 
In an effort to introduce standardized SPDX license/copyright headers I stumbled upon https://github.com/nextcloud/android/pull/12808/files#diff-1cd51989fa7e236d86ee972bf863e97cec672c42af958f0259c8b6cc86570e2f which has been labelled GPL3+ instead of AGPL3+ as stated in the projects readme file. So I guess this slipped through also during the review. So just wanted to check with that you are fine with changing it to AGPL3+? Thanks for your feedback in advance 🙏

**Comment by AndyScherzinger** [comment]
Hi @David-Development - me again. I missed one class last time, so fine to change https://github.com/nextcloud/android/pull/12808/files#diff-14695808b4cb09edc1b66d908f8551f8ef3af67c23346292f3d49961d1e52a0e from GPL3+ to AGPL3+?

**Comment by David-Development** [comment]
@AndyScherzinger Yes, for sure! 🚀

**Comment by binsky08** [comment]
> Hi @binsky08 👋 
> In an effort to introduce standardized SPDX license/copyright headers I stumbled upon https://github.com/nextcloud/android/pull/12808/files#diff-1cd51989fa7e236d86ee972bf863e97cec672c42af958f0259c8b6cc86570e2f which has been labelled GPL3+ instead of AGPL3+ as stated in the projects readme file. So I guess this slipped through also during the review. So just wanted to check with that you are fine with changing it to AGPL3+? Thanks for your feedback in advance 🙏 

sure, feel free to change it :)

**Pull request merged**
