### PR TITLE
Add direct editing capability

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Needed by: https://github.com/nextcloud/richdocuments/issues/318

--> shows collabora only if 4.0 on server is used.

Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky for some reasons we now get a lint error (which hasn't been shown before):
```
../../../src/main/java/com/owncloud/android/ui/helpers/FileOperationsHelper.java:118: Field requires API level 19 (current min is 14): java.nio.charset.StandardCharsets#UTF_8
```

**Comment by tobiasKaminsky** [comment]
Codacy hangs, so merging.

**Comment by elpraga** [comment]
Tobias, what Collqbora server 4.0 is needed? Are we talking about the loolwsd server? The latest version is 3.4.2 as of today. 

Can you please give me a hint?

Thank you!

**Comment by elpraga** [comment]
Ahh, OK! 

Thank you for clarifying Tobias! 

I'll wait until version 4.0 lands in the repository to try it out then!

Thank you!

**Comment by AndyScherzinger** [comment]
:+1: looks good code wise

**Pull request merged**
