### PR TITLE
Improve TalkBack screenreader support

### LINKED ISSUE #2780: Issues found testing with TalkBack screenreader
I did some quick testing with the [TalkBack screenreader](https://support.google.com/accessibility/android/answer/6283677) which is included in the Android accessibility settings and here’s some basic issues I found:

- Top left menu button just reads out "Open" – should be "Open sidebar"
- The "+" menu FAB is spoken as "unlabeled button", should be "Add or upload"
- In the file list, "thumbnail" is spoken, shouldn't be
- In the file list, "more icon menu" should be simply "More menu"
- ~~In the sidebar, the active menu item has "checked" prepended ("checked All files"), probably shouldn’t have~~
- ~~In the file list, it reads out "4 MB, 2 days ago", but should either say "4 MB, modified 2 days ago", or not read it at all?~~

And from @henningoschwald:

- The content descriptions currently are quite visual. For example "fingerprint icon", "shared icon" or "activity icon". I would like to suggest to strip the "icon" in this case.
- In the file list, the content description (currently "shared icon") should indicate whether a file or folder is currently shared. In case the item is not shared, the content description should be "share", if the item is shared, it should be "shared".

What do you think @nextcloud/accessibility @henningoschwald? cc @nextcloud/android

### PR DESCRIPTION
**Pull request by AndyScherzinger**
Resolves #2780

- [x] Top left menu button just reads out "Open" – should be "Open sidebar"
- [x] The "+" menu FAB is spoken as "unlabeled button", should be "Add or upload"
- [x] In the file list, "thumbnail" is spoken, shouldn't be
- [x] In the file list, "more icon menu" should be simply "More menu"
- [x] The content descriptions currently are quite visual. For example "fingerprint icon", "shared icon" or "activity icon". I would like to suggest to strip the "icon" in this case.
- [x] In the file list, the content description (currently "shared icon") should indicate whether a file or folder is currently shared. In case the item is not shared, the content description should be "share", if the item is shared, it should be "shared".

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Pinging @ardevd @mario @tobiasKaminsky for review/approval :eye: 

cc @nextcloud/accessibility :heart:

**Comment by mario** [comment]
👍

**Comment by AndyScherzinger** [comment]
Pinging @ardevd @tobiasKaminsky for review/approval :eye:

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
