### PR TITLE
replace f-droid text link with a badge

### PR DESCRIPTION
**Pull request by AndyScherzinger**

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
feel free to +1 and merge. It is just a nice badge for the f-droid link which now point to the listing of stabel and beta.

**Comment by tobiasKaminsky** [comment]
The indention is not right

**Comment by tobiasKaminsky** [comment]
Ahh, the fdroid badge has a wthitespace border, so they look never the same :/

**Comment by AndyScherzinger** [comment]
Japp, so we will have to live with the identation :( :+1:

**Comment by tobiasKaminsky** [comment]
Then :+1:

**Comment by AndyScherzinger** [comment]
needs another +1 - @przybylski @LukasReschke :)

**Comment by AndyScherzinger** [comment]
LGTM seems to have some hickups... removed latest post, merged PR

**Pull request merged**
