### PR TITLE
Auto detect encoding for text preview

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Using external lib for detecting encoding (https://github.com/albfernandez/juniversalchardet).
License: GPL2+ (https://github.com/albfernandez/juniversalchardet#license)

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Fine by me. The license is even more flexible:
```
The library is subject to the Mozilla Public License Version 1.1.

Alternatively, the library may be used under the terms of either the GNU General Public License Version 2 or later, or the GNU Lesser General Public License 2.1 or later.
```

**Comment by AndyScherzinger** [comment]
👍 fine by me

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky is this to be added to 2.0.0? (Since it is a bugfix)

**Comment by marinofaggiana** [comment]
@tobiasKaminsky @AndyScherzinger can you open this file and report me the encoding detect ?

[utf8.txt](https://cloud.twsweb.it/index.php/s/XjegCpCGkVPx9Ld)

**Comment by tobiasKaminsky** [comment]
> /tmp/utf8.txt: UTF-8 Unicode text, with no line terminators

**Comment by AndyScherzinger** [comment]
👍 rebased to satisfy lint

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky is this to be scheduled for 2.0.0?

**Comment by tobiasKaminsky** [comment]
I vote for 2.0.1 so we can focus only on hardening rc3. 
Otherwise it could happen that we get new bugs with new code and will run into an endless bugfixing loop and will never release it...

**Comment by mario** [comment]
👍

**Comment by mario** [comment]
@AndyScherzinger

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger already approved on 14.08.

**Pull request merged**
