### PR TITLE
Update to latest status icon design and fix syncronizing/failed icons

### PR DESCRIPTION
**Pull request by AndyScherzinger**
incorporating https://github.com/nextcloud/client_theming/issues/196 / https://github.com/nextcloud/client_theming/pull/200 for the Android client which adds the newly designed icons and also fixes the display of failed and synchronizing states.

cc for review @mario @tobiasKaminsky

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
:+1: as it is only a replacement of existing files/adding missing files, but no functional change

**Comment by tobiasKaminsky** [comment]
@MorrisJobke approving is not enough for us ;-)
We need a +1 to satisfy pullapprove ;-)

**Comment by MorrisJobke** [comment]
:+1:

**Comment by AndyScherzinger** [comment]
@tobiasKaminsky please merge then :)

**Pull request merged**
