### PR TITLE
new feedback email address / help redirects to forum

### PR DESCRIPTION
**Pull request by tobiasKaminsky**

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
AFAIK the email address is google@nextcloud.com 

Right @LukasReschke?

**Comment by LukasReschke** [comment]
> AFAIK the email address is google@nextcloud.com
> Right @LukasReschke?

Got you a fancy android@ address and will send you the credentials in a minute ;)

**Comment by AndyScherzinger** [comment]
Nice! :tada:

**Comment by AndyScherzinger** [comment]
LGTM

**Comment by przybylski** [comment]
👍

**Comment by tobiasKaminsky** [comment]
We should release a RC1 with this PR and #87 (after confirmed)

**Pull request merged**
