### PR TITLE
Search and others

### PR DESCRIPTION
**Pull request by mario**
This is the PR I mentioned earlier that covers several things, and is still WIP. It depends on my branding PR.

It covers:

- file search
- bottom navigation bar
- favorites and favorites view
- photos view
- recently modified view
- shared view
- videos view
- redesigned drawer menu

And many other smaller improvements. Should be hopefully ready for review by end of this week.

cc @tobiasKaminsky @AndyScherzinger @MorrisJobke

### CODE REVIEW

**Comment by aleister09** [comment]
I found an issue 

When the app was opened by first time the Navigation Bar has the "Recently Add" and "Recently Modify" options

screenshot_20170323-165733

 but if you close and reopen the app  those options were replaced by "Favorites", "Photos" and "Share" options

screenshot_20170323-170025

**Comment by mario** [comment]
@aleister09 thanks, will investigate.

**Comment by mario** [comment]
@aleister09 this particular issue is now fixed.

**Comment by aleister09** [comment]
I found another issue 

The Search Button disappear when you open photo view
screenshot_20170324-132334

screenshot_20170324-132703

**Comment by mario** [comment]
@aleister09 nice one, but not an issue - this is actually expected. You can search for photos in the main Files view if you want, but for now, there won't be filtering in already filtered views (like Photos).

**Comment by aleister09** [comment]
That's right but the real problem is when you come back to the "All Files View"  the button is hidden
418634925661067992-account_id 1

**Comment by mario** [comment]
@aleister09 yup, that is an issues - thanks for finding the bug. Any others that you've seen?

**Comment by mario** [comment]
@aleister09 should be fixed.

**Comment by aleister09** [comment]
@mario Actually I found another issue 

After to do some searches the app is crashing but i can't find the pattern to replay it 
I send you the trace

`03-24 16:13:57.483 29057-29057/com.nextcloud.client E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.nextcloud.client, PID: 29057
                                                                      java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
                                                                          at java.util.ArrayList.get(ArrayList.java:411)
                                                                          at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
                                                                          at android.widget.ListView.dispatchDraw(ListView.java:3419)
                                                                          at android.view.View.draw(View.java:17188)
                                                                          at android.widget.AbsListView.draw(AbsListView.java:4315)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6338)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
03-24 16:13:57.484 29057-29057/com.nextcloud.client E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by mario** [comment]
@aleister09 are you on Android 6 by any chance or earlier? If so, this issue is not something that I can reproduce, but am aware of it.

**Comment by aleister09** [comment]
I'm on Android 7.1.2, i will try to reproduce it and fix it

**Comment by AndyScherzinger** [comment]
@jancborchardt @eppfel can you take a look at the screenshots for the file listing please? They have AFAIK been implemented as discussed but looking at the it is obvious that the layout is now not within the material design guidelines since "the  left part" is now wider than 72dp thus the text is not aligned with the toolbar headline anymore. Google fixed this e.g. in their Gmail app by putting the favorite star icon to the right. I am aware that the actual implementation would make it look like the web app while it kind of looks a bit off on Android and also a bit not so aligned/material anymore. What do you think?... Just caught my eye.

**Comment by eppfel** [comment]
@AndyScherzinger I said this before, but @jancborchardt sees this otherwise: favorite is not as important too make give it a direct icon you can tap. All other options like share, etc. are hidden in the menu. I feel like sorting/organizing is not the common use-case for android. You would do that in the web or on your Desktop.
Therefor a icon as info under the sync icon would be enough and save a hell lot of space. Maybe I am wrong, but a well designed search is much faster and dynamic than favorites...

So my conclusion: Android compatibility vs. web ui continuity

**Comment by AndyScherzinger** [comment]
@mario feedback from Felix and Jan thus are to not explicitly have an action on the favorite icon but keep the action in the menu, which would also solve the grid issue we are facing with the favorite action. So we could revert the UI change which is also what I would recommend. What do you think?

**Comment by mario** [comment]
@AndyScherzinger I personally disagree and think a tap-able icon is important - even now, people complain that the "shared" icon next to the filename isn't tap-able :( I do think it might look nicer on the right though like Gmail has it.

Anyway, let me talk this over with @jancborchardt on Monday and see.

**Comment by mario** [comment]
@aleister09 managed to reproduce maybe?

**Comment by AndyScherzinger** [comment]
@mario all fine with me, my concern is about the design, not the click able part, so I would rather like to have the fav icon hovering the file type icon like the other icons do to and then have it click able.

**Comment by jancborchardt** [comment]
Regarding the favorites icon:
- currently the layout is destroyed – the filenames should be flush left-aligned with the header »Nextcloud«. Right now they are way too far to the right and it looks strange
- the favorite icon interactive/non-interactive is a question of icon size. If it is like it looks now, it needs to be interactive. If it’s only small in the corner of the filetype icon (retaining the current released layout of the app) then it’s ok to be not interactive.

I’d say keep the layout of the released app, put the sync state indicator on the bottom right, and put the favorite indicator on the top right so it’s before the filename. What do you think?

**Comment by AndyScherzinger** [comment]
> I’d say keep the layout of the released app, put the sync state indicator on the bottom right, and put the favorite indicator on the top right so it’s before the filename. What do you think?

Also my opinion. While I'd say we should make the icon click-able since we would always show it grey/yellow so as a user I would then expect to be able to click it since that is what I can do in other apps I am used to that sport a fav icon. Which is imho still within what you said @jancborchardt except the addition to make it clickable anyways. Would that still be fine with you?

**Comment by jancborchardt** [comment]
I’d say that could conflict with just being able to click the filename / icon to open it, no? :\

**Comment by AndyScherzinger** [comment]
> I’d say that could conflict with just being able to click the filename / icon to open it, no? :\

That is true, but from what I understood from @mario is that users are requesting to do this. For now I would be fine though with not making it clickable simply to get through with the feature quicker and postpone this issue for later.

**Comment by jancborchardt** [comment]
Talked about it with Mario, result:
- Base layout should be like before. Icon on the left, text flush with the header bar text.
- Put the green checkmark (or according status) on the bottom right of the filetype icon (where available offline is now). Reasoning: It’s like that on all desktop platforms, bottom right.
- Put the favorite indicator on the top right of the filetype icon, so it’s basically in front of the file name. That way it also correlates nicely to the name.
- The »Available offline« icon should be on the left of the sync status icon because they relate to each other. In the long run we should get rid of that icon entirely though because »green checkmark« is exactly the same meaning. Having too many icons confuses people.

Grid view will be discussed after but should of course be similar. But there are differences in height/width of the icons with images vs filetype icons so we have to adjust. Proposal:
- Put the sync state indicator (green checkmark) in the bottom right too of course. Should be in the very bottom right for images, and overlaying the bottom right of the icon for filetype icons. So we have to do some positioning magic here.
- Put the favorite icon on the top right. Same here – for filetype icons it should overlay the icon, for images it should be in the very top right to not float in the middle.
- Put the »Available offline« icon on the left of the sync status indicator.

**Comment by mario** [comment]
@AndyScherzinger can you please review & merge this? Thanks!

**Comment by AndyScherzinger** [comment]
device-2017-03-29-224128

**Comment by AndyScherzinger** [comment]
device-2017-03-29-224850

**Comment by AndyScherzinger** [comment]
@mario saw the version bump to 25.0.2 for the build tools, that is likely to break the builds :(

**Comment by mario** [comment]
@AndyScherzinger feel free to change if that's the last remaining thing.

**Comment by AndyScherzinger** [comment]
@jancborchardt Is the ordering of the menu (see below) fine with you, comparing it to the specification you posted here: https://github.com/nextcloud/android/issues/556#issuecomment-274772899
device-2017-03-31-105015

**Comment by mario** [comment]
@AndyScherzinger are we ready to merge this?

**Comment by AndyScherzinger** [comment]
@mario in general yes, but I am still waiting for @jancborchardt's approval for the menu order.

**Comment by mario** [comment]
@AndyScherzinger ok. Though I think no need in this case :)

**Comment by AndyScherzinger** [comment]
👍 fine code wise and tested, while I will open issues for the UI glitches I found that need to be fixed but don't block the PR

**Comment by aleister09** [comment]
@mario I found an issue about Favorites and Photos View, 

When you are in Participate View and taps on Favorites the view is not changing 

Also if you are in Photos View and calls the swipe refresh the filter disappears and the view shows all  the files again

**Comment by mario** [comment]
First is known, and there's already an issue about it.

For the second - still thinking what to do about it - since it's a filter, and we get all the data we might as well remove the filter completely.

**Pull request merged**
