### PR TITLE
Fix NPE in external link icon loading

### LINKED ISSUE #1976: External sites are not shown.
On 2.0 I could reach each external site. Now on 3.0 RC there are no external sites in the menu.

Well done work on the app! Rly!

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Fix #1976 & again from google dev console.

Signed-off-by: tobiaskaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
👍 looks good to me

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger I rebased and also fix #1976 with this, please re-approve.

**Comment by AndyScherzinger** [comment]
👍 still looking good :)

**Comment by mario** [comment]
👍

**Pull request merged**
