### PR TITLE
Update docker container

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @AndyScherzinger

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@LukasReschke please restart the server :roller_coaster:

**Comment by MorrisJobke** [comment]
* [ ] wait for docker hub to build and then update to version `android-5` - https://hub.docker.com/r/nextcloudci/android/builds/btbg6cjuutkkeqscw9l4yxd/

**Comment by MorrisJobke** [comment]
Conclusion: Somehow the emulator doesn't properly start with the x86 image (even if KVM is loaded inside the docker container). So we moved back to the slow image.

**Comment by MorrisJobke** [comment]
Seems to not work - let's try `android-7` https://hub.docker.com/r/nextcloudci/android/builds/b9dmdsfzotrjgvngoxmbpgf/

**Comment by AndyScherzinger** [comment]
:+1: 

works

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
